packages/app-project/README.md, packages/app-project/components/head.js, packages/app-project/components/head.spec.js, packages/app-project/components/nav.js, packages/app-project/components/nav.spec.js, packages/app-project/next.config.js, packages/app-project/package-lock.json, packages/app-project/package.json, packages/app-project/pages/index.js, packages/app-project/pages/index.spec.js, packages/app-project/pages/project.js, packages/app-project/pages/project.spec.js, packages/app-project/test/enzyme-config.js, packages/app-project/test/enzyme-setup.js, packages/app-project/test/mocha.opts
Sets up the testing harness, and adds some basic smoke tests.
=> Setup test suite

packages/lib-panoptes-js/package.json, packages/lib-panoptes-js/src/config.js, packages/lib-panoptes-js/src/config.spec.js, packages/lib-panoptes-js/src/docs/index.md, packages/lib-panoptes-js/src/index.js, packages/lib-panoptes-js/src/panoptes.js, packages/lib-panoptes-js/src/panoptes.spec.js, packages/lib-panoptes-js/src/resources/projects/index.js, packages/lib-panoptes-js/src/resources/projects/mocks.js, packages/lib-panoptes-js/src/resources/projects/projects.js, packages/lib-panoptes-js/src/resources/projects/projects.spec.js, packages/lib-panoptes-js/test/setup.js
This PR adds the ability to set the panoptes environment separately to the node environment - it's something I wished we'd had for a while. Otherwise, everything looks good - @srallen, if you're happy with these changes we can merge both this and #21
=> Add panoptes js lib review

packages/lib-panoptes-js/.travis.yml
Adds a travis yaml file to panoptes.js so we can use the CI for the test running as a pre-check to merging PRs.
=> Add travis.yml to panoptes.js package

packages/lib-panoptes-js/package-lock.json, packages/lib-panoptes-js/package.json, packages/lib-panoptes-js/src/config.js, packages/lib-panoptes-js/src/config.spec.js, packages/lib-panoptes-js/src/panoptes.js, packages/lib-panoptes-js/src/panoptes.spec.js, packages/lib-panoptes-js/src/resources/projects/projects.spec.js, packages/lib-panoptes-js/test/mocha.opts
This just fixes some linting things.
=> Default params review

docs/arch/adr-1.md, docs/arch/adr-2.md, packages/lib-panoptes-js/.gitignore
Package: N/A
Adds ADR-2. Updates a couple .gitignore files with standard ignore files. Fixes a typo in the date for ADR-1.
=> Add ADR-2. Update some .gitignore files. Fix typo in ADR-1

README.md
This is what @srallen described as the way to get started when she gave her WTF rewrite zoominar.
=> Added usage notes to readme

README.md, docs/arch/README.md
Package: All
Closes #78.
Fills out docs as suggested from this week's Zoominar and #77. @shaunanoordin I'm requesting review from you since most of these suggestions were from your review of #77.
=> Improved docs

docs/arch/adr-3.md
Documents the proposed decision to create an new auth library, and how implementation might work.
=> Create ADR for proposed auth lib

packages/lib-panoptes-js/src/panoptes.spec.js
Package: `lib-panoptes-js`
Related to #58
I found myself with an odd few minutes, so I refactored some of the tests with async/await.
=> Refactor first block of tests with async await

packages/lib-auth/dev/components/App/App.js, packages/lib-auth/package-lock.json, packages/lib-auth/package.json, packages/lib-auth/src/views/oauth/OAuthApp.spec.js, packages/lib-auth/src/views/oauth/components/LoginPopup/LoginPopup.spec.js, packages/lib-auth/src/views/oauth/components/shared/Button/Button.js, packages/lib-auth/src/views/oauth/components/shared/Button/Button.spec.js, packages/lib-auth/src/views/oauth/components/shared/Popup/Popup.js
The dependencies for this package were a bit all over the place, and given it's designed to be a standalone app I've reorganised them as such.
=> Tidy up dependencies for lib-auth

packages/lib-async-states/README.md, packages/lib-async-states/package-lock.json, packages/lib-async-states/package.json, packages/lib-async-states/src/async-states.js, packages/lib-async-states/src/async-states.spec.js, packages/lib-async-states/test/mocha.opts
Moves the async states helper to its own lib for reuse in other apps.
=> Add asyncStates lib

packages/lib-panoptes-js/src/panoptes.spec.js
Package: @zooniverse/panoptes-client
Finishes off some work I started to use async/await in the test suite.
=> Finish converting Panoptes client tests to use async/await

docs/arch/README.md, docs/arch/ard-6.md
This PR adds documentation noting our decision on how to build the Light Curve Viewer for the TESS project.
Review ready.
=> Add ADR6 - Building the TESS Light Curve Viewer

.dockerignore, Dockerfile, Jenkinsfile
=> Attempt to get tests working on Jenkins

packages/lib-async-states/src/async-states.js, packages/lib-async-states/src/async-states.spec.js, packages/lib-classifier/package-lock.json, packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js, packages/lib-classifier/src/store/Classification.js, packages/lib-classifier/src/store/Classification.spec.js, packages/lib-classifier/src/store/ClassificationStore.js, packages/lib-classifier/src/store/Project.js, packages/lib-classifier/src/store/ProjectStore.js, packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/Subject.js, packages/lib-classifier/src/store/SubjectStore.js, packages/lib-classifier/src/store/Workflow.js, packages/lib-classifier/src/store/WorkflowStepStore.js, packages/lib-classifier/src/store/WorkflowStore.js, packages/lib-classifier/src/store/utils/convertCamelCaseToSnakeCase.js, packages/lib-classifier/src/store/utils/convertMapToArray.js, packages/lib-classifier/src/store/utils/convertMapToArray.spec.js, packages/lib-classifier/src/store/utils/index.js, packages/lib-classifier/src/store/utils/session.js, packages/lib-classifier/src/store/utils/session.spec.js, packages/lib-classifier/test/enzyme-setup.js
Package: lib-classifier, lib-async-states
Branched off of multiple-choice-annotation, this finishes the basic back/next functionality of the task nav and submits the classification, loads the next subject, and resets the workflow steps back to start when done is clicked. 
~I'm still working on the conversion part of the classification from the store to JSON the API will accept. The mobx `toJS` method isn't quite working the way I think it should, so I'm investigating that.~
~Working on loading the next subject.~
=> Submit classification

package.json
Adds a few required fields to the top-level `package.json` file.
=> Update top-level package.json

packages/app-project/package.json, packages/app-project/pages/_app.js, packages/lib-react-components/src/ZooFooter/components/NavListItem/NavListItem.js
=> Add footer

packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js, packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js, packages/app-project/stores/Project.js, packages/app-project/stores/Project.spec.js
Moves background lookup to the Project model, adds a storeMapper function to the component, updates some tests.
=> Updates to `FinishedForTheDay` component

packages/lib-auth/src/models/oauth/UserResource.js, packages/lib-auth/src/models/oauth/UserStore.js
Package: lib-auth
In #268, there's a bunch of UserResource model values that aren't being correctly set, breaking the auth flow.
=> Cast API values to correct model types

packages/lib-react-components/package-lock.json, packages/lib-react-components/package.json, packages/lib-react-components/webpack.dist.js
Adds the `peer-deps-externals-webpack-plugin` to reduce the bundle size for lib-react-components.
=> Add webpack externals plugin to lib-react-components

bin/bootstrap.sh
Package: all
Follows on from #324. Add comments, build async-states, install missing dependencies
=> Update bootstrap script

plop/templates/component/Component.js.hbs, plop/templates/component/Container.js.hbs
Move `export` keyword in plop templates
=> Update exports for plop

packages/app-project/components/ClassifyPage/ClassifyPage.spec.js, packages/app-project/components/ClassifyPage/components/ClassifyBox/ClassifyBox.spec.js, packages/app-project/components/ClassifyPage/components/ConnectWithProject/ConnectWithProject.spec.js, packages/app-project/components/ClassifyPage/components/ConnectWithProject/components/ProjectLink/ProjectLink.spec.js, packages/app-project/components/ClassifyPage/components/ConnectWithProject/components/ProjectLink/components/BitbucketIcon/BitbucketIcon.spec.js, packages/app-project/components/ClassifyPage/components/ConnectWithProject/components/ProjectLink/components/WeiboIcon/WeiboIcon.spec.js, packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js, packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js, packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.spec.js, packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/components/Placeholder/Placeholder.spec.js, packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.spec.js, packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.spec.js, packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.spec.js, packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js, packages/lib-react-components/src/SpacedText/SpacedText.spec.js, packages/lib-react-components/src/ZooFooter/components/AdminCheckbox/AdminCheckbox.spec.js, packages/lib-react-components/src/ZooFooter/components/NavListItem/NavListItem.spec.js, packages/lib-react-components/src/ZooFooter/components/ZooniverseLogotype/ZooniverseLogotype.spec.js, packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.spec.js, packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.spec.js, packages/lib-react-components/src/ZooHeader/components/ZooniverseLogo/ZooniverseLogo.spec.js
Updates empty smoke tests to be more explicit.
=> Update smoke tests

packages/app-project/components/AuthModals/components/LoginModal/LoginModalContainer.js
Serialise the login form by creating an array of [name, value] pairs from the form's FormData object.
=> Use FormData to serialise login form

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.js
=> Address PR comments in `tess-lcv-2-button-remove`

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLabel.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.js
package: lib-classifier
Requires / targets #394
This PR is addresses feedback from the live demo given to the science team on 29 Jan. 
- Colours have been changed to be consistent with the current [Planet Hunters project.](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)
_Newly updated TESS Light Curve Viewer_
_Current Planet Hunters project_
Safe to review, but further tweaks are ongoing to clean up the code.
PR target chain: #394 -> #385 -> `master`
=> Classifier - TESS Light Curve Viewer - Feedback Response (29 Jan Demo)

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js, packages/lib-classifier/src/store/utils/getBearerToken.spec.js
Adds tests for `getBearerToken`
Fixes tests for MetadataModal
Fixes missing props for tests for NextButton and SlideTutorial
Fixes NextButton disabled state tests.
=> Classifier tests

packages/app-project/pages/_app.js
=> Prevent unnecessary project calls

packages/app-project/test/mocha.opts
=> Update mocha to use the /src directory

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
Package:
app-project
Key the classifier by user ID so that it re-mounts when the logged-in user changes.
=> Key the classifier on user ID

.travis.yml, README.md, bin/travis-test.sh, package-lock.json, package.json
=> Add coverage reports to Travis

.travis.yml, README.md, bin/bootstrap.sh, bin/travis-bootstrap.sh, bin/travis-test.sh, package-lock.json, package.json, packages/app-project/.babelrc, packages/app-project/package.json, packages/lib-async-states/package.json, packages/lib-classifier/package.json, packages/lib-panoptes-js/package.json, packages/lib-react-components/package.json, packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js, packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.js
Package: all
- Sets up Travis as the test runner for PRs
- ~~Disables a test that includes a delay, since this breaks the Travis build - @srallen, any ideas?~~
- Uses the the `min` reporter for CI builds
=> Setup Travis

bin/panic-button.sh
Package: all
Adds a bash script to trash all `node_modules` and compiled assets from the monorepo.
=> Add panic button

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js, packages/lib-classifier/src/store/Classification.js, packages/lib-classifier/src/store/ClassificationStore.js, packages/lib-classifier/src/store/ClassificationStore.spec.js, packages/lib-classifier/src/store/TutorialStore.js, packages/lib-classifier/src/store/TutorialStore.spec.js
For #113
Adds tests for the TutorialStore
=> Tutorial store tests

Jenkinsfile
project has been ported to the new swarm, deploy it there.
=> update swarm deploy target

packages/app-project/package-lock.json, packages/app-project/package.json, packages/app-project/stores/Recents.js, packages/app-project/stores/Recents.spec.js, packages/app-project/stores/Store.js, packages/app-project/stores/YourStats.js, packages/app-project/stores/YourStats.spec.js
Package:
app-project
Towards #38.
Add a YourStats store. Request user prefs and daily classification counts on initial user login.
Test that the store initialises, fetches activity counts on user change and increments counts properly for both authenticated and anonymous users.
Actions:
- `yourStats.fetchActivityCount()` gets your total classification count from your user preferences.
- `yourStats.fetchDailyCounts()` fetches your daily classification counts from the stats service
- `yourStats.increment()` increments your classification count for this session.
Todo:
=> Your project activity

package.json
Run all the tests in parallel with `npm test` in the top-level directory.
Package:
All of them!
I've been using this locally to check changes across all the packages, so committed it for convenience.
=> Run all the tests!

packages/lib-classifier/src/store/ClassificationStore.js, packages/lib-classifier/src/store/SubjectStore.js, packages/lib-classifier/src/store/utils/ClassificationQueue.js, packages/lib-classifier/webpack.dev.js
Package:
lib-classifier
Closes #515.
Adds Authorization headers to subject requests and classification posts.
=> Classifier auth

package.json
Add a dev script to run the project app from the top-level directory.
=> Add a dev script

packages/app-project/next.config.js, packages/app-project/package-lock.json, packages/app-project/package.json
I found a closed issue on styled-components which indicated a workaround for the FOUC issue. This avoids us having to copy over things <3
cc styled-components/styled-components#2322
fixes #327
=> Use require-control to fix SC issue with symlinked libs

Jenkinsfile
Package: all
Tests are run by Travis, so we don't need a test stage in the Jenkinsfile.
=> Remove test stage from Jenkinsfile

packages/app-project/src/shared/components/ProjectStatistics/components/CompletionBar/CompletionBar.js
Fixes a reference to a missing colour on the completion bar widget.
=> Fix completion bar color reference

kubernetes/deployment.yaml, kubernetes/service.yaml
=> Add Kubernetes config files

Jenkinsfile, kubernetes/deployment.tmpl
Uses the Git commit ID as the Docker image tag.
=> Automatically deploy to Kubernetes in Jenkins

packages/app-project/next.config.js, packages/app-project/pages/_app.js, packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.js, packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.js, packages/app-project/src/components/ProjectHeader/components/Background/BackgroundContainer.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js, packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.js, packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.spec.js, packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/CreateCollection.js, packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.js, packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js, packages/app-project/src/shared/components/ProjectStatistics/components/CompletionBar/CompletionBar.js, packages/app-project/stores/Project.spec.js, packages/app-project/stores/YourStats.spec.js
Got most things, not all of it though.
=> Run a lint on app-project

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js, packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js, packages/lib-classifier/src/components/Classifier/components/Feedback/index.js, packages/lib-classifier/src/components/Classifier/components/Feedback/locales/en.json, packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js, packages/lib-classifier/src/store/FeedbackStore.js, packages/lib-classifier/src/store/FeedbackStore.spec.js, packages/lib-classifier/src/store/SubjectStore.js
Towards #205, after #531 and #540 
- add feedback modal
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/middleware.md
https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md
=> Add feedback modal

packages/app-project/stores/Recents.js
I think this was some leftover dev code.
=> Remove logging of recents

packages/app-project/stores/Project.js
I've added `configuration` to the Project model in the app-project. Workflow selection by project's default won't work without this.
=> Add config to app-project's Project model

README.md, bin/README.md, docs/arch/README.md, docs/arch/adr-12.md
Adds an ADR for the current production build setup, and updates the README.
=> Add ADR for production docker setup

packages/app-project/next.config.js
Disable minification for the app too.
=> Temporarily disable minification for the app

packages/lib-classifier/src/store/TutorialStore.spec.js
Package:
lib-classifier
Repeat of #610 only merging to master this time around.
=> Catch unresolved medium bug in tutorial tests

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.spec.js
Centers the button label. This is a regression from some point, but not sure when. Might have been from a grommet version bump.
=> Center button label text for need help

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
Package:
app-project
Closes #542  .
This branch fixes the two styling bugs mentioned in the issue above. The second issue occurs because the [default](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation) `global.breakpoints.small.value` is 768, which cause the components to wrap too late.
=> Finished for day bug

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
Package:
lib-classifier
Closes #621.
=> Make subject metadata modal scrollable

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
=> Enable reset zoom button

packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js, packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.spec.js
=> Render link lists as ul in footer

packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js, packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
Fix an undefined user error on sign out.
Package:
app-project
Closes #668.
=> Fix sign out

README.md, docs/CONTRIBUTING.md, docs/arch/adr-13.md, packages/app-project/README.md, packages/lib-async-states/README.md, packages/lib-classifier/README.md, packages/lib-grommet-theme/README.md, packages/lib-panoptes-js/README.md, packages/lib-react-components/README.md
=> Add Contributing.md

packages/lib-grommet-theme/src/index.js
=> Fix typo in line-height

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
From #695, updates the background color noted in the issue.
=> Update background color for LCV

packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
=> Add dark theme toggle icon

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
This fixes a regression that I'm not sure when was introduced, but noticed during the PR review for #747
=> Add a defined height for the FFTD project image

kubernetes/deployment.tmpl, kubernetes/service.yaml
- Deploy production version of app-project to kubernetes
- Rename the staging version for clarity
=> Deploy production version of app-project to kubernetes

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js, packages/app-project/src/shared/components/ContentBox/ContentBox.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js, packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.js
=> Organise classify page headings

packages/app-content-pages/Dockerfile
Package:
Fix dockerfile working directory
=> Fix app-content-pages dockerfile

packages/lib-classifier/src/store/FeedbackStore.js
Remove some duplication by using applicableRules to calculate valid feedback messages.
Package:
lib-classifier
=> Simplify feedback messages

packages/app-project/src/components/ProjectHeader/ProjectHeader.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/locales/en.json
Last few things to fix before the TESS launch:
- missing className
- link to project stats, as personal stats aren't ready yet
=> Final checks before TESS launch

packages/app-project/src/components/AuthModal/AuthModal.js, packages/app-project/src/components/AuthModal/components/LoginForm/LoginForm.js, packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterForm.js, packages/app-project/src/components/AuthModal/components/RegisterForm/locales/en.json, packages/app-project/src/components/AuthModal/shared/components/FieldLabel/FieldLabel.js, packages/app-project/src/components/AuthModal/shared/components/FieldLabel/FieldLabel.spec.js, packages/app-project/src/components/AuthModal/shared/components/FieldLabel/index.js, packages/app-project/src/components/AuthModal/theme.js
UI fixes for the registration form, based on a review of #889
=> Registration form review

packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterForm.spec.js
Adds some basic input tests to the registration form - I'll circle back to this later on @srallen
=> Add basic input tests for registration form

packages/lib-grommet-theme/src/index.js
Adds the color used to indicate validations errors in the registration form.
=> Adds pink to theme. Color is used for dark theme UI errors

packages/tools-standard/options.js
Package:
all
Adds the[ consistent-return rule](https://eslint.org/docs/rules/consistent-return), which requires functions that return values to return consistent values. It should warn about missing return statements on functions that return from inside blocks.
Updates `app-content-pages` to use the same linter config as other packages.
=> Add consistent-return rule to linter

packages/app-project/src/components/AuthModal/shared/components/withCustomFormik/withCustomFormik.js, packages/app-project/src/components/AuthModal/shared/components/withCustomFormik/withCustomFormik.spec.js
Package:
app-project
Try to figure out why registration form tests are failing.
=> Fix withCustomFormik test failures

kubernetes/deployment.tmpl, packages/app-content-pages/newrelic.js, packages/app-content-pages/package-lock.json, packages/app-content-pages/package.json, packages/app-content-pages/server/server.js, packages/app-project/newrelic.js, packages/app-project/package-lock.json, packages/app-project/package.json, packages/app-project/server/server.js
=> Add new relic to production apps

README.md
Adds a link to the Roadmap Trello board, and a few badges for bling
=> Add roadmap link, badges to README

packages/app-project/src/components/AuthModal/components/RegisterForm/locales/en.json
Updates to match what is done on the PFE version of the form.
Making sure we match what's done on PFE: https://github.com/zooniverse/Panoptes-Front-End/pull/5412
=> Update Registration form validation language

bin/panic-button.sh, package-lock.json, packages/app-content-pages/package-lock.json, packages/app-content-pages/package.json, packages/app-project/package-lock.json, packages/app-project/package.json, packages/app-project/src/components/Head/HeadContainer.js, packages/app-project/src/components/Head/HeadContainer.spec.js, packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js, packages/lib-async-states/package-lock.json, packages/lib-async-states/package.json, packages/lib-classifier/package-lock.json, packages/lib-classifier/package.json, packages/lib-grommet-theme/package-lock.json, packages/lib-grommet-theme/package.json, packages/lib-panoptes-js/package-lock.json, packages/lib-panoptes-js/package.json, packages/lib-react-components/package-lock.json, packages/lib-react-components/package.json, packages/tools-standard/package-lock.json, packages/tools-standard/package.json
So the build is breaking, because `@zooniverse/standard` is not being resolved properly. This PR removes it as a dependency for the time being, just to get the build up and running again
=> Remove standard as dep

kubernetes/deployment.tmpl, packages/app-content-pages/next.config.js, packages/app-content-pages/package-lock.json, packages/app-content-pages/package.json, packages/app-content-pages/pages/_app.js, packages/app-content-pages/pages/_document.js, packages/app-content-pages/src/helpers/logger/README.md, packages/app-content-pages/src/helpers/logger/index.js, packages/app-content-pages/src/helpers/logger/initializeSentry.js, packages/app-content-pages/src/helpers/logger/logNodeError.js, packages/app-content-pages/src/helpers/logger/logReactError.js, packages/app-project/next.config.js, packages/app-project/package-lock.json, packages/app-project/package.json, packages/app-project/pages/_app.js, packages/app-project/pages/_document.js, packages/app-project/src/helpers/logger/README.md, packages/app-project/src/helpers/logger/index.js, packages/app-project/src/helpers/logger/initializeSentry.js, packages/app-project/src/helpers/logger/logNodeError.js, packages/app-project/src/helpers/logger/logReactError.js
- Add DSNs to kube deploy setup
- Add sentry package
- Add logger functions (I've kept them generic so we can swap out the internals without too much pain)
=> Add logging for sentry

bin/bootstrap.sh, bin/travis-bootstrap.sh, packages/lib-async-states/package-lock.json, packages/lib-async-states/package.json, packages/lib-async-states/src/async-states.spec.js, packages/lib-async-states/test/mocha.opts
- Remove build step
- Bump packages
- Update helper scripts
- Remove globs from test options
- Add @zooniverse/standard
=> @zooniverse/async-states fixes

packages/tools-standard/bin/cmd.js, packages/tools-standard/package-lock.json, packages/tools-standard/package.json
- Removes an unnecessary `require`
- Bump deps
- Use `~` for package versions
=> Fix @zooniverse/standard

Dockerfile, README.md, bin/bootstrap.sh, bin/panic-button.sh, package.json, packages/app-content-pages/Dockerfile, packages/app-project/Dockerfile, packages/lib-classifier/README.md
- Update shell scripts to use yarn
- Update dockerfiles to use yarn
- Update docs
=> Update scripts and docs

docs/arch/README.md, docs/arch/adr-15.md
Adds ADR 15 describing a high level API for the drawing tools based on our discussion today. Two more thoughts come to mind:
- How do we handle multi-image subjects and different streams for different frames?
- How do we handle selecting and editing a mark or deleting it?
=> Add ADR 15

packages/lib-classifier/src/store/FeedbackStore.js, packages/lib-classifier/src/store/FeedbackStore.spec.js
This only adds names to the autorun disposer functions for easier debugging in the future. I purposely added an `only` to the tests to show that they're passing.
=> [MST Upgrade] Update FeedbackStore

packages/lib-classifier/src/store/DataVisAnnotatingStore.js, packages/lib-classifier/src/store/DataVisAnnotatingStore.spec.js
There wasn't much to do here actually, but I added names for the autorun disposers to make debugging easier. I purposely added an `only` to show that its tests are passing.
=> [MST Upgrade] Update DataVisAnnotating Store

packages/lib-classifier/src/store/ProjectStore.js, packages/lib-classifier/src/store/ProjectStore.spec.js, packages/lib-classifier/src/store/ResourceStore.js, packages/lib-classifier/src/store/ResourceStore.spec.js, packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/RootStore.spec.js, packages/lib-classifier/src/store/TutorialStore.js, packages/lib-classifier/src/store/TutorialStore.spec.js, packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Updates store to use `types.safeReference`. Refactors tests to instantiate stores as needed for the tests. Purposely leaves in `only` to show `TutorialStore` tests are passing.
=> [MST Upgrade] Update TutorialStore

packages/lib-classifier/src/store/UserProjectPreferencesStore.js, packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
Updates to use `types.safeReference`. Updates tests. `only` left in on purpose to show UPP store tets are passing.
=> [MST Upgrade] Update UPP store

packages/lib-classifier/src/store/Subject.spec.js
=> Add tests for subject.openInTalk

.travis.yml
- Uses the `yarn bootstrap` script to get things up and running on Travis
- Performs a test build of each app to check things are compiling properly
Fix #989
=> Perform a build during tests

packages/app-project/README.md, packages/app-project/docker-compose.yml
Build from the monorepo image.
Start a dev server on http://localhost:3000 with `docker-compose up`.
Stop the dev server with `docker-compose down`.
Run the tests with `docker-compose run --rm dev test`.
Package:
app-project
=> Add docker-compose to the project app

.travis.yml
Turn off duplicate branch tests except for master.
=> Speed up Travis CI on PRs

.yarnrc
=> Update yarn to 1.17.3

packages/lib-classifier/src/store/tasks/DrawingTask.js, packages/lib-classifier/src/store/tasks/drawingTools/Line.js, packages/lib-classifier/src/store/tasks/drawingTools/Line.spec.js, packages/lib-classifier/src/store/tasks/drawingTools/index.js
=> Add drawing task line tool model

packages/app-project/package.json, yarn.lock
We're just updating Next, we can start using the new features once we know it works.
=> Bump Next.js to v9 in app-project

docs/PULL_REQUEST_TEMPLATE.md
The template now asks devs to run `yarn bootstrap` and test a production build of the app.
Package:
Closes # .
=> Update PULL_REQUEST template

packages/lib-grommet-theme/CHANGELOG.md, packages/lib-grommet-theme/README.md, packages/lib-grommet-theme/package.json
Adds a changelog, updates the readme, and package.json in preparation to publish on npm.
=> Preparation for publishing @zooniverse/grommet-theme

packages/lib-classifier/src/store/WorkflowStore.js, packages/lib-classifier/src/store/WorkflowStore.spec.js
Fixes some remaining items that got missed in a previous pass:
- Use `isValidReference` when checking the active project before using it for the default workflow.
- Remove the `rootStore` global variable in the tests.
Some space changes crept when I copied and pasted from my old PR. I'll fix that with the linter in the branch it is merging into all in one go.
=> [MST Upgrade] Update WorkflowStore and tests

packages/app-content-pages/package.json, yarn.lock
Update app-content-pages to the latest Zoo Grommet theme.
Package:
=> Update Zoo grommet theme

packages/app-project/.storybook/addons.js, packages/app-project/.storybook/config.js, packages/app-project/package.json, yarn.lock
Package:
app-project
This has already found an error in the Your Stats code so I'm pleased with it so far.
=> Add accessibility checking to the project storybook

.yarnrc
=> Upgrade yarn to 1.19

packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js, packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js, packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.spec.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.spec.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.spec.js, packages/app-project/src/shared/components/StubComponent/StubComponent.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js, packages/app-project/stores/YourStats.js, packages/app-project/stores/YourStats.spec.js
Run yarn lint for the project app. Manual errors haven't been fixed.
=> Lint the project app

packages/app-project/package.json
=> Fix storybook static file path

packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.spec.js, packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.js, packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.spec.js
Some test fixes for the dismiss-banners branch. One of the failing tests I put into a pending mode because I'm not sure what the goal of the test was exactly. The usage of the two sets of markup with `Media` makes it so that there are several `Box` components with props. I'm not sure what the best approach is for testing with the responsive `Media` component. Maybe move the two variants into their own component files and test them separately?
=> Fix tests for announcement banner dismiss feature

packages/lib-classifier/src/store/TutorialStore.js, packages/lib-classifier/src/store/TutorialStore.spec.js
I was going to work on something else, but I started up the dev classifier with the staging TESS-like project. I was logged out of staging and the tutorial modal opened, but I couldn't close it or do anything else because of MST errors being thrown. This PR does not fix this, but does some refactors missed in the MST upgrade. I've added in several safe reference existence checks and refactored the `activeStep` to just consistently use numbers rather than use a string conversion to deal with 0 indexes.
Everything works in the actual project app with the real TESS project, so I'm still not sure what's …
=> Refactor TutorialStore

packages/app-content-pages/package.json, packages/app-content-pages/pages/_app.js, packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js, yarn.lock
Updates the content pages app with the newest version of next
=> Update next.js for content pages app

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js, packages/lib-classifier/src/store/ClassificationStore.js
Right now, staging 400 errors because the default annotation isn't actually being created when you click next or done. This was missed by me in review of #1228. I've fixed this by removing the now cruft `createDefaultAnnotation` and calling `addAnnotation` directly. I've added some tests to check that default annotations are actually created for the TaskNav container.
=> Actually call to create a default annotation on next or on done

packages/app-project/pages/_app.js, packages/app-project/pages/projects/[owner]/[project]/logger.js
This is related to testing out sentry logging. I have a test page where you can click a button to throw an error in an MST action which should be caught by the MST middleware that logs to sentry. I am unable to load this page using the staging environment (since we don't want to expose this test page to production). This adds the query params to the page props and I use that to be able to determine if the test page should be loaded.
=> Environment query param for project app pages

docs/arch/README.md, docs/arch/adr-19.md
For #1142 .
Github Project: https://github.com/zooniverse/front-end-monorepo/projects/12
CodePen: https://codepen.io/simensta/pen/484d3438ef39101dd9579dd12b973173?editors=0010
I have the following questions about developing the Pages Filmstrip Viewer. The choices made for the Pages Viewer will likely affect future Filmstrip Viewer styles.
1. *How will researchers select the Pages Viewer in the Project Builder?* 
In PFE, the research team selects the viewing option for multi-image subjects in the workflow editor. For the future viewers, including the Pages Viewer, how do we want to store the filmstrip viewer preferences on a …
=> Proposing ADR 19: Pages Filmstrip Viewer

docs/arch/README.md, docs/arch/adr-20.md
Package: ADR
Adding a proposal ADR describing the transcription task. We need to make sure we clearly understand what we're doing here. I've included a link to the user stories @beckyrother put together. I've noted in the consequences that the transcription line mark has a different user interaction than the standard line mark. 
Another question is whether or not we can use the HTML datalist element for the input/dropdown for the previous transcriptions. If not, I might advise that we just have the text task input and a separate dropdown for previous transcriptions rather than some kind of custom combo function component like …
=> Add ADR-20 about the transcription task

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js, packages/lib-react-components/src/helpers/getGradientShade/README.md, packages/lib-react-components/src/helpers/getGradientShade/getGradientShade.js, packages/lib-react-components/src/helpers/getGradientShade/getGradientShade.spec.js, packages/lib-react-components/src/helpers/getGradientShade/index.js, packages/lib-react-components/src/index.js
Adds the new design for the workflow select button.
=> Add the new workflow button

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js, packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js, packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js, packages/lib-classifier/src/plugins/tasks/models/Task.js, packages/lib-classifier/src/store/WorkflowStepStore.js
- When a drawing task is complete, move its marks from the drawing tools to the task annotation.
- When a drawing task starts, copy any existing marks from the task annotation to the task's drawing tools.
- Pass previous drawing annotations into the interaction layer component and render their values as inactive marks.
Adds `task.start()` and `task.complete()` to the task model, which run when a task starts and finishes respectively.
TODO:
Closes #1104.
Test URL: http://localhost:8080/?project=908&workflow=3370
Package:
lib-classifier
Closes #1103.
=> Drawing: Copy drawn marks to drawing annotations

packages/lib-classifier/src/store/AnnotationsStore.js, packages/lib-classifier/src/store/AnnotationsStore.spec.js
Explicitly check annotations for undefined values. Allow null or 0 as annotation values.
Package:
lib-classifier
Closes #1320.
=> Check annotations for undefined values

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, yarn.lock
This an alternative to #1332 and for comparison reasons. I've tested this in browser stack using Safari 12 and it works as expected. Other modern browsers do not fire the polyfill and it is scoped to just the `InteractionLayer` following the PEP API. 
The advantage of this is that there's less code we have to maintain and less guesswork on making sure we're correctly falling back when we need to. Around September 2020, we should be able to drop this because Apple releases major version for Safari annually.
=> Add PEP for Safari 12 fallback

packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js, packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
Package: `app-content-pages`
Closes #1359 
Added a couple tabs to the about page to include the Highlights and Donate about pages. This is a quick fix, a long term fix would be resolving #1353 to add the page content into the monorepo.
=> Add Highlights and Donate External Links

.travis.yml, Dockerfile, README.md, package.json, packages/app-content-pages/src/api/publications/buildResponse.js, packages/app-content-pages/src/api/publications/buildResponse.spec.js
Package: all
Updating to Node 12 which is LTS.
=> Update to node 12

.yarnrc
Upgrade yarn to 1.21.1. with `yarn policies set-version`.
=> Upgrade yarn to 1.21.1

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
Closes #1427
This adds the UI for error bars in either the y (vertical) and/or x (horizontal) direction.
How it looks with the sample variable star data using vertical bars:
And random data displaying horizontal direction:
Here is the invision for comparison: https://projects.invisionapp.com/d/main?origin=v7#/console/17294981/361090808/preview?scrollOffset=0
=> [VSLCV] Scatter bar viewer support for error bars

Jenkinsfile
=> Deploy staging to Azure

Jenkinsfile
Add build environment variables to the Jenkinsfile stages that build the project and content apps.
Closes #1451.
=> Add build environment to Jenkinsfile

packages/app-project/src/helpers/logger/initializeSentry.js
Log Sentry initialisation so that we can check its status in build logs and in the browser dev console.
Package:
app-project
=> Project app: log Sentry status during builds

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/README.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
This is another preparation PR for the composite variable star LCV. Right now, the SingleImageViewer is assuming that you'll be drawing on the image or at least might be drawing on it. For the VSLCV, the image that is render isn't going to be drawn on, but should potentially be pan and zoomable. This adds a prop to make the rendering of the `InteractionLayer` configurable as needed.
This PR also adds a readme and fixes the storybook stories.
=> Make InteractionLayer configurable for SingleImageViewer

packages/app-project/package.json, packages/lib-classifier/package.json, yarn.lock
Package: lib-classifier, app-project
Fixes the duplicate and cruft dependencies for babel in the classifier library.
=> Fix rebase mistake

Jenkinsfile
=> Deploy production to Azure

kubernetes/deployment-staging.tmpl
ensure sentry reports the correct app_env for preview staging deploys, this will default to production if not explicitly set
=> add staging app_env env var

packages/app-project/package.json
Closes #1530 
Adds babel-loader to the dev dependencies.
=> Add babel-loader to app-project dev deps

packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
Offset the start of the line to a point on the radius of the opening circle.
The appearance of the transcription lines has been bugging me. This should fix them.
Before:
After:
Package:
lib-classifier (plugins/drawingTools)
=> Fix transcription line appearance

.github/workflows/main.yml
add automated 'approved' labels on PR approval, these can be used in pull reminders to filter the reported PRs
=> add approved labels to pull requests

.yarnrc
`yarn` is nagging that our version is out of date, so upgrade to latest with `yarn policies set-version`.
=> upgrade yarn to 1.22

.github/workflows/sentry-production-releases.yml
Finalise the latest Sentry release, and tag it as a production release, on each push to the `production-release` tag.
Follows on from #1601.
=> Update Sentry production on tag push

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/TranscriptionLine.js
Fixings a couple of warnings that were coming up in the classifier.
=> Fix a couple of React warnings

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/ResizeIcon.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/ResizeIcon.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/index.js, packages/lib-grommet-theme/CHANGELOG.md, packages/lib-grommet-theme/src/index.js
I'm updating the styles on the sub-task while aggregation is being worked on for the transcription task.
I'm basing some updates off of the invision: https://projects.invisionapp.com/d/main?origin=v7#/console/12923997/404084878/inspect?scrollOffset=7796
But I have a few questions for @beckyrother:
- I've made the sub-task min-width to be 350px based on what I see in the invision. Is this ok?
- ASM has an icon in the corner to indicate resizability. Do you want that ported here or use an updated icon?
- The border on the text task is really hard to see in dark mode. It's currently #2D2D2D. What would you …
=> Sub-task styles

docs/arch/adr-25.md
Package: ADRs
Related to https://github.com/zooniverse/aggregation-for-caesar/pull/289
@CKrawczyk Will the example change once you account for the `tool` to `toolIndex` change (documented in ADR 24 applying to all drawing annotations)?
=> Update ADR 25 with information about aggregation

packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js, packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
Closes #1637
Possible fix for #1637. Checks that the element target is an svg or a button for the element areas we allow keyboard control for pan/zoom. The `textarea` element is firing the keydown handler defined in `withKeyZoom` and adding `event.stopPropagation()` to that handler or onto the text area itself doesn't work. I don't know why.
=> Check for element type when keydown happens

kubernetes/deployment-production.tmpl
Limits are best guesses based on current usage. They are probably overestimates and are subject to change.
=> Add k8s resource limits to production template

kubernetes/deployment-staging.tmpl
Reasonable resource utilization limits for staging deployments.
=> Add k8s limits for staging

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.js, yarn.lock
=> Upgrade NextJS to 9.4.1

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js, packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.js, packages/lib-classifier/src/store/TranscriptionReductions/mocks/index.js, packages/lib-classifier/src/store/TranscriptionReductions/mocks/reducedASMSubject.json
This finishes the refactor on the `TranscriptionLine` mark to make it fully flexible between its usability with the drawing task and the transcription task.
Right now this can be previewed at http://local.zooniverse.org:8080/?project=1764&workflow=3392 or using the storybook's `TranscribedLines` story which can preview all four state colors in the now interactive story using a transcription task. Alternatively, the transcription line color can be previewed in the `TranscriptionLine` story where it is using the drawing task and the task is set to use the drawing-orange color to make it obvious its the drawing task. Here are …
=> When transcription task, use the hard coded colors for transcription line

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
Fixes some issues with the mocked data that are being used for the `BarChartViewer` and `VariableStarViewer` stories. I need this reviewed, merged, and deployed before a meeting on Tuesday.
=> Fix the bar chart and the VSLCV stories

.github/workflows/codeql-analysis.yml
=> Setup CodeQL security scan

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js, packages/lib-react-components/src/MovableModal/MovableModal.js
Package: lib-react-components, lib-classifier
Swaps out the Layer and ReactRnd component in the sub-task with the new MovableModal. Here's how it's looking in the transcribed lines story:
=> Refactor subtask to use MovableModal

README.md
Markdown didn't render as expected, so this adjusts the spacing a tad and also provides some more info on the final point
Package:
Closes # .
=> Update sub-lists in publishing section

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
Upgrade the Sentry client for the content pages and project NextJS apps.
Package:
app-project
=> Sentry 5.18.1

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
This adds the basic functionality for loading the subject image location for the HR diagram for the composite subject viewer. Here's how this looks in the story:
Compared to the Invision:
https://projects.invisionapp.com/d/main?origin=v7#/console/17294981/403043950/preview?scrollOffset=210
I am having one problem with the accessibility. Since we know the image for this viewer will be a HR diagram, I was trying to label it, but VoiceOver keeps telling me it is not labeled, so I'm not sure what I'm doing wrong. I would appreciate any suggestions for this.
=> [VSLCV] HR Diagram

README.md, packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
Packages should be built before they are published. This adds that info to the README and also prepares the app for a new version, which will be published after running the `yarn build` script
=> Update react components build

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
Small tweaks to the text about the location file types.
=> Update information on expected location files for VSLCV

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/Tooltip/components/Label/Label.js, packages/lib-react-components/src/Tooltip/components/Label/Label.spec.js
Closes #1681 
This fixes a regression introduced by the tippyjs-react major version update. The arrow position is now correct based on the tippyjs-react position set on the tooltip. This can be demoed in the react-component stories or in context in some of the classifier stories. As seen with `TranscribedLines`:
=> Fix arrow positioning for Tooltip

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js, packages/lib-classifier/package.json, packages/lib-react-components/package.json, packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js, packages/lib-react-components/src/CloseButton/CloseButton.stories.js, packages/lib-react-components/src/PlainButton/PlainButton.stories.js, packages/lib-react-components/src/Tabs/Tabs.stories.js, packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js, yarn.lock
Package: all
For #1469
This gets us on styled-components v5. There are several improvements including fixes for memory leaks in the v5 release. I had started updating and fixing some storybook stories along the way, but that's a lot of work, so that can finish separately.
=> Upgrade styled-components

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Confirmed regression from #1726. Not sure how this was missed, but the assumption that d3's `zoom` function handled this is incorrect. Compare to in production behavior: https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify
I reversed the sign of the `xMultiplier` value passed to the d3 `zoom` function in the TESS LCV's `pan` method. This corrects the direction the TESS LCV pan goes when using the arrow keys. Before this fix in `61a490f`:
Zoom in twice, hit right arrow twice, the plot pans left. Hit left arrow twice, the plot pans right.
Fixed:
Zoom in twice, hit right arrow …
=> Fix TESS LCV direction for left and right arrow panning

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js, packages/lib-classifier/src/store/Step.js, packages/lib-classifier/src/store/Step.spec.js, packages/lib-classifier/src/store/WorkflowStepStore.js, packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Towards #687, additional work on previous needed to close.
- refactor Step with `next` and `previous` properties and related actions to set
- refactor Step with `isThereBranching` view if there's a single choice task with branching including in step tasks
- refactor WorkflowStepStore to remove `isThereANextStep` and `isThereAPreviousStep` views now included in Step
- add WorkflowStepStore annotation observer if branching to update next step accordingly
- refactor WorkflowStepStore tasks conversion to steps for next, previous, and if combo task comes after tasks included in combo
- refactor TaskNavButtonsContainer to remove `isThereANextStep` and `isThereAPreviousStep` views now included in Step
- update tests
branching with combo - …
=> Refactor Step and WorkflowStepStore for branching

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
I accidentally hardcoded in a label for the phase focus, so this updates the controls to make sure they use the series' options labels and only use the hardcoded values as fallback.
You can see the issue here:
=> [VSLCV] Use series option label and hardcoded string as fallback

packages/app-project/src/screens/ProjectHomePage/components/Hero/HeroContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.stories.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/index.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/helpers/index.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/helpers/mockWorkflow.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/index.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/locales/en.json, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
Add a client-side subject set picker to the workflow selector links, which is shown on click when `workflow.grouped` is set (ie. when Panoptes expects you to pass a subject set ID with subject queries for that workflow.)
TODO:
Package:
app-project
=> Project app: Subject set picker

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
Toward #1777 
This adds a `nice` chained functional call to the d3 `scaleLinear` functions. A description of what this does is in the d3 docs (https://observablehq.com/@d3/d3-scalelinear) under the `Nice Bounds` header (they don't have anchor links for hte headings).
I'm still playing around actually adding padding to the min and max but this isn't as straight forward as it seems. There's layout impacts for other positions, particularly the enable zoom button, so this will be in a follow up.
Before:
After:
=> Add nice to scaleLinear utility functions

kubernetes/deployment-production.tmpl
Noticed high k8s HPA pod cpu metrics when investigating pod failures
Linked to #1794 - increase the pod cpu requests to enable the pods autoscaler a more accurate metric to scale from
e.g. if the request is 10Mi and the app is running at 9Mi (90%) that's already over our 80% target so the the app will scale after sustaining this cpu load for a time period. We don't want this, we want the app to autoscale under more load than this, say 1/4 vCPU (250Mi) for a period of time is our target, e.g. 200Mi load / 250Mi request is 80% cpu use, so we will scale when over the 200Mi value for a time period.
I'm happy to change these values, they are best guess :)
_Please request review from `@zooniverse/frontend` team. If PR is related to design, please request review from `@beckyrother` in addition._ …
=> increase the app pods cpu request for k8s HPA targets

Jenkinsfile
Package: all/none - ops related
notify slack ops channel when this job succeeds, get some visibility for deploy success
=> notify ops when job succeeds

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
Fixes the image displayed in the VSLCV to be dynamically sized reusing the container component and its onload behavior now that the store connection is separate. ~This is currently branched off of `single-image-viewer-connector` and will update to merge into master once that's merged.~
Also updates the figure caption since `temperature` was redundant.
This can be reviewed using the dev classifier https://localhost:8080/?project=4878&workflow=16135&env=production at or the project app at: http://localhost:3000/projects/adamamiller/stellar-sleuths/classify
Here's a screenshot:
Note that the overall height …
=> [VSLCV] dynamic image size

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/README.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/isDataSeriesVisible.js
A regression was introduce in one of the recent changes for the VSLCV, so this PR fixes it. The stand alone scatter plot was missing fill colors for the data points:
I fixed this by adding some more specs to test for fill color on the glyphs. I also added specs for the `isDataSeriesHighlighted`, a readme, and defaulted it to highlight. Additionally, I renamed everything 'visibility' named to 'highlight' to better reflect the actual function of the feature.
Now we see fill colors by default:
This can be manually confirmed by running `yarn storybook` in the `lib-classifier` folder and checking  out the …
=> Fix color regression in scatter plot

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
Closes #1548
This add's vx's `withParentSize` HOC to the `VariableStarViewer` to get the parent container's width as a prop. If the parent container width is less than or equal to 768, then we fallback to a single column layout. This isn't great, but it's better than nothing and we can consider additional messaging or alternatives based on if we get feedback about it during the beta.
This can be viewed by running `yarn bootstrap` first from the parent repo folder, then going into the `app-project` folder and running `yarn start` and going to http://localhost:3000/projects/adamamiller/stellar-sleuths/clas …
=> [VSLCV] Responsive grid

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
Closes #1847 
In the renaming of visibility to highlight, I missed the renaming for the on change handler in passing it down as a prop.
This can be tested using the dev classifier at: https://local.zooniverse.org:8080/?env=production&project=4878
~Ignore the style issue with the three checkboxes as this is scoped specifically to fix the on change handler.~ The subject data that had three data series has been removed for now, so ignore this comment!
=> [VSLCV] Fix the missed renamed prop for the checkbox on change handler

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/helpers/constants.js
Closes #1848 
Updates the calculation for the phased period bar chart based on request in #1848. This can be tested by using the dev classifier: https://localhost:8080/?env=production&project=4878 and using the phase multiple radio buttons. The period bar chart values should update depending on the multiple value chosen. The specs have been updated to check that the value is additive not multiplicative now.
The dynamically calculated y-axis domain also is updated for its minimum using the extent since we are not using absolute values anymore either.
=> [VSLCV] Updated phased bar chart calculation

packages/app-project/pages/_app.js, packages/app-project/src/components/ProjectHeader/ProjectHeader.js, packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.js, packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.spec.js, packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/index.js, packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/locales/en.json, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/index.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.js, packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.spec.js, packages/app-project/src/shared/components/StandardLayout/index.js, packages/app-project/stores/Project.js, packages/app-project/stores/Project.spec.js
We were missing the visual indicators for projects under review aka in beta. This involved adding a few of the project resource properties to its store model, a getter view for the beta state, some new components for the 'under review' label, connecting some existing components as well as refactoring the layout to be able to display the border.
Compare the Stellar Sleuths project home page and classify page, currently in the beta state, now with teal border and label:
To TESS which is launched approved, no teal border and label:
It'd be great if we could have this reviewed and ready for merge on Monday.
=> Add visual indicators that project is in beta aka under review

kubernetes/deployment-production.tmpl
avoid hard coding the number of PDB replicas, instead use a percent of the available replicas https://kubernetes.io/docs/tasks/run-application/configure-pdb/ (the underlying value rounds up to, e.g. 50% of 1 results in 1)
This allows more lenient eviction rules for the relevant pods. I came across pods that wouldn't evict due to the PDB settings when doing the cluster / node pool upgrades the other day. Specifically from https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
> If you set maxUnavailable to 0% or 0, or you set minAvailable to 100% or the number of replicas, you are requiring zero voluntary evictions. When you set zero voluntary evictions for a workload object such as ReplicaSet, then you cannot successfully drain a Node running one …
=> switch pdb to percent of available replicas

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/README.md
Adds a readme on the expected configuration and JSON data for the viewer to work.
=> Add readme for DataImageViewer

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
Package:  lib-classifier
I've hardcoded some margin and offset values to make sure the y-axis label doesn't overlap with the y-axis tick labels. This is so the subject viewer looks nice for the workshop next Tuesday. Future iteration of this would allow this to be set by either the subject JSON data configuration or by the workflow configuration. To manually check this, run `yarn dev` in the lib-classifier folder and go to https://localhost:8080/?project=10996&workflow=16264&env=production. The current issue can be seen on the preview site: https://frontend.preview.zooniverse.org/projects/mrniaboc/superluminous-supernovae/classify/workflow/16264
=> [DataImageViewer] Hard code margin and label offset for workshop

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
This implements a layout for the DataImageViewer for narrow screen sizes like we see on mobile. This can be previewed using the storybook, run `yarn storybook` in the lib-classifier folder, and check the DataImageViewer > Narrow view story. Note that the simulated device type screen size can be changed using a dropdown menu just above the story render area. Here's also a gif preview:
=> DataImageViewer responsive layout

Jenkinsfile
Consolidate the build step into a single script, to avoid undefined environment variables.
=> Fix broken Jenkins builds

README.md, docs/arch/adr-12.md, packages/app-content-pages/README.md, packages/app-project/README.md
Package: app-content-pages, app-project
Since #1887 has been merged, I'm reviewing to make sure I understand and found several places the docs didn't get updated.
- Remove outdated instructions on running production docker compose files.
- Add note about running from top level if production testing is needed based on this comment from the original PR:
> I've made the assumption that if you're using Docker for an individual package, you're doing development work on that package. If you're using Docker at the top level, it's because you want to start all the services and see how they'll work together in production.
- Updated status of ADR 12 to …
=> Update the docs that got missed from #1887

kubernetes/deployment-staging.tmpl
these were being killed in the k8s cluster due to OOM errors increasing to 500MB for each app should help
```
Containers:
fe-project-staging:
....
Port:          3000/TCP
Host Port:     0/TCP
Command:
yarn
workspace
@zooniverse/fe-project
Args:
start
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    1
Started:      Wed, 09 Dec 2020 17:22:21 +0000
Finished:     Wed, 09 Dec 2020 17:22:31 +0000
Ready:          False
Restart Count:  30
```
Package:
Closes # .
=> increase ram limits for staging apps

packages/app-content-pages/package.json, packages/app-content-pages/src/screens/Publications/getStaticProps.js, packages/app-content-pages/src/screens/Team/getStaticProps.js, packages/app-project/package.json, yarn.lock
Upgrade next to 9.5.5 and change `unstable_revalidate` to `revalidate` for static pages.
Specify `dist: bionic` for the Travis builds.
Package:
app-project
Closes #1829.
=> Upgrade NextJS to 9.5

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
Package: app-project, app-content-pages
The newrelic package has to be updated to version 7 to support node 14. I'm not sure how to test this other than check that the docker containers build, which they do for me.
=> Update newrelic to version 7 in preparation of node 14 update

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request--data-store--ops--etc.md, .github/ISSUE_TEMPLATE/feature-request--ux--ui--accessibility--design--etc.md
Replace the bold strings in issue templates with headings, to improve accessibility for assistive technology.
=> Accessible headings for issue templates

packages/app-project/pages/_app.js, packages/app-project/pages/_document.js, packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js, packages/app-project/src/helpers/logger/logReactError.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.spec.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/index.js, packages/app-project/stores/initStore.js
This replaces [`_app.js`](https://nextjs.org/docs/advanced-features/custom-app), `ProjectHomePageContainer` and `ClassifyPageContainer` with functional components. It also fixes a small HTML bug by adding the required `lang` attribute to every page, and build warnings about a missing `Html` component on every page.
I've also added a `useStore` hook to create the MobX State Tree store, both on the server and in the browser, based on [the latest NextJS MST example](https://github.com/vercel/next.js/tree/master/examples/with-mobx-state-tree/pages).
This is the first of a series of PRs where I'll be replacing class components with functions in the project app. I'm hoping that this will give us [faster page build times and a smaller memory …
=> Project: remove classes for _app and page containers

packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js, packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js, packages/app-project/src/shared/components/ContentBox/ContentBox.js, packages/app-project/src/shared/components/ContentBox/ContentBox.spec.js, packages/app-project/src/shared/components/NavLink/NavLink.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js
This extends #2019 to fix broken links to project pages from the dropdown navigation menu (used on small screens or projects with really long names), content boxes (the Stats link) and the project introduction (Learn More.)
The `NavLink` component is generalised to remove any default link styles and allow any Grommet Anchor prop to be passed in as a prop. `DropdownNav`, `ContentBox` and `Introduction` are updated to replace `next/link` with the `NavLink` component. The project `Nav` component is updated to pass styled Anchor and Text components down to each menu item, now that these aren't the defaults for each link.
Not included here:
- remove the deprecated `as` prop from links (#1973.)
- ~~add tests for the `DropdownNav` component, beyond the smoke test that it currently has.~~
- maybe …
=> Project: Fix all the broken links

packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js, packages/app-project/src/helpers/fetchProjectData/fetchProjectData.spec.js, packages/app-project/src/helpers/fetchProjectData/index.js, packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js, packages/app-project/stores/Project.js, packages/app-project/stores/Project.spec.js
Remove `project.fetch` from the Project model. Replace it with `helpers/fetchProjectData`, which is imported into `getStaticPageProps` and only runs on the server. That should remove unused API code from client-side code bundles.
> Note: You can import modules in top-level scope for use in getServerSideProps. Imports used in getServerSideProps will not be bundled for the client-side.
>
>This means you can write server-side code directly in getServerSideProps. This includes reading from the filesystem or a database.
https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering
Package:
app-project
=> Project: fetch project data on the server

packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js, packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js, packages/app-project/src/shared/components/NavLink/NavLink.js, packages/app-project/src/shared/components/NavLink/NavLink.spec.js
Restore external link behaviour for project navigation links, which I removed in #2026.
Add the `isPFELink` check back to `NavLink`. Render an external link to PFE if `isPFELink` is true and we're using the production API.
Test URL:
http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess?demo=true&env=production
Clicking on 'Classify' should render the Classify page client-side, requesting the page props as JSON. If `PANOPTES_ENV` is production, clicking on About should load the research page from zooniverse.org with a full page refresh. Clicking on 'Learn more' should also force a full page refresh.
Try it out with
```
PANOPTES_ENV=production yarn dev
```
or
```
yarn build && yarn start
```
Running a local dev build (`$PANOPTES_ENV=staging`) should still allow you to preview …
=> Project: Restore external link behaviour for nav links

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
These are suggested test improvement or additions for #2071
=> Test suggestions for #2071

.github/ISSUE_TEMPLATE/feature-request--ux--ui--accessibility--design--etc.md, docs/PULL_REQUEST_TEMPLATE.md
Removes Becky from the issue templates.
=> Remove Becky from the issue and PR template

packages/lib-classifier/src/components/Classifier/Classifier.js
Define a global store for the `useStore` hook, so that useStore doesn't generate a new, empty store on every re-render of the Classifier. Check for a valid project before updating the store on project change. Add the passed project prop to the initial store snapshot.
When I added the `useStore` hook to the classifier in #2101, I missed that [`store` should be global](https://github.com/vercel/next.js/blob/5201cdbaeaa72b54badc8f929ddc73c09f414dc4/examples/with-mobx-state-tree/store.js#L4). This PR fixes that oversight, and updates the other classifier hooks so that we never initialise the classifier store with an empty project (if there's a `project` prop.)
To check this against the original issue, you'll need to build the classifier, then start up the project app (with the newly built …
=> Classifier: fix store re-renders

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
Upgrade the Sentry clients to 6.3.6.
Package:
app-project
=> Upgrade Sentry to 6.3

packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.spec.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.spec.js, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.spec.js
Package:
app-project
This PR adds spec files and tests for components specific to the project About Pages (`AboutMarkdownz`, `AboutNavLink`, `TeamMember`)
=> Add spec files and tests for About Pages components

packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.spec.js
Closes #2180 
I extracted out the transcription line mark into a separate component in #2159, so I could conditionally render a tooltip, but forgot to wrap it in a `mobx-react` observer. This adds the observer to it. 
If anyone has ideas on how to test to make sure a component is decorated by a particular decorator, I'm open to suggestion.
Manually testable with: https://localhost:8080/?project=11300&env=production&demo=true
And the transcription line story, to check that it works outside of the transcription task context.
=> Observe TranscriptionLineMark

packages/app-project/.storybook/webpack.config.js
This should fix broken storybook deploys.
`yarn storybook` builds and serves the `app-project` storybook.
`yarn deploy-storybook --dry-run` builds all the storybooks without errors.
```asosxlap127:front-end-monorepo odonnell$ yarn deploy-storybook --dry-run
yarn run v1.22.10
$ storybook-to-ghpages --packages packages --dry-run
=> Getting the git remote URL
executing: git config --get remote.origin.url
=> Building storybook for: @zooniverse/fe-content-pages
executing: build-storybook  -o out4103
=> Building storybook for: @zooniverse/fe-project
executing: npm run build-storybook -- -o out4103
=> Building storybook for: @zooniverse/classifier
executing: npm run build-storybook -- -o out4103
=> Building storybook for: @zooniverse/react-components
executing: build-storybook  -o out4103
=> …
```
=> Project: Use @sentry/browser in storybook builds

README.md
Package: N/A
Updates the readme based on latest experience publishing.
=> Update readme on publishing

packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
Package:
app-project
Toward #2213.
On FEM preview, team members rendered on a project's team page were missing placeholder avatars, and listing a `0` when not assigned any roles. Example: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team
This PR fixes those two styling bugs.
=> Clean up team array

packages/lib-react-components/CHANGELOG.md
Package:
-Record change to `LinkList` height in PR #2222.
-Record change to `Markdownz` to provide backwards compatibility for custom image sizes in PR #2153.
=> Update lib-react-components Changelog

Dockerfile, packages/app-project/next.config.js
Publish the latest commit hash to https://fe-project.zooniverse.org/commit_id.txt during Jenkins builds.
Linked to https://github.com/zooniverse/lita/pull/105, which enables lita to check the status of the monorepo by pinging this file.
To test this out locally, build an image then check the `commit_id.txt` file was created inside the image.
```
docker compose build --build-arg COMMIT_ID=05503fc5
docker compose run --rm bash
cd packages/app-project/public
ls
exit
```
You can also check that the file is served by running the Next app locally with `docker compose up` then browsing http://localhost:3000/commit_id.txt. Remember to run `docker compose down` when you're finished with the container.
=> Publish /commit_id.txt during builds

packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js, packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js, packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js, packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
Package:
- add DrawingTask tests for isComplete view
- refactor Step.isComplete for incomplete drawing task (for below minimum marks or incomplete subtask)
=> Refactor Step isComplete

packages/app-project/pages/projects/[owner]/[project]/about/team.js
Package:
app-project
Closes #2213.
The team page data is being fetched correctly on the deployed preview for PH TESS, but the same team data wasn't fetched for PH TESS locally. Passing the `env` param in the `query` object for getting `/project_roles` and then `/users` within `getServerSideProps` solves this bug.
Can be tested with PH TESS deployed: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team
and PH TESS run locally: http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess/about/team?env=production
=> Team Page: Pass env param when fetching team members data

packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitation.stories.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js
I missed updating the store connector for the authentication invitation banner since my refactor on the stores for the UPP integration and it didn't cause a merge conflict, so it was missed on my part. 
You should be able to build the project app and run `yarn start` and go to http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess
Compare to current staging where it's broken: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess
=> Update store connection to reflect recent refactor for UPP.

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
after auditing the FEM running apps after ~19 hours, this PR introduces changes to how much RAM and CPU resources are requested and limited. 
Specifically this PR decreases the RAM use of both apps but allows significant growth if needed. It also decreases the CPU requests and increases the limits to 1vCPU should they need this capacity.
the fe project app  uses ~270MB
```
zooniverse-org-project-production-6fbd9bd96b-bl7n9        fe-project-production                   2m           262Mi           
zooniverse-org-project-production-6fbd9bd96b-k8nnr        fe-project-production                   2m           211Mi 
```
- content pages app uses ~170MB RAM
```
zooniverse-org-content-pages-production-c94b68455-pn6dl   fe-content-pages-production             2m           168Mi
```
_Please …
=> modify cpu and memory resource requests and limits

packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js, packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js, packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js, packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
Package:
Closes #2252 
The `TextTask` instructions should be rendered using `Markdownz`. This fixes that.
Before: https://frontend.preview.zooniverse.org/projects/srallen/untitled-project-3-25-2021-12-33-27-pm/classify/workflow/18818
After: https://localhost:8080/?project=15565&workflow=18818&env=production
=> Use Markdownz to render text task instructions.

packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js, packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Closes #2234 in preparation of #2249
This adds the workflow order logic from PFE to the project app here. I need correct ordering for Gravity Spy (and other projects).
Incorrect order on Gravity Spy using the new project app (https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy):
Correct order on Gravity Spy using this branch:
And intended order can be confirmed in the lab using the reorder view: https://www.zooniverse.org/lab/1104/workflows
=> Add reordering logic to workflow fetch in project app

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.stories.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/mock-data/task.js
Package:
Towards #1991.
Staging:
- https://local.zooniverse.org:8080/?project=1634&workflow=2434
- conditionally adds focus to Choice components, as follows:
- Choice with more than one image focus (after 1 tab) on Carousel
- Choice with no images, yes confusions, focus on first confusion button
- Choice with no images or confusions, yes questions, focus on first question
- if first question is checkbox then first input gets focus
- if first question is radio and no existing answer then first input gets focus
- if first question is radio and existing answer then existing answer gets focus
- Choice with no images, confusions, or questions focus is on "Identify" button
=> Add conditional focus to survey task Choice components

packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js, packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js, packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.spec.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js, packages/app-project/src/shared/components/SubjectPicker/locales/en.json
Convert `checkRetirementStatus` to use the `subjects/selection` endpoint (with the current user's auth token), which gives us the already seen and retired status of each subject. Subjects have three possible statuses now: 'Unclassified', 'Already seen' and 'Retired'.
I've also localised the subject statuses so that they can be translated.
You can try it out on the Index or Minutes workflows for Scarlets & Blues, although those subjects are all unclassified at the moment.
http://localhost.zooniverse.org:3000/projects/bogden/scarlets-and-blues?env=production
Package:
app-project
Closes #1955.
=> Engaging Crowds: Subject Picker: add Already Seen status

packages/app-project/package.json, packages/lib-classifier/package.json, yarn.lock
Package: fe-project, lib-classifier
This PR updates the underlying PJC to v3.3.2, specifically to include the changes that improve the bearer token refresh event handling and decrease the time expose to scenarios where the API token may have expired.
See https://github.com/zooniverse/panoptes-javascript-client/blob/master/CHANGELOG.md#v332-2021-05-07 for specific version changes
~Also this PR removes the PJC as a `devDependency` in lib-classifier. I'm not sure why this is included as the fe-project injects it's version of the PJC via the classifierWrapper. If this is for testing perhaps better use of test doubles here can help vs the `devDependency` - TBC pending the test runs.~
=> Update pjc lib

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-react-components/package.json, yarn.lock
Package: several
Related to #2301 
This just installs react-testing-library as a dev dependency so we can start experimenting with it.
=> Add react-testing-library

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.stories.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.stories.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
Package:
- remove `height: 100%` styling in Choices component, fixing Safari issue
- refactor survey task stories (though still plan remove and restructure more in subsequent PR) 
Staging:
- https://local.zooniverse.org:8080/?project=1634&workflow=2434
=> Refactor survey task Choices styling for Safari

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
Fixes a regression introduced by #2198. A refactor was included among the feature which swapped the store connection over to a separate connector file using the newer mobx-react API, however, not all the data needed was copied over. Since `tutorial` was missing, the tutorial has never rendered correctly in the tabbed view:
I added a smoke test for the connector using react-testing-library. Actually testing that the tutorial is viewable should come later via more refactoring on the test strategy on child components since this will necessarily have to be an integration test, so that will come later.
=> Fix tutorial

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-classifier/test/setup.js, packages/lib-react-components/package.json, yarn.lock
Package:
`app-content-pages`
`app-project`
`lib-classifier`
`lib-react-components`
Adds the testing library `chai-dom`. This is an extension to the `chai` assertion library and provides a set of assertions when working with the DOM (specifically, HTMLElements and NodeList)
[chai-dom docs](https://www.chaijs.com/plugins/chai-dom/)
=> Add chai-dom package

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js
Package:
- refactors RTL tests removing `getByRole` when possible or adding `{ hidden: true}` to remaining role based queries
=> Refactor survey task Choice and Questions RTL tests

packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js, packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js, packages/app-project/src/shared/components/WorkflowSelector/components/index.js
- remove the deprecated `onSelect` handler for workflow buttons.
- add subcomponents.
- add prop descriptions to the component.
- add controlled args to the individual stories.
http://localhost:9001/?path=/docs/project-app-shared-workflow-selector--default
Package:
app-project
Towards #2370.
=> Project: Tidy up WorkflowSelector stories

packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
Follow up from #2418. There was a missing existential check for the workflow configuration in the effect hook. If you navigate to the classify page using the project nav bar, the app was crashing because `workflowFromUrl` didn't exist.
Found while I was testing Gravity Spy on the front end preview site, so you can confirm the fix manually by running the project app and checking that as well: https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy?env=production
Use the project navigation bar link to just `/classify` and confirm the page loads and does not crash.
=> Existential check for workflow from the url

packages/lib-classifier/src/store/README.md
Adds a basic top level read me about the classifier store based on our conversation today.
=> Store docs

packages/lib-classifier/src/store/feedback/README.md, packages/lib-classifier/src/store/feedback/strategies/drawing/column/README.md
Adding some general feedback docs.
=> Feedback docs

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js, packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
Package:
- app-project
Closes #2461 .
- refactors ClassifyPage to set `canClassify` (which determines if WorkflowMenuModal is shown) based on `workflowID` instead of `workflowFromUrl` (which requires the full workflow resource, and if the workflow ID in URL is a complete workflow then that workflow resource will not be requested in `app-project` per `fetchWorkflowHelper`)
Links:
- CAUTION - PRODUCTION PROJECT - https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production
- https://local.zooniverse.org:3000/projects/markb-panoptes/all-completed-workflows/classify/workflow/3111
NOTE:
this does not fix:
- https://local.zooniverse.org:3000/projects/markb-panoptes/all-completed-workflows/classify (I'm not sure what should happen?)
=> Refactor ClassifyPage canClassify per workflowID

yarn.lock
=> Bump NextJS

packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
Split `createClassificationObserver` into `createClassificationPostObserver`, which should run when we post a new classification, and `createClassificationChangeObserver`, which should run when the active classification changes.
#2520 added a listener to the subject store, which starts a new undo history when a new subject loads. A side effect of that has been that `subjects.advance()` runs once for the first subject you classify, twice for the second, three times for the third etc. This PR should fix that bug, so that only one new subject loads after each classification is submitted.
Package:
lib-classifier
=> Classifier: Refactor SubjectStore createClassificationObserver

packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js, packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
Package:
Closes #2556.
I could only reliably recreate issue on app-project, or https://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/18504/subject-set/98887/subject/69734730?demo=true&env=production (then click "Next available subject")
I don't understand why clicking "Next available subject" is causing `subject` to be undefined, therefor causing the destructuring error. Maybe in addition to changes so far, if `subject` is undefined the related task nav button should render and include `disabled={true}` as well?
- adds `subject` optional chaining to task nav button connectors
=> Add subject optional chaining to task nav button containers

yarn.lock
Bump `mime-types` and `panoptes-client`. `panoptes-client@3.3.4` includes a bugfix for missing Auth headers when a classification session lasts longer than 2 hours.
This update includes https://github.com/zooniverse/panoptes-javascript-client/pull/149, which fixes a bug where `authorization` here is undefined if I submit a classification more than 2 hours after I started it. That leads to classifications which are saved but not linked to a user account, so not included in Recents or Already Seen.
https://github.com/zooniverse/front-end-monorepo/blob/cefbb27ff23a2b172346e60f15f751ad8c8ca4c5/packages/lib-classifier/src/store/utils/ClassificationQueue.js#L63-L67
Package:
app-project
=> Bump mime-types and panoptes-client

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
Upgrade `@sentry/node` and `@sentry/browser` to 6.16.
Package:
app-project
=> Upgrade Sentry

package.json, yarn.lock
Upgrade lerna to 4.0. Includes a security update for `glob-parent`.
=> [Security] Upgrade lerna

packages/lib-classifier/.babelrc, packages/lib-classifier/package.json, packages/lib-react-components/.babelrc, packages/lib-react-components/package.json, yarn.lock
Class properties are now supported in Babel without a plugin.
This should fix the following warning, which is making the build and test logs very noisy.
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```
Package:
lib-classifier …
=> Remove @babel/plugin-proposal-class-properties

packages/lib-react-components/package.json, yarn.lock
This upgrades `remark` from 10 to 11. 12 has breaking changes with our plugin setup.
I've also upgraded the rehype plugins and `remark-react` to 8.0, which is the latest version that supports CommonJS exports. ESM modules break our test setup.
Note that [`remark-react`](https://www.npmjs.com/package/remark-react) is no longer supported, so long-term support for markdown in the project builder might involve a migration of our code to `rehype-react`.
A full scale upgrade of `remark` and plugins to the latest version breaks our setup (#2608), so I've chosen to go down the route of gradually upgrading here to the latest versions that don't break our builds or tests.
Package:
Towards #2607.
=> Upgrade remark to 11

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-react-components/package.json, yarn.lock
Upgrade all outdated `@babel` packages to 7.16.
Package:
app-project
lib-classifier
=> Upgrade babel

packages/app-project/.storybook/main.js, packages/lib-classifier/.storybook/main.js, packages/lib-react-components/.storybook/main.js, yarn.lock
[Storybook 6.4.13](https://github.com/storybookjs/storybook/blob/v6.4.13/CHANGELOG.md) includes a fix for `process` in Webpack 5.
Package:
app-project
lib-classifier
Closes #2656.
=> Bump storybook to 6.4.13

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
Package:
Closes #2499.
Testing:
- (WARNING - production project) https://local.zooniverse.org:8080/?project=9006&workflow=19684&env=production&demo=true
- adds `minZoom={0.1}` to MultiFrameViewer, mirroring [SingleImageViewer](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js#L136)
Question:
- should [the default maxZoom and minZoom values in SVGPanZoom](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js#L145-L146) be updated to reflect the zooms actually used in …
=> Add minZoom 0.1 to MultiFrameViewer

packages/app-project/package.json, packages/app-project/test/create-global-document.js, packages/lib-classifier/package.json, packages/lib-classifier/test/setup.js, yarn.lock
Upgrade `graphql-request` to 3.7. Includes security fixes for `node-fetch`.
Package:
app-project
lib-classifier
=> [Security] upgrade graphql-request

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
=> Bump babel-plugin-styled-components to 2.0.2

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
=> Remove log from ProjectHomePage > RecentSubjectsContainer

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js, packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js, packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js, packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js
- Replace `@inject` with `@helpers/withStores`.
- Rewrite `FeedbackModal` as a functional component.
- Rewrite `Graph2dRangeFeedback` as a functional component.
- Wrap `drawFeedbackBrushes` in `useCallback`.
- Fix feedback colours when the SVG is first rendered.
Try it out on Planet Hunters: TESS in the dev classifier.
https://local.zooniverse.org:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true
or PH Staging while the live project is offline.
https://local.zooniverse.org:8080/?project=nora-dot-test/planet-finders-beta&demo=true
Package:
lib-classifier
Closes #2877.
=> Classifier: Refactor FeedbackModal. Remove @inject.

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
I've changed the `useEffect` hook in `ClassifierContainer` to:
- Restrict the new side effects to projects that have `cachePanoptesData` set, so they shouldn't affect projects like PH TESS or Beyond Borders.
- Advance the subject queue after a reset, which should request new subjects from Panoptes.
Package:
lib-classifier
Closes #2891.
=> Classifier: fix empty subject queue on load

packages/app-project/package.json, packages/lib-classifier/package.json
app-project
lib-classifier
`counterpart` is no longer used for anything in lib-classifier or app-project, so this PR uninstalls it from those packages.
All fine-grained review of converting the two package's components from `counterpart` to `i18next` is already complete. This PR requires only big picture review. 
- Check that `yarn bootstrap` runs as expected
- Check that lib-classifier's storybook runs locally
- Check that app-project's storybook runs locally
- Check that [TESS](https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?env=production) loads locally by running app-project
Translations project board: https://github.com/zooniverse/front-end-monorepo/projects/15
=> Uninstall counterpart from lib-classifier and app-project

packages/app-project/public/locales/en/screens.json, packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.js
app-project
WidgetHeading inside YourStats wasn't rendering text because the string was assigned to `text` instead of `children`. WidgetHeading expects `children`. DailyClassificationChart already has a WidgetHeading, so I removed the extra from YourStats and also deleted the unused translation key from the dictionary.
Visit any project such as [Ultraman](https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022/classify/workflow/3581) workflow while signed in, and check that the daily classification chart in the Your Stats area has a heading that says "[Project] Daily Classification Counts".
=> App-project: Remove unused YourStats translation key

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.spec.js
Remove subject viewer tests that check details of the implementation, like `componentDidMount`, `componentDidUpdate` and internal component state.
Instead, test the component's rendered output and callbacks after mounting with and without a subject. This makes the tests more robust and opens up the path for converting the viewer from a class to a function with hooks.
The tests here are based heavily on the new tests that I wrote for the bar chart viewer in #2719.
[Testing Implementation Details](https://kentcdodds.com/blog/testing-implementation-details) by Kent Dodds is a good argument for retiring these old unit tests for class components.
Package:
lib-classifier
=> SingleTextViewer: remove implementation tests

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/store/ResourceStore/ResourceStore.js, packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.js
- When the classifier mounts, reset the UPP store to clear any stale user state that might persist in the global store.
- Update the `ResourceStore` model to reset loading state on reset.
- refactor `tutorial.hasNotBeenSeen`.
This fixes #2954 by forcing the classifier to check for a logged-in user after mounting, even if the classifier mounts with an existing store from a previous session in the same window/tab. The popup tutorial should wait for that user check to complete before opening.
To test this: log out then log back in on a project where you've already seen the tutorial. The tutorial should open when you log out, but should stay closed when you log back in.
Package:
lib-classifier
Closes #2954.
=> Classifier: always check for a logged-in user on mount

packages/lib-classifier/.eslintrc
Fixes the following error: Parsing error: The keyword 'import' is reserved
Added an .eslintrc file to add correct parser.
N/A
Open any component file in your IDE of choice. The image above is from VSCode.
The first `import` should no longer show an error.
N/A
N/A
=> Added .eslintrc file

packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js, packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.spec.js, packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
For FEM aggregation, all closed shapes (minus Polygon and Freehand Line) must use `x_center` and `y_center` as variable names for position.
This PR updates the Ellipse tool from using `x` and `y` to use `x_center` and `y_center`.
[Local testing url](https://localhost:8080/?env=production&project=16201&workflow=18675)
All Ellipse tool functionality should still work.
1. Create
2. Move both handles to resize
3. Move entire shape
4. Delete
N/A
- Are there plans for follow up PR’s to further fix this bug or develop this …
=> Ellipse Refactor

packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
- app-project
- closes #2991 
- adds tests for project with workflow assignment and workflow ID definition expectations
- adds test for project without workflow assignment and completed workflow
- refactors ClassifyPageContainer workflow ID passed to ClassifyPage component to be undefined if workflow is not allowed per workflow assignment
- (signed-out, workflow assignment, high level, should not have access) https://local.zooniverse.org:3000/projects/srallen086/workflow-assignment-testing/classify/workflow/2619?demo=true&env=staging
- (completed workflow, should have access) https://local.zooniverse.org:3000/projects/markb-panoptes/all-completed-workflows/classify/work …
=> Refactor ClassifyPageContainer workflow ID for workflow assignment and complete workflows

.github/workflows/deploy_staging.yml
The deploy step needs to checkout the repo to have access to the deploy templates. …
=> Add checkout step to app deployment workflow

.github/workflows/deploy_staging.yml
This should fix the ‘Job is not found’ messages in the Slack notifications for deploys. …
=> Fix slack notifications for staging deploys

packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js, packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.stories.js, packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js, packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js, packages/app-project/src/shared/components/Stat/Stat.stories.js, packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.stories.js, packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js, packages/lib-react-components/src/CloseButton/CloseButton.stories.js, packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js, packages/lib-react-components/src/Markdownz/Markdownz.stories.js, packages/lib-react-components/src/Media/Media.stories.js, packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js, packages/lib-react-components/src/MovableModal/MovableModal.stories.js, packages/lib-react-components/src/PlainButton/PlainButton.stories.js, packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js, packages/lib-react-components/src/SpacedHeading/SpacedHeading.stories.js, packages/lib-react-components/src/SpacedText/SpacedText.stories.js, packages/lib-react-components/src/Tabs/Tabs.stories.js, packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js, packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js
app-project
lib-classifier
The best way to test this is probably to start the storybooks, with `yarn storybook`, and compare against the published storybooks at https://zooniverse.github.io/front-end-monorepo
=> Migrate storybooks from `storiesOf` to `CSF`

.yarnrc
Bump yarn with `yarn policies set-version`.
=> Bump yarn to 1.22.19

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
Missed in #3244. This removes an unused authorisation token from `QuickTalk`.
lib-classifier …
=> Remove unused auth from QuickTalk

packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
- refactor tests to use `@test/mockStore` for mocks.
- add tests for localised workflow task text.
lib-classifier
Run the tests. Maybe check coverage for `setTaskStrings` in `WorkflowStepsStore`.
=> Classifier: Refactor WorkflowStepStore tests

docs/PULL_REQUEST_TEMPLATE.md
PR template link to VoiceOver Guide was out of date.
=> PR Template: Update VoiceOver Guide link

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Wrap the classifier in [`StrictMode`](https://reactjs.org/docs/strict-mode.html), which triggers additional checks in development.
lib-classifier
Run the dev classifier on https://localhost:8080. You shouldn't really see any changes on this branch, except possibly for stricter error checking in the console. `StrictMode` renders a component twice, which can surface bugs in code that assumes a component is initialised once eg. #3218. …
=> Classifier: React strict mode

Jenkinsfile
This PR removes the master branch from the jenkinsfile setup as we do not want trigger jenkins builds or notifications on master branch - this is now via GH actions.
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-c …
=> remove master branch from jenkins

packages/app-project/public/locales/en/screens.json, packages/app-project/public/locales/test/screens.json, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js
app-project
https://github.com/zooniverse/front-end-monorepo/issues/3384
I added translation keys to screens.json for all TeamMember roles. This will aid in converting PFE dictionaries to FEM dictionaries.
To review by running app-project locally, visit i-fancy-cat's [Team page](https://local.zooniverse.org:3000/projects/test/brooke/i-fancy-cats/about/team), and either manually add `test` to the url or force LocaleSwitcher to be rendered with `availableLocales = ['en', 'test']`.
To review by running app-project's storybook, visit TeamMember's [story](http://localhost:9001/?path=/story/project-app-screens-about-pages-teammember--default&globals=locale:test;locales.en:English;locales.test:Test+Language) and toggle locale with the globe button in the top toolbar.
_PR Creator - Please cater …
=> App-project: Add translation keys for TeamMember roles

packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.stories.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Some small refactors to the freehand drawing tool:
- a `FixedNumber` type which represents numbers that are fixed to 2 decimal places (from #3389.)
- refactor the line path to use a mapped array of points.
- set the visible line width to 1px.
- allow freehand lines to be drawn inside other freehand shapes.
- add `freehandLine.setCoordinates` to match other drawing tools.
- add Freehand Line stories.
lib-classifier
- Follows on from #3389.
There's a Freehand Line story in the storybook, which allows you to draw freehand lines. I've also added freehand lines to my test workflow on staging: https://localhost:8080/?project=908&workflow=3370 …
=> Classifier: refactor freehand line tool

packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
First pass at a responsive layout for tablet screens:
- Subject fills available space on larger screens.
- Fixed task area width of 25.333rem (405px) on larger screens.
- Proportional columns in the ratio 45.333/25.333 on medium screens.
- Single column layout on small screens (less than 700px.)
Pixel widths are calculated assuming a root font size of 16px in the browser. Users may have customised this to fit their own needs eg. enlarged text for poor eyesight.
lib-classifier
- closes #3410.
Try out the project Classify page at a variety of viewport widths, representing different devices. Also try out the Classify page at a variety of page zoom levels (maybe up to 200%?) …
=> Classifier: responsive layout for tablets

packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js, packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js, packages/app-project/stores/User/UserPersonalization/Notifications/helpers/getTalkUnreadNotificationsCount.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js, packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
- towards #2459
- refactor Notifications initial unread notifications request with `panoptes-js` `talkAPI`, in a similar way to [QuickTalk helpers](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-classifier/src/components/Classifier/components/QuickTalk/helpers)
- Which storybook stories should be reviewed? - N/A
- Are there plans for follow up PR’s to further fix this bug or develop this feature? - yes, incoming Messages unread count PRs will also utilize `panoptes-js` `talkAPI`
_PR Creator - Please cater the checklist to fit the review needed for your …
=> Refactor Notifications with panoptes-js talkAPI

package.json, yarn.lock
Reverts zooniverse/front-end-monorepo#3465
=> Revert "Bump lerna from 5.1.8 to 5.2.0"

.github/workflows/deploy_staging.yml
Allows running staging deploys via the Github UI that point to a branch. This will let us easily fix revert broken staging builds to a new branch (checked out from a known good commit or one that needs testing) if the cause of the breakage is unclear.
Also, this will trigger a new round of builds and a staging deploy. …
=> Allow manual staging deploys via workflow dispatch

packages/app-project/package.json, packages/app-project/pages/_app.js, packages/app-project/src/hooks/index.js, packages/app-project/src/hooks/usePanoptesUser.js, packages/app-project/stores/User/User.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js, packages/app-project/stores/initStore.js, packages/app-project/stores/initStore.spec.js, packages/app-project/webpack.config.js
- Save user snapshots to `window.sessionStorage`.
- When a project page first loads in the browser, read user data from session storage and render the page instantly.
- Add a `usePanoptesUser` hook to fetch up-to-date user data in the background.
- Remove `checkCurrent` from the `User` model.
With the changes here, you should see much faster loading times when leaving the project app and returning, eg. going to Talk or your inbox, then returning to the Classify page.
https://user-images.githubusercontent.com/59547/159286530-6407cd0b-9028-4e30-85aa-9ff5fca6c417.mov
Testing checklist (all tested locally on PH-TESS.)
Package:
app-project
Closes #2980.
=> App-project: Persist user sessions in session storage

packages/app-project/public/locales/es/components.json, packages/app-project/public/locales/es/screens.json, packages/lib-classifier/src/translations/es/components.json, packages/lib-classifier/src/translations/es/plugins.json, packages/lib-react-components/src/translations/es.json
app-project
lib-classifier
This PR is a combination of the three auto-generated PR's with Spanish translations from Lokalise.
The only changes are to Spanish .json dictionary files.
- Run `yarn bootstrap` with this branch locally.
- Visit Planet Hunters TESS, and change the locale to Spanish using the language dropdown.
=> Add professional Spanish translations for all FEM packages

packages/app-project/pages/_middleware.js, packages/app-project/server/dev-server.js, packages/app-project/server/server.js
`app-project` middleware which looks for a `language` query parameter and sets the locale.
This allows us to support links to FEM project pages from the PFE project navigation bar (see https://github.com/zooniverse/Panoptes-Front-End/pull/6146), from https://translations.zooniverse.org, and from the Translations page in the Project Builder.
app-project
Try it out with the test locale.
https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/about/research?env=production&language=test …
=> Project: Language middleware

packages/app-project/package.json, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js, packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js, packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js, packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js, packages/app-project/src/helpers/addQueryParams/README.md, packages/app-project/src/helpers/addQueryParams/addQueryParams.js, packages/app-project/src/helpers/addQueryParams/addQueryParams.spec.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js, packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js, packages/app-project/src/shared/components/NavLink/NavLink.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js, packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js, packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js, yarn.lock
A clean rebuild and re-install of `yarn.lock`, to update outdated packages and remove conflicting babel modules.  
- Includes an upgrade of `next` to [12.1.6](https://github.com/vercel/next.js/releases/tag/v12.1.6).
- Updates tests that mock `useRouter`, which fails with NextJS 12.1.6 and higher.
- Closes #3429.  …
=> Maintenance: rebuild yarn.lock. Upgrade NextJS to 12.1.6

packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
Fix a typo in a prop types declaration that was introduced along with project admin mode. 
app-project
Without this PR, the project app will crash with a reference error when you run `yarn dev`.
- It is …
=> Project admin: fix typo

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-grommet-theme/CHANGELOG.md, packages/lib-grommet-theme/package.json, packages/lib-react-components/package.json
- update changelog.
- v3.1.0.
- update installed packages.
Once this is merged, we can `npm publish` the new version to NPM.
lib-grommet-theme
`npm publish --dry-run` will publish the new version without uploading it to NPM.
=> @zooniverse/grommet-theme v3.1.0

packages/lib-classifier/webpack.dist.js
Follow up to #2185 as it's no longer in use but seemed to linger here... …
=> remove seven-ten client

docs/PULL_REQUEST_TEMPLATE.md
I added a new checklist item to the PR template for guidance on adding new translation keys to English dictionaries.
=> PR Template: Add new checklist item for translation keys

yarn.lock
- Bump `next` and `eslint-plugin-next` to [12.3.3](https://github.com/vercel/next.js/releases/tag/v12.3.3).
app-project
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally in Node](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still build and run.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), then check both NextJS apps on localhost.
- [Build and deploy a Docker image of this branch](https://github.com/zooniverse/front-end-monorepo/actions/workflows/deploy_branch.yml), then check the project app on https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess. There's no branch preview on …
=> Bump NextJS to 12.3.3

.github/workflows/deploy_branch.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
Follow up to #3910 and #3770. This PR switches to the Azure/aks-set-context@v3 and adds an explicit login step before using the context as the v1 version had the login step included. 
note v2 had the login step extracted, not v1 …
=> Update gh actions set context version v3

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
- skips longest running survey task tests causing CI tests timeout, alternative while #3933 work continues
- confirm CI tests pass
=> Classifier: Skip some survey task tests

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
Move some duplicated test setup code into `beforeEach()` hooks for each `describe()` block.
lib-classifier
Run the survey task tests.
=> Refactor survey task tests with beforeEach() hooks

packages/lib-grommet-theme/CHANGELOG.md, packages/lib-grommet-theme/package.json, packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json
Bump `lib-grommet-theme` and `lib-panoptes-js` to include dependency updates and updated package descriptions.
lib-grommet-theme
=> Bump library packages

packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json
Require `superagent` 8.0.6 or higher.
=> @zooniverse/panoptes-js v0.2.3

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
Give the classifier the same `max-width` as the rest of the Classify page, so that it doesn't overflow on extra wide displays.
app-project
- fixes #3958.
Load I Fancy Cats and zoom out to simulate an extra-wide display. Or view the Classify page on an extra-wide monitor, if you have one available.
The screenshot of I Fancy Cats, above, uses an effective viewport width of ~2500px on a Retina display.  …
=> Restrict classifier width on wide displays

packages/app-project/public/locales/tr/components.json, packages/app-project/public/locales/tr/screens.json
This pull request was initiated by Lokalise (user Samantha) at 2023-01-06 22:21:59
=> Update Turkish dictionaries in app-project via Lokalise

packages/lib-react-components/src/translations/tr.json
This pull request was initiated by Lokalise (user Samantha) at 2023-01-06 22:12:45
=> Update Turkish library in lib-react-components via Lokalise

packages/lib-react-components/src/ZooniverseLogo/ZooniverseLogo.stories.js, packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogo.stories.js, packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.spec.js
Follows #3750 
Part of: Maintenance Week
This PR adds React Testing Library tests for Zooniverse Logotype, and stories for both Zooniverse Logo & Logotype.
=> Maintenance Week: add tests & story for Zooniverse Logo & Logotype

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
Follow-up to PR #4112 
Update changelog and package.json version. Post-merge I will publish this update to npm.
=> lib-react-components v1.3.3

README.md
Add some instructions for checking out and running the latest production release in Node.
_Please request review from `@zooniverse/frontend` team or an individual member of that team._
=> Instructions for debugging the production release

packages/app-project/next.config.js
=> Bypass the CDN for /projects/_next/static

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
- app-project
- iteration on #4225 
- while the intermittent CDN issue is ongoing, we'll _temporarily_ route production traffic to bypass the CDN (https://fe-project.zooniverse.org bypasses the CDN), and we think avoid the javascript loading issue
- while the intermittent CDN issue is ongoing, we'll use staging (https://frontend.preview.zooniverse.org/) with the CDN, so we or outside support can test/recreate the ongoing javascript loading issues
_PR …
=> Edit next app asset prefixes to bypass CDN on production, go through CDN on staging

Dockerfile
Deploys are failing because they now require Node 18.
- Can be …
=> Fix broken Docker builds

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
Refactor survey task filter button queries to use CSS selectors, which should be faster than the React Testing Library query methods.
lib-classifier
=> Refactor survey task filter button queries

packages/app-content-pages/server/server.js, packages/app-project/server/server.js
Add Sentry Express middleware for error logging.
See https://github.com/zooniverse/sugar/pull/151 and https://docs.sentry.io/platforms/node/guides/express/.
app-project
The project app has a `[owner]/[project]/logger` page, which you can use to generate errors and test error logging in the browser.
https://github.com/zooniverse/front-end-monorepo/blob/0992b36570fd996a5e903e7ba1c5b99285160ced/packages/app-project/pages/%5BpanoptesEnv%5D/%5Bowner%5D/%5Bproject%5D/logger.js#L33-L43
To test errors on the server, you might have to deliberately introduce an error into a page, so that it throws during server-side rendering.
Here's a typical error from Sugar, to give an idea of the level of reporting that the Express middleware gives us. …
=> Add Sentry Express middleware

packages/app-project/pages/_document.js
Add the app deploy environment and release version to logged errors.
app-project
=> Update Sentry logging

packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
app-project
Closes https://github.com/zooniverse/front-end-monorepo/issues/3940
Removed the unneeded min-width property from the middle grid-area in ProjectAboutPage.
Check that projects' /about pages display as expected in all browsers on this branch:
[TESS Research page](https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/about/research?env=production)
[People's Digital Archive Research Page](https://local.zooniverse.org:3000/projects/kmc35/peoples-contest-digital-archive/about/research?env=production)
[i-fancy-cats Team Members page](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/about/team?env=staging) …
=> Fix Safari layout bug on /about pages

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
Disable [default gzip compression](https://nextjs.org/docs/api-reference/next.config.js/compression) in `next.config.js` for both NextJS apps.
app-project
This is deployed to kubernetes, so we can test it out on:
https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess
On staging or production domains, compression should be handled by FrontDoor.
=> Turn off NextJS gzip compression

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
- removes Grommet wrapper from text viewer with labeled text story
- adds all available highlighter color options as defined in https://github.com/zooniverse/Panoptes-Front-End/pull/6538
- http://localhost:6006/?path=/story/subject-viewers-singletextviewer--with-labeled-text&globals=locale:en;locales.en:English;locales.test:Test+Language
- Are there plans for follow up PR’s to further fix this bug or develop this feature? yes - will get @seanmiller26's input on insufficient color contrast with some highlighter label colors
_PR Reviewer - Use the checklist during your review. Each …
=> Classifier: refactor text viewer with labeled text story

yarn.lock
root
Terminal message recommended `npx update-browserslist-db@latest`, so this PR is the result. It updates `caniuse`.
- It is passing accessibility checks in the storybook
=> Run update-browserslist-db@latest

packages/lib-classifier/src/store/utils/README.md
Rewrite the Readme for `/src/store/utils` with examples for all the store utilities.
lib-classifier
- includes the changes to the classification queue from #4736.
=> Classifier: updated Readme for store utils

packages/lib-classifier/src/store/FieldGuideStore/FieldGuideStore.js
- closes #3295 
- edits field guide attached media request with `page_size: 100`
- ^ fixes bug with field guides with items > 20 not showing item icon images
- ⚠️ live project ⚠️ - https://local.zooniverse.org:8080/?project=1104&env=production&demo=true&workflow=1610
- open field guide, note all items' icon images show
- Are there plans for follow up PR’s to further fix this bug or develop this feature? yes - tests should be refactored with nock, will revisit asap, but with a June 21st deadline for linked issue opening this PR as is …
=> lib-classifier: Edit field guide attached media request

packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Validate the current bearer token before refreshing the subject queue. Log any token errors to Sentry, tagged with `subjectQueueError:tokenError`.
lib-classifier
Subject selection shouldn't be changed. In the event that `getBearerToken` returns an invalid token (this should never happen!), the error should be logged to Sentry. …
=> Validate auth'ed subject queue requests

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js, packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js, packages/lib-classifier/src/hooks/useProjectPreferences.js, packages/lib-classifier/src/hooks/useProjectRoles.js
Wait for API calls to resolve for anonymous users, and make sure that both UPP and project roles are null when no one is signed in.
Make sure that the project and workflow have loaded before rendering the classifier (see #5012.)
lib-classifier
- closes #5009. 
The modal tutorial should show now for anonymous users. It's set to automatically open when the project preferences are null.
UPP loading state should also be properly set to 'success' for anonymous users. …
=> Show modal tutorial for anonymous users

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Set the classifier callbacks whenever the callback props change.
Fix the missing `subjectID` parameter for `onAddToCollection`.
lib-classifier
- closes #4977.
- closes #5013. 
- Can be used from the keyboard [WebAIM guide to …
=> Update classifier when callbacks change

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
lib-classifier
Added inline code comments explaining logic in ClassifierContainer and Classifier. I'll add a couple of Github comments with my questions about sequence of events (data fetching, updating store etc).
=> Document the ClassifierContainer and Classifier with code comments

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
Refactor `useCallback` hooks in `ClassifierWrapper` to remove warnings (from `eslint-react`) and clean up their dependency arrays.
Refactor subject URL routing to use a `useEffect` hook, triggered by changes in the classifier subject (see #4977.)
app-project
- closes #5036.
- Can be used from the keyboard [WebAIM guide …
=> Lint ClassifierWrapper callbacks

packages/lib-grommet-theme/README.md
=> Updated design system links

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.js
Enable data selection tools in the scatter plot viewer, so that we can test them out on workflows that use the data selection task (see https://github.com/zooniverse/Panoptes-Front-End/pull/6808.)
lib-classifier
- https://github.com/zooniverse/Panoptes-Front-End/pull/6808
See https://github.com/zooniverse/Panoptes-Front-End/pull/6808 for details of the staging project and workflow that has this tool set up. 
It should only be active for workflows that use the data annotation task, so SuperWASP Black Holes shouldn’t be affected by the changes here. 
_PR Reviewer - Use the checklist during your review. Each …
=> Enable the experimental data selection tools.

packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js, packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Upgrade `Graph2dRangeFeedback` from the `LightCurveViewer` to the `JSONDataViewer`. Refactor component props to pass the feedback brushes down, rather than a callback function.
lib-classifier
- towards #5297.
Subject 90833319 is a training subject for PH-TESS, so you can test these changes with that subject:
https://local.zooniverse.org:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true&subject=90833319
Note that #5270 will need to be merged first, otherwise the light curve and feedback won't render in the dev classifier.
_PR Reviewer - Use the checklist during your review. Each …
=> Generalise graph2dRangeFeedback for JSON subjects

docs/ADR_TEMPLATE.md
We discussed best practices in the frontend team standup around ADRs that supersede decisions made in older ADRs. This PR adds a clarifying note to the ADR template.
=> Add notes to ADR Template file

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/src/Media/components/Data/components/DataSeriesPlot/helpers/utils.js
Fix ESM loading errors by importing `d3-array` via `@visx/vendor`, which is distributed as both CommonJS and ESM.
- closes #5340.
Example Staging …
=> ZRC: import @visx/vendor/d3-array

packages/lib-classifier/dev/components/App/App.js, packages/lib-classifier/src/hooks/useCaesarReductions.js, packages/lib-classifier/src/hooks/useTranscriptionReductions.js
- Fix a couple of race conditions in Caesar data-fetching by [adding an `ignore` flag](https://react.dev/reference/react/useEffect#fetching-data-with-effects).
- Fix dropdown menus in the dev classifier, so that they always reflect the language and workflow in the URL.
- closes #5415.
On a project like Davy Notebooks, you shouldn't see store errors after changing workflow in the dev classifier.
https://localhost:8080/?project=humphrydavy%2Fdavy-notebooks-project&env=production&demo=true&workflow=25217&language=test
The dev classifier's select menus should also reflect the language and workflow in the URL.
_PR Creator - Please cater the checklist to fit the review needed for …
=> Fix transcription task errors for async Caesar reductions

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js, packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js, packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
Refactor field guide item anchors. Configure `react-rnd` to ignore clicks on buttons and item links.
- Field Guide doesn't work on an iPad: https://www.zooniverse.org/projects/elliereed185/knitting-leaflet-project/talk/4675/3112459?comment=5095774
- closes #5422.
On a touch device with a medium-sized viewport, or in the Firefox touch emulator, you should be able to open the field guide and navigate the items with touch. …
=> Fix Field Guide movable modal on touch devices

bin/bootstrap.sh, packages/lib-classifier/package.json, packages/lib-react-components/package.json
Use `prepare` to build both `@zooniverse/react-components` and `@zooniverse/classifier` during installation. Build both ESM and CJS modules so that the tests run. Switch the bootstrap script to use `yarn install` during local builds.
lib-classifier
```sh
yarn panic
yarn bootstrap
cd packages/app-project
yarn start
cd ../app-content-pages
yarn start
```
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/a …
=> Build libraries with 'npm prepare'

README.md
Fixed typo in main README.md of the repo.
- Can be used with a …
=> Fix #5510 - typo in readme

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/src/SpacedHeading/SpacedHeading.js
(and update version in others)
Bumped the lib-react-components version to 1.8.1
While using SpacedHeading in https://github.com/zooniverse/front-end-monorepo/pull/5578 I discovered that passing a `size` prop does not actually change the font-size of its child SpacedText or span element. I fixed that here.
We use SpacedHeading in a few different places, but none that I could find where the font-size relied on defining a `size` prop. 
- Check the lib-react-components storybook
- Compare places where SpacedHeading is used in the Classifier's [storybook](http://localhost:6006/?path=/story/tasks-survey-choice--default) to the deployed [version](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/tasks-survey-choice--default)
_PR …
=> Pass the size prop to SpacedHeading's child component

packages/lib-classifier/src/plugins/tasks/dropdown-simple/README.md, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.mock.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.spec.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/SimpleDropdownTask.js
lib-classifier
Type to complete search: [#5130 ](https://github.com/zooniverse/front-end-monorepo/issues/5130)
No max limit on items: [#5128](https://github.com/zooniverse/front-end-monorepo/issues/5128)
To see the changes go to [Storybook > Tasks > Simple Dropdown](http://localhost:6006/?path=/story/tasks-simple-dropdown--default)
Add search to the SimpleDropdown task using datalist
=> Add search to SimpleDropdown.

packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json
Bump `@zooniverse/panoptes-js` to keep `jose` up-to-date.
- @zooniverse/panoptes-js
=> Bump @zooniverse/panoptes-js to 0.5.1

packages/lib-user/eslint.config.js, packages/lib-user/package.json, packages/lib-user/src/components/UserStats/components/ProfileHeader.spec.js, packages/lib-user/webpack.dev.js, yarn.lock
- lib-user
- refactor lib-user package from type module to type commonjs for consistent mocha setup with rest of monorepo
- add ProfileHeader tests
- Can be …
=> lib-user: add ProfileHeader tests with mocha, with type commonjs

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
(bump version in all packages)
=> Bump lib-react-components to v1.12.0

packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js, packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.stories.js
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5971
Linked to: https://github.com/zooniverse/front-end-monorepo/pull/5947
Change AnimatedNumber to animate (tween) the number only one time, but after that just update the displayed number to the `value` prop.
- I added a new story for this component that includes a button incrementing the `value` prop. Note that the number animates once, but then simply updates without animating from 0 again when `value` is incremented.
- Steps for testing a project are noted in #5971  …
=> Animated Number bug fix - handle update of value prop

kubernetes/deployment-staging.tmpl, packages/app-root/server/server.js
- app-root
- refactors the app-root k8s probes to check `/users` instead of a non-existent `Index.js`
- changes console.error to console.info in server.js that is expected when in `production` mode
- not sure how to test/confirm other than by deploying (to staging)
=> Refactor app-root probes path

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-content/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-user/package.json
- See the changelog for lib-react-components versioning
- I'll publish to npm when this PR is merged
=> Bump lib-react-components to 1.13.0

packages/lib-content/src/screens/Home/Community/Community.js, packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.js, packages/lib-content/src/screens/Home/DefaultHome/components/Introduction.js, packages/lib-content/src/translations/en.json, packages/lib-user/src/components/UserHome/UserHome.js, packages/lib-user/src/components/shared/Layout/Layout.js
lib-content
lib-user
- Adjust elevation of lib-user Layout to match Community, Homepage, About pages, etc
- Adjust responsive margins of Community and DefaultHome to match lib-user's Layout
- Update copy in DefaultHome's introduction
- Run app-root locally and visit https://local.zooniverse.org:3000 while signed-in and signed-out.
=> Homepage: styling adjustments

packages/lib-user/src/components/shared/BarChart/BarChart.js
- lib-user
- not exactly, but closer to [related Figma design](https://www.figma.com/design/qbqbmR3t5XV6eKcpuRj7mG/Group-Stats?node-id=96-831&m=dev)
- add bar color gradient to BarChart
- What user actions should my reviewer step through to review this PR? reviewing stories probably sufficient
- http://localhost:6008/?path=/story/components-shared-barchart--last-7-days
- Are there plans for follow up PR’s to further fix this bug or develop this feature? see linked GitHub project …
=> lib-user: Add gradient to BarChart bars

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js, packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js, packages/lib-react-components/src/MovableModal/MovableModal.js
Cancel the RnD draggable library on field guide items, so that touch gestures can scroll long items on tablets.
- fixes #6143.
- may also fix #5772.
https://local.zooniverse.org:3000/projects/abbsta/south-coast-threatened-fauna-recovery-project/classify/workflow/21967?env=production should work with touch gestures (tested with the touch emulator in Firefox desktop.)
- …
=> fix(lib-classifier): touch should scroll field guide items

packages/lib-content/src/screens/Home/Community/Community.js, packages/lib-user/src/components/UserHome/UserHome.js, packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabs.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/tabsTheme.js, packages/lib-user/src/components/UserHome/components/UserHomeLayout/README.md, packages/lib-user/src/components/UserHome/components/UserHomeLayout/UserHomeLayout.js, packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.js
lib-content
lib-user
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6151
- Itemized changes are listed in the Issue above. The only item not addresses here is the underline-on-hover links that are in https://github.com/zooniverse/front-end-monorepo/pull/6174 instead.
- lib-user can be run locally to view your logged-in homepage, or app-root can be run locally. 
=> Logged-in Homepage styling updates

packages/lib-user/src/components/Certificate/Certificate.stories.js, packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.spec.js, packages/lib-user/src/components/Contributors/components/MemberStats/MemberStats.js, packages/lib-user/src/components/Contributors/components/ProjectStats/ProjectStats.js, packages/lib-user/src/components/Contributors/helpers/getExportData.spec.js, packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js, packages/lib-user/src/components/shared/BarChart/BarChart.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.stories.js, packages/lib-user/src/components/shared/TitledStat/TitledStat.js, packages/lib-user/src/utils/convertStatsSecondsToHours.js, packages/lib-user/src/utils/convertStatsSecondsToHours.spec.js
- lib-user
- refactor convertStatsSecondsToHours utility function to include one decimal place
- refactor components and tests per ^
- go to your user stats page, change the bar chart to hours, note how time displayed throughout
- go to a group stats page, change the bar chart to hours, note how time displayed throughout
- go to the group's contributors page, note time displayed on page and in data export
- Profile - http://localhost:6008/?path=/story/components-shared-profileheader--user-with-hours
- BarChart (hours) - …
=> lib-user: Refactor convertStatsSecondsToHours to include one decimal place

packages/lib-user/src/components/MyGroups/MyGroups.js, packages/lib-user/src/components/UserHome/UserHome.js, packages/lib-user/src/components/shared/GroupForm/GroupForm.js, packages/lib-user/src/components/shared/GroupModal/GroupModal.js, packages/lib-user/src/components/shared/Layout/components/PageHeader.js, packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/components/StyledTab.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
lib-user
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6153
See details in #6153 for itemized changes and discussion with Sean.
Run lib-user or app-root locally to view your stats page, signed-in homepage, and a group you're an admin of (to use the manage model).
=> User stats and groups styling updates

packages/lib-user/src/components/UserStats/UserStatsContainer.js
- lib-user
- refactor UserStatsContainer to request user resource with `created_at` (which will always include `avatar_src`), as `created_at` is needed for stats date range select "All Time" option
- different types of user auth will return different user objects, some of which do not include the `created_at` property of the user, these changes will make sure the `created_at` property is defined for the user and request a user resource accordingly
_PR Creator - Please …
=> lib-user: Refactor UserStatsContainer to request user with created_at

packages/app-root/next.config.mjs
app-root
Similar to https://github.com/zooniverse/front-end-monorepo/pull/4470
- Disable gzip compression in app-root's next.config.js.
- Not something that can be tested locally, but will have to be monitored once deployed to production.
=> app-root: Disable gzip compression

packages/lib-user/src/components/Certificate/Certificate.js
- lib-user
- fixes default page positioning for printing to `landscape` per https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size#landscape , was `'landscape'` in error
- go to your user certificate page
- click "save certificate"
- browser should prompt save/print modal in landscape
_PR Creator - Please cater the checklist to fit the review needed for your code …
=> lib-user: Fix default page positioning for Certificate save or print

packages/lib-user/src/components/shared/TopProjects/TopProjects.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.stories.js, packages/lib-user/test/mocks/panoptes/projects.js, packages/lib-user/test/mocks/stats.mock.js
- lib-user
- show top 20 projects, instead of top 6
- refactor TopProjects grid and row layouts accordingly
- load your user stats page All Time and note Top Projects section
- group: https://local.zooniverse.org:3000/groups/1326962?start_date=2024-03-16  
- http://localhost:6008/?path=/story/components-shared-topprojects--default
- http://localhost:6008/?path=/story/components-shared-topprojects--grid
_PR Creator - Please cater the checklist to fit the review needed …
=> lib-user: Refactor TopProjects with up to 20 items

packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js, packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js, packages/lib-react-components/src/AuthModal/AuthModal.js, packages/lib-react-components/src/Modal/Modal.js, packages/lib-react-components/src/Tabs/Tabs.stories.js, packages/lib-react-components/src/Tabs/theme.js
lib-classifier
Follow-up from: https://github.com/zooniverse/front-end-monorepo/pull/6297#issuecomment-2359154970
Slack conversation: https://zooniverse.slack.com/archives/CANKLB50E/p1727204702907309
- Decrease padding of tab-panels
- Decrease height of Tab buttons
- Remove default padding of `<fieldset>` elements
(I double checked with Sean in-person for a design review) …
=> Styling adjustments for Tabs and AuthModal

packages/lib-user/src/hooks/usePanoptesProjects.js
- lib-user
- return projects accumulator (likely empty array) if the projects request responds with an error
- if as an admin a user classifies on a private project, then attempts to load their user stats NOT as an admin, the request for noted private project will respond with an error
- if other projects are requested at the same time, those projects will be included in the response, and there will be no error
- but if only the private project that the user does not have access to (unless admin on) is requested, then the request response is an error that causes the UserStats and MainContent to display [an unexpected error message](https://drive.google.com/file/d/149uBzEb--gh7byhauTL7s5olgrZA77hG/view?usp=sharing)
- these changes, when the projects request response is an error, returns …
=> lib-user: Fix usePanoptesProjects request error return

.github/workflows/sentry-production-releases.yml, .github/workflows/sentry-staging-releases.yml
Action failure: https://github.com/zooniverse/front-end-monorepo/actions/runs/11351878404
Slack: https://zooniverse.slack.com/archives/C01M8PJGLR5/p1729017936681689
- Remove unused SENTRY_CONTENT_APP env
=> Remove SENTRY_CONTENT_APP

packages/app-project/src/screens/ClassifyPage/components/YourProjectStats/useYourProjectStats.js
- app-project
- iteration on #6472 
- after #6472 was deployed to frontend.preview we noted the "All Time" stats request didn't include the expected `start_date` which should be a user's `created_at` date. The ERAS request `start_date` was not included because the related user request that would provide a user's `created_at` date was not structured as expected. The user request was not structured as expected because the request host was set per `getServerSideAPIHost`. I think it works when `host` and is set with defaults within `panoptes-js` (these changes).
- refactors `fetchUserCreatedAt` to use `host` and `env` as defined in `panoptes-js` instead of setting within user fetch request
- refactors `fetchUserCreatedAt` to use authorization header token per `usePanoptesAuthToken`
_Helpful …
=> app-project: Refactor useYourProjectStats fetchUserCreatedAt panoptes request

packages/lib-content/src/screens/Educate/Educate.js, packages/lib-content/src/translations/en.json
lib-content
[Figma](https://www.figma.com/design/oZB2yOd3sjw3JTvUyz7lj1/Get-Involved-Pages?node-id=0-1&node-type=canvas&t=ztCF5fWildsC22XB-0)
Adds the blog link to https://blog.zooniverse.org/2024/10/01/fulfilling-service-hour-requirements-through-zooniverse-2.
This is a simple change to the translation key. I'll be self-merging for deploy this week.
=> lib-content: Add blog post link to Get Involved > Educate

packages/lib-react-components/src/translations/ja.json
This pull request was initiated by Lokalise (user Delilah Clement) at 2025-01-15 18:27:13
=> Japanese translations for ZooFooter

packages/lib-content/src/translations/en.json, packages/lib-content/src/translations/test.json
This pull request was initiated by Lokalise (user Delilah Clement) at 2025-01-20 22:53:14
=> lib-content: Add a Test Language dictionary

packages/lib-user/src/translations/en.json, packages/lib-user/src/translations/test.json
This pull request was initiated by Lokalise (user Delilah Clement) at 2025-01-20 23:06:47
=> lib-user: Add a Test Language dictionary

packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
- closes #6705 
- if screen width is 430px or less, style background alternately, based on index of shown choices
- https://local.zooniverse.org:8080/?project=1634
- with survey task at 3 or 2 columns
- zoom in so screen width is less than 430px, note 1 column
- note ChoiceButton backgrounds alternate, unlike screenshot in linked issue …
=> lib-classifier: Refactor ChoiceButton background color for very small screens

packages/lib-subject-viewers/src/VolumetricViewer/components/ComponentViewer.js, packages/lib-subject-viewers/src/VolumetricViewer/components/Cube.js, packages/lib-subject-viewers/src/VolumetricViewer/components/MarkButtons.js, packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js, packages/lib-subject-viewers/src/VolumetricViewer/components/Slider.js
- [Issue #6657](https://github.com/zooniverse/front-end-monorepo/issues/6657)
- [Figma](https://www.figma.com/design/HCox3z5YQhoNcni70HRcwF/Brain-Tool?node-id=0-1&node-type=CANVAS&t=yr0zPzw4Okv9t1Sj-0)
- Expand/Collapse labels toggle Plane's visibility (Issue point 1)
- Coordinates don't show up on pageload (Issue point 2)
- Plane slider direction Inverted (Issue point 3)
- Fix "10 Ahead" hover + active (Issue point 4)
- Cube + Toolbar Overlap (Issue point 5)
- Metatools Toolbar: punted - related to Layout (Issue point 6)
- Round Cube bottom-left corner (Issue point 7)
- .5px stroke #A6A7A9 to all sides except bottom (Issue point 8)
- Slices + Cube horizontally aligned on …
=> Finish styles for Volumetric Viewer

Dockerfile
Node 20 has incremented to version 19, which is currently incompatible with this repo. This update has changed the version that the `node:20-alpine` image uses, so this PR pins the version by switching the image to `node:20.18-alpine`. …
=> Pin Docker image to node version 20.18

packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js
- https://github.com/zooniverse/front-end-monorepo/issues/6810
Fix reference for calculating where the LineControls component should layout. There is some undesired positioning due to the zoom/scaling factor being an integer instead of a float.
Follow same steps as issue.
=> Fix LineControls bug with zoom refactor

packages/lib-react-components/src/ProjectCard/components/CardHeader.js
- unexpected - the project card header is blurring when only the classification count badge shown
- expected - if only a classification count badge is shown, the project card header should not blur the project card background image
- conditionally style project card header with blur if project state is "paused" or "finished"
- http://localhost:6007/?path=/story/components-projectcard--nfn-cali-flowers
_PR Creator - Please cater the …
=> lib-react-components: Fix project card blur per project state

packages/app-project/next.config.js, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-classifier/webpack.dev.js, yarn.lock
app-project
lib-classifier
Reverts https://github.com/zooniverse/front-end-monorepo/pull/5264
- After the conversion to Vitest, which included changing React component file extensions from `.js` to `.jsx`, the `million` compiler isn't reliably compiling certain files when lib-classifier's dev App is run locally.
- For example, the [getIcon()](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/plugins/tasks/drawing/components/helpers/getIcon.js) function returned an empty function rather than an Icon component
- Small or no performance improvements were originally noted in the above PR's [review](https://github.com/zooniverse/front-end-monorepo/pull/5264#pullrequestreview-1751633589)
- Run lib-classifier locally and visit a test project that uses a …
=> Remove Million.js
