zooniverse/front-end-monorepo

packages/app-project/stores/User/UserPersonalization/UserPersonalization.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
Fetch the full UPP resource when the stored user changes. When refreshing the UPP resource, fetch data in the background and only refresh stored settings, so as to avoid overwriting the stored classification count.
#2349 introduced a couple of undesired side effects for all projects:
- every 5 classifications, the user's `activity_count` is refreshed from Panoptes. `activity_count` is updated every 5 minutes, so this can lead to weird behaviour where your classification count, on the Classify page, can go up, then down, then up again.
- every 5 classifications, the classifier is replaced by a loading icon and reloads, including clearing the stored subject queue and refreshing it from Panoptes.
This PR should fix both those effects, by silently requesting UPP (every 5 classifications) and …
=> Refactor UPP data-fetching

packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
Define our production and staging hosts in the code. Default `pageProps.host` to `https://localhost:3000` if the deploy environment is undefined.
Try it out with `APP_ENV=staging yarn build && yarn start` or `APP_ENV=production yarn build && yarn start`.
Package:
app-project
Closes #2487.
=> Fix OpenGraph preview URLs

packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.spec.js
Package:
- app-project
Closes #2522.
- temporary solution until further refactoring can be done, see #2515 and #2431 for additional context
- refactors the WorkflowAssignmentModal to update if the UPP.settings.workflow_id (workflow promoted to) changes, prompting user to try workflow promoted to
- this doesn't restore the prompting every 5 classifications, but prompts if a user has been promoted
=> Refactor workflow promotion prompt

packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js, packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
Remove `Provider`. Render `SubjectSetProgressBanner`, not `Banners`. Wire up story controls to component props.
Since #2402, the stories are broken with
```
MobX Provider: The set of provided stores has changed. See: https://github.com/mobxjs/mobx-react#the-set-of-provided-stores-has-changed-error.
```
The controls should be updating component props, not generating a new MobX store, when they change.
Package:
lib-classifier
=> Fix SubjectSetProgressBanner stories

packages/lib-classifier/package.json, packages/lib-react-components/package.json, yarn.lock
Bump `webpack-cli` to 4.9.1.
Bump `webpack-dev-server` to 3.11.3.
Fixes the dev classifier, which currently fails with:
```
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
```
See also https://github.com/webpack/webpack-cli/issues/2990
Package:
lib-classifier
=> Upgrade webpack build tools

packages/app-project/stores/Store.spec.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js, packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.js, packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
Daily classifications break on Sundays, when `today.getDay()` is 0. This removes the array index from daily stats. Instead, it adds the day number to daily counts, and uses that to find today's count.
Talk thread here: https://www.zooniverse.org/projects/bogden/scarlets-and-blues/talk/4757/2211561
Package:
app-project
=> Fix UserPersonalisation on Sundays

package.json, yarn.lock
Upgrade `trim` to 1.0.1 and bump `node-fetch` to 2.6.5
Package:
app-project
=> [Security] Upgrade trim and node-fetch

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Add `/projects` and `/about` prefixes to the liveness probes. Extend timeouts to 10s and allow for retries.
=> Fix liveness probe paths

packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js, packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js, packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.spec.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.spec.js, packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js, packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js, packages/app-project/stores/Project.js, packages/app-project/stores/UI.js
#2519 added `/projects` as a base path for the project app. This PR updates links, which have been hardcoded with `/projects` and now point to `/projects/projects/:owner:/:name:`.
Package:
app-project
=> Projects: Remove /projects from internal links

packages/app-project/pages/[owner]/[project]/about/index.js
Now that the project app has `basePath` set, the Research page path is `/:owner:/:project:/about/research`.
Package:
app-project
=> Fix About page redirects

packages/app-project/pages/[owner]/[project]/classify/index.js
This fixes single workflow projects, where `/classify` is redirecting to `/projects/projects…`.
Package:
app-project
Closes #2540
=> Remove /projects from /classify redirects

packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Circle/Circle.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Rectangle/Rectangle.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/RotateRectangle/RotateRectangle.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalPoint/TemporalPoint.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalRotateRectangle/TemporalRotateRectangle.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/CircleTool/CircleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/EllipseTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/RotateRectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/TemporalPointTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalRotateRectangleTool/TemporalRotateRectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
mobx actions previously `explicitly` returned functions.
This PR refactored all the drawing tools model actions to `implicitly` return functions.
This approach allows for less code, is easier to read and is a modern clean style.
This PR does not change any functionality.
=> Drawing tools models cleanup

packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js, packages/lib-classifier/src/store/locales/en.json
Observe the classifier store for changes to subject work in progress. When there are unsaved annotations, add a `beforeunload` listener, which warns volunteers that they may lose unsaved work.
I've been testing this, in Chrome 95, on
https://localhost:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18619/subject-set/83565?demo=true
Try leaving the page with and without having filled out the text boxes.
https://user-images.githubusercontent.com/59547/142406692-4db7cd67-5015-42a7-97eb-73a1c3c820ef.mov
Package:
lib-classifier
=> Engaging Crowds: Warn volunteers about unsaved work

packages/lib-classifier/src/store/ClassificationStore.spec.js, packages/lib-classifier/src/store/FeedbackStore.js, packages/lib-classifier/src/store/FeedbackStore.spec.js, packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
#2520 revealed a subtle bug in the way that hooks like `onPatch` are being run in the classifier. `onPatch` was called inside an `autorun` listener, which ran every time a new classification was created. A side effect of this was that a new patch listener was created for each subject classified. So the first subject advanced the subject queue by one subject, the second by two subjects, the third by three subjects and so on.
This PR removes `onPatch` from the subjects store and moves it to the root store, where it can observe changes in the `classifications` sub-tree and call actions in the `subjects` sub-tree.
I've also unwrapped `onAction` and `addMiddleware`, which were being run inside `autorun` listeners, and removed some stubs that were needed to pass tests in #2520. In retrospect, I …
=> Classifier: Run addMiddleware, onAction and onPatch outside of autorun

packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js, packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
When selecting a specific subject to classify, ignore the selected subject if it is already active. This fixes a bug where the classifier resets the subject queue, and active classification, if we select the current active subject to work on.
This fixes a subtle bug in Scarlets & Blues, which uses subject IDs in Classify page URLs. If you made some annotations and navigated away from the classifier, to another client-side page (About or Home), then back to Classify with the browser Back button, the subjectID in the URL would trigger the subjects store to reset and reload the subject queue. In the browser you would see your annotations appear briefly, then disappear as the active subject reloads.
This PR checks the `subjectID` parameter (from the URL) against the active subject before …
=> Engaging Crowds: Ignore active subjects when selecting a subject

packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/StepHistory.js, packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/locales/en.json
Move the `onbeforeunload` warning from `RootStore` down to `StepHistory`, where it observes `checkForProgress` for changes. Add a reset on `stepHistory.finish()`, so that the warning is removed when we press Done or Done & Talk.
Package:
lib-classifier
Closes #2561.
=> Classifier: Refactor the beforeunload warning

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Fixes: #2553 
This PR fixes the issue where the LightCurveViewer's existing annotations "disappear" (i.e. go invisible, but still exist in the stores so they'd be submitted in the Classification!) when navigating away from the FEM Classify page to another FEM page, then back to the Classify page.
Basically, there's a desync between the UI visuals (D3.js graph) and the data (Mobx store).
- The problem is that...
- right now, D3.js is the "source of truth" and syncs one-way to the Mobx store (you draw something on D3.js, it tells the stores "this is what's happening")
- This is fine in most cases, UNLESS you navigate away (to another FEM page) and _return_ to the Classify page, because _returning_ to the Classify page resets the D3.js graph but NOT the MobX stores. …
=> LightCurveViewer: fix "invisible annotations" when returning to Classify page

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/store/RootStore.js
Add an `onSubjectChange` prop to the classifier, which passes a snapshot of the active subject to the containing page. The `ClassifierWrapper` component listens for subject changes and performs a shallow update of the page location, if we're on a page that uses the `subjectID` parameter.
As a result, if we go to Talk and back, or if we refresh the page, the page should always reload the active subject ID.
Package:
app-project
lib-classifier
Closes #2537.
=> Engaging Crowds: track classifier subject changes in the page URL

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.js, packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
- Add `subject.markAsSeen()`, which sets `subject.already_seen` to true.
- Update the task area to react to changes in `subject.retired` and `subject.alreadySeen`.
- Call `subjects.active.markAsSeen()` after submitting a classification but before advancing the subject queue for indexed workflows. 
These changes submit the classification, for an unseen subject, with `classification.metadata.subject_selection_state.already_seen: false` then update the store state so that this subject displays as finished.
Try it out, in demo mode, on the last subject in a Scarlets & Blues subject set.
https://localhost:8080/?project=bogden/scarlets-and-blues&workflow=18505&subjectSet=98881&subject=69734532&demo=true&env=production
Package:
lib-classifier
Closes #2569.
=> Engaging Crowds: Mark subjects as seen on subjects.advance()

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
- refactor `TranscribedLinesConnector` to use the `withStores` helper.
- add the current annotation to `TranscribedLines` as a prop.
- update the active annotation when we create a new transcription line from an existing line.
This PR adds `annotation.update()` to previously transcribed lines, which enables them to use the work-in-progress flag introduced in #2411 and #2415. It will also set them up to refresh auth tokens on update (#2563), which will allow volunteers to stay logged in when working on long pages.
Try it out on a test subject with many previously transcribed lines. If you edit a few lines, then reload the page, you should be warned that your work will be lost.
https://localhost:8080/?project=11300&subject=55414217&env=production&demo=true
Package:
lib-classifier
Closes …
=> Add a warning for unsaved work from the transcription task

packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js, packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
Package:
Continuation on zooniverse/Panoptes-Front-End/pull/6062
- adds Mobile App nav item
- adds related test
=> Add mobile app nav item

docs/arch/README.md, docs/arch/adr-37.md, docs/arch/adr-38.md
ADRs for the last two major pieces of Engaging Crowds: browsing subject sets and searching available subjects, and browsing the available subject queue in order to pick a subject to classify.
Package:
lib-classifier
=> Engaging Crowds: ADRs for selecting a subject

.github/workflows/ci-tests.yml
The latest version of `actions/setup-node` has [built-in package caching](https://github.com/actions/setup-node#caching-packages-dependencies). This PR removes `actions/cache` from test builds and uses `setup-node@v2` to cache yarn installs.
Package:
all
=> CI: Use built-in Node package caching

packages/lib-classifier/package.json, packages/lib-classifier/src/store/utils/ClassificationQueue.js, yarn.lock
Malformed classifications are silently dropped by the classifier, with no warning that volunteer work has been lost. This logs the classification data to Sentry, under the project app DSN, so that we can track failed classifications and investigate.
Here's an example of an error logged from this PR:
https://sentry.io/organizations/zooniverse-27/issues/2908437878/?environment=development&project=1492691&query=is%3Aunresolved
Package:
lib-classifier
=> Classifier: log malformed classifications

packages/lib-classifier/src/store/utils/ClassificationQueue.js
Log dropped classifications to Sentry after an error writing to local storage.
Follow up to #2598. The classifier silently deletes classifications after errors in `ClassificationQueue.store(classification)`. This PR logs those errors to Sentry, so that we can follow up and investigate.
Package:
lib-classifier
=> Classifier: Log dropped classifications to Sentry

packages/lib-classifier/src/store/Classification/ClassificationMetadata.js, packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js, packages/lib-classifier/src/store/ClassificationStore.js
Add a test for `classificationMetadata.startedAt` and an `afterCreate` hook, which sets the start time after a new classification is created. 
Package:
lib-classifier
Closes #2603.
=> Classifier: set classification.metadata.started_at when a classification is created

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
Add a `visible` prop to `TranscribedLines`, which hides transcribed lines except when `shownMarks` is set to `ALL`. Refactor `TranscribedLinesConnector` to use the same prop names as `TranscribedLines`.
I've also refactored `TranscribedLines` from a class component to a functional component.
Try it out on the Davy Notebooks Project:
https://local.zooniverse.org:8080/?env=production&project=humphrydavy/davy-notebooks-project&workflow=20178&demo=true
Package:
lib-classifier
Closes #2595.
=> Classifier: toggle show/hide for transcribed lines

packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Add `mockStore`, which includes mocked clients for the Panoptes and Caesar APIs, to the classifier task stories. This should fix store errors in these stories, where `getRoot(self).client` is undefined when you change the value of any of a story's controls.
Package:
lib-classifier
=> Add mockStore to classifier task stories

packages/lib-classifier/package.json, yarn.lock
Includes a low priority security patch for `node-forge`.
Package:
lib-classifier
=> Upgrade webpack-dev-server to 4.7

docs/arch/README.md, docs/arch/adr-39.md, docs/arch/adr-40.md
Note: ADR 39 is here https://github.com/zooniverse/front-end-monorepo/pull/2594.
app-project
lib-classifier
This is an ADR outlining the decision to use [Next.js Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing#sub-path-routing) to provide translated content based a user's locale preference.
Backend team, I'm tagging you to keep everyone in the loop about locale being reflected in the url.
The status of this ADR says "accepted" based on the frontend team's discussion on PR #2550 as well as discussion during weekly stand-ups. To see an example of how this internationalization routing strategy works, take a look at PR #2592, which implements Next.js internationalized routing in app-project, lib-classifier, and lib-react-components.
=> ADR #40: Next.js Internationalization Sub-path Routing

packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, yarn.lock
Remove `require-control` from the NextJS config for `app-content-pages`. It worked around an issue that’s since been fixed. 
Package:
=> Remove require-control

yarn.lock
Patch updates for `@testing-library/dom`, `mocha` and `nock`.
=> Bump test dependencies

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
Missed in the recent NextJS upgrades, this upgrades the ESLint config from 11 to 12.
Package:
app-project
=> Update NextJS ESLint to 12

packages/app-project/package.json, packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js, yarn.lock
`fetch` is polyfilled in NextJS, since 9.7, so this removes the direct dependency from the project app.
Package:
app-project
=> [Security] Projects: remove direct node-fetch dependency

packages/lib-react-components/package.json, yarn.lock
Bump `formik` to 2.2.9. Removes `node-fetch@1.7.3` from our dependency tree.
Package:
=> [Security] Upgrade formik

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js, yarn.lock
Add the [`useSWR`](https://swr.vercel.app/) hook to the root `Classifier` and an `onWorkflowChange` effect which updates the store when workflow data changes in Panoptes.
Package:
lib-classifier
Closes #2668.
=> Classifier: Refresh workflows with SWR (stale-while-revalidate)

package.json, yarn.lock
Pin `node-fetch` to ^2.6.7, at least until NextJS 12.0.9 is released.
Package:
app-project
=> [Security] remove node-fetch@2.6.1

yarn.lock
6.4.14 includes a fix for the Webpack 5 `process` fix that was added in 6.4.13.
Package:
app-project
lib-classifier
=> Patch storybook to 6.4.14

packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js, packages/lib-classifier/src/components/Classifier/components/Layout/Layout.spec.js
Remove `@inject` from `Layout` and rewrite it as a functional component.
Package:
lib-classifier
Towards: #2712.
=> Classifier: remove @inject from Layout

yarn.lock
Bump `@babel/core` and `@babel/preset-env` to latest.
Package:
lib-classifier
=> Patch @babel/core and @babel/preset-env

packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Replace the classifier's `workflowData` prop with `workflowSnapshot` and `workflowVersion` props. `workflowData` changes when eg. workflow completeness changes, which isn't very useful. This change restricts updates (and re-renders) to cases where `workflow.version` has explicitly changed.
Closes: #2749.
=> Classifier: react to workflow version changes

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js, packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
Set the `cachePanoptesData` flag for projects where any workflow uses ordered subjects. This ensures that it is set before the `Classifier` component mounts.
In #2657, I missed that `cachePanoptesData` wasn’t being set until after the classifier mounts. This PR should fix that. 
Package:
app-project
Closes #2610.
=> Enable session storage for projects with ordered subjects

packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, yarn.lock
Remove `node-cache`, which isn't used anywhere in the code.
I've also enabled ESLint build checks, to match the project app.
http://localhost:3000/about/team
http://localhost:3000/about/publications
Package:
=> Content pages: remove node-cache

packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js, packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
- refactor `subject.stepHistory` as `subject.startClassification()`, which starts a new undo history when a subject becomes active.
- remove `subject.stepHistory` from snapshots.
- refactor `subject.transcriptionReductions` so that they are only fetched from Caesar when empty.
- explicitly set `subjects.active` to undefined on reset, despite it being `types.safeReference`.
Testing URL:
https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project?env=production&demo=true
Package:
lib-classifier
Closes #2799.
=> Classifier: Refactor subject snapshots

packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsCarousel.js
app-project
This PR refactors DailyClassificationsChart, its storybook, and tests to use Next.js's router `locale` instead of counterpart. I also removed imports of counterpart where it was unused in /src/screens.
- Run app-project's storybook with this branch, and check the [DailyClassificationChart story](http://localhost:9001/?path=/story/project-app-screens-classify-daily-classifications-chart--plain)
- Run app-project locally with this branch, make a classification on a staging project such as [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/classify/workflow/693), and the daily classification chart should update accordingly
=> App-project: Use router locale for DailyClassificationsChart

packages/app-project/.storybook/i18n.js, packages/app-project/pages/[owner]/[project]/about/education.js, packages/app-project/pages/[owner]/[project]/about/faq.js, packages/app-project/pages/[owner]/[project]/about/research.js, packages/app-project/pages/[owner]/[project]/about/results.js, packages/app-project/pages/[owner]/[project]/about/team.js, packages/app-project/pages/[owner]/[project]/classify/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js, packages/app-project/pages/[owner]/[project]/index.js, packages/app-project/public/locales/en/components.json, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.spec.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/locales/en.json, packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js, packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js, packages/app-project/src/components/Announcements/components/FinishedAnnouncement/locales/en.json
This PR refactors app-project's Announcements components to use `next-i18next` instead of `counterpart` for string translations.
Translations project board: https://github.com/zooniverse/front-end-monorepo/projects/15
app-project
Added AuthenticationInvitation and FinishedAnnouncement translation keys to `/en/components.json`. Each key that used `counterpart('Some.String.Here')` now uses the `t` function like `t('Some.String.Here')`.
I also passed `'components'` to each `getServerSideProps` function to bundle the new dictionary file.
Changes to tests involve removing tests that looked for passing of props rather than testing elements rendered to the UI.
Run `yarn storybook` with this branch and check that AuthenticationInvitation and FinishedAnnouncement render their translated text.
=> App-project: Translate Announcements components with next-i18next

packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/hooks/Readme.md, packages/lib-classifier/src/components/Classifier/hooks/index.js, packages/lib-classifier/src/components/Classifier/hooks/useHydratedStore.js, packages/lib-classifier/src/components/Classifier/hooks/useStore.js, packages/lib-classifier/src/components/Classifier/hooks/useWorkflowSnapshot.js, packages/lib-classifier/src/store/RootStore.js
- Add a `hooks` directory to the `Classifier` component. Import the `useStore` and `useWorkflowSnapshot` hooks from that directory.
- Explicitly declare `SWR` options in the `useWorkflowSnapshot` hook.
- Add a `useHydratedStore` hook, which hydrates the store from session storage when `cachePanoptesData` is set. Otherwise, it just returns `true`.
- Add a `useEffect` hook to clean up the store and set up volatile callbacks for the parent page after hydration has finished.
- Add a `store.startClassification()` action, to replace the `subjects.setActiveSubject(subjects.active?.id)` hack.
- Additional console logging when the classifier mounts and creates the store.
This PR includes #2792. It shouldn't change anything, just refactor the hooks to make the classifier component easier to read …
=> Classifier: Refactor ClassifierContainer hooks

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Package:
Closes #2871.
- from LightCurveViewerContainer only returns LightCurveViewer if `dataPoints` has length (would have length if populated from JSON data) 
- What Zooniverse project should my reviewer use to review UX? 
- https://local.zooniverse.org:8080/?project=7929&env=production&demo=true
- https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?env=production&demo=true
- throttle to Fast 3G, reload page if necessary, focus on subject viewer
- N/A
- …
=> Refactor LightCurveViewerContainer to return null if dataPoints has no length

packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/locales/en.json, packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.js, packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/locales/en.json, packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.js, packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/locales/en.json, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/locales/en.json, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/locales/en.json, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js, packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/locales/en.json, packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/TextTagButtons.js, packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/locales/en.json, packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js, packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.spec.js, packages/lib-classifier/src/plugins/tasks/components/InputStatus/locales/en.json, packages/lib-classifier/src/translations/en/plugins.json
This PR refactors lib-classifier's "plugins" components to use `react-i18next` instead of `counterpart` for string translations.
Translations project board: https://github.com/zooniverse/front-end-monorepo/projects/15
lib-classifier
Added components that live in `/plugins` translation keys to `/en/plugins.json`. Each key that used `counterpart('Some.String.Here’)` now uses the `t` function like `t('Some.String.Here’)`.
There was a `en.json` locale file in DataVisAnnotationTask, but the translation strings were not actually used in the component, so I removed those keys.
Some unit tests required refactoring if they looked for previous translation strings.
Task components that can be reviewed in storybook:
- InputStatus is in the Drawing story
- Simple Dropdown
- SurveyTasks's Choice …
=> Lib-classifier: Translate /plugins components with react-i18next

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
lib-classifier
In #2866 I re-introduced Choice component's unit tests, but they have a history of timing out during Github actions as detailed in Issue #2532. This PR adds "skip" back in to `Choice.spec.js`.
=> Classifier: Skip Choice component tests due to timeout

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Follows #2719
Whenever a new Subject is loaded on the LightCurveViewer, an "animation" plays where the data points "swoosh in" from the top-left corner. This PR attempts to fix that.
https://user-images.githubusercontent.com/13952701/155182096-b01addd1-0b1a-4fd5-931e-90395bea4824.mov
_The issue in question. In the movie above, we cycle through 3 Subjects (by clicking the Done button, not picture). There is a significant animation playing on the 2nd and 3rd Subjects loading_
**Analysis Pt 1:**
- The "swooshing" animation is triggered by `LightCurveViewer.js`'s `updateDataPoint()`'s `.transition()`.
- This in turn is triggered by `drawChart()`, when it's called when shouldAnimate is true.
- This in turn turn is triggered by EITHER...
- **Scenario 1** `<ReactResizeDetector>` detecting a …
=> Light Curve Viewer: stop Animation when new Subject loads

packages/lib-classifier/src/store/SubjectStore/SubjectStore.js, packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Add `subjects.prioritized` for prioritised workflows. Check subject priority, for priority queues, and only add new subjects with priorities beyond the last subject priority in the queue.
EDIT: bypass that check for completed workflows, which fall back to showing subjects to a volunteer in a random order.
With this change, you should always see prioritised subjects in ascending priority order, starting at the last subject that you classified, without any repeats.
Test projects:
- Davy Notebooks (uses prioritised workflows): https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project/classify?env=production&demo=true
- HMS NHS (uses grouped, prioritised workflows): https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/classify?env=productio …
=> Classifier: Filter prioritised subject queues

packages/lib-classifier/src/store/TutorialStore/TutorialStore.js
Package:
Closes #2894 .
- refactors TutorialStore `hasNotSeenTutorialBefore` to return `false` if:
- UPP initialized, loading, or errors (i.e. loadingState !== success) because we don't know if user hasn't seen tutorial until UPP are loaded or if signed out store will change state to success but leave UPP.active undefined
- if tutorial undefined 
- What Zooniverse project should my reviewer use to review UX? any project with tutorial, noting:
- https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?env=production&demo=true (for signed in especially, can also test signed out)
- https://local.zooniverse.org:8080/?project=7929&env=production&demo=true (for signed …
=> Refactor TutorialStore hasNotSeenTutorialBefore to return false if UPP or tutorial not determined

packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/index.js
`SlideTutorial` stories were commented out in the code. This removes the commented stories and replaces them with a couple of new stories, written in CSF. `StepNavigation` is refactored as a plain component, so that we can render the tutorial without having to wrap it in a store.
I've put the new stories under `Other / SlideTutorial` in the classifier storybook.
Package:
lib-classifier
=> Classifier: Add SlideTutorial stories

packages/lib-react-components/.storybook/i18n.js, packages/lib-react-components/.storybook/main.js, packages/lib-react-components/.storybook/preview.js, packages/lib-react-components/package.json, yarn.lock
This PR only affects lib-react-components storybook.
Run `yarn storybook` with this branch locally. In the toolbar at the top of the screen, there should now be a globe button. This is the locale switcher. It should have two language options: English and Test Language.
Stories rendered in lib-react-components' storybook should not have changed. …
=> Lib-React-Components: Add storybook-react-i18next config

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
Package:
Closes #2810.
- adds active tool validation on frame change to MultiFrameViewerContainer
- (confirm existing issue) https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/classify/workflow/20543?demo=true
- (check fixed) https://local.zooniverse.org:8080/?project=rachaelsking/corresponding-with-quakers&workflow=20543&env=production&demo=true
- (multi frame viewer without active tool to check negative side effects) https://local.zooniverse.org:8080/?project=1876&demo=true
1. on a frame start to create transcription line, but don't click twice to …
=> Add activeTool validation on frame change to MultiFrameViewerContainer

packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js, packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
Call `tutorial.setSeenTime()` when the modal tutorial is closed by either activating the close button, clicking outside the popup, or pressing the `Esc` key. That marks the tutorial as complete in user project preferences.
Package:
lib-classifier
=> Classifier: Set ModalTutorial as complete on close

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
Refactor the generic `SubjectViewer` container as a functional component, and remove the deprecated `@inject` decorator.
Towards #2712.
=> Classifier: Remove @inject from SubjectViewer

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-react-components/package.json, yarn.lock
Grommet 2.20 fixed [a bug in `TextInput`](https://github.com/grommet/grommet/pull/5860) with suggestions, where suggestions should always be shown when you type into the text box. Our `TextTaskWithSuggestions` relies on the old behaviour, where you could type text without seeing any suggestions. This PR rolls Grommet back to 2.19 as a workaround for #2948 until the text task can be fixed.
Package:
app-project
lib-classifier
Temporary workaround for #2948, while we work on a fix.
=> Roll Grommet back to ~2.19.0

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
Explicitly pass a userID prop to the `ClassifierWrapper` component in the Classify page. Set the `Classifier` key from this prop, so that the classifier unmounts and remounts when you log out.
To test this out: sign out from PH-TESS. You should see that the classifier resets and reloads without a logged-in user.
Package:
app-project
Closes #2962.
=> Reset the Classifier key after logging out

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/hooks/useSubjectImage.js
Refactor `SingleImageViewerContainer` and `MultiFrameViewerContainer` as functional components. Move the common image loading code into a `useSubjectImage` hook.
Package:
lib-classifier
=> Classifier: useSubjectImage hook

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
`mobx-react@7.3.0` fixes a bug in components that are decorated with `observer()`, but `DrawingToolMarks` tests rely on the old behaviour and fail after the upgrade. This upgrades the tests to use component selectors, instead of display names, which fixes the bug.
This PR will fix the failing tests in #2858, allowing us to upgrade `mobx-react`.
Package:
lib-classifier
=> Fix mark selectors in DrawingToolMarks tests

packages/app-project/pages/_app.js, packages/app-project/src/helpers/getCookie/getCookie.js, packages/app-project/src/helpers/getCookie/getCookie.spec.js, packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js, packages/app-project/stores/UI.js, packages/app-project/stores/UI.spec.js, packages/app-project/stores/initStore.js
Remove server-side cookie handling and the `initialState.ui` page prop. Read cookies in the browser on app mount and apply to the store. This should remember your selected theme across projects, rather than using cached page props from the CDN.
To test this out, toggle the theme between light and dark, then check that it persists across page transitions, and also after refreshing the page.
Package:
app-project
Closes #2555.
=> app-project: Fix broken dark/light mode theme toggle

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js, packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/lib-classifier/dev/components/App/App.js, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
- Add a `showTutorial` prop to the classifier, which controls whether the `ModalTutorial` component can be rendered.
- Set `showTutorial` in the Classify page, based on the value of `canClassify` page state. This should stop tutorials from being shown if we haven't started classifying yet.
- Refactor `classifierProps` to use `useState`. That should avoid page renders where `classifierProps` is set to an empty object, while the workflow is in the process of changing.
Package:
app-project
lib-classifier
Closes #2936.
It's probably easiest to test this while not logged in, so that the popup tutorial will always appear when you start to classify on a workflow. Here are some test workflows, both of which have tutorials.
- a branching workflow: …
=> Add a showTutorial hint to the popup tutorial

.github/workflows/ci-tests.yml, Dockerfile, README.md, package.json, packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-async-states/package.json, packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js, packages/lib-grommet-theme/package.json, packages/lib-panoptes-js/package.json, packages/lib-react-components/package.json
Node 16 is LTS now. This updates the Dockerfile, GitHub actions and package files from 14 to 16.
3 of the `ZoomingScatterPlot` tests fail in Node 16. I've skipped those tests here.
Package:
All
=> Upgrade builds to Node 16

packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Not all marks have an initial drag interaction, so make it optional. 
See #2960 for details.
Package:
lib-classifier
=> Make mark.initialDrag optional

packages/lib-classifier/webpack.dev.js
The [`https` option](https://webpack.js.org/configuration/dev-server/#devserverhttps) is deprecated in webpack dev server, replaced by [`server`](https://webpack.js.org/configuration/dev-server/#devserverserver).
Package:
lib-classifier
=> webpack dev server: replace https with server

packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
The subject progress banner added for Engaging Crowds projects, which allows you to browse Next and Previous subjects, will error if it renders before a classification has started. This will happen when a subject is defined in the page URL. This PR adds an existence check to the subject step history when checking for work in progress (which disables the Next and Previous buttons.)
To test this out in the dev classifier, with all the indexing features enabled, change `cachePanoptesData` from `false` to `true` in `dev/App.js` and load in the RBGE project with a subject set and subject selected:
https://local.zooniverse.org:8080/?project=emhaston/the-rbge-herbarium-exploring-gesneriaceae-the-african-violet-family&workflow=19381&subjectSet=99948&subject=70656987&env=production
You can also …
=> Classifier subject banners: Fix `stepHistory is undefined` on load

docs/arch/README.md, docs/arch/adr-42.md
An ADR to summarise the work I've been doing to persist classifier state in window session storage, mostly for Engaging Crowds projects.
=> ADR 42: record classifier store snapshots

packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
Refactor the classify page to filter the available project workflows by workflow level, when workflow assignment is enabled. Don't allow a volunteer's chosen workflow (from the page URL) to be a higher level than their assigned workflow. Remove redundant state that was set by a `useEffect` hook.
I found this was useful advice on avoiding effects that set state:
https://beta.reactjs.org/apis/usestate#storing-information-from-previous-renders
Package:
app-project
=> Project: add allowedWorkflows to ClassifyPage

packages/lib-classifier/dev/components/App/App.js
Add some simple workflow routing to the dev classifier, so that the location bar updates when the selected workflow changes.
I've also fixed a few React errors in the console:
- use `htmlFor` instead of `for` in JSX.
- use keys on arrays of JSX elements.
- use `defaultValue` instead of `selected` for the `<select>` element.
Try it out on a project that has multiple workflows. When you select a new workflow, from the dropdown menu, the window location should update to include the new value of the `workflow` query parameter. I've also added a [`popstate`](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) handler so that you can navigate backwards and forwards with the browser Back and Forward buttons. 
https://localhost:8080/?project=eatyourgreens%2F-project-testing-gro …
=> Dev classifier workflow routing

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerConnector.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerConnector.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.spec.js
- single text subject viewer fails to render content when single text subject `contentLoadingState` changes to `success`
- basic react component mistake on my part :face_palm, a change in the nested property of a prop won't trigger a re-render, previously the SingleTextViewerContainer had the subject as the prop, so when subject stayed the same but properties changed (notably contentLoadingState) the container did not update because the subject was still the same subject, solution here is to deconstruct the subject in the connector and pass the meaningful properties of a single text subject as props into the container, and the container will now update when those properties change, as expected
- refactor SingleTextViewerConnector and SingleTextViewerContainer with single …
=> Refactor SingleTextViewer with deconstructed single text subject

yarn.lock
#3005 broke the storybook. It builds but won't load in a browser. This fixes it by making sure that all `@storybook/*` packages are updated to [6.4.21](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md#6421-april-9-2022).
=> Bump storybook to 6.4.21

packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js, packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
Render the modal tutorial with and without `hasNotSeenTutorialBefore` set. Test that the close button closes the tutorial and updates user project preferences to mark the tutorial as seen.
lib-classifier
=> Classifier: test the modal tutorial

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/components/InputGroup/components/QuestionInput.spec.js, packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js, packages/lib-classifier/test/.mocharc.json, yarn.lock
- upgrade `user-events` to 14 (13.5 is no longer maintained.)
- test the text task with suggestions when we click into it, both with and without an existing value. Suggestions should show when the input is empty.
- fix broken test setup. Enzyme must be set up after JSDOM.
- disable timeouts on slow-running tests, so we can run the `Choice` tests again.
Follow up to #3001, which fixed a bug in transcription projects but didn't add tests.
lib-classifier
=> Classifier: test text task with suggestions

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
While investigating the `ZoomingScatterPlot` tests in Node 16, I rewrote `ZoomingScatterPlot` and `VisXZoom` as functions.
~~I'm setting this as draft because the `VisXZoom` tests rely on `wrapper.instance()`, which only exists for class components.~~
To test this, try out the zooming scatter plot in the classifier storybook.
Package:
lib-classifier
=> Classifier: Refactor zooming scatter plot components as functions

.github/workflows/ci-build.yml, .github/workflows/coverage.yml
Split the `ci-tests` workflow into two workflows:
- `ci-build`, which builds the libraries, apps and storybooks after pushes to PRs.
- `coverage`, which runs the tests and generates a coverage report after pushes to PRs and merges to `master`. It can also be run manually from the Actions panel.
#2581 broke our coverage reports, so that the last build reported was 14 December 2021. This PR restores test and coverage reports on changes to `master`.
https://coveralls.io/github/zooniverse/front-end-monorepo
=> Run coverage reports on changes to main branch

packages/lib-classifier/src/store/utils/ClassificationQueue.js, packages/lib-classifier/src/store/utils/ClassificationQueue.spec.js
- Clean up the `ClassificationQueue` tests, to make them easier to read. 
- Use fake timers to test the retry timeouts.
- Add tests for the case where a classification can't be saved (422 response.)
lib-classifier
=> Classifier: Test `ClassificationQueue` with fake timers

packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
`lib-classifier`
Converted enzyme test to RTL
The intent for the Delete Button Component test is to only ensure the button renders properly. The functionality (removing an annotation) will be tested in each tool (circle, rectangle, polygon...). This will be added in future PRs. 
N/A
Checkout this branch and run `yarn test`
N/A
Yes. Functionality of the delete button will be tested in each tool (circle, rectangle, polygon...)
=> Convert DeleteButton enzyme test to RTL

packages/app-project/package.json, yarn.lock
Downgrade `devcert` to 1.2.0 so that we can run a local development server again.
app-project
https://github.com/davewasmer/devcert/issues/83
=> Project: pin devcert to 1.2.0

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Affects: LightCurveViewer component, Planet Hunters TESS project
This PR fixes an issue where the LightCurveViewer doesn't work with Safari 15.
**The Problem:** When you view [Planet Hunters TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess) on Safari 15, you don't "see" the light curve graph. Actually, what's happening is that the graph has a height of 33 million pixels.
_Above: screenshot of the Light Curve Viewer on Planet Hunters TESS, using Safari. The light curve graph isn't visible, and if you inspect the element, you'll see that the SVG element is absurdly tall._
_Above: screenshot of the LCV on PHTESS, using Chrome. This is the expected view._
**Analysis:**
- The LightCurveViewer exists in an SVG with the setup `<svg …
=> LightCurveViewer: change height to 80vh, fix Safari 15 issues

.yarnrc
`yarn` is nagging that our version is out of date, so upgrade to latest allowed with `yarn policies set-version`.
=> Bump yarn to 1.22.18

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Remove a stray import that was left over in `SingleImageViewer`.
lib-classifier
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
- It is passing accessibility checks in the storybook
=> Remove `inject` from single image viewer

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/Comment.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserAvatar.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserAvatar.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserRole.spec.js, packages/lib-classifier/src/translations/en/components.json
Part of: Maintenance Week
This PR adds tests for the QuickTalk feature, which have thus far been lacking proper tests.
- Most of the functionality tests are performed in `QuickTalk.spec.js`
- Basic tests have been added for the subcomponents
- `QuickTalkContainer.spec.js` meanwhile is missing more robust tests, due to issues with hooking it up to a mock store.
- I think the problem is that this container might need to be rewritten as a functional component
- For the record, this is what it needs to test for:
- If store.project.experimental_tools contains 'quicktalk', then the QuickTalk button should render.
- If store.project.experimental_tools doesn't contain 'quicktalk', then the QuickTalk button shouldn't render.
- If there's no store or project, don't render.
I'm going to mark this as …
=> Maintenance Week: QuickTalk tests

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
lib-classifier
https://www.zooniverse.org/talk/17/2439164?comment=4008206
Linked to the fix in #3119 - this PR solves the underlying issue without overriding the height based on view port. 
The underlying issue is in webkit browsers when combining height and width 100% it incorrectly calculates the height. However removing the width setting allows height to work correctly for webkit.
related issue https://stackoverflow.com/questions/7570917/svg-height-incorrectly-calculated-in-webkit-browsers/12631326
Tested on chrome, ff and safari (latest)
- Are there …
=> LightCurveViewer: fix svg height rendering including in webkit browsers (safari)

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
The task area connector tests have been timing out and blocking CI. This overrides the Mocha timeout for those tests.
lib-classifier
=> Classifier: Override mocha timeout for TaskAreaConnector

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
`inject` is deprecated in `mobx-react`. This replaces it with the `withStores` HOC to connect `QuickTalk` to the classifier store.
lib-classifier
#2712
=> Classifier: remove `inject` from QuickTalk

packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/models/TextFromSubjectAnnotation.spec.js
#3043 added a broken mock for text-from-subject tasks. This fixes the broken tests, which are failing in #3145
lib-classifier
#3145 
=> Fix broken textFromSubjectAnnotation tests

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js, packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.spec.js, packages/lib-react-components/src/Markdownz/Markdownz.js
lib-classifier
Bug discovered from modifying Markdownz for https://github.com/zooniverse/front-end-monorepo/issues/3039
I removed the hard-coded `{{ color: #00000 }}` from Markdownz so it doesn't interrupt dark mode styling on things like the classifier's TaskArea, etc.
Each field guide item's title is now rendered with Grommet Paragraph instead of Markdownz in FieldGuideItemAnchor. Styling should look exactly the same.
Comparing Beyond Borders's TaskArea (includes lists) and its Field Guide item titles with production, the styling should appear the same. https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-lan …
=> Bug Fix: Remove hard-coded color for lists and remove Markdownz from field guide anchor

packages/lib-classifier/dev/components/App/App.js, packages/lib-classifier/dev/index.js, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/hooks/Readme.md, packages/lib-classifier/src/hooks/index.js, packages/lib-classifier/src/hooks/usePanoptesTranslations.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.spec.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.stories.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/models/DataVisAnnotationTask.js, packages/lib-classifier/src/plugins/tasks/models/Task.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js, packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js, packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Wire up workflows to the Panoptes `/translations` endpoint.
- Add a `usePanoptesTranslations` hook to fetch translations by type, ID and language.
- Add a `strings` property to workflows and tasks, which holds the dictionary of translated strings for that resource.
- Modify the data vis annotation task to show instructions, help, and tool labels from the `strings` dictionary.
- Add a `language` query param to the dev classifier.
- Add an [`autorun` reaction](https://mobx.js.org/reactions.html) to the workflow steps store, which injects new strings into the workflow tasks whenever the workflow translation changes.
lib-classifier
You should be able to load PH-TESS in the classifier in three different languages.
- English (default): …
=> Classifier: Localise workflows

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js, packages/lib-classifier/src/translations/en/components.json
Affects: experimental QuickTalk feature (only affects projects with experimental tool enabled)
This PR refactors the QuickTalkContainer into a _functional component._
- No actual functions or features have been changed (EDIT: except for the two minor changes below). Users should see no difference in the feature.
- Minor: error messages now use translated text.
- Minor: when QuickTalk panel opens, close button now automatically gets focus. (I thought I added this in 3048, but I must have dropped it, d'oh!)
- Test on `lib-classifier` (not app-project) with a project with QuickTalk enabled, e.g. https://local.zooniverse.org:8080/?env=staging&project=darkeshard%2Ftest-project-2022&workflow=3581
- You should be able to see the QuickTalk button on the lower-right of …
=> QuickTalk: Refactor to functional component

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
A quick fix for auth in `QuickTalk`. Establish a Panoptes user session before requesting a bearer token. This avoids a bug where `authorization` can be empty when you are actually logged in.
lib-classifier
This is a quick fix for a bug where the first comment you post fails, because the auth token is requested before `checkCurrent()` has established a Panoptes user session. …
=> Quick Talk: fix user authorisation

packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
- Pass translation `strings` down to tutorial components.
- Use the `strings` dictionary to show step content.
lib-classifier
Load PH-TESS in the dev classifier and change the language.
https://localhost:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production
https://user-images.githubusercontent.com/59547/169840507-0f3cb79f-28cf-46bb-9e46-3d7932135dac.mov
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibi …
=> Classifier: localise tutorials

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
- pass onError and onReady from SubjectViewer to ImageAndTextViewer to either SingleImageViewer or SingeTextViewer
- fix - https://local.zooniverse.org:8080/?project=1952&workflow=3594&demo=true
- bug - https://frontend.preview.zooniverse.org/projects/markb-panoptes/digileap-testing/classify/workflow/3594?env=staging
- What user actions should my reviewer step through to review this PR? try to edit text in textFromSubject task (text input)
- Which storybook stories should be reviewed? I think N/A, bug in task related to code missing in viewer, separate stories
- Are there plans for follow up PR’s to further fix this bug or develop this feature? yes! …
=> Fix ImageAndTextViewer not calling onReady or onError

packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
Replace `inject` with `withStores` in subject `MetaTools`.
lib-classifier
#2712
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
- It is passing accessibility checks in the storybook
=> Classifier: Remove `inject` from MetaTools

packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/translations/i18n.js, packages/lib-classifier/test/mockStore/mockStore.js
Add tests that render the classifier with a mock workflow and single image subject. Check the rendered classifier for the two task area tabs, the task answers and the SVG subject image. Test that locale changes are passed to the store, and that user roles are checked before loading a workflow.
lib-classifier
=> Test the Classifier

packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addInterfaceLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js, packages/lib-classifier/src/store/ResourceStore/ResourceStore.spec.js, packages/lib-classifier/test/mockStore/branchingWorkflow.js
Make the check for workflow version changes more stringent, before re-rendering the classifier and starting a new classification.
- remove the `workflowVersion` prop from the classifier.
- check `workflowSnapshot.version` against the active workflow in the store.
- only re-render the classifier if `workflowVersionChanged` is true.
- merge `workflowSnapshot` into any existing workflow, to avoid #3256, where `workflowSnapshot.subjectSet` could be set to a subject set that isn't in the store.
- add some tests which rerender the classifier after a workflow version change, with new task answers.
- update all the classifier tests to mock the image `load` event, when an image subject loads.
- add tests for a grouped workflow with linked subject sets, to catch #3256.
app-project
lib-classifier …
=> Classifier: more stringent workflow version checks

packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js, packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js, packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
`types.frozen` is assumed to be immutable, but `workflow.strings` changes when the locale changes. This refactors `workflow.strings` as an observable map, applying new snapshots of the language strings when the locale changes.
`WorkflowStepStore` is also updated to explicitly update task strings whenever the workflow version changes, so that workflow edits in the project builder are shown in the classifier's task panel.
- Closes #3266.
- Based on #3220, so take a look at that first.
lib-classifier
Open a workflow in either the dev classifier or the project app. Change the workflow's language strings by either editing the workflow in the project builder or by switching to another language on the project's Classify page.
This PR should also fix background refresh in the classifier, so that …
=> Classifier: Refactor workflow strings as a map

README.md, kubernetes/deployment-production.tmpl, packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, packages/app-project/next.config.js, packages/app-project/package.json
- set the default build and deploy environment to 'development', not 'production'.
- update the description of `APP_ENV` in the Readme.
- explicitly set `APP_ENV` in the kubernetes templates.
app-project
Try building the apps with different environments eg. `APP_ENV=staging yarn build` should give you a build that can be deployed to staging. `APP_ENV=production yarn build` should give you a production app. In terms of the builds themselves, I think the only visible change in the HTML might be the links that are published in the page `<head>`. Staging builds should use `https://frontend.preview.zooniverse.org` and production should use `https://www.zooniverse.org`.
_PR Reviewer - Use …
=> Set default APP_ENV to 'development'

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js, packages/lib-classifier/src/hooks/useHydratedStore.js
- Catch undefined tasks in the `Task` component, and display an error message in place of the task.
- Catch invalid snapshot errors, when the store loads, and create a new, empty store.
lib-classifier
- Closes #3292.
- Closes #3251.
The task bug only exists in the production build of the classifier, so build the classifier then run the project app (either development or production build) and load this test workflow, which contains a task where the type is 'dropdown'.
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3489?env=staging …
=> Classifier: better handling of invalid tasks

packages/app-project/src/components/ProjectHeader/ProjectHeader.js
Use `APP_ENV` to check the deploy environment. Show the `LocaleSwitcher` component in development, but not when code has been deployed to staging or production.
app-project
This should show the project language menu when you build and run the app locally, but should hide it for staging (`APP_ENV=staging`) and production (`APP_ENV=production`) builds.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/tes …
=> Project header: show LocaleSwitcher in development

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/helpers/postTalkComment.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/helpers/postTalkDiscussion.js
This converts all the `QuickTalk` data fetching functions to use SWR (stale-while-revalidate.) New comments are parsed out of the POST response and appended to the `comments` array, so that they appear without refreshing the whole list and losing your place.
~~Labelled as draft until comments are refreshed after you post a new comment.~~
lib-classifier …
=> QuickTalk: data-fetching with SWR

packages/app-project/pages/[owner]/[project]/classify/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js, packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
Add existential checks to `workflows.find()` and `subjectSets.find()` calls in the project app pages, so that they return a 404 response rather than erroring on the server when workflows or subject sets don't exist.
app-project
Closes #3319.
See #3319 for instructions to reproduce the bug, and check whether it's fixed. On this branch, you should see 404 responses, not 500 errors, if a project or workflow can't be found in the Panoptes API.
- Can be used with a screen reader [BBC …
=> Project app pages: fix broken Array.find

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Circle/Circle.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js, packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js, packages/lib-classifier/src/plugins/drawingTools/stories/helpers.js, packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js, packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.spec.js, packages/lib-classifier/src/plugins/tasks/experimental/transcription/TranscriptionTask.stories.js
- Add `task.setToolTaskStrings(stringsSnapshot)` to drawing and transcription tasks. It parses individual task strings from `stringsSnapshot` for each drawing tool, then applies those snapshots to each tool subtask in `tool.tasks`.
- Run `self.setToolTaskStrings` whenever a drawing task's language strings change.
- Add tests.
- Based on #3193.
- Closes #3313.
lib-classifier
Each drawing tool in the storybook has a subtask story, which can be used to check that the task instructions and questions are displayed correctly. Compare with #3193, where the questions and instructions are missing.
#3198 adds localised answers for the question tasks.
_PR Reviewer - Use the checklist during your review. Each …
=> Classifier: localise drawing subtasks

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/getDefaultPosition/getDefaultPosition.js
- Change the minimum popup height to 200px.
- Include the visible window in position calculations.
- When the popup is below the transcribed line, place the top left corner on the bottom of the transcribed line's bounding box, not in the middle of the line.
- When the transcribed line is towards the bottom of the screen, position the popup above the transcribed line, allowing an offset for the minimum popup height and the transcribed line's bounding box.
lib-classifier
Towards #2233. (I'm not sure if the changes here would close that issue for all possible transcription documents and workflows.)
https://localhost:8080/?project=mariaedgeworthletters/maria-edgeworth-letters&env=production
Try transcribing some lines towards the top or the bottom of the viewport. The popup shouldn't appear …
=> Transcription workflows: adjust subtask position

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
noted in Slack per pre-deploy testing:
- invert button not working with multi-frame subjects - https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21240?demo=true
- line color should be consistent regardless of image inverted or not inverted
- return null for invert button regardless of whether invert button enabled
The following workflows have invert enabled, but shouldn't show the invert button in the image toolbar:
- https://local.zooniverse.org:8080/?project=humphrydavy%2Fdavy-notebooks-project&env=production&demo=true&workflow=18575
- https://local.zooniverse.org:8080/?project=1952&workflow=3602&dem …
=> Hide invert button

packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.js, packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.spec.js, packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.stories.js, packages/lib-classifier/src/plugins/tasks/experimental/transcription/TranscriptionTask.stories.js
Use `task.strings.get()` for the tool labels in drawing and transcription tasks.
Based on #3193.
lib-classifier
Try this out on Rosetta Zoo:
https://localhost:8080/?project=ellenjj/rosetta-zoo&env=production
or in the project app:
https://local.zooniverse.org:3000/projects/fr/ellenjj/rosetta-zoo/classify/workflow/19473?env=production
https://user-images.githubusercontent.com/59547/170259934-ac80c841-18e7-4367-90f9-c0e8ba79b308.mov …
=> Classifier: localise drawing task tools

packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.spec.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js
Use `task.strings.get()` for dropdown menu options.
Based on #3193.
lib-classifier
I've updated the test and story to use French strings for a task with English options. I've also got a test workflow in three languages.
https://localhost:8080/?project=908&workflow=3339&language=fr
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
- Can be used from the keyboard [WebAIM …
=> Classifier: localise dropdown task options

kubernetes/deployment-static.tmpl
avoid use of HPAs for fe-static.zooniverse.org use replicas instead and we don't want service node_ports either.
I'll manually clean up the HPAs once this is merged via
- `kubectl delete hpa zooniverse-org-project-static`
- `kubectl delete hpa zooniverse-org-content-pages-static`
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed …
=> remove HPAs and service node port

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js, packages/lib-classifier/src/plugins/tasks/survey/mock-data/task.js
- Pass task language strings down to survey task components.
- Use the strings map to render text for choices, questions, confusions and filters.
- Update the tests and stories to use a mock survey task with a strings map.
Based on #3193.
lib-classifier
Wildcam Darién in Spanish is probably a good workflow to test survey task translations:
https://localhost:8080/?project=wildcam/wildcam-darien&env=production&language=es …
=> Classifier: localise survey tasks

packages/app-project/pages/[env]/[owner]/[project]/about/team.js, packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js, packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js, packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js, packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js, packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js, packages/app-project/src/helpers/getServerSideAPIHost/getServerSideAPIHost.js, packages/app-project/src/helpers/getServerSideAPIHost/index.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js, packages/lib-panoptes-js/src/resources/projects/commonRequests.js
Use internal service names to connect directly to Panoptes when the project app is deployed to our kubernetes cluster.
- Add a `getServerSideAPIHost` helper, which will return the service name for a given deployment and API environment. It falls back to the default host in local development.
- Use `getServerSideAPIHost` to set an optional hostname in all server-side data-fetching functions.
app-project
- towards #3341.
_PR Creator - Please cater the checklist to fit the …
=> Project App: Use internal API service names for SSR

packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
- invert does not reset on subject change
- reset invert to `false` on subject change
- https://local.zooniverse.org:8080/?project=1952&workflow=3602&demo=true
- click the invert button to invert a subject
- click Done to get a new subject
- new subject should not have inverted subject
- Which storybook stories should be reviewed? N/A
- Are there plans for follow up PR’s to further fix this bug or develop this feature? N/A
_PR Reviewer - Use the checklist during your review. Each point should …
=> Reset invert on subject change

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/hooks/useHydratedStore.js, packages/lib-classifier/src/hooks/useHydratedStore.spec.js
There's some code in `ClassifierContainer` which runs when the classifier mounts, but should only run when the window loads and the classifier store is created. This moves that code into the `useHydratedStore` hook, where it runs when the store is first created.
The effect of this is that reloading the page should give you a new subject, as expected, but unmounting and mounting the classifier by navigating the NextJS app, eg. by changing locale, should preserve your current subject and classification, even when session storage is enabled for your project.
Closes #3218.
lib-classifier
The changes are in the classifier, but to test them you'll need to unmount and mount the classifier in Classify pages in the project app. I've got a test project, on staging, which has session caching enabled …
=> Classifier: Refactor ClassifierContainer effect hooks

packages/lib-react-components/src/Tabs/Tabs.stories.js, packages/lib-react-components/src/Tabs/theme.js
Package: `lib-react-components`
This PR fixes an issue where the `<Tabs>` component incorrectly assigns all its children to have `flex-bases: 50%`, NO MATTER the number of child `<Tab>`s.
Expected: `<Tabs>` should display all `<Tab>`s in a row, if there's space.
Actual: `<Tabs>` only displays up to two `<Tab>`s in a row.
Some terminology notes:
```
<Tabs>  // This is the parent/container
<Tab title='cat'>Meow!</Tab>  // This is the first child, with a Tab HEADER saying "cat", and a Tab BODY (or Tab Panel) saying "Meow!" 
<Tab title='dog'>Bark!</Tab>  // ...second child
<Tab title='shaun'>Fart!</Tab>  // ...etc
<Tabs>
```
So here's what's causing the problem:
- `<Tabs>` tries to assign each child `<Tab>` an equal flex-basis ("default size") value, i.e. `flex: 1 1 ${100 / …
=> UI Fix: allow `<Tabs>` to have more than 2 `<Tab>`s in a row

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.spec.js, packages/lib-classifier/src/translations/en/components.json
Affects: QuickTalk experimental feature
This PR attempts to improve the UI for the QuickTalk component.
The goals of this PR:
- Improve messaging for (expanded) QuickTalk panel
_Above: the messages that appear when a Subject has no comments, and user isn't logged in._
- Accessibility: status messages are now marked with role="status"
_Above: the QuickTalk button (on lower right) merges visually with the content a large Task area._
- OPTION 2: make QuickTalk a **tab,** alongside Task and Tutorial in the TaskArea. (might spin off this idea into its own experimental PR) (UPDATE: this is a separate PR)
Not addressed in this PR (probably):
- Advanced keyboard navigation.
- Paging, for Subjects with 10+ comments.
⚠️ TO INVESTIGATE:
- On `lib-classifier`, when a user …
=> QuickTalk: Improve UI

packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js, packages/app-project/src/helpers/getServerSideAPIHost/getServerSideAPIHost.js
Set the default API environment to 'production', which matches our default environment for deploys.
I've also updated the tests to test against a mock API for the default `env`, rather than explicitly setting the API environment.
- #3345 sets the API host to use when the app is deployed, but the default API environment is undefined, which corresponds to `www.zooniverse.org`.
=> getServerSideAPIHost: set default API env

packages/app-project/pages/[owner]/[project]/about/team.js, packages/app-project/src/helpers/fetchTeam/fetchTeam.js, packages/app-project/src/helpers/fetchTeam/index.js
Refactor the project Team page to fetch the team members with a single Panoptes API query, rather than running one query per person.
app-project
Project Team pages can be quite slow to build. Here we can see the SuperWASP Black Holes Team page taking 11s, most of which is spent in 5 calls to `/api/users`.
Testing a project team page against a live project might be the best way to test this. Here's the team page for HMS NHS.
https://local.zooniverse.org:3000/projects/msalmon/hms-nhs-the-nautical-health-service/about/team?env=production …
=> Project: Refactor Team page

packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js, packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js, packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.stories.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Polygon/Polygon.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/PolygonTool/PolygonTool.js, packages/lib-classifier/src/plugins/drawingTools/types/FixedNumber.js, packages/lib-classifier/src/plugins/drawingTools/types/FixedNumber.spec.js, packages/lib-classifier/src/plugins/drawingTools/types/index.js
Some small refactors to the polygon drawing tool:
- a `FixedNumber` type which represents numbers that are fixed to 2 decimal places.
- an `initialDrag` method which copies the initial drag for line tools.
- refactor the polygon path to use a mapped array of points.
- refactor `polygon.setCoordinates` to match other drawing tools.
- refactor Polygon drag handles to use `point.moveTo({ x, y })` for better performance.
- refactor the first point to use `DragHandle`. The starting point can now be moved!
- double click to finish the polygon from a point.
- add Polygon stories.
This PR also fixes a bug where creating an invalid polygon can crash the classifier, when the invalid mark is automatically deleted but the code tries to call `mark.finish()` on the deleted mark.
lib-classifier
The …
=> Classifier: refactor polygon tool

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
lib-classifier
https://github.com/zooniverse/front-end-monorepo/issues/3414
Removed word-break: all and center-aligned FieldGuideButton's text.
To review on a live project, run any project such as PH TESS locally and check out its Classify page.
To review using Storybook, run lib-classifier's stories and check out Field Guide.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac …
=> Classifier: Adjust FieldGuideButton text styling

.github/workflows/deploy_branch.yml, kubernetes/deployment-branch.tmpl
Attempt to allow a k8s deployment for specific branches, similar to how the FE SSG changes PR was setup in #2531 
This PR adds an action that can be manually dispatched to allow the caller to specify which branch should be deployed and then the action & K8s yaml will go deploy that branch build of the fe-project app on a custom subdomain, https://fe-project-branch.preview.zooniverse.org
With this setup we can envisage a chat ops style cmd to deploy a known PR branch from a member of the front end team, e.g. something like `lita fem branch deploy $branch-name` and lita would issue a workflow dispatch event specifying the branch name as the dispatch ref to checkout and deploy, https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event
This K8s setup is a shared space …
=> Branch deploy k8s setup

packages/app-project/pages/[owner]/[project]/classify/index.js
- use [`context.resolvedUrl` and `context.defaultLocale`](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter) to construct the redirect.
- prepend the locale to the new URL path.
app-project
- closes #3436.
Load `/classify` for any project with a single workflow. You should be redirected to the workflow page: `/classify/workflow/[workflowID]`. The redirect should preserve the locale and any query parameters in the request URL.
- Can be used …
=> Project: Refactor /classify redirects

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/plugins/drawingTools/README.md, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js, packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
Refactor drawing tool validation to fix a few bugs that can be triggered when drawing extended marks eg. polygons or transcription lines.
- Finish any incomplete marks when the active tool changes.
- Validate marks, and delete invalid marks, during `mark.finish()`
- Finish any incomplete marks when the Next button is pressed.
- Finish any incomplete marks when another mark is selected. 
- Turn off pointer events for drawn marks and previously transcribed lines, while drawing is in progress. This prevents them from being accidentally selected while there's an unfinished mark on the drawing canvas.
lib-classifier
- Closes #2959.
On my test drawing tools workflow:
- draw an incomplete polygon then switch tools.
- draw a couple of red points and an incomplete polygon then move on to the next …
=> Classifier: validate drawn marks on tool change

yarn.lock
Bump all the storybooks to [version 6.5.9](https://github.com/storybookjs/storybook/releases/tag/v6.5.9) with `yarn upgrade-interactive -S @storybook`.
app-project
lib-classifier
Build and run the storybooks with `yarn storybook`. This PR bumps all the storybook packages from [6.5.4](https://github.com/storybookjs/storybook/releases/tag/v6.5.4) to [6.5.9](https://github.com/storybookjs/storybook/releases/tag/v6.5.9).
=> Bump storybook to 6.5.9

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/CircleTool/CircleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/EllipseTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool/LineTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/RotateRectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/TemporalPointTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalRotateRectangleTool/TemporalRotateRectangleTool.js, packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Drawing tools were set up with a default behaviour that's common to all tools: create a new mark on drag ( `mark.initialPosition(e)` on `pointerDown` and `mark.initialDrag(e)` on `pointerMove`) then finish it on release (`mark.finish()` on `pointerUp`.) This single gesture works for points, lines, circles, rectangles and other simple shapes but doesn't work for extended shapes that require more than one gesture. Complex shapes (transcription lines, ellipses, polygons and freehand lines, at the moment) have to override the default gesture before we can add new code.
This removes the default event handlers from the `Tool` component and copies them explicitly into each drawing tool. Tool code is more verbose but there's no hidden, default tool behaviour to trip up developers of new tools. …
=> Classifier: remove default drawing tool gestures

packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
Set the sanitised locale to the router locale, or English.
- Fixes #3463.
- I've removed the mock router from tests, towards #3429.
Check the Daily Classifications Chart story with different locales, I think.
- Can be used from the keyboard [WebAIM guide to keyboard …
=> Daily Classifications Chart: fix locale

packages/app-project/src/components/ProjectHeader/ProjectHeader.js, packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
app-project
~~Note: This PR is blocked from being merged until #3447 is merged.~~
This PR removes the check for a development environment so the language dropdown will appear on the production site.
Because this change will have no effect on locally-hosted FEM, I recommend using TESS to complete the general checklist below, and then double checking the LocaleSwitcher appears on the staged site once merged to master: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess …
=> App-project: Enable locale switcher for live site

packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, packages/app-content-pages/src/helpers/logger/initializeSentry.js, packages/app-content-pages/src/helpers/logger/logNodeError.js, packages/app-content-pages/src/helpers/logger/logReactError.js
Install `@sentry/node` in the content pages app. Configure webpack to use `@sentry/browser` for logging in browser bundles.
This brings `app-content-pages` into line with the Sentry setup that we use in the project app (#2044.)
Note that [the latest Sentry/NextJS example](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) now uses the [`@sentry/nextjs`](https://docs.sentry.io/platforms/javascript/guides/nextjs/) package for both server-side and client-side logging. We should consider upgrading to that.
- Are there plans …
=> Content pages: log SSR errors with @sentry/node

packages/app-project/next.config.js, packages/app-project/package.json
Remove `dotenv` and `dotenv-webpack` from the project app.
app-project
There isn't a linked issue, but a recent update to lerna broke the project app when it tries to read `.env` on startup. We don't use `.env` files in production, only in local development and then only for the content pages app.
See also:
- #3479 …
=> Project: remove dotenv

packages/app-project/src/shared/components/Loader/Loader.js, packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
- Check whether we're running in a browser window before rendering the `Loader` component.
- Refactor user loading state to simplify the workflow selector logic.
app-project
- Closes #3541.
Run the project app by running `yarn dev` from the `packages/app-project` directory. You should be able to load up Davy Notebooks and test the bug on the home page.
https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project?env=production
- Can be used with a screen reader …
=> Project: don't render Loader component during Server-Side Rendering

packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js
Assign a unique ID to each reduced line that is sent back from Caesar, when that line is first calculated. This avoids a bug where the line IDs change each time that `consensusLines(frame)` is run.
lib-classifier
- closes #2082.
On a workflow which uses previous transcriptions, you should find that each magenta line is dimmed and disabled after a new green line has been created from that line.
https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project/classify/workflow/21734?env=production
https://user-images.githubusercontent.com/59547/185199430-24042c61-3720-4a74-a106-9c7b72582387.mov …
=> Classifier: assign unique IDs to transcribed lines

packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
- Add an `editing` state to freehand lines.
- Double-click to start editing, then click a second time to select the area to cut.
- Drag the open drag handle to draw. Editing automatically ends when you reach the target point.
- ~~Closed shapes aren't fully supported at the moment.~~
- Undo isn't supported at the moment, to cancel accidental cutting of line segments.
https://user-images.githubusercontent.com/59547/179710672-1f6fb58c-a9bc-4479-b837-449dc9059cea.mov
lib-classifier
Freehand lines should be editable in any project that uses them, or in the Freehand Line story in the classifier storybook.
This PR doesn't include undo/redo, but a future PR could wrap `line.points` in an undo manager, so that we can undo and redo changes to a line. …
=> Drawing tools: edit freehand lines

packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/Classifier.workflows.spec.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.js
Add `Classifier.workflows.spec.js`, which defines an array of mock workflows, then loops over that array, testing the Classifier with each workflow in turn.
This tests a branching question workflow and the PH-TESS workflow at the moment. Hopefully, it can be generalised to other types of workflow eg. transcription or survey.
lib-classifier
Just new tests here, so this shouldn't change how the classifier itself runs. I'd be interested in thoughts on how extensible the tests are to different types of workflows, or how we might come up with a set of tests that are general enough to test any workflow while still being useful.
This PR might be a useful jumping off point for automating tests that we currently conduct by hand ie. load a workflow into the classifier, then check that it works …
=> Generalise Classifier workflow tests

packages/lib-classifier/src/helpers/withFeatureFlag/withFeatureFlag.js
- Add `forwardRef` to `withFeatureFlag`, so that refs are passed to the wrapped component.
- Refactor `withFeatureFlag` to use `useStores` and `observer`.
lib-classifier
- #3413 wraps a `Tab` component, but tabs use refs passed down from their parent `Tabs`. …
=> Classifier: add forwardRef to withFeatureFlag

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
- add a `subtaskpopup-task` CSS class to task components.
- use that class to find tasks in the tests.
This merges into #3568, and should fix the broken tests in that PR.
=> Fix SubTaskPopup tests

packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js, packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
- Fix broken prop types in `WorkflowSelectButton`.
- Add a mock `RouterContext` to `Hero` and `WorkflowMenuModal` stories.
- The workflow menu waits for the user to load, so apply a snapshot of a mock, loaded user to the mock store in stories.
app-project
- closes #3567.
Open the project storybook and check the stories for Screens > Project Home > Hero and Screens > Classify > Workflow Menu Modal. Both of them should show a list of mock workflows.
- Can be used with a screen …
=> Project: show workflow menu in stories

packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.spec.js
Refactor `QuickTalk` to replace `withTranslation` with `useTranslation`, `withStores` with `useStores` and `authClient` with `usePanoptesAuth`.
lib-classifier
Shaun's test project uses QuickTalk on staging.
https://localhost:8080/?project=darkeshard/test-project-2022&workflow=3581&env=staging
- Can be used from the …
=> Classifier: Replace QuickTalk HOCs with hooks

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js, packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js, packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
- use `tryReference` to reference `task.activeMark`, which avoids crashes caused by invalid reference errors when the active mark changes.
- use `mark.id` in `task.setActiveMark`, because MST references use node identifiers, not the nodes themselves.
- remove `activeMark.finish()` when a new mark is selected. Otherwise, creating a new mark will automatically select it and then delete it.
- cancel event bubbling, as well as the default handler, when a mark finishes.
lib-classifier
- Closes #3498.
- Are there plans for follow up PR’s to further fix this …
=> Drawing tools: refactor active mark selection

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
- style the SVG subject with [`touch-action: pinch-zoom`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).
- cancel both the default handler and event bubbling for all pointer events on the drawing canvas.
This PR should apply the same changes to the drawing tools that we added to PFE in https://github.com/zooniverse/Panoptes-Front-End/pull/5411.
lib-classifier
- Towards #3534
Marsh Explorer is a good project to check the drawing tools on touch devices. Basically, we expect that you should be able to draw without triggering any default browser behaviours, such as scrolling the screen when you drag to create a mark.
https://www.zooniverse.org/projects/marshexplorer/marsh-explorer/classify
In the dev classifier: https://local.zooniverse.org:8080/?project=marshexplorer/marsh-ex …
=> Improved touch event handling for drawing tools

packages/app-project/pages/_app.js, packages/app-project/src/hooks/index.js, packages/app-project/src/hooks/usePanoptesAuth.js, packages/app-project/src/hooks/useUserFavourites.js, packages/app-project/stores/User/Collections/Collections.js, packages/app-project/stores/User/Collections/Collections.spec.js, packages/app-project/stores/User/User.js, packages/lib-panoptes-js/src/resources/collections/rest.js
- Add a `usePanoptesAuth` hook to get bearer tokens in components.
- Add a `useUserFavourites` hook, which runs periodically to check user project favourites.
- Refactor the Collections model to fetch or create favourites when new subjects are added to favourites.
- Add tests.
app-project
- closes #2473.
Visiting a project that you've visited or classified on before, the project should try to fetch favourites when it first loads. When you favourite a new subject, it should either be added to the already loaded favourites collection, or favourites should be fetched and then updated.
Visiting a new project, favourites should be created the first time that you favourite a subject (when `user.collections.addFavourite` is called.) You shouldn't find an empty favourites …
=> Project: Refactor data-fetching for favourites

packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
#1699 
The sidebar with the filters has been placed before the list of publications so that individuals with screen readers can tab through the filtered controls before getting to the publications list.
I also changed the width of the sidebar from medium --> small to improve the responsive layout.
- Run the app-content-pages using yarn dev.
- Navigate to the about/publications page (http://localhost:3000/about/publications)
- Tab through the links and it should go from 'Donate' to 'Show All'
- Alternatively, activate screen reader (CMD+F5 on macOSv.12.5) and see how the page navigates straight to the filter on the sidebar instead of the main body- more useful for screen readers.
- Are there plans for follow up …
=> Fixed accessibility issue: content filters are before the publications list in the tab order

Jenkinsfile
Update the production NextJS apps to fetch assets via `www.zooniverse.org`.
Since #2541, NextJS assets should be fetched from `www.zooniverse.org` in production and `frontend.preview.zooniverse.org` on staging.
Closes #3587.
=> Fix NextJS asset prefixes

packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
- copy the current line path to `mark.originalPoints` before cutting a freehand line.
- listen to changes in the `active` prop and restore the original line when `active` is false (when the line loses focus.)
lib-classifier
- closes #3558.
Draw a freehand line, start to edit  it then try selecting another mark, or switching to a different drawing tool. On this branch, switching away from a line should cancel editing and restore the original line.
https://user-images.githubusercontent.com/59547/185629689-98efd437-37cf-4e61-8b82-02097e6ebdb6.mov …
=> Freehand line: cancel edits on deselect

packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js, packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js, packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js, packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.js, packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.spec.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js, packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js, packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.spec.js
app-project
This is a follow-up to unit test refactoring started in #3571.
A mocked store object is injected as a prop for several components in a testing environment. I've refactored the naming of `mockStore` to make it clear this is not a prop normally passed to a component in the production app.
This is mostly a refactor for our unit tests, so tests should be passing locally and on Github. The General UX checklist with i-fancy-cats is also a good review tool to check that all project pages (Home, About, Classify) load without error.
I'll make another PR with the same refactor for lib-classifier.
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed …
=> Project App: Refactor naming of mockStore when it's injected as a component prop

packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
Refactor Recents, on the Classify page, so that the placeholder subject is null during SSR.
app-project
- closes #3606.
On the Classify page: 
- while logged in, check that #3606 is fixed by looking at recent subjects after leaving and returning to the page.
- while logged out, check that the placeholder images show up.
You can refer to the [Recent Subjects story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-classify-recent-subjects--plain&globals=locale:en;locales.en:English;locales.test:Test+Language) to see how the component should be laid out.
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked …
=> Project: only render user recents in the browser

packages/app-project/stores/User/User.js
Use `applySnapshot` to clear the stored user on sign out, including collections, recents and personalisation.
app-project
- closes #3608.
- Log in and out of a project that you've classified on. Recent subjects should only be displayed while you are logged in.
- Also check that the classifier loads properly for both logged-in and logged-out volunteers.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/t …
=> Project: clear stored User on log out

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
Turn on [React Strict Mode](https://reactjs.org/docs/strict-mode.html) for both NextJS apps.
app-project
Running the apps in development (`yarn dev`) will now use [Strict Mode](https://reactjs.org/docs/strict-mode.html). You'll see console warnings for deprecated features or code that may cause problems in future versions of React. Otherwise, both apps should continue to work as usual. …
=> NextJS apps: enable Strict Mode

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
In Safari v16 the light curve viewer height expands infinitely, similar to issue related to #3119 and #3139 .
- create const for container height as string with px (i.e. `"700px"`), which I believe represents the 100% height value intended
- set d3 generated svg height attribute with new const for container height
- to confirm bug:
- with Safari v16, load https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235, note light curve subject viewer expands infinitely
- to confirm fix:
- lib-classifier - https://local.zooniverse.org:8080/?project=1862&workflow=3317
- app-project - …
=> Refactor LightCurveViewer height with defined value before d3 svg defined

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Reverts zooniverse/front-end-monorepo#3646
Cuts off x-axis:
=> Revert "Refactor LightCurveViewer height with defined value before d3 svg defined"

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/index.js, yarn.lock
- add named exports to `@viewers/components/SVGComponents`.
- Use the `Chart` component as the root `svg` element of `LightCurveViewer`.
- refactor `LightCurveViewer` to use `height` and `width` from the SVG's client bounding rectangle.
- draw the SVG chart on component mount.
- wrap `LightCurveViewer` in a fixed-height box, like `ScatterPlotViewer`.
lib-classifier
- Closes #3654.
Dev classifier: https://localhost:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy …
=> Classifier: Refactor LightCurveViewer to use Chart component

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
- iteration on #3661, related to #3654
- edits reference to `props` to `this.props` per refactors in #3661
- confirm bug (no `annotation.values` after drawing a few transits): https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?demo=true
- confirm fix (`annotation.values` includes transits drawn): https://local.zooniverse.org:8080/?project=1862&workflow=3317
- draw a few transits (**in demo mode if on production project!**), click Done, note classification logged in console
- …
=> Edit LightCurveViewer saveBrushesToAnnotations props reference

packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
- Add `revertEdits` and `cancelClipPath` actions.
- Revert any existing clipped points before starting a new edit.
- Refactor `line.cutSegment` to take the start and end of the segment as arguments: `cutSegment(startPoint, endPoint)`.
- Refactor splicing and trimming the points array to allow for drawing in either direction. The line should now reverse if you edit in the opposite direction to the original drawing.
- Refactor the freehand line state logic to use `segmentationInProgress` which will be true if either:
- the line path (open or closed) has been cut into two segments in the middle.
- the line is open but we are editing the ends of a closed shape.
I've also included some fixes for small bugs that came up in the review of #3559.
These changes allow the clipped path to be modified …
=> Freehand line: adjust segments before editing 

packages/app-project/public/locales/en/components.json, packages/app-project/src/components/AdminContainer/AdminContainer.js, packages/app-project/src/components/AdminContainer/AdminContainer.spec.js, packages/app-project/src/components/AdminContainer/index.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js, packages/app-project/src/components/index.js, packages/app-project/src/hooks/index.js, packages/app-project/src/hooks/useAdminMode.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js, packages/app-project/stores/User/User.js
- add `user.admin` to logged-in users.
- add a `useAdminMode` hook to manage admin state across project pages.
- add `AdminContainer` to the footer, which manages the 'Admin Mode' toggle button.
- add the project admin link to project navigation.
- add named exports for project components to make imports easier to write.
- add RTL tests for the project header, project home page and standard layout.
app-project
- Logged in as an admin: the admin toggle should be enabled in the page footer. When it's on, the project admin page link is added to the project navigation.
- Logged out, or logged in as a non-admin user, you should just see the regular project.
_PR Reviewer - Use the checklist during your …
=> Projects: add Admin Mode

packages/lib-react-components/src/Markdownz/Markdownz.js
Add a try/catch block to Markdownz so that markdown parsing errors don't crash the parent app, making the page unusable. When there is a parsing error, the error message is displayed instead of the original content.
- closes #3673.
With these changes, markdown errors in the Maria Edgeworth Letters team page will be caught during server-side rendering, and the page content should at least show correctly when React runs in the browser and renders the content for a second time.
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke …
=> Markdownz: catch parsing errors

packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.spec.js
Copy the `required` flag across when creating simple dropdown tasks from legacy dropdown tasks.
lib-classifier/src/plugins/tasks/simple-dropdown
- fixes #3639 
The dropdown task should require an answer now, on this test workflow.
https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/3852
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-m …
=> Classifier tasks: Copy task.required for legacy dropdowns

packages/app-content-pages/package.json, packages/app-content-pages/src/shared/components/AuthModal/AuthModalContainer.js, packages/app-content-pages/src/shared/components/AuthModal/AuthModalContainer.spec.js, packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js, packages/app-content-pages/test/create-global-document.js, packages/app-project/package.json, packages/app-project/src/components/AuthModal/AuthModalContainer.js, packages/app-project/src/components/AuthModal/AuthModalContainer.spec.js, packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js, packages/lib-panoptes-js/package.json, packages/lib-panoptes-js/src/resources/projects/helpers.js, yarn.lock
Replace the [`url-parse`](https://www.npmjs.com/package/url-parse) package with the [native URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL), which is supported in Node and in browsers. Using the native interface should make both NextJS apps more secure. 
From `url-parse`'s Readme:
>`url-parse` was created in 2014 when the WHATWG URL API was not available in Node.js and the URL interface was supported only in some browsers. Today this is no longer true. The URL interface is available in all supported Node.js release lines and basically all browsers. Consider using it for better security and accuracy.
app-project
Sign in and register should work in both NextJS apps. The project app should still load projects based on the slug in the …
=> Replace url-parse with URL

packages/lib-classifier/src/plugins/drawingTools/components/Circle/Circle.spec.js, packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js, packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.spec.js
Drawn marks are SVG, so need to be wrapped in an `<svg>` element in order to render without errors.
lib-classifier/src/plugins/drawingTools
- closes #3624.
Run the tests for `Circle`, `Rectangle` or `DeleteButton` and check for errors.
=> Drawing tool tests: wrap marks in <svg>

packages/app-content-pages/src/screens/Publications/Publications.js, packages/app-content-pages/src/screens/Publications/PublicationsContainer.js, packages/app-content-pages/src/screens/Publications/components/Category/Category.js, packages/app-content-pages/src/screens/Team/Team.js, packages/app-content-pages/src/screens/Team/TeamContainer.js, packages/app-content-pages/src/screens/Team/components/Team/Team.js, packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js, packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js, packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js, packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
- closes #3584.
- closes #3693. 
Made the Publications heading and content tag its own section so that screen readers can navigate the page. This (however) has slightly altered the layout.
See screenshot below:
- top-level page navigation uses [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) and shows the active page visually, closing #3693.
- Publications filters are marked up as a list, to match the filters on the Team page.
- Every filter is a link with a document fragment identifier, giving each section its own URL eg.
- http://localhost:3000/about/team#the-adler-planetarium
- http://localhost:3000/about/publications#nature
- Go to about, [Publications]( http://localhost:3000/about/publications) and use …
=> Improve Publications and Team page content accessibility

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
When drawing is enabled for video subjects, style the root SVG element with `touch-action: pinch-zoom;` so that dragging doesn't scroll the screen.
lib-classifier
- #3535.
- #3534.
On an iOS device, or Chrome on Android, you should find that you can draw a rectangle on a Solar Jets subject without the window scrolling when you drag the shape.
https://frontend.preview.zooniverse.org/projects/eostlund/video-project/classify/workflow/16843
- Can be used with a screen reader [BBC …
=> Video subjects: Add touch styles

packages/lib-react-components/src/ZooFooter/ZooFooter.js, packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js, packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js, packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.js, packages/lib-react-components/src/ZooFooter/components/index.js, packages/lib-react-components/src/translations/en.json
- Replace `enzyme` with `@testing-library/react` in `ZooFooter`.
- Add some tests for the lists of links in the footer.
`ZooFooter` wasn't tested at all, so I've written some quick tests that check if the various lists of links exist in the DOM.
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR …
=> Zooniverse-React-Components: Remove Enzyme from ZooFooter

packages/lib-react-components/src/ZooHeader/ZooHeader.js, packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js, packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.js, packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js, packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
- Replace `enzyme` with `@testing-library/react` in `ZooHeader`.
- Test the header menus with both logged-in and logged-out users.
- Can be …
=> Zooniverse-React-Components: Remove Enzyme from ZooHeader

packages/lib-react-components/src/Markdownz/Markdownz.js, packages/lib-react-components/src/Markdownz/Markdownz.spec.js, packages/lib-react-components/test/setup.js
Rewrite `Markdownz` as a functional component and update tests that rely on it being a class.
Remove Enzyme from the tests. 
Where class methods were being tested directly, I rewrote them as pure functions and rewrote the tests to test those functions. 
- follows #3678.
Probably easiest to review this by running the tests and checking the Markdownz stories in the storybook, which seem to comprehensively test expected Markdown support.
- Can be used with a …
=> Refactor Markdownz as a functional component

packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/README.md, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
A couple of optimisations to reduce the size of marks produced by the freehand line tool.
- Replace `line.points` with `line.pathX` and `line.pathY`, which are flat arrays of the line's `x` and `y` coordinates.
- Set a minimum distance of 0.5px between adjacent points when appending to the line, or inserting new points.
- refactor the calculation of the SVG path with `useMemo`.
- https://github.com/zooniverse/Panoptes-Front-End/issues/4423
- https://github.com/zooniverse/Panoptes-Front-End/issues/3551
lib-classifier/src/plugins/drawingTools/experimental
It's probably best to test this on a real cell from Etch-A-Cell, to try out the drawing tools with a large annotation.
https://localhost:8080/?project=h-spiers/etch-a-cell&workflow=8921&env=production
Alternatively, try out the deployed PR …
=> Freehand lines: optimise annotation size

packages/app-project/src/shared/components/Stat/Stat.js, packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.js, packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.js, packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js, packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js, packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js, packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/components/SubjectGroupComparisonTask.js, packages/lib-react-components/src/ZooFooter/ZooFooter.js, packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js, packages/lib-react-components/src/ZooHeader/ZooHeader.js
Packages: `app-project`, `lib-classifier`, `lib-react-components`
This PR is a minor maintenance refactor. The `tag` prop for Boxes (and by extension, all components descended from it) in Grommet is deprecated; the correct prop to use is `as`.
Ready for review, low priority.
=> Maintenance: replace deprecated Grommet 'tag' prop with 'as'

packages/app-project/src/components/ProjectHeader/ProjectHeader.js, packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/shared/components/ContentBox/ContentBox.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/lib-react-components/src/ZooHeader/ZooHeader.js
- Remove `header` from the `ProjectHeader` and `ContentBox` components.
- Remove presentational `header` from `ZooHeader`.
- Add headers to the `StandardLayout` template, and to the `ProjectHomePage` component, so that each project page only has one page-level banner, which includes the Zooniverse site header, the project header and any project announcements.
Deployed to https://fe-project-branch.preview.zooniverse.org/projects/brooke/i-fancy-cats?env=staging
app-project
- closes #3710.
- closes #3717.
Browsing a project now, there should only be one page-level header on each page. If you open the rotor in VoiceOver, there should only be one page banner listed under Landmarks.
https://user-images.githubusercontent.com/59547/192894951-328e08ca-0e79-4b98-afeb-034121cd0d8 …
=> Add project page-level headers

packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/RotateHandle.js, packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/RotateHandle.spec.js, packages/lib-classifier/src/translations/en/components.json
Part of: Maintenance Week Oct 2022
Adds React Testing Library tests for the RotateHandle component
- RotateHandle is a mostly presentational component. (Functionality tests should be in draggable and the components that use the draggable RotateHandle.)
- Test IDs added for querying. (I based this on Rectangle.spec.js's pattern, since I can't find a good consensus online on what kind of ARIA role this should take on.)
=> Maintenance Week: add tests for RotateHandle

packages/app-content-pages/package.json, packages/app-project/package.json, packages/lib-classifier/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
- Print HTML tags in the `lib-react-components` changelog as inline `<code>` text.
- Update changelog with new version and undocumented changes.
- Update version.
- Update installed package versions.
Once this is merged, we can `npm publish` the new version and update any projects that use `@zooniverse/react-components`.
`npm publish --dry-run` will build and publish the new package without actually uploading it to `npm`.
=> @zooniverse/react-components v1.2.0

packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js, packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js, packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js, packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.spec.js
- refactor `fetchStatuses` to remove the callback and translation arguments.
- set state directly in the `SubjectPicker` component, after fetching data from APIs.
- refactor `useEffect` to make its dependencies explicit in the subject picker.
- refactor subject statuses to use the `useTranslation` hook in the parent component.
#3571 highlighted bad tests in the `SubjectPicker` component, which failed when we upgrade to NextJS 12.2. Here, the `fetchStatuses` helper is refactored to fetch new data and return it to the parent component. Previously, it used a callback to set state in the parent component, which led to problems when tests mocked the `setRows` function.
app-project
`yarn build` shouldn't generate any warnings for the `SubjectPicker` component. Many of the other build warnings …
=> Project app: Refactor subject picker data fetching

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
- Add admin mode to the classifier.
- Allow admin users to override `canPreviewWorkflows` when admin mode is on.
- Test the classifier for admin users, with and without admin mode enabled.
- refactor some repeated code as functions in the `Classifier` tests.
app-project
lib-classifier
Admins should have permission to load any workflow on projects where they aren't already a team member. To test this out, you'll need to try loading an inactive workflow on a project that you don't own or collaborate. With admin mode turned off, the workflow won't load but it should load with admin mode turned on.
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before …
=> Admin mode: admins can load inactive workflows

.github/workflows/ci-build.yml, .github/workflows/coverage.yml, .github/workflows/deploy_staging.yml
These GH actions are [deprecated at v2](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). This bumps them to v3.
- checkout.
- setup-node.
- upload-artifact.
- download-artifact.
=> Bump GitHub v2 actions to v3

.github/workflows/sentry-production-releases.yml, .github/workflows/sentry-staging-releases.yml
- update to `actions/checkout@v3`.
- replace the old CLI install with the new Sentry release action.
- Merge to the main branch creates a new Sentry staging release for the project and content-pages apps.
- Updating the `production-release` tag finalizes that staging release as a production release.
=> Update Sentry release actions

.github/workflows/sentry-production-releases.yml
The `projects` key is required in order for the action to run.
=> Add projects to Sentry production releases

packages/app-project/src/hooks/useAdminMode.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js, packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
- check for an admin user in the `useAdminMode` hook.
- wait for an admin user to log in before adding the admin border to the page.
- clear admin mode on log out.
- style the page border with `styled()` when Admin Mode is on.
- mock the Talk API when the page requests unread notifications and messages.
app-project
- closes #3690.
- closes #3747.
When I set up the `useAdminMode` hook, I forgot to check for a logged-in admin user. With the changes here, admin mode requires both a logged-in admin user and the admin toggle (in the page footer) to be set. When the page loads, admin mode should wait until your user profile has loaded before adding the page border, which fixes #3690. Admin mode should be turned off when you sign out, which fixes #3747.
_PR Creator - Please cater the checklist …
=> Admin Mode: check for logged-in admin user

docs/arch/adr-46.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/Flipbook.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/README.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js, packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js, packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js, packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js, packages/lib-classifier/src/store/SubjectStore/Subject/Subject.spec.js, packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
lib-classifier
Flipbook Project Board: https://github.com/zooniverse/front-end-monorepo/projects/21
ADR 46 describes the intended flipbook features and that this viewer is completely separate from the Multiframe Viewer.
Development of the Flipbook Viewer is divided into bite-size PR's. This PR sets up the basic classifier configuration and code files to display the flipbook for subjects with multiple images in the `locations` array. The flipbook is now the default viewer for that subject type unless a workflow config specifies `multiFrame`. See SubjectStore > Subject model > getViewer() for more details.
I included a basic storybook file and placeholder unit test file. The Flipbook Viewer component itself has a simple placeholder Grommet Box for now.
To see the Flipbook Viewer run …
=> Flipbook Viewer: Display this viewer for non-transcription multiple-image-subjects

kubernetes/deployment-production.tmpl
Image pulls for the new production deploy pod are failing because it's still looking at Docker Hub. This updates the image locations to point to GHCR.
- Can be …
=> Update images in prod deploy template

packages/lib-react-components/src/ZooniverseLogo/ZooniverseLogo.js, packages/lib-react-components/src/ZooniverseLogo/ZooniverseLogo.spec.js, packages/lib-react-components/src/translations/en.json
Replaces #3733 
Package: `lib-react-components`
Part of: Maintenance Week Oct 2022
This PR adds React Testing Library tests for the ZooniverseLogo component.
- Also, the "Zooniverse Logo" title now has translations hooked up.
- No tests will be added for ZooniverseTypeLogo, since these were removed in #3732
=> Maintenance Week: add tests for ZooniverseLogo

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
- removes `react-progressive-image`.
- adds `useProgressiveImage` hook to exports.
=> @zooniverse/react-components v1.2.1

Dockerfile, packages/app-project/middleware.js
- Pass requests for `/commit_id.txt` through to the NextJS app without rewriting the request URL.
- Publish the deployed commit for the content pages app.
app-project
- fixes #3864.
[Build and run a docker image](https://github.com/zooniverse/front-end-monorepo#docker), then check that `http://localhost:3000/projects/commit_id.txt` and `http://localhost:3001/about/commit_id.txt` return a file. The file contents will be whatever `$COMMIT_ID` is set to in your local environment, which might be empty/undefined.
EDIT: you can pass a mock commit hash to the Docker build in order to test it. See the instructions for #2217.
```
docker compose build --build-arg COMMIT_ID=05503fc5
```
Alternatively (and much quicker), run [a branch …
=> Fix the project status check

packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/Classifier.workflows.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
lib-classifier
The `xlink:href` attribute for svg is [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href).
I removed xlink:href from SVGImage and SGVGridCell components as well as any unit tests that looked for it as an attribute.
To test this PR, view the subject viewers in storybook that use SVGImage under the hood such as 
- SingleImageViewer
- FlipbookViewer
- MultiFrameViewer
Run any project locally that uses the above viewers such as [Wildwatch Burrowing Owl](https://local.zooniverse.org:3000/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify?env=production) or i-fancy-cats.
The SubjectGroupViewer in storybook uses SGVGridCell. …
=> Classifier: remove deprecated xlink from svg images

packages/app-content-pages/.babelrc, packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, packages/app-content-pages/pages/_document.js, packages/app-content-pages/src/shared/components/AuthModal/AuthModalContainer.js, packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginFormContainer.js, packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterFormContainer.js, packages/app-project/.babelrc, packages/app-project/next.config.js, packages/app-project/package.json, packages/app-project/pages/[panoptesEnv]/[owner]/[project]/logger.js, packages/app-project/pages/_document.js, packages/app-project/src/components/AuthModal/AuthModalContainer.js, packages/app-project/src/components/AuthModal/components/LoginForm/LoginFormContainer.js, packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterFormContainer.js, packages/app-project/src/components/Head/HeadContainer.js, packages/app-project/src/components/ProjectName/ProjectNameContainer.js, packages/app-project/src/components/ThemeModeToggle/ThemeModeToggleContainer.js, packages/app-project/src/helpers/GrommetWrapper/GrommetWrapperContainer.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js, packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModalContainer.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Background/BackgroundContainer.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js, packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js, packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js, packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProjectContainer.js, packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js, packages/app-project/src/shared/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.js, yarn.lock
- Replace `babel-plugin-styled-components` with the [built-in styled components compiler](https://styled-components.com/docs/advanced#nextjs) for both NextJS apps.
- Remove `babel-plugin-dynamic-import-node`. Async imports are supported in Node now.
- Remove class decorators. They were a noble attempt at more readable syntax but no one liked them. 
- Use SWC for builds. Keep Babel to run the tests.
app-project
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still work without these plugins.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), then check both NextJS apps on …
=> NextJS: remove outdated babel plugins

.github/workflows/deploy_branch.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
Reverts zooniverse/front-end-monorepo#3770
Deploys to Azure fail with the updated action.
=> Revert "Bump Azure/aks-set-context from 2 to 3"

packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
- Extract `focusMark` into its own function.
- Focus a mark when it is both active and finished.
- Focus a mark when its subtasks close.
- Open a mark's subtasks automatically when the mark is finished.
- Remove the delete button from the DOM tab order, since it's nested inside a focusable mark, which is masquerading as a labelled button. You can't nest buttons inside other buttons.
- Convert tests from Enzyme to React Testing Library. 
lib-classifier
- towards #3815.
- fixes #3858.
I have a test workflow, with various drawing tools (with and without popup questions) that you can use to test this PR from the keyboard.
From the keyboard you should be able to tab through all the drawn marks, open the sub task forms, edit the sub tasks and close each popup. You should only need a mouse (or …
=> Refactor drawing tool focus management

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
lib-classifier
Flipbook Project Board: https://github.com/zooniverse/front-end-monorepo/projects/21
In PFE, the flipbook viewer persists play speed when volunteers are shown a new subject. This PR moves FEM's flipbook play speed from FlipbookControls component state to a `flipbookSpeed` property on the subject viewer store. A volunteer's chosen play speed will be saved across subjects instead of resetting.
View [Wildwatch Burrowing Owl on PFE](https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify) to see how its subject viewer saves flipbook speed. Then run this branch locally and view the same project [locally](https://local.zooniverse.org:3000/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify/workflow/21141?env=production). FEM's flipbook …
=> Classifier: Save Flipbook play speed between subjects

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
lib-classifier
https://github.com/zooniverse/front-end-monorepo/issues/3792
For subjects with multiple images in the `locations` array, SubjectViewerStore's `resetSubject()` (called upon subject load) handles `metadata.default_frame`. This PR specifies that a default frame of 2 should be set as index 1, or a default frame of 1 should be set as index 0, etc.
Flipbook's storybook now has a case where the subject's default frame is 3. Viewing that story on this branch should correctly show frame 3 selected when the subject loads.
As mentioned in Issue #3792, Correct-a-cell's subjects have `default_frame` of 3, so viewing the project [locally](https://local.zooniverse.org:3000/projects/h-spiers/etch-a-cell/classify/workflow/8921?env=production) should correctly show frame 3 selected when the …
=> Classifer: handle default frame for multi-image subjects

packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/components/FilterButton.js
Refactor the filter buttons `onChange` and delete functions as callbacks that can toggle the selected option on or off (if already selected.)
Fix filter icon styling so that icons aren't clipped.
lib-classifier
This can be checked with the Survey Task story in the storybook. Filter icons shouldn't be clipped any more, and there shouldn't be a flash of teal placeholder for each filter radio button. Other than that, the survey task filter should continue to work as expected.
- Can …
=> Survey task: refactor filter buttons onChange

packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
- fix styling issue with Confusion button container
- https://local.zooniverse.org:8080/?project=1634&workflow=2434
- with bug: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/tasks-surveytask-choice--default&globals=locale:en;locales.en:English;locales.test:Test+Language
- with fix (locally): http://localhost:6006/?path=/story/tasks-survey-choice--default&globals=locale:en;locales.en:English;locales.test:Test+Language
- Are there plans for follow up PR’s to further fix this bug or develop …
=> Classifier: survey task confusion button container styling fix

packages/app-content-pages/README.md, packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, packages/app-project/README.md, packages/app-project/next.config.js, packages/app-project/package.json, yarn.lock
- Add [`@next/bundle-analyzer`](https://www.npmjs.com/package/@next/bundle-analyzer) to both NextJS apps.
- Add `yarn analyse` to generate bundle size reports for an app.
Builds on #3900 so review that first.
app-project
Run `yarn analyse` for each NextJS app. It should build the JS bundles, then generate webpack bundle analyser reports for the browser bundle and the server bundle
=> Install @next/bundle-analyzer

package.json, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
- refactor survey task tests for when choice with required questions selected
- refactor some (not all, left at least one test with `getByRole` for related component) tests with `getByText` instead of `getByRole`
- improves `SurveyTask.spec.js` tests runtime by approximately 4 seconds
_PR Reviewer - Use the checklist during your review. Each point should be …
=> Classifier: Refactor survey task tests

packages/lib-classifier/webpack.dist.js, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/webpack.dist.js
- Remove source maps from production webpack builds.
- Bump `@zooniverse/react-components` to 1.3.1.
lib-classifier
=> Remove source maps from webpack builds

packages/lib-classifier/dev/index.js, packages/lib-classifier/package.json, yarn.lock
Remove `query-string` from the dev classifier.
Replace [`query-string`](https://www.npmjs.com/package/query-string) with the native [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) interface.
lib-classifier
Run the standalone classifier on https://localhost:8080 with `yarn dev`.
=> Remove query-string

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
Refactor Done button queries in the survey task tests to use `querySelectorAll` rather than `getByRole`.
lib-classifier
=> Refactor Done button queries

packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
Refactor choice button labels to use the Grommet `Image` component and fix invalid HTML inside the `<button>` element.
lib-classifier
You can check the changes here with the Survey Task story in the storybook. It shouldn't have changed, except that the layout shift when choices first load should now be fixed.
=> Refactor survey task choice button labels

packages/app-project/src/components/ProjectHeader/ProjectHeader.js, packages/lib-react-components/src/ZooHeader/ZooHeader.js
Debounce resize observers, in the Zooniverse page header and the project header, in order to avoid resize loop limit errors from browsers.
Sentry is logging thousands of resize observer loop limit errors per week for project pages. This change might reduce or even prevent them entirely.
app-project
- See the discussion on https://github.com/maslianok/react-resize-detector/issues/45.
I'm not entirely sure how to check this, since resize observer errors are thrown by the window, so not logged in the console. You could resize the browser window and check that adding the debounce hasn't altered the re-rendering of the Zooniverse header or the project header.
EDIT: to test this out, add an error listener to the window, then look for resize errors firing when you navigate …
=> Debounce resize observers

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
app-project
Re-opens Issue https://github.com/zooniverse/front-end-monorepo/issues/3958 for now
Reverts PR https://github.com/zooniverse/front-end-monorepo/pull/3961
Per @snblickhan and I’s suggestion, we’re going to remove the max-width constraint on the classify page today - primarily because the projects that benefit from a max-width are not launched on FEM yet. Volunteers working on transcription projects have reported on more than one occasion that the ability to increase subject width in relation to task area (via browser zoom) is crucial to their ability to make a classification.
Load I Fancy Cats and zoom out to simulate an extra-wide display. Or view the Classify page on an extra-wide monitor, if you have one available.
Load a transcription project such as [Poets & …
=> Project App: Remove max-width on Classify Page

README.md
Package: root
This PR updates the README with better(?) publishing instructions. I haven't tried the old `yarn publish` method myself TBH, but I _can_ attest to the fact that `npm publish` worked correctly for me when publishing `@zooniverse/react-components` [v1.3.2](https://www.npmjs.com/package/@zooniverse/react-components) today.
=> Update README with better publishing instructions

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
lib-classifier
Relevant [ADR](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-11.md)
Related Slack [thread](https://zooniverse.slack.com/archives/C01TYAR0V43/p1661374475093859)
I removed the formatting intended to add `+tab+` to links in MetadataModal's `data`. That sequence would have worked in PFE's markdown handler, but is no longer supported in FEM's Markdownz.
This is best reviewed in storybook. There's a Metadata Modal story with data that includes a url. When displayed as a table, the url is rendered as a link that should open in a new tab. Previously, the link did not work at all.
There's much more refactoring of MetaTools coming in a future PR (on branch `metatools-refactor`).
_PR Creator - Please cater the checklist to fit the review needed for your …
=> Classifier: Remove legacy +tab+ formatter from MetadataModal

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
lib-classifier
Follow-up to video subject viewer dev: https://github.com/zooniverse/front-end-monorepo/projects/13
This PR adds the [controlslist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-controlslist) attribute 'nodownload' to the video element of the video subject viewer because [PFE](https://www.zooniverse.org/projects/elwest/woodpecker-cavity-cam/classify)'s video subject viewer does not allow downoads.
Load the classifier's storybook to view the SingleVideoViewer story, or view a video project such as [Woodpecker Cavity Cam](https://local.zooniverse.org:3000/projects/elwest/woodpecker-cavity-cam?env=production) while running this branch locally. …
=> Classifier: Specify no download for video subject viewer

yarn.lock
Bump `next` and `eslint-plugin-next` to [12.3.4](https://github.com/vercel/next.js/compare/v12.3.3...v12.3.4).
This will close an open [Dependabot security alert](https://github.com/zooniverse/front-end-monorepo/security/dependabot/60).
app-project
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally in Node](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still build and run. You can run `yarn bootstrap:es6` to skip the Webpack builds, for a faster build used in production deploys.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), …
=> [Security] Bump NextJS to 12.3.4

packages/lib-react-components/src/Tooltip/components/Label/Label.spec.js, packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.spec.js
Follows #4107 
Part of: Maintenance Week
This PR adds React Testing Library tests for Tooltip's sub-components. They're pretty basic, honestly.
=> Maintenance Week: add tests for Tooltip's sub-components

packages/lib-react-components/src/Markdownz/Markdownz.js, packages/lib-react-components/src/Markdownz/Markdownz.spec.js, packages/lib-react-components/src/Markdownz/markdownGridExample.md, packages/lib-react-components/src/Media/Media.stories.js, packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
Closes: https://github.com/zooniverse/front-end-monorepo/issues/2554
- Allow `height` to be undefined when parsing markdown image strings that contain custom dimensions such as "=200x" or "=100x100".
- Refactored Media component's stories to have more explicit examples of images
- linting
This can be reviewed by looking at the Media or Markdownz stories in lib-react-components storybook.
You can also run app-project locally and visit Superwasp's [Team page](https://local.zooniverse.org:3000/projects/hughdickinson/superwasp-black-hole-hunters/about/team?env=production). The network requests should not error, and the images in the page's markdown should be source from thumbnails.zooniverse.org.
Note that I will follow up with a documented Issue and separate PR for …
=> Refactor Markdownz's handling of custom image dimensions

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
- fix `DataImageViewer` stories when the light curve data is in the `{ x, y }` format used by PH-TESS and the mock data.
- replace `Object.assign()` with spread operators in a few places.
- update `DataImageViewer` stories to use a mock store.
- limit the size of image toolbars in stories that use them.
- remove `addon-knobs`.
lib-classifier
- towards #2370.
- fixes an issue where the [`DataImageViewer` stories](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-dataimageviewer--light-theme&globals=locale:en;locales.en:English;locales.test:Test+Language) are showing `data is undefined`. 
- removing `addon-knobs` also fixes an issue …
=> Fix data image viewer stories

packages/app-content-pages/server/server.js, packages/app-project/server/server.js
Only load `https` and `selfsigned` in local development.
- app-project
- docker builds erroring with "Error: Cannot find module 'selfsigned'"
- in both app's `server.js` - moves `https` and `selfsigned` (selfsigned is a dev dependency) within if block that checks `APP_ENV` = "development" environment
_PR Creator - Please cater the checklist to fit the …
=> Require selfsigned in local development

packages/app-content-pages/test/create-global-document.js, packages/app-project/test/create-global-document.js, packages/lib-classifier/test/setup.js
Set [`nock.disableNetConnect()`](https://github.com/nock/nock#enabledisable-real-http-requests) for all tests. Any requests and responses that are required for tests must be mocked.
app-project
lib-classifier
- towards #4105.
Run the tests.
=> Disable real HTTP requests in tests

packages/lib-classifier/src/hooks/usePanoptesUser.js, packages/lib-classifier/test/mockStore/mockStore.js
Refactor the `usePanoptesUser` hook to subscribe to changes in the auth client session, which matches how PFE handles login and logout. Remove SWR for fetching user sessions from the Panoptes Auth API.
lib-classifier
- Closes #4119
Sign in and sign out on a project's classify page. Signing in should enable personalisation features in the classifier eg. personalised subject queues, QuickTalk, collections and favourites. Signing out should turn personalisation features off and start an anonymous classification session. …
=> Refactor classifier user authentication

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
- closes #4210 
- adds default value per `filterByLabel` helper of `['#', '!']` to `filters` prop of MetadataModal
- https://local.zooniverse.org:8080/?project=1862&workflow=3317
- click "Subject Info" button, note ID and Target at minimum shouldn't show, or any subject metadata field that starts with `#` or `!`
- no changes to, but http://localhost:6006/?path=/story/meta-tools-metadatamodal--default&args=filters:!null&globals=locale:en;locales.en:English;locales.test:Test+Language will continue to work
- Are there plans for follow up …
=> Add filters default value to MetadataModal

packages/lib-classifier/.babelrc, packages/lib-classifier/package.json, yarn.lock
We don't use class decorators any more, so the Babel plugin isn't being used.
lib-classifier
- #2712. …
=> Remove @babel/plugin-proposal-decorators

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
Follow-up to https://github.com/zooniverse/front-end-monorepo/pull/4238
Per [ADR 36](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-36.md), use root URL  https://fe-content-pages.zooniverse.org/about/ for app-content-pages production site to bypass the CDN while debugging intermittent page loading issues. …
=> Correct the app-content-pages production assetPrefix to bypass CDN

packages/lib-classifier/src/store/RootStore.js
Mute MobX State Tree liveliness warnings, to make the test logs less noisy.
lib-classifier
- towards #4136.
The test logs should ignore [livelieness warnings](https://mobx-state-tree.js.org/API/#livelinessmode), which might make them easier to read.
=> Classifier: mute liveliness warnings in tests

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
[`assetPrefix`](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix) shouldn't be used as a replacement for `basePath`. It should only be set when static assets are hosted on a different domain than the NextJS app.
=> Remove redundant asset prefixes

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.js
Remove the default Grommet menu icon from the hamburger menu button on small screens.
lib-react-components 
- closes #4207. 
Look at the Zooniverse Header in the storybook with the viewport set to a phone screen size. 
- Can be used from the keyboard [WebAIM guide to keyboard …
=> Remove drop-down icon from hamburger menu

packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
- Throw an error if subjects are missing the `priority` field in a prioritised workflow.
- Log subject queue errors to Sentry, so that we can debug them.
lib-classifier
- closes #4272.
Load a prioritised workflow with a subject that doesn't have the `priority` field set in its metadata. The classifier will fail, but the error should be logged in the console and recorded by Sentry. …
=> Log errors from prioritised subject queues

packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js, packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
Links to the privacy policy should be external links from the NextJS apps.
app-project
Open the registration form from each NextJS app and check that the link to the privacy policy goes to the correct URL now.
=> Fix privacy policy links

packages/lib-classifier/src/hooks/Readme.md, packages/lib-classifier/src/hooks/index.js, packages/lib-classifier/src/hooks/useCaesarReductions.js, packages/lib-classifier/src/hooks/useTranscriptionReductions.js
- extract `useCaesarReductions(reducerKey)` into its own hook.
- add error-handling to Caesar requests.
- add `useTranscriptionReductions` and `useCaesarReductions` to the hooks Readme.
lib-classifier
- Check that previous transcriptions load from Caesar for a transcription workflow.
- Check that previous transcriptions load in the Transcribed Lines story.
- Can be used with a screen …
=> Classifier: Refactor and document Caesar hooks

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
Refactor the `TranscribedLines` tests with React Testing Library, instead of Enzyme.
Fixes a couple of evergreen tests that are broken but still pass.
Tests for tooltips are broken by #1705 so I've skipped them for the time being.
https://github.com/zooniverse/front-end-monorepo/blob/25fe1627fdc24e981c912cf10f36b535546c2c8f/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js#L506-L511
Companion PR to #4237.
lib-classifier
Run the tests.
=> Refactor TranscribedLines tests with RTL

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/index.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/index.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/index.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/index.js, packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.spec.js, packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js, packages/lib-classifier/test/mockStore/mockStore.js
Add a layout with a restricted maximum subject width to the classifier. Keep the existing default layout for transcription workflows.
Grommet-ify the container and viewer grids, including using [`Grid`](https://v2.grommet.io/grid) for layout and adding a [responsive context](https://v2.grommet.io/responsivecontext) so that we can use themed breakpoints and sizing.
**Accessibility bug:** I've also fixed the 1160px breakpoint so that it works for base font sizes other than 16px. Here's I Fancy Cats with 'Larger Text' enabled in MacOS 11.7.2. The text is bigger but the subject and task still use a 9:5 column width ratio.
This should fix #3958 without changing the current behaviour of transcription projects. Here's I Fancy Cats zoomed out to an effective screen width of around 3600px. The …
=> Classifier: limit subject width in extra-wide viewports

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
- iteration on #4195 
- as detailed in the linked issue, volunteers should to be able to distinguish between 1, l, and I, which is crucial to transcription work
- the font "Anonymous Pro" differentiates well between the noted (and other) commonly confused characters/glyphs
- this PR adds "Anonymous Pro" font to the subject single text viewer
- #4310 also uses "Anonymous Pro"
- local lib-classifier - https://local.zooniverse.org:8080/?project=1952&workflow=3602
- local app-project  - https://local.zooniverse.org:3000/projects/markb-panoptes/digileap-testing-staging/classify/workflow/3602
- What user actions should my reviewer step through to review this …
=> Refactor text viewer font

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Zoom continuously in or out while the pointer is down on the zoom in and zoom out buttons in the image toolbar.
lib-classifier
- closes #4314.
- reverts changes from #4008 that broke the zoom buttons.
Use a pointing device to press the zoom buttons on any image subject. The subject should zoom continuously while the button is pressed.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voice …
=> Restore continuous zoom in and out

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.spec.js
- Add pointer events to the base `Button` component.
- Remove extra `span` elements from the zoom controls.
- Remove mouse events.
- Replace HOC's with hooks in the zoom buttons.
This reverts #4315 and fixes #4314 by adding pointer events to the image toolbar's base `Button` component.
Closes #4351.
lib-classifier
#4314 shouldn't regress here, so continuous zoom should still work while the pointer is down. This should also fix styling bugs that were caught by @goplayoutside3.
=> Image toolbar: use pointer events

packages/app-project/pages/_document.js
- Add Sentry to the page head, so that it's available before scripts load.
- Add `onload` and `onerror` handlers to each script tag in the downloaded page.
app-project
=> Quick and dirty script error logging

packages/app-content-pages/next.config.js, packages/app-content-pages/package.json, packages/app-content-pages/pages/publications.js, packages/app-content-pages/pages/team.js, packages/app-content-pages/src/helpers/logger/initializeSentry.js, packages/app-content-pages/src/helpers/logger/logNodeError.js, packages/app-content-pages/src/helpers/logger/logReactError.js, packages/app-project/next.config.js, packages/app-project/package.json, packages/app-project/pages/_document.js, packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js, packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js, packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.js, packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js, packages/app-project/src/helpers/fetchTeam/fetchTeam.js, packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js, packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js, packages/app-project/src/helpers/logger/initializeSentry.js, packages/app-project/src/helpers/logger/logToSentry.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js, packages/app-project/stores/Store.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js, yarn.lock
- install `@sentry/tracing` in both NextJS apps.
- enable performance tracing in Express and in the browser.
- turn off Sentry in local development mode (`NODE_ENV = 'development'`) so that Sentry isn't spammed with empty development releases.
app-project
There are a few options. Pick the one you're most comfortable with:
- [Build and start both NextJS apps locally in Node](https://github.com/zooniverse/front-end-monorepo/#with-node-and-yarn) to verify that they still build and run.
- [Build and start a Docker image](https://github.com/zooniverse/front-end-monorepo/#docker), then check both NextJS apps on localhost. This will verify that a production install (no dev dependencies) starts and runs in a container.
- [Build and deploy a Docker image of this …
=> Trace page performance with Sentry

.github/workflows/codeql-analysis.yml
CodeQL is warning that the `on.push` branch config should match the `on.pull_request` branch config.
Closes #4382.
=> Add pull request branch to CodeQL workflow config

packages/lib-react-components/.npmignore, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
- Ignore mock light curves and screenshots in `@zooniverse/react-components`. That removes ~500k of unused files from the published package.
- Update the changelog.
- Bump the version to 1.5.1.
`npm publish --dry-run` to check which files are included in the published package.
=> lib-react-components: update .npmignore

packages/app-content-pages/package.json, packages/app-project/package.json, yarn.lock
app-project
Reverts bugs caused by  #4433, #4434, #4437.
Issue that details the bugs: #4441 
Revert Sentry packages version to 7.46 in both app-project and app-content-pages.
🚫 ⚠️ Note that Sentry packages version 7.47 deprecates `Integrations` methods that were added as performance tracing for app-project in https://github.com/zooniverse/front-end-monorepo/pull/4394. 🚫 ⚠️  This must be taken care of before bumping Sentry packages.
See more details in Issue #4441 
Sign-in should work for any Zooniverse project whether on PFE, FEM, staging, or production. The FEM classifier should always load for a project that has workflow data. …
=> Revert Sentry packages to version 7.46.0

.github/workflows/deploy_storybook.yml
Build the libraries and run `yarn deploy-storybook` when the `production-release` tag changes. Allow deploys to be run manually too, via `workflow_dispatch`.
=> Deploy storybooks from production-release

.github/workflows/deploy_storybook.yml
The `deploy-storybook` script needs an extra `--ci` flag and `GH_TOKEN` environment variable when it's run by GitHub Actions. See https://github.com/storybook-eol/storybook-deployer/blob/master/README.md#deploying-storybook-to-github-pages-as-part-of-a-github-action
Follows on from #4463.
You should be able to deploy the storybook from this branch, under the Actions tab:
https://github.com/zooniverse/front-end-monorepo/actions/workflows/deploy_storybook.yml
Deploys fail on master, because of the missing `--ci` flag and GH token.
=> Add missing CI env to deploy_storybook workflow

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.stories.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/README.md, packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/index.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/index.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.js, packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.spec.js, packages/lib-classifier/src/translations/en/plugins.json
Changes to the Freehand Line tool as its used for annotating images with svg paths.
lib-classifier
In the staging environment I have a project called "kieftrav/freehand-line-test" that preloads a very basic drawing from Caesar and allows the user to change the path. Experiment with modifying the path and exploring any edge cases that could cause failure to draw an enclosed path.
Example Staging Project: [freehand-line-test](https://local.zooniverse.org:3000/projects/kieftrav/freehand-line-test) …
=> Add undo, redo, and tests to the freehand line tool.

.github/workflows/label_approved.yml
Use the [`pullreminders/label-when-approved`](https://github.com/marketplace/actions/label-approved-pull-requests) action, rather than the Zooniverse fork, which has stopped running.
_Please request review from `@zooniverse/frontend` team or an individual member of that team._
=> Label approved pull requests

packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.js
- closes #4498 
- add `onTouchEnd` handler to Highlighter task buttons for iOS text selection and highlighting
- ^ including `event.preventDefault()` to prevent `handleClick` from running twice on Android
- use BrowserStack to test on iOS device and Android device
- local - https://local.zooniverse.org:8080/?project=1952&workflow=3538
- branch deploy - TBD
1. highlight text
2. click a Highlighter task button
3. note the text becomes highlighted as per button clicked
4. with BrowserStack, I could only get Android/Chrome to work, but can see dev console, if add console log to …
=> Classifier: add onTouch handler for Highlighter task button

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotPoint.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotSeries.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/index.js, packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js, packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js, packages/lib-classifier/src/hooks/Readme.md, packages/lib-classifier/src/hooks/index.js, packages/lib-classifier/src/hooks/useKeyZoom.js
Refactor `ScatterPlot` in preparation for adding new features in #4482.
- Extract a `useKeyZoom` hook from `withKeyZoom`.
- Rewrite `ScatterPlot`, `withKeyZoom`, `ImageToolbar` and `Background` tests using RTL.
- Extract data series logic into `ScatterPlotSeries` and `ScatterPlotPoint`.
lib-classifier
The easiest way to test changes to the scatter plot viewer is to take a look at the storybook. Note that internal components from the `ScatterPlotViewer` package are imported into `DataImageViewer` and `VariableStarViewer`, so check those stories too. Nothing should have changed. …
=> Refactor ScatterPlot components

packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js, packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
Remove `forwardRef` from `withKeyZoom`, so that a component wrapped in `withKeyZoom` will now error if you pass a ref to it.
- See the discussion in #4503.
lib-classifier
Check the dev classifier with a variety of subject viewers (similar to #4538.) None of them should error, but if any are using refs then React should warn (or error) in the console, as refs can't be passed to functional components.
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i …
=> Remove refs from withKeyZoom

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
Survey task keyboard focus tests were skipped in order to pass with React Testing Library v9. This restores them, wrapped in `waitFor` so that each test waits for focus to change before running.
This PR reverts changes from #4395, where failing expectations were either commented out or skipped.
lib-classifier
Tests should pass on this branch, with the latest testing library.
=> Restore survey task focus tests

packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/OrganizationLink.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/OrganizationLink.spec.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/index.js, packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.js
- app-project
- towards #3579 
- adds organization link to project hero section …
=> app-project: Add OrganizationLink to Hero component

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerConnector.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/DeleteButton.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selection.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/index.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/index.js, packages/lib-classifier/src/translations/en/components.json, yarn.lock
Add x-range selection to the scatter plot viewer, using [`@visx/brush`](https://airbnb.io/visx/docs/brush). When annotation is selected in the image toolbar, the brush event layer overrides the zoom event layer, and clicking and dragging selects an x-range.
- add `Selections` and `Selection` components, which handle pointer interaction (when annotation is enabled) and data selection.
- add an `experimentalSelectionTool` flag, which is off by default.
- add an 'X Range Selection' story, which renders `ScatterPlotViewer` with `experimentalSelectionTool` set.
- add a 'Selected X Ranges' story, which renders `ScatterPlotViewer` with `experimentalSelectionTool` set and some data already selected, but selection itself disabled.
https://user-images.githubusercontent.com/59547/234002462-f1ca76a5-2 …
=> Scatter plot viewer: add x-range selection

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
Affects: ScatterPlotViewer (and theoretically any component that would use VisXZoom)
Follows: #4482's review
Fixes #4593 
At the moment, the "zoom layer" (the invisible rectangle that's supposed to cover a scatterplot chart, and listen for pan/zoom actions from the mouse) has an odd offset.
_Screenshot: (before fix, [SuperWASP Blackhole on lib-classifier](https://localhost:8080/?env=production&project=hughdickinson/superwasp-black-hole-hunters&workflow=17386)) : The visible "zoom layer", marked by a focus-outline on Chrome, is offset to the bottom-right. This means if a user's mouse is on the far left or top edge of the chart, they can't use the mouse to pan & zoom._
This fix removes that offset.
_Screenshot (after fix, [ScatterPlotViewer -> X Range Selection on …
=> Classifier: fix offset in VisXZoom's "zoom-layer"

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
Fix an invalid `width` attribute, on the Field Guide's SVG help icon, by replacing it with a CSS style.
lib-classifier
- closes #4604.
The image toolbar shouldn't warn about an unexpected `width` attribute now.
=> Fix Field Guide icon width

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js, packages/lib-classifier/src/plugins/tasks/survey/mock-data/task.js
- closes #2437 
- linked to https://github.com/zooniverse/Panoptes-Front-End/pull/6460
- conditionally show survey task instruction
- update stories, tests, and mock task accordingly
- survey task with instruction - https://local.zooniverse.org:8080/?project=1634&workflow=3729
- survey task without instruction - https://local.zooniverse.org:8080/?project=1634&workflow=2434
- note task instruction
- http://localhost:6006/?path=/story/tasks-survey--default&globals=locale:en;locales.en:English;locales.test:Test+Language
- Are there plans …
=> lib-classifier: Add survey task instruction

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js, packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.js, packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.js
- towards #3663 
- per Slack discussion
- change text viewer and highlighter task selection font color for proper contrast
- increase TextFromSubject task rows per feedback
- https://local.zooniverse.org:3000/projects/markb-panoptes/digileap-testing-staging
- go to Highlighter Task Testing workflow, make a few highlights in light and dark mode
- go to TextFromSubject Task Testing workflow, note increased rows of TextFromSubject task input
- [Text viewer with highlighter task selections](http://localhost:6006/?path=/story/subject-viewers-s …
=> lib-classifier: Refactor styling for text viewer, highlighter task selection, and TextFromSubject task

packages/lib-classifier/webpack.dev.js
- `HOST=local.zooniverse.org yarn dev` errors with "Can’t resolve ‘url’ in ‘/Users/markbouslog/zooniverse/front-end-monorepo/node_modules/normalizeurl/lib"
- as per additional information logged in noted Error message, adds `fallback: { "url": false }` to dev webpack
- run `HOST=local.zooniverse.org yarn dev` and https://local.zooniverse.org:8080/?project=335 loads
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before …
=> lib-classifier: Add fallback url false to dev webpack

packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
- increase the height to `73vh`.
- increase the width to `400px`.
- remove the first heading to allow for more text on the first slide.
- change the slide image from `cover` to `contain`.
- includes #4639. Check the deployed branch with the DOM inspector. 
lib-classifier
- towards #4558.
I think best to try out the popup and inline slide tutorial on a range of projects, to see how the size changes work with a variety of images and text.
Some random projects with a variety of tutorial content:
- Daily Minor Planet: https://local.zooniverse.org:3000/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354?env=production
- Beyond Borders: …
=> Increase popup tutorial size

packages/lib-classifier/.babelrc, packages/lib-classifier/package.json, yarn.lock
This plugin is included in `@babel/preset-env`. Logical assignment operators have been part of standard JavaScript since 2021.
lib-classifier
=> Remove @babel/plugin-proposal-logical-assignment-operators

packages/lib-classifier/src/store/Classification/Classification.js, packages/lib-classifier/src/store/Classification/Classification.spec.js, packages/lib-classifier/src/store/utils/ClassificationQueue.js, packages/lib-classifier/src/store/utils/ClassificationQueue.spec.js
- Rewrite the `ClassificationQueue` tests to mock the Panoptes API with 'nock'.
- Add tags to Sentry logs.
- Use `classification.id` to uniquely identify classifications.
- Fix a broken map in `classificationQueue.flushToBackend()`.
- Remove successful classifications from the queue, rather than deleting the whole queue then rebuilding it.
lib-classifier
- may close #4725.
- may close #3016.
The easiest way to check this in a browser is probably with the dev classifier. Verify (in the Network tab) that Done & Talk aborts your classification before it can be saved, but that the classification is kept in local storage, to be retried the next time that you load the classifier or press Done. …
=> Classifier: preserve pending classifications

packages/app-project/public/locales/en/components.json, packages/app-project/public/locales/es/components.json, packages/app-project/public/locales/test/components.json, packages/app-project/public/locales/tr/components.json, packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.stories.js, packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
app-project
Google Plus doesn't exist anymore, so this PR removes the link from ConnectWithProject. I also deleted the translation key from Lokalise.
- View the ConnectWithProject component's story: http://localhost:9001/?path=/story/project-app-shared-connectwithproject--default
- View TESS locally to see the Connect With Project section: https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production&demo=true
- Can be used with a screen reader [BBC …
=> app-project: Remove google+ link from Connect With Project

packages/lib-classifier/src/store/utils/ClassificationQueue.js
Set `saveFailed` as the default tag for classification errors, so that we can group and count Sentry errors, even when there was no API response eg. when a request terminated before completion.
lib-classifier
At the moment, we can't search for failed classifications in Sentry except when there was an API response, with an error status eg. [`classificationError: 503`](https://zooniverse-27.sentry.io/issues/?project=1492691&query=is%3Aunresolved+classificationError%3A503&referrer=issue-list&sort=date&statsPeriod=14d&stream_index=2).
This PR should tag errors with `classificationError: saveFailed` when there's no response from Panoptes eg. when a request is terminated before completion.
_PR …
=> Default Sentry tag for classification errors

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selection.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js
- Add a hook to inject any active `dataVisAnnotation` task into the `Selections` component.
- Render selection colours based on the active tool index, using the theme's highlighter colours.
- Refactor the storybook to show selections with a couple of different coloured tools.
lib-classifier
- towards #4302.
You can use the 'X Range Selection' and 'Selected X Range' stories to review this, in the classifier storybook. They have a data selection workflow set up, with two data selection tools.
'X Range Selection' has two steps, so you can try out the viewer with and without an active data selection task. When the selection task isn't active, selections should be visible but not editable. …
=> Add DataVisAnnotation task to scatter plot viewer

docs/arch/README.md, docs/arch/adr-48.md
An Architecture Decision Record for the latest updates to JSON data subjects. It follows on from [ADR 28](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-28.md), ie. the consequences from ADR 28 form the context for this ADR. 
_Please request review from `@zooniverse/frontend` team or an individual member of that team._
=> JSONData ADR

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js, packages/lib-classifier/src/store/ClassificationStore.js
Wait until `classificationQueue.add(classification)` has resolved before updating the classification store state and advancing the subject queue. This should prevent the window from navigating away from the classifier until the new classification is either saved in local storage or posted to Panoptes.
Disable both Done and Done & Talk after one click, to avoid duplicate classification submissions.
lib-classifier
- https://github.com/zooniverse/front-end-monorepo/issues/3016#issuecomment-1098849554
- Closes #4772.
This should prevent a race condition where the page can unload before a classification has saved, when you press Done & Talk. I've been able to reproduce the original issue reliably by …
=> Defer Done & Talk until classification has saved

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js, packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
lib-classifier
Follow-up to https://github.com/zooniverse/front-end-monorepo/pull/4767
The Done and Done&Talk buttons should be disabled while a classification is being posted to panoptes. This PR moves the local `saving` state into TaskNavButtons so that both buttons can listen to it and be disabled at the same time.
Test a classification on any test project. I used this transcription project: https://local.zooniverse.org:3000/projects/blicksam/transcription-task-testing/classify/workflow/13898?env=production
Check that the Done and Done&Talk buttons appear in storybook: http://localhost:6006/?path=/story/tasks-simple-dropdown--default …
=> Classifier: Disable both Done&Talk and Done buttons while classification is saving

packages/app-project/src/helpers/fetchOrganization/fetchOrganization.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js, packages/app-project/stores/Organization.js, packages/app-project/stores/Project.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
- add `organization` to the store during SSR, and pass a snapshot to the browser.
- return null when organisations aren't found eg. they exist but are not public.
- model translation strings as a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) of nullable strings.
app-project
Try this out with projects that are part of public organisations, eg. Snapshot Serengeti or Notes from Nature, and projects that are part of private organisations, eg. Galaxy Zoo or Gravity Spy. …
=> Organisations: small fixes

packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
Fixes #4806 
Affects: Workflow Selector.
This PR fixes an issue where - if you have project that has both locked & unlocked workflows _and_ the browser height is too short - the Workflow Selector component starts "squeezing" its content, causing it to visually overlap one another.
This is usually only visible on the project's `/classify` path (with no Workflow selected), for projects with a sufficient amount of locked & unlocked workflows.
The problem:
With fix applied:
The solution is to set flex="grow" to the Workflow Selector's container (see [4806's analysis;](https://github.com/zooniverse/front-end-monorepo/issues/4806#issuecomment-1593339650) the container is the div with the pink border) to prevent it from shrinking below the height necessary to contain its …
=> WorkflowSelector: prevent container from squeezing/overlapping content

packages/app-content-pages/.eslintrc, packages/app-content-pages/package.json, packages/app-content-pages/pages/_app.js, packages/app-content-pages/src/api/publications/buildResponse.js, packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js, packages/app-project/.eslintignore, packages/app-project/.eslintrc, packages/app-project/package.json, packages/app-project/pages/_document.js, packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js, packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.js, packages/app-project/src/hooks/useAdminMode.js, packages/app-project/src/hooks/useSugarProject.js, packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js, packages/lib-classifier/.eslintrc, packages/lib-classifier/eslint.config.js, packages/lib-classifier/package.json, packages/lib-react-components/package.json, packages/tools-standard/options.js, packages/tools-standard/package.json, yarn.lock
- Add the [ESLint React plugin](https://www.npmjs.com/package/eslint-plugin-react) to `@zooniverse/standard`. 
- Enable the recommended React rules and JSX a11y rules when running `zoo-standard`.
- Upgrade the classifier to the new `eslint.config.js`, with the recommended React rules and JSX accessibility rules.
- Add the JSX accessibility rules to both NextJS apps.
- app-project
- tools-standard
You can lint the classifier with `zoo-standard` by running `yarn lint`. It will probably generate a lot of errors and warnings, as it hasn't been linted for a while. I've also added a `yarn eslint` script, which runs ESLint with the React and JSX accessibility …
=> ESLint: Add eslint-plugin-react

packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
app-content
Closes: #4860 
Added `currentWorkflowID` and `promptAssignment` to useEffect. Removed `router` as a dependency because that was the initial solution to telling the modal the workflow id had changed.
In app-project storybook, the Workflow Assignment Modal [story](http://localhost:9001/?path=/story/project-app-screens-classify-workflow-assignment-assignment-modal--default) should show the modal. If you check the checkbox and close the modal, workflowAssignmentModalDismissed will appear in your session storage. There should be a message in storybook that tells you that too. Open storybook in a fresh browser tab and the modal will reappear.
To test on a live project, login to zootester1 account and visit [Gravity Spy](https://localhost.zooniverse.org:3000/projects/zooniverse/gravit …
=> Classifier: Fix build warning about workflow assignment modal

packages/lib-classifier/src/store/RootStore.js
Wait for sign-in to complete before refreshing the subject queue, when the auth'ed user changes.
lib-classifier
- closes #4847.
Load the Classify page while signed out, then sign in. The first request for queued subjects should be made with your Authorization header.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-tec …
=> Wait before refreshing the subject queue

packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/4804
Move the check for `workfowAssignmentModalDismissed` (session storage) to inside WorkflowAssignmentModal's functional component. Previously, defining the constant outside of the component was resulting in it being sudo cached as `false` and not accurately checked again when needed.
To test on a live project, login to zootester1 account and visit [Gravity Spy](https://localhost.zooniverse.org:3000/projects/zooniverse/gravity-spy/classify/workflow/1610?env=production) locally. The modal should appear when viewing Level 1 workflow. Check the checkbox, dismiss the modal, and navigate to the project's home page. Go back to Level 1 workflow and the modal should stay hidden.
_PR Creator - Please cater the checklist …
=> Workflow Assignment Modal: check for session storage item on every render

packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js, packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js, packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js, packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
`seenThisSession` is now handled by the classifier when you sign out.
See #4838. 
- app-content-pages 
- app-project
- #4838. 
See the review for #4838. Seen subjects should be reset when the signed-in user changes. 
- Can be …
=> Remove seenThisSession from ZooHeaderWrapper

packages/lib-classifier/src/store/Classification/ClassificationMetadata.js, packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js
Add an `_onLocaleChange` listener to `ClassificationMetadata`, which sets `metadata.userLanguage` from the root store locale.
lib-classifier
- closes #4521.
If you change language during a classification, the classification metadata should update to match the current language.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/ass …
=> Set classification userLanguage from locale

packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.spec.js
app-project
There have been repeated time-outs during the Run Tests action for FEM PRs.
This PR separates the "getBy" queries into each unit test rather than in one big `before` hook, and changes one of the `getByRole` queries into `getByText` to try and prevent action timeout.
This edits just one spec file, so check that the PR Github Actions pass and do not timeout.
=> app-project: minor refactor of Hero tests

packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js, packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js
- the `search` parameter should not be included in the API call when the text box is empty.
- the `SelectCollections` component should observe the project store for changes.
- Use Postgres full text search for long search strings. Otherwise, filter collection display names by short search strings. 
https://github.com/zooniverse/front-end-monorepo/assets/59547/34022d1d-b3bb-4dd4-9f1a-fc492e50b6b0
app-project
- closes #4865.
While logged in, search your collections from the 'Add to collection' button underneath any subject on the Classify page (including subject previews.) You should be able to search both collections that you own, and collections that have been shared with you.
Clearing the text …
=> Project: fix collections search

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js, packages/lib-classifier/src/hooks/useTranscriptionReductions.js, packages/lib-classifier/src/store/subjects/Subject/TranscriptionReductions/TranscriptionReductions.js
- Add `subject.caesarReductions.userIDs`, a list of unique users who have contributed transcriptions to a subject.
- Update `useTranscriptionReductions` to check the logged-in user against the list of previous users from Caesar.
- Mark subjects as seen if you've previously transcribed them.
- Log an error to Sentry for duplicate subjects.
- Refactor `TranscriptionReductions` for readability.
lib-classifier
Caesar reductions for the transcription task include a list of user IDs for each transcribed line. This PR reduces those arrays down to an array of unique user IDs for each previously transcribed subject, then checks the logged-in user against that array. If you've already transcribed this …
=> Transcription task: catch duplicate subjects

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
Restore `activeTool.disabled` to the drawing canvas. It checks whether a tool has reached its maximum allowed marks. I think it was removed in #2415.
lib-classifier
- closes #4905.
Try adding marks with a drawing tool, until you reach the maximum configured in the project builder for that tool.
- Can be used from the …
=> Restore drawing tool disabled state

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js, packages/lib-react-components/src/Media/Media.js, packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js, packages/lib-react-components/src/Media/helpers/getThumbnailSrc.js
`Media` components must specify either a width or a height. This sets the width of the `ProjectImage` and survey task 'confused with' images to 400px. Embedded images in markdown text use a default width of 999px, as before.
- app-project
- Closes #4862
Image thumbnails should have valid URLs, which don't error.
- Can be used with a screen reader …
=> Specify dimensions for Media images

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
Rate limit the flipbook resize observer, adding a delay of 100ms between calls to the callback function.
lib-classifier
This should fix resize observer errors that throw when you load a flipbook viewer in the dev classifier. …
=> Debounce flipbook resize observer

packages/app-content-pages/package.json, packages/app-project/next.config.js, packages/app-project/package.json, yarn.lock
Reverts zooniverse/front-end-monorepo#4907
=> Revert "build(deps): bump @sentry/nextjs from 7.56.0 to 7.57.0"

packages/app-content-pages/package.json, packages/app-content-pages/src/shared/stores/User/User.js, packages/app-project/package.json, packages/app-project/src/hooks/usePanoptesUser.js, packages/app-project/stores/User/User.js, packages/app-project/stores/User/User.spec.js, packages/app-project/stores/User/UserPersonalization/UserPersonalization.js, packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/Classifier.js, packages/lib-classifier/src/components/Classifier/Classifier.spec.js, packages/lib-classifier/src/components/Classifier/Classifier.workflows.spec.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js, packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js, packages/lib-classifier/src/hooks/Readme.md, packages/lib-classifier/src/hooks/useHydratedStore.js, packages/lib-classifier/src/hooks/useHydratedStore.spec.js, packages/lib-classifier/src/hooks/usePanoptesAuth.js, packages/lib-classifier/src/hooks/usePanoptesUser.js, packages/lib-classifier/src/hooks/useProjectPreferences.js, packages/lib-classifier/src/hooks/useProjectRoles.js, packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js, packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js, packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json, packages/lib-panoptes-js/src/auth.js
Refactor `usePanoptesUser` to get the current user from the stored Panoptes JWT (#4766.) Fall back to `auth.checkCurrent()`, which gets a new session and token from the Panoptes API, if we don't have a stored token.
Refactor the classifier to authenticate in `ClassifierContainer`, waiting until sign-in is complete and all user data has loaded before rendering the `Classifier` component (#4845 and #4875.) Move all the workflow validation up to `ClassifierContainer`, so that we validate the workflow ID (from the URL) when the user has loaded, then pass down null to `Classifier` if they don't have permission to view that workflow.
Test `ClassifierContainer`, checking that:
- inactive workflows only load when you have permission to view them.
- the mock API for `/subjects/queued` is only …
=> Refactor Panoptes authentication in all packages 

packages/lib-classifier/src/components/Classifier/ClassifierContainer.js, packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js, packages/lib-classifier/src/hooks/useProjectPreferences.js, packages/lib-classifier/src/hooks/useProjectRoles.js
Set the current `userID` to undefined while the user is loading. Check that in both `useProjectPreferences` and `useProjectRoles` so that the possible return values are:
- undefined (resource is loading.)
- null (user isn't logged in.)
- a Panoptes resource (user is logged in.)
Wait until workflow translations have loaded before rendering the classifier (closes #5015.)
lib-classifier
I checked this in the dev classifier. With these changes, you shouldn't see any requests made for either project preferences or project roles until the user is authenticated, and set to either null or a Panoptes user resource.
You shouldn't see GET requests like this, where the user ID is `false` because the user …
=> Stronger checking for classifier data fetching 

packages/lib-classifier/dev/components/App/App.js
The dev classifier stubbed callback functions are constants, but the `App` component generates new `onAddToCollection` and `onCompleteClassification` callback functions on each render. This declares them once, so that they are only set once.
lib-classifier
This is a small change, but you shouldn't see console logs warning that the dev classifier's callbacks have been reset on every render eg. when toggling the theme from dark to light.
=> Use constant callbacks in the dev classifier

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Separate frames mode uses its own callback functions for zoom, so they need to be called continuously while the zoom buttons are pressed.
I've also updated the tests to expect each zoom callback to run once on button click (see #5043.)
lib-classifier
- closes #5049.
You can test this on Daily Minor Planet in the standalone classifier:
https://localhost:8080/?project=fulsdavid/the-daily-minor-planet&env=production
Pressing the +/- buttons next to each frame, with either a pointing device or the keyboard, should continuously zoom while each button is pressed.
_PR Reviewer - Use the checklist during your …
=> Continuous zooming in separate frames mode

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
lib-classifier
Follow-up to #5050 
Separate frames mode uses its own callback functions for invert, rotate, and reset so the existence of those custom callbacks can be used instead of looking for `separateFramesMode` in the store. This PR doesn't have any affect on functionality, it just matches the same callback pattern as PR #5050's refactoring of the zoom buttons.
Note that the Move and Annotate buttons cannot use this pattern because they also involve a move or annotate "mode" from the store.
Review the SeparateFramesViewer in the lib-classifier storybook.
Use Daily Minor Planet, or this test flipbook project to check that all image toolbar buttons function as expected in both the FlipbookViewer mode and SeparateFrame mode.
https://local.zooniverse.org:3000/projects/goplayoutside3/fem- …
=> Image Toolbar: change button callbacks to match zoom callback pattern

packages/app-project/stores/User/UserPersonalization/UserPersonalization.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js, packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.js
- store `user.personalization.sessionCount` in user snapshots, so that it can persist across page visits (closes #5081.)
- only run the graphQL query for daily stats when we're fetching a new user from Panoptes. Existing users (including users stored in browser session storage) will already have their stats stored in the personalisation models.
- increment daily counts separately from session counts, since open tabs can persist across calendar days.
- increment project activity count separately from session counts, to avoid double counting of classifications.
- add `user.personalization.todaysStats` and `user.personalization.todaysCount` for convenience.
- add `stats.increment()` as a convenience method to increment daily counts.
_Please request review from `@zooniverse/frontend` team or …
=> Refactor daily classification counts

packages/app-content-pages/pages/_app.js, packages/app-project/pages/_app.js, packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
Fixes for tests to improve compatibility with React 18 and React Testing Library v14 (#3887.)
This PR also turns off `observer` during SSR (`enableStaticRendering(true)`). `observer` should only be run in the browser, and warns in the builds if you try to use it in Node. This is a warning with React 17, but will stop the NextJS apps from building with React 18.
app-project
lib-classifier
- #3887.
- #3888.
Build and run the NextJS apps to test static rendering. Their behaviour shouldn't have changed.
Tests should all continue to pass. Builds should run without `useLayoutEffect` warnings. …
=> Fixes for tests and SSR errors

docs/ADR_TEMPLATE.md
This is a follow up to the FEM Documentation discussion at ZTM.
I added a basic ADR template for our reference. It's based on the examples here: https://github.com/joelparkerhenderson/architecture-decision-record#adr-example-templates
=> Add ADR template

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
`@zooniverse/react-components` version 1.5.5
- add `sideEffects: false` to `package.json`, so that [bundlers prune unused exports](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free).
Build and run the NextJS apps. You should see that the output from `next build` reports somewhat smaller sizes for the first load JS. Webpack bundler analyzer (#5155) should report smaller bundled sizes for `@zooniverse/react-components`.
You can also look in the CI build logs to check the build sizes for each app.
- [content pages](https://github.com/zooniverse/front-end-monorepo/actions/runs/5872109608/job/15923026217?pr=5186#step:7:54).
- [project …
=> Mark ZRC as free of side effects

packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json, packages/lib-panoptes-js/src/resources/projects/commonRequests.js, packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
Catch any project slugs that begin with `/projects/` or `projects/`, rather than matching on `projects` anywhere in the slug. Add a test for the buggy behaviour and publish as v0.4.1.
Load a project that includes `projects` in either the username or the project name. …
=> Panoptes client: match project slugs more strictly

packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.mock.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js, packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js, packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js, packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js, packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.js, packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.spec.js, packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.stories.js
app-project
Converted tests for the SubjectPreview from Enzyme to RTL. Includes changes for CollectionsButton and TalkLink.
[SubjectPreview Story](http://localhost:9001/?path=/story/project-app-shared-subject-preview--plain)
[CollectionsButton Story](http://localhost:9001/?path=/story/project-app-shared-collections-button--collections-button)
[TalkLink Story](http://localhost:9001/?path=/story/project-app-shared-talk-link--talk-link)
=> SubjectPreview: Remove enzyme and convert tests to RTL

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
- Remove `Object.assign()`.
- Use local component state to pass the SVG viewbox down to child components.
- debounce the drag handler for smoother dragging (#5110.)
- Remove Enzyme tests.
lib-classifier
Image zooming should continue to work as before on a project like I Fancy Cats.
- Can be used from the keyboard …
=> Refactor SVGPanZoom

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-project/pages/_document.js, yarn.lock
Reverts zooniverse/front-end-monorepo#5239
The storybook isn’t building with `@sentry/nextjs` 7.65.
=> Revert "build(deps): bump @sentry/nextjs from 7.64.0 to 7.65.0"

packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/CollectionsStoreMock.js, packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.mock.js, packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.spec.js, packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
app-project
Converted tests for the RecentSubjects from Enzyme to RTL. 
[RecentSubjects Story](http://localhost:9001/?path=/story/project-app-screens-project-home-recent-subjects--plain)
=> RecentSubjects: Remove enzyme and convert tests to RTL.

packages/app-project/src/shared/components/withRequireUser/withRequireUser.mock.js, packages/app-project/src/shared/components/withRequireUser/withRequireUser.spec.js, packages/app-project/src/shared/components/withRequireUser/withRequireUser.stories.js
app-project
Converted tests for the withRequireUser from Enzyme to RTL. 
[withRequireUser Story](http://localhost:9001/?path=/story/project-app-shared-withrequireuser--default)
=> withRequireUser: Remove enzyme and convert tests to RTL

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Empty the `LightCurveViewer` SVG on unmount. Otherwise, `viewer.initChart()` does weird things if it runs with an existing viewer DOM already set up.
lib-classifier
- Fixes #5266.
Run `yarn dev` to run the classifier in strict mode, then load PH-TESS at this URL:
https://local.zooniverse.org:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true
- Can be used with a …
=> Clear LightCurveViewer on unmount

packages/app-project/pages/404.js, packages/app-project/src/hooks/useSugarProject.js
Headings can't be nested inside paragraphs, so this fixes the 404 page by moving the heading and 404 image into the `PageContent` div.
`useEffect` must return a function or undefined, so this also fixes the broken `useSugarProject` hook, which crashes the 404 page in development.
- Fixes #5277.
- Fixes #5276.
app-project
Build the project app, then start it and browse to a project URL that doesn't exist.
eg. https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats123
The 404 page should also render in development mode, `yarn dev`, without crashing. …
=> 404 page: fix invalid HTML

packages/app-content-pages/.storybook/lib/i18n.js, packages/app-content-pages/.storybook/specConfig.js, packages/app-content-pages/package.json, packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js, packages/app-content-pages/src/screens/Teams/TeamsContainer.spec.js, packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js, packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js, packages/app-project/.storybook/lib/i18n.js, packages/app-project/.storybook/specConfig.js, packages/app-project/package.json, packages/app-project/src/components/ProjectName/ProjectName.mock.js, packages/app-project/src/components/ProjectName/ProjectName.spec.js, packages/app-project/src/components/ProjectName/ProjectName.stories.js, packages/lib-classifier/.storybook/specConfig.js, packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js, packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js, packages/lib-react-components/.storybook/specConfig.js, packages/lib-react-components/package.json
app-project, lib-classifier, and lib-react-components
Incorporates the alternative config implementation from [PR#5310](https://github.com/zooniverse/front-end-monorepo/pull/5310) based on https://storybook.js.org/docs/react/writing-tests/stories-in-unit-tests#configure. 
- Create a specConfig.js file in `lib-classifier`, `app-project`, and `lib-react-components` that sets the global config for Storybook's projectAnnotations (needed for Grommet in stories that are included in spec files).
- Remove manually added projectAnnotations from spec files
- Add specConfig.js file to test command in package.json
- Fix import of i18n files from `require()` to an `async import`
Pull code and run tests locally.
=> Create wrapper function for running Stories in Specs

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
lib-classifier
This is a follow-up to https://github.com/zooniverse/front-end-monorepo/pull/5165. 
Note that this PR does _not_ solve https://github.com/zooniverse/front-end-monorepo/issues/5110. However, my latest comment in https://github.com/zooniverse/front-end-monorepo/issues/5110 shows a video of the degraded drag/pan feature for subject viewers specifically using a cursor in desktop browsers. This PR intends to revert that degraded UX, but a bit of lag will remain (as initially described when that Issue was first opened).
1. I found that lodash's `debounce` was the cause of unresponsive dragging in the image subject viewers, and the responsiveness increased when I removed it from `setOnDrag`. I think debouncing was causing a build up of `onDrag` calls, and when the 10ms delay was …
=> Restore image viewer drag performance

packages/app-project/pages/_app.js, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/src/ZooHeader/ZooHeader.js, packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js, packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js, packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
- **lib-react-components:** wrap both `SignedInUserNavigation` and `SignedOutUserNavigation` in a labelled `nav` element, to avoid this hydration error in the header: `Expected server HTML to contain a matching <nav> in <div>.` (#5273)
- bump `@zooniverse/react-components` to 1.5.6.
- update the changelog.
- **app-project:** add `disableDynamicMediaQueries` (see https://github.com/artsy/fresnel/blob/main/README.md#%EF%B8%8F-react-18-notice.)
- app-project
- towards #5273.
Run the project app with `yarn dev`. Some page components will still throw mismatch errors, but they should be fixed in `ZooHeader`. Sign in and out should continue to work as before. 
Accessibility fix: …
=> ZRC: Refactor ZooHeader to avoid hydration errors

packages/lib-react-components/src/ZooHeader/ZooHeader.js, packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js, packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
PR #5278 accidentally removed the padding from the signed-out user navigation menu in `ZooHeader`. This restores it.
This also fixes an invalid button label on the user account dropdown menu.
Compare the signed-out user navigation menu with the live web site.
=> Fix missing padding in the logged-out user menu

packages/lib-react-components/package.json
Since #5325 replaced `main` with `exports`, `@zooniverse/react-components` is empty when published. This fixes that by restoring the main entry point.
- Fixes #5338.
`npm publish --dry-run` or `npx npm-packlist` to preview the files that will be included in the published package.
=> ZRC: restore the package main entry point

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-react-components/src/Markdownz/Markdownz.js, packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js, packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js, yarn.lock
- Display `Media` images with `inline-flex`, rather than `flex`, columns.
- Replace the container element with `span`, rather than `div`, so that media images can be displayed inside paragraphs.
- `Markdownz`: Convert line breaks to `<br>` with [`remark-breaks@2.02`](https://www.npmjs.com/package/remark-breaks/v/2.0.2).
- Bump `@zooniverse/react-components` to 1.6.2.
- Closes #2462.
Images on the Galaxy Zoo Research page now display inline, as expected.
However, there could be project teams that have relied on the incorrect, block display for images in their field guides etc., so that needs checking.
Here's the Galaxy Zoo field guide on this branch. Images are displayed …
=> Display Media images inline

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
- add a drop shadow to all previously transcribed lines.
- darken the grey, completed lines to `light-4`.
- towards #5291.
You can use the Transcribed Lines story, in the Classifier storybook, to view the new styles.
You can also see them on Davy Notebooks:
https://localhost:8080/?project=humphrydavy/davy-notebooks-project&env=production&workflow=24822
- Can be used …
=> Add drop shadow to transcribed lines

packages/app-project/pages/404.js, packages/app-project/public/locales/en/components.json, packages/app-project/src/helpers/404theme.js
Toward: https://github.com/zooniverse/front-end-monorepo/issues/4257
- Update default 404 page to incorporate changes
- Create custom 404 component to handle "project not found" errors
- Incorporates rotating background images and translations
- General 404: https://local.zooniverse.org:3000/projects/test404
- Missing Classification Workflow: https://local.zooniverse.org:3000/projects/kieftrav/freehand-line-test/classify/workflow/403
- Existing Classification Workflow: https://local.zooniverse.org:3000/projects/kieftrav/freehand-line-test/classify/workflow/3691?env=staging
** Still working on test and various edge cases / permutations …
=> Implement Custom 404 page for project pages

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/helpers/constants.js
- [Reset the `SVGPanZoom` component state](https://react.dev/reference/react/useState#resetting-state-with-a-key) when its image size changes, so that the default viewbox always matches the current image height and width.
- allow `SVGImage` to be passed a ref. Use that ref to report subject image dimensions in classifications. 
- fix `TranscriptionLine` scaling.
- fixes #5384.
- closes #5291.
This bug was first reported on Davy Notebooks and Beyond Borders, because it's most obvious when previous transcription lines are shown on top of an image. However, it affects all the image subject viewers.
When a subject loads:
- the correct client dimensions should be recorded in the …
=> Fix SVG subject scaling

packages/app-content-pages/package.json
Replace the custom Express server with `next start`.
The app should start without problems on kubernetes?
=> Content pages: run with next start

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/PrimaryButton/helpers/getGradientShade.js, packages/lib-react-components/src/translations/i18n.js, packages/lib-react-components/test/setup.js
- Replace `require` with `import` in a couple of places.
- Remove the `React` global from the tests.
```sh
yarn panic
yarn bootstrap
cd packages/app-project
yarn start
cd ../app-content-pages
yarn start
```
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html …
=> @zooniverse/react-components: remove require

packages/app-project/src/components/Head/Head.js, packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/hooks/useSubjectImage.js
- Style `SingleImageViewer` with a placeholder background image.
- Set default placeholder dimensions for each styled image viewer.
- Remove the placeholder image from `useSubjectImage`.
- Preload the placeholder image when a project first loads in the browser.
- app-project
Inspired by this idea from Harry Roberts: https://csswizardry.com/2023/09/the-ultimate-lqip-lcp-technique/
Try out a few different subject image viewers. They shouldn't have changed, except that the subject image now starts to download immediately, rather than waiting for the placeholder image to load.
_PR Reviewer - …
=> Replace subject placeholder with background image

packages/lib-react-components/src/FavouritesButton/FavouritesButton.mock.js, packages/lib-react-components/src/FavouritesButton/FavouritesButton.spec.js, packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
Converted tests for the FavouritesButton from Enzyme to RTL. 
[FavouritesButton Story](http://localhost:9001/?path=/story/components-favourites-button--disabled)
=> FavouritesButton: Remove enzyme and convert to RTL

packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js, packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.mock.js, packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.spec.js, packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
Converted tests for the MetaToolsButton from Enzyme to RTL. 
[MetaToolsButton Story](http://localhost:9001/?path=/story/components-metatoolsbutton--button)
=> MetaToolsButton: Remove enzyme and convert to RTL

packages/app-project/src/shared/components/NavLink/NavLink.mock.js, packages/app-project/src/shared/components/NavLink/NavLink.spec.js, packages/app-project/src/shared/components/NavLink/NavLink.stories.js
app-project
Converted tests for the NavLink from Enzyme to RTL. 
[NavLink Story](http://localhost:9001/?path=/story/project-app-shared-navlink--on-current-page)
=> NavLink: Remove enzyme and convert tests to RTL

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
A patch release to export the `package.json` file for build tools. Fixes warnings like 'unable to find package.json for @zooniverse/react-components' in the storybook.
Fixes a bug where the storybooks warn that they can't find `package.json` for `@zooniverse/react-components` when you build them.
With the changes here, tools should be able to `import '@zooniverse/react-components/package.json'` without errors. …
=> @zooniverse/react-components v1.6.4

package.json, packages/app-content-pages/next.config.js, packages/app-project/src/components/Head/Head.js, yarn.lock
- fix `eslint-config-next` errors when `app-project` builds.
- move `modularizeImports` up to the top level in the `app-content-pages` config.
- fix a build error in the project `Head` that stops the app from building. 
- closes #5409.
- app-project
With a clean install of the monorepo, both Next.js apps should build and start without the build errors from #5409. …
=> Fix Next.js build warnings and errors

packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js, packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.spec.js, packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js, packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.spec.js, packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js, packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.spec.js, packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.stories.js, packages/lib-classifier/src/plugins/tasks/multiple/components/mockTask.js, packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js, packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.spec.js, packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.stories.js, packages/lib-classifier/src/plugins/tasks/single/components/mockTask.js
- refactor `MultipleChoiceTask` and `SingleChoiceTask` to use `fieldset` and `span`, so that they produce valid HTML.
- refactor `TaskInputLabel` to use `span` inside `label`, rather than `p`.
- Add new task stories to show `MultipleChoiceTask` and `SingleChoiceTask` with an existing annotation.
- convert the `MultipleChoiceTask` and `SingleChoiceTask` tests from Enzyme to React Testing Library.
- convert `TaskInput` and `TaskInputLabel` tests to RTL.
- add experimental support for `autoFocus` on question fieldsets. Autofocus the fieldset itself when there is no selected answer.
TODO: 
In the process of fixing focus for question tasks (#5417), I've updated the question tasks to use valid fieldsets, labels, legends, and RTL tests.
_Please request review from `@zooniverse/frontend` team or …
=> Fix keyboard autofocus for question tasks

packages/app-content-pages/src/screens/Publications/Publications.js, packages/app-content-pages/src/screens/Teams/Teams.js, packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
Replace `next/link` links with `as={Link}` on styled Grommet anchors and button links.
- closes #5467.
Navigation links and sidebar links should continue to work, without being wrapped in an extra `<a>` element. `next/link` no longer [requires a link as a child](https://nextjs.org/docs/pages/api-reference/components/link#legacybehavior).
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/test …
=> Remove legacy next/link components

yarn.lock
This reverts commit 550176f616668c1d17e9c5b44e3dc9e64b4e367d.
The FEM staging [deploy](https://zooniverse.slack.com/archives/C01M8PJGLR5/p1697668103030929) is failing this afternoon with the message `ERROR: failed to solve: process "/bin/sh -c YARN_CACHE_FOLDER=/home/node/.yarn yarn install --production=false --frozen-lockfile" did not complete successfully: exit code: 127`
=> Revert: build(deps-dev): bump sinon from 16.1.0 to 16.1.1 (#5490)

.github/workflows/ci-build.yml, .github/workflows/coverage.yml, Dockerfile
Don't run post-install scripts during Docker builds. This is a vector for supply chain attacks, and there have been a few cases where they have been exploited to distribute malware via NPM.
A Docker build should still run without errors, even though post-install scripts don't run during the build stage. 
Unfortunately, we don't run a Docker build during CI, so that won't be tested by our test builds. 
CI tests and CI builds in Node should still run successfully without post-install scripts. 
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR …
=> [Security] Ignore post-install scripts

packages/app-content-pages/next.config.js, packages/app-project/next.config.js
- restore `newrelic` to the content pages app. It was accidentally removed in #5427.
- fix a missing default for `GITHUB_REF_NAME` in the project app.
- app-project
`GITHUB_REF_NAME` should now be set when you build the project app locally (and shouldn't trigger build warnings about a missing string.)
The content pages app should start sending telemetry data to newrelic again, once this is deployed to staging. The content pages config should now match the project app config.
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR …
=> Restore newrelic monitoring for app-content-pages

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.stories.js
- Test subject metadata with and without filtered labels.
- Test mock subject metadata with a mixture of numbers and strings.
- Render URLs in subject metadata as HTML links with `target=_blank` and `rel="nofollow noopener noreferrer"`.
- #5352.
Open up the subject metadata modal in I Fancy Cats. The Flickr link should open in a new tab. `window.opener` should be empty in the new tab.
In the storybook, the link in the `MetadataModal` story should continue to open in a new tab (again, without `window.opener` set.)
_PR Reviewer - Use the checklist during your review. Each point should be …
=> Refactor URLs in subject metadata

packages/app-project/pages/_document.js
Bump the inline Sentry script, on project pages, to the latest version. It catches errors when page scripts fail to load.
- app-project
I think this should be ok to merge once CI passes.
=> Bump inline Sentry to 7.75.1

packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js, packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Return '404 Not Found' for project About pages, when the project doesn't exist.
- Fixes #5533.
- app-project
Build the project app, then run it with `yarn start` or `npm start` and check the following URLs:
- https://local.zooniverse.org:3000/projects/zoniverse/gravity-spy/about/research should show a 404 page.
- https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy/about/research should show the Gravity Spy Research page. …
=> Fix Not Found responses for project About pages

packages/app-content-pages/server/server.js, packages/app-project/server/server.js, packages/app-project/webpack.config.test.js
Remove outdated references to `@sentry/node` and `@sentry/browser`. Since #4764, we use `@sentry/nextjs`.
- app-project
- #4764.
The Next.js apps should still build and run without problems.
- Can be used …
=> Clean up Sentry config

.github/workflows/ci-build.yml, .github/workflows/coverage.yml, .github/workflows/deploy_storybook.yml, Dockerfile, README.md, packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-root/package.json, packages/lib-async-states/package.json, packages/lib-classifier/package.json, packages/lib-grommet-theme/CHANGELOG.md, packages/lib-grommet-theme/package.json, packages/lib-panoptes-js/docs/CHANGELOG.md, packages/lib-panoptes-js/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json, packages/lib-user/package.json
Upgrade all the build scripts, and the Dockerfile, from Node 18 to Node 20. 20 is now the Active LTS release of Node.
Bump the libraries with new minor versions.
All of them (I think.)
Install and build the monorepo with Node 20. You should be able to run the Next.js apps without any changes in their behaviour.
Docker builds should build and run the Next.js apps on Node 20 on Alpine Linux. There shouldn't be any changes in behaviour. …
=> Build and deploy with Node 20 (lts/iron)

packages/app-root/.eslintrc.json, packages/app-root/next.config.mjs, packages/app-root/package.json, packages/app-root/server/server.js, packages/app-root/src/app/about/page.js, packages/app-root/src/app/projects/page.js, packages/app-root/src/components/PageContextProviders.js, packages/app-root/src/components/PageFooter.js, packages/app-root/src/components/PageHeader.js, packages/app-root/src/components/RootLayout.js, packages/app-root/src/contexts/PanoptesAuthContext.js, packages/app-root/src/contexts/index.js, packages/app-root/src/helpers/fetchPanoptesUser.js, packages/app-root/src/helpers/index.js, packages/app-root/src/hooks/index.js, packages/app-root/src/hooks/useAdminMode.js, packages/app-root/src/hooks/usePanoptesUser.js, packages/app-root/src/hooks/useUnreadMessages.js, packages/app-root/src/hooks/useUnreadNotifications.js, yarn.lock
- configure ESLint.
- add the [Panoptes auth client](https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-auth), from `panoptes-client`.
- add the [`useSWR` hook](https://swr.vercel.app/), from 'swr'.
- add `usePanoptesUser` for SWR-style user fetching.
- add an express server to handle HTTPS in local development.
- add a page context component to provide global styling, the Grommet theme, and Panoptes auth context.
- add the panoptes user to both page header and footer.
- fetch your unread message count (`useUnreadMessages`) and unread notifications count (`useUnreadNotifications`), once you've signed in.
- add an admin toggle to the page footer, and an admin border to the page body.
_Please request review from `@zooniverse/frontend` team or an individual …
=> Add Panoptes auth to app-root

packages/app-content-pages/src/screens/Publications/Publications.js, packages/app-content-pages/src/screens/Teams/Teams.js
package: `app-content-pages`
Affects: About -> Team, About -> Publications
Fixes #5575
Follows #5552
This PR fixes a small UI issue where, on extremely vertically short viewports _(OR when the browser is zoomed in, OR the browser has increased font sizes),_ the nav list in the sticky sidebar isn't fully displayed and can't be scrolled
Solution is a very straightforward `max-height: 100vh` and `overflow: auto`
Design flaw/tradeoff:
- Curiously, with the existing sticky behaviour, if you scroll aaallll the way down to the end of the page, the sidebar will eventually show the final items in the nav list. (screenshot on left) With this PR, the sidebar needs to be manually scrolled. (screenshot on right) 
Tested with macOS + Chrome 119
- Open the About -> Publications page (since it has the …
=> Fix #5575, allow sticky sidebar in About page to overflow/scroll

packages/app-project/src/shared/components/SubjectPicker/helpers/columns.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.spec.js, packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js, packages/app-project/src/shared/components/SubjectPicker/helpers/slugify.js
Slugify data property names in subject metadata so that, for example, 'verm. Lemma' becomes `verm_lemma`.
Fixes a bug where the data table used by `SubjectPicker` won't display a data column with names that contain punctuation or whitespace.
- app-project
The subject data table here should now show some values in the 'verm. Lemma' and 'verm. Ort' columns.
https://local.zooniverse.org:3000/projects/dschopper/the-abcs-of-dialect/classify/workflow/25015/subject-set/116692
Compare with staging, where those columns are empty.
https://frontend.preview.zooniverse.org/projects/dschopper/the-abcs-of-dialect/classify/workflow/25015/subject-set/116692
_PR Creator - Please cater the checklist to fit the …
=> SubjectPicker: slugify data property names

packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js, packages/lib-classifier/src/translations/en/plugins.json
https://github.com/zooniverse/front-end-monorepo/issues/5604
Added a confirm / cancel when clicking the delete icon on the LineControl for the FreehandLine tool.
[FreehandLine Storybook](http://localhost:6006/?path=/story/drawing-tools-freehand-line--drawing)
=> FreehandLine LineControls: Add confirm or cancel to delete.

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
Since #5574, `@zooniverse/react-components` uses the `swr` package in custom data-fetching hooks, but it isn't installed as a dependency.
- closes #5655.
- See the [build errors](https://github.com/zooniverse/community-catalog/actions/runs/6890778197/job/18744497530?pr=213) on https://github.com/zooniverse/community-catalog/pull/213
=> Bugfix: missing SWR package

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.spec.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchSubjectData.js
Refactor home page `RecentSubjects` to use `useSWR`. The `RecentSubjects` component, on the project home page, will now refresh in the background when the fetched API data is stale.
Preserve the subject comment order when fetching subjects from Panoptes.
- Closes #5589.
- app-project
With a project home page open in a tab, the list of recent Talk subjects should now refresh in the background when recent subject comments change in Panoptes. Previously, you would have to reload the page to see new comments.
Here, I open the project home page in one tab, leave a new subject comment in another tab, then see the recent subjects update in the original tab. …
=> Background refresh project Talk recent subjects

packages/app-project/src/shared/components/ContentBox/ContentBox.mock.js, packages/app-project/src/shared/components/ContentBox/ContentBox.spec.js, packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
app-project
Converted tests for the ContentBox from Enzyme to RTL. 
[ContentBox Story](http://localhost:9001/?path=/story/project-app-shared-contentbox--plain)
=> ContentBox: Remove enzyme and convert tests to RTL

packages/app-content-pages/package.json, packages/app-project/package.json, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/package.json
Add `@zooniverse/panoptes-js`, which is used by the `fetchPanoptesUser` helper.
Bump the version to 1.10, to include the new text subject feature.
- @zooniverse/react-components
=> Fix missing dependency in lib-react-components

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js, packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchSubjectData.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5765
- Check if a subject exists in `fetchSubjectData` helper before returning subjects array to RecentSubjects component
- Adjust error handling so that if a subject isn't found, the other recently commented-on subjects will still display
See in-code comment below about how to review by running locally.
Gravity Spy's home page was previously crashing due to the recently commented-on subjects, but enough comments have come through Talk that it's no longer crashing. …
=> Check if subject exists for recent subjects on homepage

packages/app-project/pages/[panoptesEnv]/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js, packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js, packages/app-project/src/screens/ClassifyPage/ClassifyPage.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5770
Related to: https://github.com/zooniverse/front-end-monorepo/issues/4977
- Use the project `slug` from the store rather than rely on `router.query` to form href to project home page
- Don't render a link for the Project Title when already on the project's home page.
- Use `history.replaceState` rather than NextJS's `router.replace`. This line was causing the router object to be reset and the important `query` params were no longer available in ClassifierWrapper.
- Add more in-code documentation to props
- The bugs described in the Issues linked above can be tested on [PRINT](https://www.zooniverse.org/projects/printmigrationnetwork/print) and [Deciphering …
=> Subject Set Selection bug fixes

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
Add check in the SubjectViewer for a FreehandLine or Transcription task and, if so, set `enableInteractionLayer` to true and pass the property through to the FlipbookViewer, MultiFrameViewer, and SeparateFramesViewer.
Pull the code locally and view these two projects. The first project should enable drawing while the second project should not.
- https://localhost:8080/?project=kieftrav/freehand-line-multiframe
- https://localhost:8080/?project=kieftrav/multiframe-no-drawing
=> Create check in SubjectViewer for whether to enable InteractionLayer.

packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.js
- fix page navigation in the About section so that only one page is marked as the current page.
- add more robust checks for page paths during SSR, when a project page path will be prefixed with `/production` or `/staging` according to whether it is a production or staging project.
=> Accessible project navigation: fix server-side page paths

packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js, packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js, packages/lib-classifier/src/plugins/tasks/components/TaskInput/index.js
- Clarify the naming of the task label and text for `TaskInput` components.
- Give each input a unique ID, based on the input type, task key and index.
- Explicitly label each input with the HTML `for` attribute.
- Clarify the naming of the label text in `TaskInputLabel`.
- Render labels with the inline markdown parser.
- lib-classifier/plugins/tasks
- towards #5737.
This can be reviewed in the storybook, using the stories for question tasks (single and multiple choice), drawing tasks and data annotation tasks. The behaviour of the radio button and checkbox inputs should not have changed, but they should all now be labelled with the HTML `for` attribute. Explicit labelling is needed by …
=> Use explicit labels for TaskInput components

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
lib-classifier
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5750
- Use `cover` instead of `contain` so the placeholder image behind a subject image stretches to the dimensions of the viewer rather than remain a landscape rectangle
- Any project that incorporates the SingleImageViewer can be reviewed locally (i-fancy-cats, Daily Minor Planet, etc). Here's the current FEM project's [spreadsheet](https://docs.google.com/spreadsheets/d/1X9345vQ_xNX6BJf9_xwVCQCjxjbWWErGmV7Xe8WpHZo/edit#gid=0) and use the Zoom Out button in the image toolbar 
_PR Reviewer - Use the checklist during your …
=> Adjust size of placeholder behind subject image

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
`enableInteractionLayer` must be set now, in subject viewers, in order to display previously drawn marks on top of a subject.
The `TranscribedLines` story, in the classifier storybook, should now show previously transcribed lines from Caesar.
=> Show transcribed lines in TranscribedLines story

docs/arch/README.md, docs/arch/adr-57.md
A quick ADR to explain the switch from Webpack UMD builds to ESM builds with Babel in #3900.
- towards #4214.
=> ADR 57: library build scripts

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js
lib-classifier
This reverts https://github.com/zooniverse/front-end-monorepo/pull/5306
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5826
Re-opens: https://github.com/zooniverse/front-end-monorepo/issues/5304
Remove `useWindowMoveEvents` from VisX Brush component in Scatterplot's Selections component
- View the Scatterplot's X-range selection [storybook](http://localhost:6006/?path=/story/subject-viewers-scatterplotviewer--x-range-selection). Test that you can draw a selection via mouse click and with touch emulation in browser tools. You can also run the storybook locally on your mobile device via [IP address strategy](https://github.com/zooniverse/how-to-zooniverse/blob/master/Frontend-Handbook/general-dev-resources.md#how-to-test-local-code-on-a-mobile-device).
- Note …
=> Remove useWindowMoveEvents from VisX Brush for Scatterplot Viewer

docs/arch/README.md, docs/arch/adr-58.md
A brief summary of how we used the Panoptes translations API in order to serve localised projects and workflows.
- towards #4214.
=> ADR 58: the Panoptes translations API

packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.mock.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.spec.js, packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.stories.js
app-project
Converted tests for the WidgetHeading from Enzyme to RTL. 
[WidgetHeading Story](http://localhost:9001/?path=/story/project-app-shared-widget-heading--widget-heading)
=> WidgetHeading: Remove enzyme and convert tests to RTL

packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitation.stories.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.js, packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.spec.js, packages/app-project/src/components/PageHeader/PageHeader.js, packages/app-project/stores/UI.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5869
- Create `authModalActiveIndex` on the UI store for the project pages. PageHeader was previously the only component setup to open or close the sign-in/register modal, but we want to be able to do so from other components too.
- Use `setAuthModalActiveIndex` in AuthenticationInvitation component rather than rely on changing the url to open the auth modal (that was legacy behavior).
- Ideally in the future all of the Announcements components will get a refactor in favor of RTL tests and more responsive styling, but for now I've only put a bandaid fix on the affected spec files.
- AuthenticationInvitation has a story that can be run for a visual check
- To try out sign-in or register buttons, run app-project …
=> app-project: Track AuthModal's active index in the UI store

packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js, packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
Fixes #5880 
May need iteration to fix tests / adopt alternate solution. Not sure whether this is an issue with the modal URL variable (as assumed by this original solution) or a larger router issue.
Adds `/projects` to link URL
Test with `zootester` prod user who has leveled up to second level on Gravity Spy:
1. Login as zootester (creds in Passbolt)
2. Navigate to Gravity Spy: https://www.zooniverse.org/projects/zooniverse/gravity-spy
3. Select Level 1 Workflow from homepage.
4. Because zootester is leveled up into Level 2, you should see the Workflow Assignment Modal pop-up -- note the incorrect URL for the "Take me to the next workflow" button.
- Can be used with a screen reader …
=> Workflow Assignment Modal: URL fix

packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
lib-classifier
[Issue #5922](https://github.com/zooniverse/front-end-monorepo/issues/5922)
Added a conditional check for when the mark is considered "finished" to check if its closed so that it updates the state properly to be a finished mark.
Load up the [FreehandLine Story](http://localhost:6006/?path=/story/drawing-tools-freehand-line--drawing) locally and test that you can draw two successive full, closed circle on first draw. Before this fix, you could not draw a 2nd mark without clicking the 'close' button in the LineControls.
=> FreehandLine drawing not recognizing closed mark

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/hooks/useFreehandLineReductions.js, packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js, packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.js, packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.spec.js, packages/lib-classifier/src/store/subjects/Subject/Subject.js
[Issue #5493](https://github.com/zooniverse/front-end-monorepo/issues/5493) 
[Issue #5833](https://github.com/zooniverse/front-end-monorepo/issues/5833) (unresolved in this PR)
- Pull the frame into and through the `FlipbookViewer`, `SeparateFrameViewer`, and `SingleImageViewer` components. 
- Enable Interaction Layer in `FlipbookViewer`
- Use the 'setCurrentFrame` hook from the `SubjectViewerStore` for all frame changes
- Update `FlipbookViewer` spec given serial vs async test running
- Moved mark process storage into the individual Subject store instead of SubjectStore
- Frame selection happens at the Viewer level
- All new marks get the actual frame value from where they were created (editing on a different frame won’t change the mark frame value)
- Because …
=> Change Flipbook and SeparateFrames viewers behavior to not clone drawing marks

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js, packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/Media/components/Video/Video.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/5840
- In app-project home pages and classify pages, turn off video controls for subject preview cards in RecentSubjects components.
- I also increased the contrast of the text-shadow behind the subject number displayed on project home pages. Although video subjects' controls are now hidden, there are data projects that use subjects with a white background
- Storybook for project home page's recent subjects: http://localhost:9001/?path=/story/project-app-screens-project-home-recent-subjects--plain
- Storybook for project classify page's recent subjects: http://localhost:9001/?path=/story/project-app-screens-classify-recent-subjects--plain
- An FEM project that has video subjects: …
=> Turn off video controls for subject preview cards

packages/lib-react-components/src/CloseButton/CloseButton.spec.js, packages/lib-react-components/src/CloseButton/CloseButton.stories.js
Converted tests for the CloseButton from Enzyme to RTL. 
[CloseButton Story](http://localhost:9001/?path=/story/components-closebutton--default)
=> CloseButton: Remove enzyme and convert to RTL

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
lib-classifier
Partial fix of https://github.com/zooniverse/front-end-monorepo/issues/5951
❗ This bug is not specific to the flipbook viewer, however it was reported via Daily Minor Planet because that project has an autoplay flipbook, hence exacerbating the Issue linked above. This PR is not a full fix, but of high priority to get Daily Minor Planet data exports back online while I investigate a full fix for all subject viewers.
- Use local state for `frame` in FlipbookViewer rather than `setFrame` and `frame` from the SubjectViewerStore.
- This is how flipbook worked prior to #5754, so this is a partial reversion of that PR for now.
Steps to reproduce the bug are outlined in the linked Issue. Here is a flipbook projects for testing (Daily Minor Planet's workflow might be deactivated):
- …
=> Use local state for Flipbook Viewer's frame to avoid MST re-renders

packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js, packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
Handle the case where `upp.settings.workflow_id` is a number
by converting it to a string before storing it.
- add tests to specify the behaviour of UPP settings.
- use the `numberString` type for Panoptes workflow IDs.
- fix the bug where `workflow_id` errors if it is a number.
- app-project
- fixes #5972
See #5972 for a test case, I think.
- Can be used with a screen reader [BBC guide …
=> fix: ensure upp.settings.workflow_id is a string

packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js, packages/lib-classifier/src/hooks/usePanoptesTranslations.js
app-project
lib-classifier
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6015
I edited `fetchTranslations()` and `usePanoptesTranslations()` in app-project and lib-classifier respectively. When a project team enables project-specific translations for a language in the project builder, but does not complete all necessary translation strings for a workflow resource, project page, etc, those translation keys end up as empty strings. Rather than display an empty string, we want the frontend to fallback to English.
Bug is described with screenshots in the Issue linked above, but generally you should be able to visit any project and change the selected locale via the dropdown or coerced in the URL. For example, in [Daily Minor …
=> Handle partial translated project-specific translation strings

packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
lib-classifier
https://github.com/zooniverse/front-end-monorepo/issues/6048
This bug was introduced by the freehand-line not recognizing the closing of a mark. In that fix, the follow up item of putting the [x,y] values in the annotations array.
Check out [this branch](https://fe-project-branch.preview.zooniverse.org/projects/kieftrav/freehand-line-multiframe/classify/workflow/3760?env=staging) and see that the Completed Classification in the `console.log()` has full `pathX` and `pathY` values for both closed and open marks.
=> Make sure the array of points gets added for a closed path

Dockerfile
To include the new lib-content package in FEM's staging deploy
Follows https://github.com/zooniverse/front-end-monorepo/pull/6034
- Add lib-content to the Dockerfile in a similar config to the other react component libraries.
I don't think this can be reviewed locally, but will need to be tested via Github Action such as the failed one: https://github.com/zooniverse/front-end-monorepo/actions/runs/8805448704
=> Add lib-content to the Dockerfile

packages/app-content-pages/src/screens/Publications/components/Category/Category.js, packages/app-content-pages/src/screens/Publications/components/Project/Project.js
- give each project a slug eg. `galaxy-zoo` or `backyard-worlds-planet-9`.
- give each project heading an `id` and `tabindex` to make it linkable and accessible.
- add an intersection observer, which sets the active navigation section for each project section (eg. Planet Hunters will set the active section to Space), when that project section is near the top of the viewport. 
- make sure that project sections are labelled.
- [Slack post asking for a link direct to the list of Galaxy Zoo publications](https://zooniverse.slack.com/archives/C06LHUC6R/p1713511420283709).
Project headings have human-readable IDs, which should work as links. The intersection observer should make …
=> feat: Accessible project headings for Publications

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/store/RootStore.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
Add `workflowSteps.hasAnnotateTask` to the `SubjectViewerStore` model as
a view. Add an `autorun` reaction which syncs `subjectViewer.annotateVisibility`
when `subjectViewer.hasAnnotateTask` changes.
lib-classifier
- Can be …
=> refactor: sync annotate visibility when workflow changes

packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js, packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.spec.js, packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.stories.js, packages/lib-user/src/components/GroupStats/components/MemberCard/index.js, packages/lib-user/src/components/shared/Avatar/Avatar.js, packages/lib-user/src/components/shared/Avatar/index.js, packages/lib-user/src/components/shared/ContentBox/ContentBox.stories.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js, packages/lib-user/src/components/shared/index.js, packages/lib-user/src/index.js, packages/lib-user/test/mocks/panoptes/index.js, packages/lib-user/test/mocks/panoptes/users.js
- lib-user
- refactor user avatar component from ProfileHeader to Avatar
- create MemberCard component
- add stories, tests
- refactor ContentBox stories with TopContributors story
- [related Figma design](https://www.figma.com/file/qbqbmR3t5XV6eKcpuRj7mG/Group-Stats?node-id=386-8409&mode=dev)
- What user actions should my reviewer step through to review this PR? review noted stories
- MemberCards: http://localhost:6008/?path=/story/components-groupstats-membercard--default
- TopContributors: http://localhost:6008/?path=/story/components-shared-contentbox--top-contributors (note the order will be ranked from most to …
=> lib-user: Add MemberCard

packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js, packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.spec.js
Quick fix for a bug where the survey task won't display when `task.alwaysShowThumbnails` is a string. In that case, the snapshot preprocessor will coerce it to a boolean.
- lib-classifier/plugins/tasks/survey
- fixes #6084.
Task T0 for Offal Watching should be displayed in the classifier now. …
=> fix(classifier): surveyTask.alwaysShowThumbnails must be a boolean

packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js, packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
- app-root
- when I rebased recent PRs I neglected to update the app-root GroupStats component with the `joinToken` passed from the group stats `page.js` file
- refactors role and joinGroup useEffect for if already a member but have join_token in url
- production group, should show group not found: https://local.zooniverse.org:3000/groups/2620016?env=production
- production group, join should fail: https://local.zooniverse.org:3000/groups/2620016?env=production&join_token=1234567
- production group, join should work: https://local.zooniverse.org:3000/groups/2620016?env=production&join_token=a05cc85a3b11b6d8
- …
=> app-root: Fix group join issue

kubernetes/deployment-staging.tmpl
Adds existing Contentful keys to the staging deployment of the fe-root app's env vars. …
=> Add Contentful keys to fe-root env

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js, packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.spec.js
lib-classifier
Follow-up from https://github.com/zooniverse/front-end-monorepo/pull/6007
- Use a Text component for field guide anchor labels to reduce the line height and font size. The labels do not need to be paragraphs and their line height is too large at the moment.
- Review the local lib-classifier Field Guide [story](http://localhost:6006/?path=/story/help-resources-field-guide--general) compared to the production [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/help-resources-field-guide--general)
- Field guide anchor labels are used in every FEM project - [spreadsheet](https://docs.google.com/spreadsheets/d/1X9345vQ_xNX6BJf9_xwVCQCjxjbWWErGmV7Xe8WpHZo/edit#gid=0)
- I got design approval from Sean in-office 👍 
_PR Creator - …
=> Classifier: use Text for field guide anchors

packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.js
lib-classifier
Toward: https://github.com/zooniverse/front-end-monorepo/issues/6063
- This change is intended to improve volunteer's classifying experience when a workflow has a "tall" task area and landscape oriented subject viewer. For example, when a volunteer clicks "Done" on a survey task, we want them to keep the subject in view rather than forced to scroll up and down the page to complete each classification.
- Added sticky css styling to the ViewerGrid component for NoMaxWidth and MaxWidth layout. MaxWidth layout is the default layout and NoMaxWidth layout is specific to transcription projects.
- The CenteredLayout's task area wasn't being sticky (e.g Daily Minor Planet) especially for separate frames view, so I fixed that. CenteredLayout only applies when a project team …
=> Make the classifier's subject viewer sticky

packages/lib-grommet-theme/src/index.js
lib-grommet-theme
- Remove links to Invision (that app is deprecated)
- Add code comments outlining the default Grommet breakpoints that are in use for viewport width
=> Update breakpoints and brand documentation in lib-grommet-theme

packages/lib-user/src/components/GroupStats/GroupStats.js, packages/lib-user/src/components/GroupStats/GroupStatsContainer.js, packages/lib-user/src/components/GroupStats/components/GroupUpdateFormContainer/GroupUpdateFormContainer.js, packages/lib-user/src/components/GroupStats/components/MembersList/MembersListContainer.js, packages/lib-user/src/hooks/usePanoptesMemberships.js, packages/lib-user/src/utils/deletePanoptesMembership.js, packages/lib-user/src/utils/updatePanoptesMembership.js, packages/lib-user/src/utils/updatePanoptesUserGroup.js
- lib-user
- this PR comment - https://github.com/zooniverse/front-end-monorepo/pull/6100#discussion_r1624490539
- refactor group update with useSWRMutation
- refactor membership delete with useSWRMutation
- refactor membership update with useSWRMutation
Example …
=> lib-user: Refactor group and membership changes with useSWRMutation

packages/lib-user/src/components/Certificate/CertificateContainer.js, packages/lib-user/src/components/Contributors/Contributors.js, packages/lib-user/src/components/GroupStats/GroupStats.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js, packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjectsContainer.js, packages/lib-user/src/components/UserStats/UserStatsContainer.js, packages/lib-user/src/hooks/usePanoptesProjects.js
- lib-user
- if a user made a classification on a private or development project then the related recent or project_preference would cause an error on the logged-in homepage when the previous `usePanotpesProjects` hook would return a list of projects that would not include the private or development project 
- adds auth to `usePanoptesProjects` so private or development projects will be returned
- adds filters and slices to prevent RecentProjects and RecentSubjects errors
- refactors UserStats, Certificate, GroupStats, and Contributors components use of `usePanoptesProjects`
- reproduce bug: if …
=> lib-user: Refactor usePanoptesProjects hook with auth, update usage accordingly

packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js
-lib-user
- rename `project_slug` to `projectSlug` to match the actual property of the object per [RecentSubjectContainer here](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjectsContainer.js#L57)
- go to logged-in homepage, note recent subjects now have expected/correct url
_PR Reviewer - Use the checklist during your review. Each point should …
=> lib-user: fix RecentSubjects projectSlug variable

packages/lib-content/src/components/Article/Article.js, packages/lib-content/src/screens/Home/Community/Community.js
lib-content
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6152
- Blog post titles link out
- 'See all posts' and 'Read more' links  de-bolded and grey
- 'Read more' links right-aligned
- 'The Zooniverse Blog' header styling fixed
- Article and Community components are in lib-content's Storybook
- Run app-root locally and visit the homepage signed-out or signed-in
=> Community section styling updates

packages/app-project/pages/404.js, packages/lib-content/src/screens/404/Default404.js
lib-content
app-project
Follow-up from https://github.com/zooniverse/front-end-monorepo/pull/6162
- Place anchors inside list items instead of using `forwardedAs`.
Run app-root locally and try to visit any non-existent page such as https://local.zooniverse.org:3000/notreal
Run app-project locally and try to visit any non-existent project url such as https://local.zooniverse.org:3000/projects/notreal.
=> Quick fix for 404 page links

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js, packages/lib-classifier/src/hooks/useKeyZoom.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js, packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
- Refactor `SVGPanZoom` to use a ref for `zoom`, rather than component state. Hopefully, this will lead to fewer rerenders when dragging a zoomed image, and smoother performance.
- Use a ref to store pointer coordinates in the `draggable` decorator, to avoid unnecessary rerenders.
- Move the cropped SVG viewbox into a nested SVG, for better performance when dragging a zoomed image.
- Remove the `1.5` easing factor on dragged images, so that they 'stick' to the pointer when dragged.
- Use `focus-visible` so that focus rings are only shown for keyboard interactions.
- refactor the `useKeyZoom` hook to support rotated images. 
Screen recordings from Firefox 125 running on an M3 MacBook (Sonoma 14.4.1.)
Pan and zoom with a trackpad:
https://github.com/zooniverse/front-end-monorepo/assets/59547 …
=> fix(classifier): Fix wonky drag when image is rotated

packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js, packages/lib-user/src/components/UserHome/components/UserHomeLayout/UserHomeLayout.js
lib-user
Follow-up to https://github.com/zooniverse/front-end-monorepo/pull/6179 and https://github.com/zooniverse/front-end-monorepo/issues/6151
- Adjust the margin of PageBody for the UserHome-specific layout so that ZooHeader is not hidden on mobile widths.
- Icons in the Dashboard are 1.5rem on mobile, but should stay 1rem on desktop, so I fixed that here too.
I don't typically self-merge PRs, but this one affects only fe-root.preview, and the changes need to be deployed before ZTM sessions today for preview purposes.
=> Quick fix for signed-in homepage mobile layout

packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
- lib-user
- getDateRangeSelectOptions tests failed when running FEM locally in Oxford, but passed when running in CI (presumably in a US timezone), [related Slack thread](https://zooniverse.slack.com/archives/C010QAPB67J/p1721631284997649)
- stats are recorded (ERAS) and displayed (user/group stats pages) in UTC
- refactor tests to reflect when there might be conflicts between a user's date and UTC, i.e. someone 2 hours ahead of UTC at 1AM (the user is on the 16th of the month, but UTC is still the 15th) or someone 2 hours behind UTC at 11pm (the user on the 14th of the month, but UTC is on the 15th)
- refactor getDateRangeSelectOptions to properly reflect UTC date (not user's local date)
- What Zooniverse project should my …
=> lib-user: Add getDateRangeSelectOptions tests before and after UTC

packages/lib-user/src/components/shared/BarChart/BarChart.js, packages/lib-user/src/components/shared/BarChart/BarChart.spec.js, packages/lib-user/src/components/shared/BarChart/BarChart.stories.js, packages/lib-user/src/components/shared/BarChart/helpers/getCompleteData.js, packages/lib-user/src/components/shared/BarChart/helpers/getCompleteData.spec.js
- lib-user
- closes #5841 
- add index to complete (includes empty periods) stats data array
- based on data length, show appropriate number of x-axis labels (less data -> show all x-axis labels, a lot of data -> show every fourth item's label)
- update stories and tests
- review your user stats bar chart, noting x-axis label frequency with different date ranges
- review a group stats bar chart, noting x-axis label frequency with different date ranges
- BarChart stories, most notably http://localhost:6008/?path=/story/components-shared-barchart--last- …
=> lib-user: Refactor BarChart and getCompleteData to show x-axis labels as intended

packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js, packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js, packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.spec.js, packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.stories.js
- Refactor `AnimatedNumber` to add missing `value` and `duration` effect dependencies. Declare `animateValue` as a pure function outside the component, so that it doesn’t generate a new function on every render.  Refactor the `useEffect` hook to minimise side effects.
- Check that the current and initial values are different before animating. Update the displayed value when animation is complete, so that a render always returns the latest value, not 0. Animate numbers with a delay when the displayed value is 0 and prefers reduced motion is off. Otherwise, display changes immediately eg. after submitting a classification and incrementing your counts.
- Add a `DeferredAnimation` story, which reproduces #6190.
- Add a status live region to the `YourStats` component, so that changes to your …
=> fix(lib-react-components): AnimatedNumber displays async values as 0

packages/lib-content/src/translations/en.json, packages/lib-react-components/src/PlainButton/PlainButton.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js
lib-user
lib-content
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6181
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6183
This PR makes minor changes to the logged-in and logged-out homepage components to close the above Issues. I also add a small change to the `label` in PlainButton so it can be a button that renders an aria-labeled icon without a string label. If `text` is an empty string, then we don't want to render SpacedText in PlainButton.
Run lib-user locally to see the logged-in homepage, and the change to lib-content is only two words in a translation string, but it can be run via Storybook or via app-root to review the logged-out homepage.
_PR Creator - Please cater the checklist to fit the review needed for your code …
=> Fix homepage dashboard links and minor logged-out copy update

packages/lib-user/src/components/shared/MainContent/MainContent.js
- lib-user
- [Figma link](https://www.figma.com/design/qbqbmR3t5XV6eKcpuRj7mG/Group-Stats?node-id=658-15872&m=dev)
- originally added [here](https://github.com/zooniverse/front-end-monorepo/pull/6132/files#diff-7ddb94740b3bf0fbefeac7e9a8e7958177ff669c0007e21939ae1484ad261f37R114-R122), but I must have removed it by mistake in a rebase at some point...
- add Tip about hours stats calculation to MainContent "Hours" tab
- review your user stats or a group stats page
- http://localhost:6008/?path=/story/components-shared-maincontent--default
- Are there …
=> lib-user: Add MainContent tooltip about hours stats calculation

packages/app-root/src/app/page.js, packages/lib-content/src/components/Article/Article.js
lib-content
This is a small change to the Article component for mobile widths. I noticed in the recent blog post, a long url runs off the screen and causes awkward shifting of the whole page. To solve, I hid featured images on mobile widths and also limited the excerpt to only 120 characters to show more articles on the screen at once.
I also realized I forgot to include a `revalidate` timeframe in the home page file, so I added a 1-hour revalidation similar to the Team and Publications pages (only affects blog post data because those are fetched server-side).
Before:
After:
@seanmiller26 please take a look at the screenshots above.
To review the code locally, run lib-content's Storybook and change the viewport size, or run app-root locally and view your homepage on mobile and desktop. …
=> Homepages: Adjust mobile styling of Article in Community section

packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js, packages/app-project/src/hooks/useAssignedLevel.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/LevelingUpButtons.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
app-project
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6198
- Full details are in the linked Issue, but essentially this PR checks if `assignedWorkflowID` exists, and always fetches data about the assigned workflow's config because sometimes a workflow will retire when a volunteer is assigned to it in the leveling up structure (e.g Gravity Spy).
- In app-project, there's code that double checks if a user is allowed to see a workflow page (ClassifyPageContainer) and code that filters the workflows array into locked / unlocked (WorkflowSelectButtons). I added a helper hook `useAssignedLevel()` to utilize in both.
- I also cleaned up WorkflowSelectButton's component code. There was no actual use of `gap`, `onSelect`, or different theme edges.
- I have to include this …
=> Refactor Workflow Select Buttons for leveling up retirement bug

packages/app-root/src/app/page.js
app-root
As stated in Slack, there’s something strange going on with https://fe-root.preview.zooniverse.org/ where sometimes I see the content and other times it’s blank 🤔 Zach observed the same behavior today, so we're testing the reversion of `revalidate` for the home page file.
I don't think this can be replicated locally, but when app-root is run locally it's https://local.zooniverse.org:3000.
=> app-root: Remove revalidate param from home page

packages/lib-user/src/components/shared/GroupForm/GroupForm.js, packages/lib-user/src/components/shared/GroupForm/GroupForm.spec.js
- lib-user
- add 60 max character validation for group name in GroupForm
- create or edit a group locally (lib-user or app-root)
- attempt to create a group name more than 60 characters, note error message
- http://localhost:6008/?path=/story/components-shared-groupform--create
- http://localhost:6008/?path=/story/components-shared-groupform--manage …
=> lib-user: Add max character group name validation to group form

packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
lib-classifier
Issue #6224 
Research team started creating a group subject selection for FEM and realized that the tool wouldn't allow "selecting" or "annotating" individual subjects within the group viewer. Found that the bug is related to a previous PR that has a list of tasks that enable the Annotate Button in the Classifier, specifically noting that the `subjectGroupComparison` task does not pass that filter.
Load up the Classifer locally and visit Mike Wallamsley's test project ["Not Galaxy Zoo FEM"](https://local.zooniverse.org:8081/?project=mikewalmsley%2Fnot-galaxy-zoo-fem&env=production&workflow=27251). You should be able to see the pencil icon to annotate and it should be selected by default. 
You can also view it on the [Deployed Branch …
=> SubjectGroupComparison tool not allowing Annotating

packages/lib-content/src/screens/About/components/Contact.js, packages/lib-content/src/screens/About/components/Highlights.js, packages/lib-content/src/screens/Collaborate/Collaborate.js, packages/lib-content/src/screens/Collaborate/Logos.js, packages/lib-content/src/screens/FAQ/FAQ.js, packages/lib-content/src/screens/Resources/Resources.js, packages/lib-content/src/translations/en.json, packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.js, packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.js
lib-content
lib-user
- All of the Get Involved and About pages are built into lib-content for use in app-root, so links to their pages can be relative paths.
- I refactored `BASE_URL` in getHeaderItems() so that on launch of those pages it will equal zooniverse.org.
- Links edited in this PR should work as expected with app-root run locally. There's one case where I corrected a link to the FAQ page, and I'll comment on it below.
- When you click "share a group" or "copy join link", the base of the url should be your local host, and when deployed it will be etc.zooniverse.org.
=> Use relative paths for any links with /about or /get-involved or sharing groups

packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js, packages/lib-react-components/src/hooks/Readme.md
lib-content
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6229
- In the Hero component, detect if the component has mounted, the screen is not small, and the device does not prefer reduced motion before autoplaying the Hero video.
- Run app-root locally and load the signed-out homepage on desktop and a mobile device. For instance, you can see these changes on your mobile device by using https://xxx.xxx.x.x:3000 with your IP address.
- Change your local device settings for [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) and the video will not display if accessibility settings are set to reduce motion. On macOS this is in Settings > Accessibility > Display.
_PR Creator - Please cater the checklist to fit the review …
=> Signed-out homepage Hero video - autoplay only once screen size is detected

packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js, packages/app-root/src/app/users/[login]/stats/UserStatsContainer.js, packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
- app-root
- refactor updateStartDateParam with `router.replace` instead of `router.push`
- related [Next useRouter docs](https://nextjs.org/docs/app/api-reference/functions/use-router#userouter)
- updateStartDateParam runs when the start_date param is undefined, and sets the start_date param as the default value (7 days ago for user and group stats, all time for certificate page), with router.push this was creating a new entry to the browser history stack, with router.replace it does not add a new entry
- confirm bug:
- start from your MyGroups page, i.e. …
=> app-root: Refactor setting stats startDate param with router.replace

docs/arch/README.md, docs/arch/adr-60.md
This PR adds documentation and context for @kieftrav's work on the Caesar-enabled Drawing Tasks.
- See [FEM PR 6039](https://github.com/zooniverse/front-end-monorepo/pull/6039), which implements the new Caesar-fetching conditions for the FEM Classifier.
- See [PFE PR 7148](https://github.com/zooniverse/Panoptes-Front-End/pull/7148), which enables project owners to toggle `workflow.configuration.enable_caesar_data_fetching`.
Ready for review!
=> Add ADR 60: Enabling Aggregations (Caesar Reducers) on Workflows

packages/app-content-pages/src/screens/About/components/Stats/Stats.js, packages/lib-content/src/components/Stats/Stats.js
lib-content
Updating static offsets for platform-wide classification and user counts.  Parallels changes in https://github.com/zooniverse/Panoptes-Front-End/pull/7167.
1. Visit the not-logged-in homepage (equiv to https://fe-root.preview.zooniverse.org/) and the new About page (equiv to https://fe-root.preview.zooniverse.org/about).
2. Check that new classification and user count values appear. Current approx values: classifications = 832,512,123; users = 2,757,137 (as of Fri Sept 6).
=> Update platform-wide classification and user count offsets

packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js, packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js
- closes #5112 
- positions Confusion drop below ConfusedWith button
- prevents repositioning Confusion drop per browser view height, affixes Confusion drop below ConfusedWith button
- fix `characteristic.values` type warning, similar to #6087 
- https://local.zooniverse.org:8080/?project=1634&env=staging&workflow=2434
- in [an existing survey task](https://frontend.preview.zooniverse.org/projects/markb-panoptes/survey-task-test-project/classify/workflow/2434?env=staging) and locally, compare:
- click a survey task choice confusion, note the confusion drop positioning
- with the …
=> lib-classifier: Fix survey task Confusion drop positioning

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
Manually focus the current consensus line when the consensus popup is closed, for the transcription task. This fixes an issue in Firefox, where keyboard focus switches to the document body when the popup is closed.
- closes #6271.
- https://github.com/zooniverse/Panoptes-Front-End/pull/4125
- https://github.com/zooniverse/Panoptes-Front-End/issues/4123
Window scroll position shouldn't change now, after closing the consensus transcriptions popup. Remember to test opening/closing the popup with both the keyboard and a mouse/trackpad.
Dev classifier: https://localhost:8080/?project=printmigrationnetwork/print&workflow=20199&subjectSet=111064&subject=84319115&env=production …
=> fix(classifier): focus management for consensus lines

kubernetes/deployment-production.tmpl
Includes the service, deployment, and autoscaler for the production instance of the fe-root app. Gave it the same resources & scaler config as the fe-project app, but I'll keep an eye on it and scale it up if necessary.
This will create the new resources when the template is applied during the production deploy, but will have no other effect until routing changes in a static PR starts pointing traffic at the new service.
_PR Creator - Please cater the checklist to fit …
=> Add fe-root resources to production k8s template

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
Similar to https://github.com/zooniverse/front-end-monorepo/pull/6046 which was changed for fe-root.
- Change the liveness probe to `/about` because `/about/Index` does not exist have adding the Get Involved routes to the Pages Router.
- Will need to be double check after deployment.
=> app-content-pages: change liveness probe url

packages/app-root/src/app/mock/faq/page.js, packages/app-root/src/app/mock/page.js, packages/app-root/src/app/mock/resources/page.js, packages/app-root/src/middleware.js, packages/lib-content/src/components/AboutHeader/AboutHeader.js, packages/lib-content/src/index.js
lib-content
app-root
- Create /mock page.js files
- Export AboutHeader from lib-content for use in app-root
I'll be self-reviewing this in collaboration with @zwolf. These changes do not affect any public facing FEM pages.
=> Create a temporary /mock route in app-root for compatibility testing with FrontDoor

packages/app-root/src/middleware.js
app-root
Follows: https://github.com/zooniverse/front-end-monorepo/pull/6292
- Add rules to middleware.js to bypass Next.js internals. Middleware and basePath do not work well together for the `matcher` function.
I'll be self-reviewing this in collaboration with [@zach](https://zooniverse.slack.com/team/U11KL1NLW). These changes do not affect any public facing FEM pages.
=> app-root: Try same config as app-project in app-root middleware file

kubernetes/deployment-production.tmpl, kubernetes/deployment-staging.tmpl
app-root
Follows: https://github.com/zooniverse/front-end-monorepo/pull/6294
- With basePath, use /mock for the liveness probe.
I'll be self-reviewing this in collaboration with [@zach](https://zooniverse.slack.com/team/U11KL1NLW). These changes do not affect any public facing FEM pages.
=> app-root: Use /mock for liveness rather than /users

packages/lib-content/src/components/DropdownNav/DropdownNav.js, packages/lib-content/src/components/Sidebar/Sidebar.js, packages/lib-content/src/screens/About/About.js
- Remove `next/link` from sidebar links, so that the browser focuses the linked heading when you follow an in-page link on one of the About pages.
- Link the 'Our Mission' link to its corresponding heading on the About page, so that readers aren't sent back to the top of the page body.
- lib-content
- closes #6289.
In a screenreader, like NVDA or VoiceOver, reading focus should now move to the linked heading when you follow a sidebar link. Similarly, focus should move logically through the page when you tab through the page and follow sidebar links from the keyboard. See [WCAG 2.4.3: Focus order](https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html).
Testing this PR revealed some other …
=> fix(lib-content): accessible sidebar links for screenreaders and keyboard users

packages/app-root/package.json, packages/app-root/server/server.js, yarn.lock
app-root
This is a feature request by @zwolf 
Install `morgan` and setup logging in the same manner as app-project.
Run the app locally in production mode `yarn start` instead of dev mode `yarn dev`. Visit any app-root url such as https://local.zooniverse.org:3000 and the page requests are logged to the terminal.
=> app-root: Add morgan for logging on production server

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/ProjectCard/ProjectCard.js
Add a minimum width and a height to the project card badge.
>At least one of the box's sizes needs to be automatic in order for aspect-ratio to have any effect. If neither the width nor height is an automatic size, then the provided aspect ratio has no effect on the box's preferred sizes.
https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio
- fixes #6313.
You can use the `ProjectCard` stories to test this. The badge should now be circular in Safari, even when the number is small. …
=> fix(lib-react-components): project card badge width in Safari

packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js, packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js, packages/app-project/src/components/ProjectHeader/hooks/useProjectNavigation.js
app-project
Follow-up to https://github.com/zooniverse/front-end-monorepo/pull/6320
- Links in the ProjectHeader that do not use next/link need the `/projects` path manually added.
- Run any project locally and the Talk, Collect, and Recents links in the project header should form the correct urls.
=> app-project: add /projects to useProjectNavigation external links

packages/lib-classifier/README.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/README.md, packages/lib-classifier/src/plugins/tasks/readme.md, packages/lib-classifier/src/store/README.md, packages/lib-classifier/src/store/feedback/README.md
lib-classifier
The purpose of this Classifier Documentation PR is to link together all of the existing README’s in the Classifier and to provide some visual/overarching sense of the code architecture and underlying data models that tie together the Classifier. Because this has no effect on the underlying code, this can be merged in without testing / other deployment-oriented concerns.
- Updated to give more of an overview of what the Classifier is and the underlying concepts that create the classifier
- Add some Mermaid diagrams to visualize the relationship between the SubjectViewer, TaskArea, and RootStore
- Describe the Render process with links to other Classifier documentation
- Add link to the Hooks Readme so they are not orphaned
- Add links to the FlipbookViewer and …
=> Classifier README updates

packages/app-root/package.json, packages/app-root/src/app/layout.js
app-root
next/third-parties documentation: https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-tag-manager
- Add GoogleTagManager component to top level layout.js in app-root. It uses the same tag ID as PFE and app-project.
- When run locally, the tag html can be inspected when in production mode, but not in development mode.
=> Add Google Tag Manager to app-root's layout

packages/lib-subject-viewers/README.md
lib-subject-viewers
- Add documentation to lib-subject-viewer's README for users trying to bootstrap FEM from an Apple computer with M1 or M2 chip.
=> Document troubleshooting M1 chips with canvas in lib-subject-viewers

packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabs.js
A small accessibility fix. Style the home page user tabs with `text-transform: uppercase;` so that they aren't read as all capitals (letter by letter) in screen readers.
- lib-user
>Always type words with appropriate capitalization (capitals for the beginning of a sentence and proper nouns, etc., lowercase for other words). Then apply a style or text effect to create the appearance of all caps. Screen-reading devices will then announce the words correctly (as opposed to, e.g., trying to treat them as an initialism or acronym and reading out each word letter by letter). Other assistive technologies or conversions will also work correctly because they have the option to override your style to …
=> fix(a11y): style user tabs label text with CSS

packages/lib-user/src/components/UserHome/components/SubjectCard/SubjectCard.js
Double the size of subject card images, so that they are not pixelated on the home page.
- lib-user
- fixes #6333.
Your personal subject card images are blurred on the main branch, but sharp here.
This branch:
zooniverse.org:
- It is passing accessibility checks in the storybook
=> fix(lib-user): pixelated home page subject cards

packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
Add missing time zones to the date range tests, so that they pass in all time zones.
- lib-user
- fixes #6354
Tests are passing now when I run them in a UK time zone (UTC + 1.) I'm not sure how to test this outside the UK. Maybe run it in a CST or CDT time zone in the US?
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistiv …
=> test(lib-user): broken date range tests

packages/lib-user/src/components/MyGroups/components/PreviewLayout/PreviewLayout.js, packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js, packages/lib-user/src/components/shared/HeaderLink/HeaderLink.js, packages/lib-user/src/components/shared/MainContent/MainContent.js
Use `next/link` for the home page link to user stats, the link to your stats certificate, and the Back link at the top of each page.
Also fix the `lib-user` peer dependencies, which were still requiring Next.js 13.5.
- lib-user
- fixes #6350.
'More stats', on the home page, and 'View certificate', on the user stats page, and the Back link on each of those pages, should now use client-side routing in the root Next.js app.
Build the user library with these changes, then build and run the root app with `yarn build && yarn start`, to verify that those links are now using client-side routing (ie. the page doesn't reload, and `app-root` doesn't unmount and remount in the browser, when moving between …
=> fix(lib-user): use next/link for internal app routes

packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js, packages/lib-user/src/components/shared/ContentBox/components/ContentLink.js
lib-user
Follows: https://github.com/zooniverse/eras/pull/76
Might fix: https://github.com/zooniverse/front-end-monorepo/issues/6332
- Use eras instead of `/project_preferences` to fetch contribution count per project on the homepage and sort the Recent Projects section.
- Looking at the Recent Projects section, compare your signed-in homepage at https://www.zooniverse.org to app-root run locally. The order and classification count might vary a little bit because we're migrating to ERAS from `/project_preferences`.
- With the changes in this PR, the stats count on each Recent Projects badge should match the stats count on your stats page. For instance, eras says I made 123 classifications on i-fancy-cats which is displayed on my homepage and in the Top Projects of my all-time stats page. …
=> Refactor homepage recent projects to use ERAS

packages/lib-react-components/CHANGELOG.md, packages/lib-react-components/src/hooks/useUnreadMessages.js, packages/lib-react-components/src/hooks/useUnreadNotifications.js, packages/lib-user/src/hooks/usePanoptesAuthToken.js, packages/lib-user/src/hooks/usePanoptesMemberships.js, packages/lib-user/src/hooks/usePanoptesProjects.js, packages/lib-user/src/hooks/usePanoptesUser.js, packages/lib-user/src/hooks/usePanoptesUserGroup.js, packages/lib-user/src/hooks/useStats.js
Wait for the current Panoptes user to be signed-in before fetching unread messages and notifications. See https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-auth-authcheckbearertoken
Update user hooks that had the same race condition. Move token fetching code into a hook.
I've moved token fetching into a hook so that the auth token can be used in the SWR cache key, invalidating cached values when auth state changes. See the example in [the SWR docs for multiple fetcher arguments](https://swr.vercel.app/docs/arguments#multiple-arguments).
- lib-user
- fixes #6337.
- #6336.
Unread notifications should now be fetched with your bearer token. …
=> fix(app-root): wait for login to complete before fetching authenticated user data

packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.mock.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.spec.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.js, packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
- test the daily stats chart, on the Classify page. Check that each bar has the expected day and classification count.
- fix a bug thrown up by those tests, where the bar date wasn't correctly calculated as UTC.
- fix a bug in the mocks, so that the current daily count matches the count for the current day.
- fix a bug in the storybook, where the mocks were in reverse order.
- app-project
- closes #2244.
- closes #6324.
- #6383.
This started out as replacing some tests that were removed in #5210, but those tests failed, because of bugs in the `YourStats` component. So this now:
- tests the stats component to check that each day has the correct day name and classification count.
- fixes the …
=> fix(app-project): test the daily stats chart

packages/app-project/package.json, packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-content/src/screens/About/components/HowItWorks.js, packages/lib-content/src/screens/Donate/Donate.js, packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js, packages/lib-content/src/screens/Home/DefaultHome/components/Researchers.js, packages/lib-content/src/screens/Volunteer/Volunteer.js, packages/lib-react-components/package.json, packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.js, packages/lib-react-components/src/ZooHeader/ZooHeader.js, packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js, packages/lib-react-components/src/ZooHeader/components/UserNavigation/UserNavigation.js, yarn.lock
app-project
app-root
lib-classifier
lib-content
lib-user
Grommet releases: https://github.com/grommet/grommet/releases
- This PR bumps Grommet from v2.35.0 to v2.41.0
- There shouldn't be any visible changes to styling on FEM pages due to the upgrade. The only change I found, which isn't even mentioned in the Grommet releases, is that `styled()` Anchor components are now displayed inline-flex instead of flex 🤔 This discrepancy could be because of how Grommet and `styled-components` interact, but I did make a few bandaid fixes in this PR particularly for ZooHeader and ProjectHeader to keep their items center-aligned.
- I spent a lot of time comparing Storybook components of all packages in FEM to check for differences introduced by bumping `grommet`. I don't recommend …
=> Upgrade Grommet to v2.41.0

packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js
lib-user
Reverts: https://github.com/zooniverse/front-end-monorepo/pull/6397
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6407
Talk thread: https://www.zooniverse.org/talk/2354/3435274?comment=5721484&page=13
Slack decision: https://zooniverse.slack.com/archives/C010QAPB67J/p1729885678034879?thread_ts=1729873643.092939&cid=C010QAPB67J
- Reverts changes to RecentProjects data fetching back to `/project_preferences` because displaying projects in exact order of recently classified takes precedence. See Slack convo for UI/UX decision.
- Hides classification counts badge to remove discrepancy with ERAS counts on user stats pages.
Follow-up explanations on the linked Issue and Talk thread about expected ERAS behavior to follow.
_PR Creator - Please cater the checklist to fit …
=> Revert: Refactor homepage recent projects to use ERAS

.github/dependabot.yml
Dependabot Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
Change `open-pull-requests-limit` in dependabot.yml. As noted in Slack, right now the limit is 5, but several dependabot PRs are left open/un-merged due to failing CI (needs dev work to upgrade). Rather than close and forget about dependabot PRs, I’m going to self-approve a PR that increases the limit, and hopefully that’ll help us keep third party libraries up to date.
=> Increase dependabot PR limit to 15

.github/dependabot.yml
As mentioned in [Slack](https://zooniverse.slack.com/archives/CANKLB50E/p1730822483375389?thread_ts=1730325928.928729&cid=CANKLB50E), dependabot is still hitting a limit of 5 open PRs 🤔 
- Place `open-pull-requests-limit` near the "npm" section in dependabot.yml to try triggering more dependabot PRs.
I'll be self-reviewing and merging this PR as it has no effect on any builds, components, staged apps, storybook, etc.
=> Re-arrange open-pull-requests-limit

packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/app-root/src/components/RootLayout.js
app-project
app-root
Slack: https://zooniverse.slack.com/archives/C4RJRAGKA/p1731079514305719
Corresponds to: https://github.com/zooniverse/Panoptes-Front-End/pull/7217
- Add html and css for a simple `<details>` and `<summary>` at the top of each layout.
- I will likely end up just self-reviewing and merging this due to its simplicity and non-permanence.
- Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technolog …
=> Add temporary notice banner to app layouts for scheduled downtime

packages/app-project/src/hooks/useAssignedLevel.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageConnector.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js, packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/LevelingUpButtons.js, packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
Fix missing dependency errors in the `useAssignedLevel` hook by using `useSWR` to fetch and cache the assigned workflow level. SWR also adds revalidation of the Panoptes API request for cases where I might classify in the same tab over several days or weeks.* 
Adds conditional data-fetching, so that we only fetch a workflow configuration if we don’t already have it in the `workflows` page prop. 
Also fixes the workflow assignment tests in `ClassifyPageContainer` so that they test against the correct levels, and restores skipped tests to double check that nothing is broken.
~~Adds Mock Service Worker, for mocking API requests in stories.~~ I've moved the story for this into #6406. It sets up a test case where the assigned workflow, level 3, is complete and must be fetched from the Panoptes …
=> fix(app-project): data-fetching for assigned workflow level

.github/dependabot.yml
- Add a `groups` config for `@sentry`, Storybook, and VisX. This will group their version update PRs into one PR per group, making it easier to maintain consistent versions across the monorepo.
- Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- This will only apply to dependabot once merged.
=> Dependabot: Create groups for sentry, storybook, and visx

Dockerfile, README.md, docker-compose.yml, packages/app-project/README.md, packages/app-project/docker-compose.yml, packages/app-root/README.md, packages/app-root/docker-compose.yml
- replace the outdated `docker-compose` command with `docker compose` in the READMEs.
- fix `AS` in Dockerfile.
- update the Docker instructions in the READMEs.
- make sure that environment variables are set for local development in the `docker-compose.yml` files.
- https://github.com/zooniverse/front-end-monorepo/pull/6446#issuecomment-2475316117
To build and run the monorepo packages from the root directory:
```sh
docker compose build
docker compose up -d
```
That runs production builds of the project app and root app in a container:
- http://localhost:3002/projects/nora-dot-eisner/planet-hunters-tess
- http://localhost:3003
Shut down the running services and test the project docker compose …
=> build: docker instructions and fixes

packages/app-project/src/shared/components/StandardLayout/StandardLayout.js, packages/app-root/src/components/RootLayout.js
app-root
app-project
Reversion of https://github.com/zooniverse/front-end-monorepo/pull/6456
Corresponding PFE PR: https://github.com/zooniverse/Panoptes-Front-End/pull/7221
- Remove `<details>` component from layouts.
- app-root should run locally without the banner
- app-project should run locally without the banner
=> Remove temporary banners from app layouts

packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
- go to project with survey task, like production project https://www.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/7766 
- apply filters, close filters drop content
- note filter characteristic images do not display in FilterStatus component
- refactors `characteristics` and `characteristic.values` with `.get` because they are maps
- any survey task project, including:
- staging: https://local.zooniverse.org:3000/projects/markb-panoptes/survey-task-test-project?env=staging
- production: https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy/classify/workflow/7766?env=production
- What user actions should my reviewer step …
=> lib-classifier: Fix survey task FilterStatus images not showing

packages/app-project/package.json, yarn.lock
app-project
Follow-up to https://github.com/zooniverse/front-end-monorepo/pull/6472
Remove the unused VisX packages from app-project.
- This is a simple change I've tested locally by building app-project and will double check on frontend.preview.
=> Remove visx packages from app-project

packages/lib-panoptes-js/dev/index.html, packages/lib-panoptes-js/dev/index.js, packages/lib-panoptes-js/src/experimental-auth.js
This PR improves PR #6375 with the following updates:
- Output & "error handling" for Event Listener functions:
- addEventListener() no longer throws errors.
- addEventListener() and removeEventListener() now returns true/false if the action succeeded/failed.
- Documentation: the Sign In and Event Listener functions now have full documentation.
- Code cleanup: unnecessary PJC reference code removed.
- Dev Server/Dev Test Page:
- Dev test page now displays success and/or error messages on the web page itself, so we don't need to look at the dev console to see wtf is happening.
Merging into 6375.
=> Panopte.js: improve initial experimental auth

packages/lib-classifier/src/store/utils/ClassificationQueue.spec.js
Configure the fake timers for `ClassificationQueue` tests so that they only mock `setTimeout` and `clearTimeout`. …
=> test(classifier): fix ClassificationQueue mock timers

packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
Replace `div` with `span` in task input labels.
- closes #6547.
This shouldn't change any visible behaviour of task input labels. It should silence any React dev warnings about invalid DOM nesting in task input components. Similarly, any warnings in the Storybook should be fixed (does the Storybook check for invalid HTML?)
- Can be used with a screen reader [BBC guide …
=> fix(a11y): Fix invalid task input labels

packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.stories.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/components/InputGroup/components/QuestionInput.js, packages/lib-classifier/src/translations/en/plugins.json
- closes #6239 
- related to #6238 and #6076 - whose related PR #6494 should be merged to production together with this PR
- refactors Choice and related components per related Figma: https://www.figma.com/design/ASqNlLhicNRzEDhYDA2t8j/Survey?node-id=55-7053&t=BvyK5fjoLo5qzkDS-4
- lib-classifier, staging: https://local.zooniverse.org:8080/?project=1634&workflow=2434
- compare Figma designs to local survey task
- note new collapsable info (choice description and confused withs)
- …
=> lib-classifier: Refactor survey task Choice and Questions styling

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/README.md, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricMockSubject.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewer.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewerWrapper.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js, packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js, packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.js, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.spec.js, packages/lib-classifier/src/store/subjects/Subject/Subject.js, packages/lib-subject-viewers/src/VolumetricViewer/VolumetricViewer.js, packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js, packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
- Refactor SubjectViewer to no longer need to handle async components.. That work was moved into the viewer itself (`VolumetricViewerWrapper`)
- Create Wrapper for VolumetricViewer in the Classifier that follows other Viewer patterns and has related tests
- Moved detection of `isVolumetricViewer` into the Subject viewer detection function alongside all other viewer detection code
- Add `onAnnotation` callback in the `lib-subject-viewers` VolumetricViewer component to communicate back to MobX the updated annotations
- All specs should pass
- Classifier Storybook: [Subject Viewers > VolumetricViewer](http://localhost:6006/?path=/story/subject-viewers-volumetricviewer--default)
- Classifier Storybook: [Tasks > Volumetric](http://localhost:6006/?path=/story/tasks-volumetric--d …
=> VV - Implement Classifier Annotation Model

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
Make sure that `SVGContext.canvas` is a reference to the SVG `rect` element that's used as a drawing canvas, so that creating new drawing marks and editing existing marks both use the same screen CTM when calculating the pointer position in SVG space.
This fixes a bug in Firefox where the `draggable` decorator doesn't correctly track the active pointer, in the context of a zoomed SVG image.
- closes #6490.
On I Fancy Cats, you should be able to draw while zoomed in, without seeing any of the mismatched positioning described in #6490. You can try it out by drawing an ellipse while zoomed in, or by placing a point then dragging the point to a new position.
Try it out in Firefox …
=> fix(lib-classifier): canvas context for SVG drawing tools

packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/MainContent.spec.js, packages/lib-user/src/components/shared/MainContent/components/StyledCalendarButton.js, packages/lib-user/src/components/shared/MainContent/components/StyledTab.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js, packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js, packages/lib-user/src/components/shared/Select/Select.js, packages/lib-user/src/translations/en.json
lib-user
Builds on top of https://github.com/zooniverse/front-end-monorepo/pull/6559
Setup react-i18next for the MainContent components
The expected text should display for the above components when lib-user is run locally, in Storybook, or as app-root pages.
- Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other- …
=> lib-user: Setup react-i18next for MainContent components

packages/lib-user/src/components/shared/Layout/components/HeaderDropdown.js, packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/MainContent.spec.js, packages/lib-user/src/components/shared/MainContent/components/StyledCalendarButton.js, packages/lib-user/src/components/shared/MainContent/components/StyledTab.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js, packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js, packages/lib-user/src/components/shared/Select/Select.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.js, packages/lib-user/src/translations/en.json
lib-user
Builds on top of https://github.com/zooniverse/front-end-monorepo/pull/6558
Setup react-i18next for HeaderDropdown, ProfileHeader, and TopProjects components
The expected text should display for the above components when lib-user is run locally, in Storybook, or as app-root pages.
- Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifi …
=> lib-user: Setup react-i18next for HeaderDropdown, ProfileHeader, and TopProjects

packages/lib-user/src/components/UserStats/UserStats.js, packages/lib-user/src/components/shared/BarChart/BarChart.js, packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.js, packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.spec.js, packages/lib-user/src/components/shared/GroupContainer/GroupContainer.js, packages/lib-user/src/components/shared/GroupContainer/components/DeactivatedGroup.js, packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.js, packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.spec.js, packages/lib-user/src/components/shared/GroupForm/GroupForm.js, packages/lib-user/src/components/shared/Layout/components/HeaderDropdown.js, packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/MainContent.spec.js, packages/lib-user/src/components/shared/MainContent/components/StyledCalendarButton.js, packages/lib-user/src/components/shared/MainContent/components/StyledTab.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js, packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js, packages/lib-user/src/components/shared/Select/Select.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.js, packages/lib-user/src/translations/en.json
lib-user
This builds on top of https://github.com/zooniverse/front-end-monorepo/pull/6556
Setup react-i18next for BarChart and GroupContainer components
The expected text should display for the BarChart and GroupContainer components when lib-user is run locally, in Storybook, or as app-root pages.
- Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/ …
=> lib-user: Setup react-i18next for BarChart and GroupContainer

packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js, packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabs.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js, packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js, packages/lib-user/src/components/UserHome/components/SubjectCard/SubjectCard.js, packages/lib-user/src/components/UserStats/UserStats.js, packages/lib-user/src/components/shared/BarChart/BarChart.js, packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.js, packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.spec.js, packages/lib-user/src/components/shared/GroupContainer/GroupContainer.js, packages/lib-user/src/components/shared/GroupContainer/components/DeactivatedGroup.js, packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.js, packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.spec.js, packages/lib-user/src/components/shared/GroupForm/GroupForm.js, packages/lib-user/src/components/shared/Layout/components/HeaderDropdown.js, packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/MainContent.spec.js, packages/lib-user/src/components/shared/MainContent/components/StyledCalendarButton.js, packages/lib-user/src/components/shared/MainContent/components/StyledTab.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js, packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js, packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js, packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js, packages/lib-user/src/components/shared/Select/Select.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.js, packages/lib-user/src/translations/en.json
lib-user
Builds on top of https://github.com/zooniverse/front-end-monorepo/pull/6555
Setup react-i18next for UserHome components
The expected text should display for UserHome components when lib-user is run locally, in Storybook, or as app-root pages.
- Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetut …
=> lib-user: Setup react-i18next for UserHome components

packages/lib-user/package.json, packages/lib-user/src/components/shared/GroupForm/GroupForm.spec.js, yarn.lock
~~There's a lib-user unit test for GroupForm fails regularly with a timeout in Github Actions. I think that behavior originated from this dependency bump, so this PR is for testing.~~
It must of just been a coincidence that `uuid` is used in lib-user and that's when the GroupFrom test started timing out. Adding `this.timeout(0)` in the unit test solved it instead. We use this technique a few other places in FEM.
=> Adjust timeout of GroupForm's unit test

packages/lib-user/src/components/shared/GroupForm/GroupForm.js, packages/lib-user/src/components/shared/GroupForm/GroupForm.spec.js, packages/lib-user/src/components/shared/MainContent/MainContent.js, packages/lib-user/src/components/shared/MainContent/MainContent.spec.js, packages/lib-user/src/components/shared/Select/Select.js, packages/lib-user/src/translations/en.json
- fix: 'Selected: [object Object]' in the labels for user dropdown menus.
- add plain English labels for the project and date range menus.
- fix: understandable labels for the group stats visibility menu.
- lib-user
- towards #6322.
- fixes #6603.
The dropdown menus on the user stats page should have accessible names now, including the selected option.
The group stats visibility menu should also have a plain English name, reflecting the selected option, in the tests and in the storybook. …
=> fix(a11y): user select menu labels

packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js
- noted in point 2 of this comment - https://github.com/zooniverse/front-end-monorepo/pull/6615#issuecomment-2603016534
- the Spyfish Aotearoa survey task characteristic values (filters) include some with images and some without
- when the workflow step store validated the (survey) task, the missing image values cause an error in staging or in dev mode that prevent the classifier from loading, but not in production 
- add `types.maybe` to CharacteristicValue model, image property
- lib-classifier: https://local.zooniverse.org:8080/?project=14054&workflow=23920&env=production
- app-project:  https://local.zooniverse.org:3000/projects/victorav/spyfish-aot …
=> lib-classifier: Refactor survey task CharacteristicValue image type

packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/shared/StyledContainers.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js, packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js, packages/lib-classifier/src/stories/components/MockTask/MockTask.js
- layout issue noted during review of #6494 
- fix MaxWidth with survey task and NoMaxWidth with survey task stories
- refactor MockTask component to reflect lib-react-components Tabs styling
- refactor Choices grid columns to reflect grid gap (if applicable)
- refactor Chooser spacing
- refactor CenteredLayout similar to MaxWidth and NoMaxWidth to handle small, medium, and large screen sizes, with different break points for survey task and other tasks
- with layout issues:
- ⚠️ live project - https://fe-project-branch.preview.zooniverse.org/projects/elwest/woodpecker-cavity-cam/classify/workflow/16997
- with fix: 
- ⚠️ live project - local …
=> lib-classifier: Refactor CenteredLayout and survey task spacing

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js, packages/app-project/src/screens/ClassifyPage/components/YourProjectStats/useYourProjectStats.js
- app-project
- closes #6588.
- a description of the stuck counters on Daily Minor Planet: https://www.zooniverse.org/talk/17/3531984?comment=5819128
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3599?env=staging
You should see your stats increment instantly after each classification, but the fetched stats aren't revalidated (there won't be any HTTP requests to `eras.zooniverse.org`.) This should decrease the load on the ERAS service when lots of classifications are coming into Panoptes. It should remove any errors in the counts when the ERAS API fails eg. the stuck counters that `mutabilitie` has reported on Talk.
_PR Creator - Please cater …
=> refactor(app-project): optimistic updates for YourProjectStats

packages/lib-react-components/src/ZooFooter/ZooFooter.js, packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
Slack: https://zooniverse.slack.com/archives/C4RJRAGKA/p1738087706161429?thread_ts=1737988588.679469&cid=C4RJRAGKA
Corresponds to: https://github.com/zooniverse/Panoptes-Front-End/pull/7254
- Add a SocialAnchor for bluesky to ZooFooter
- Run lib-react-components locally and see the new icon in ZooFooter.
=> Add bluesky icon to ZooFooter

packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
Affects: `<SelectCollection />`
This PR updates the SelectCollection component's collectionNameFilter() and collectionLabel() functions to be more robust, with respect to unexpected data.
This issue was brought in Dependabot PR #6667 , where a seemingly innocent bump from Grommet 2.41.0 to 2.45.1 caused the `CollectionModal` components to suddenly fail. The issue can be traced to SelectCollection's collectionLabel() not receiving its 'collection' data in a proper format - the function's a bit brittle in that sense.
⚠️ HOWEVER, I'm not sure why Grommet 2.45.1 (or its predecessors) suddenly caused the tests to fail. Something's changing the parameters of how `<SelectCollection>` is rendered... or something. I'm going to run some manual Storybook before/after …
=> SelectCollection: make collectionNameFilter() and collectionLabel() more robust

.github/workflows/coverage.yml, packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js, packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js, packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.js
- Remove `defaultProps` from functional components.
- Refactor transcription lines to use translation and scale transforms for the line handles.
- Style drag handles and point marks with `non-scaling-size`.
- Fixes a small issue, introduced by #6066, where drag handles aren't rendered in the correct proportion with respect to marks.
Here are screenshots of the sizing issue:
Main branch (drag handles are too small):
This branch (drag handles are correctly proportioned):
Test cases in the dev classifier:
- point, line, and rectangle tools on a relatively small image: https://localhost:8080/?project=908&workflow=3370
- transcription lines on a relatively large image: https://localhost:8080/?project=mainehistory/beyond-borders-transcribing-historic-maine-land-documents&env=production
_Please …
=> refactor(drawing-tools): drag handle sizing

packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js, packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.js
[`vector-effect: non-scaling-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/vector-effect) isn't implemented in browsers, so this reverts it back to `non-scaling-stroke` in drag handles, point marks, and transcription lines.
Test cases in the dev classifier:
- point, line, and rectangle tools on a relatively small image: https://localhost:8080/?project=908&workflow=3370
- transcription lines on a relatively large image: https://localhost:8080/?project=mainehistory/beyond-borders-transcribing-historic-maine-land-documents&env=production
This PR shouldn't change how drawn marks are rendered at all. Points and drag handles should remain the same size and width, regardless of image zoom level.
Here's a quick codepen which draws two identical SVG circles, one with 'non-scaling-stroke' …
=> refactor(drawing-tools): revert non-scaling-size

packages/lib-subject-viewers/src/VolumetricViewer/helpers/AlgorithmAStar.js
Add a max limit to how many points are checked to connect to prevent extremely large marks from being created
- All tests should pass
- Load up the `lib-subject-viewers` storybook, choose the 64x64x64 cube, and click on a neutral grey spot. Notice how it doesn't highlight a significant chunk of the whole cube but rather makes a nice-sized mark instead.
=> VV Mark Creation has max number of points per click/action

packages/lib-react-components/src/AuthModal/components/RegisterForm/RegisterFormContainer.js
Fixes #6715 
Package: `lib-react-components`, but has downstream effects on `app-root` and possibly `app-project`
This PR fixes an issue where, if you try to Register a New User on the Zooniverse home page, then an error message appears and the Register modal doesn't close, _even though you've successfully created a new user account and signed in(!)._
- The error...
- ...occurs in lib-react-component's RegisterFormContainer's onSubmit()
- ...triggers when the onSignIn parameter isn't defined. (As is the case with app-project's PageHeader's AuthModal and lib-content's Introduction's AuthModal)
- The fix is to simply add a default handler to onSignIn, so it doesn't trigger an existential failure if it's undefined. (i.e. "onSignIn isn't a function" error.) 
Note:
- app-project's PageHeader's …
=> RegisterFormContainer: add DEFAULT_HANDLER for onSignIn

packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/DeleteButton.js
Fix the survey task delete button label, which currently reads "SurveyTask.DeleteButton.delete".
lib-classifier/plugins/tasks/survey
Check the delete button label for a selected choice in the survey task.
- Can be used from …
=> fix(classifier): Survey task delete button label

packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/VolumetricLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/VolumetricLayout.stories.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/index.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/index.js, packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js, packages/lib-subject-viewers/src/VolumetricViewer/components/ComponentViewer.js
Created a new Layout that is focused on the Volumetric Viewer. The motivation being that because the viewer is new and the design ideas are relatively unique, having a separate Layout makes it easier to manage the changes that are unique to this new Viewer. In specific, this new Layout does not include the ImageToolbar because panning, rotating, and selecting tools are incorporated within both the volumetric and planar views respectively.. Which means there is no need for a global ImageToolbar of actions.
While this is a new Viewer, there are plenty of design decisions yet to be made. There are larger questions of what should happen at different breakpoints for content in combination with other page elements (specifically, Banners and related whitespace / spacing).
- Run …
=> Create Volumetric Layout

packages/lib-user/src/hooks/usePanoptesProjects.js, packages/lib-user/src/hooks/usePanoptesUserGroup.js, packages/lib-user/src/hooks/useStats.js
- lib-user
- public user group like https://www.zooniverse.org/groups/2620016 should be visible for a signed out user
- small changes from #6345 , I don't think this re-introduces any related bugs, but worth double-checking
- remove conditional check for token before defining swr keys (usePanoptesUserGroup, useStats, and usePanoptesProjects), allowing key to be defined for signed out (token = `null`) user, and then request made for user group and related stats and projects
- staging public user group: https://local.zooniverse.org:3000/groups/1326989?env=staging
- production public user group: …
=> lib-user: Refactor usePanoptesUserGroup for signed-out user access to public group

packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/team.js
- app-project
In the Teams page, check the project's `experimental_tools` attribute for a volumetric project, and if so, limit to showing just the project owner
- Run `app-project` locally and then check a [Volumetric Project](https://local.zooniverse.org:3000/projects/cmcbrain/axonal-pathfinders/about/team?env=production&demo=true) to see its only showing the CMCBrain user and compare to [Daily Minor Planet](https://local.zooniverse.org:3000/projects/fulsdavid/the-daily-minor-planet/about/team?env=production&demo=true) having its full team. 
=> Filter Volumetric Project Research Team to only show the Project Owner.

packages/lib-classifier/package.json, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, yarn.lock
- In `VisXZoom`, listen for wheel events from the subject components (including the drawing canvas.)
- Explicitly set `passive: false` to allow `event.preventDefault()` in the wheel event listener (to turn off window scrolling.)
- Add the `move` prop so that we can enable/disable wheel zoom according to whether 'pan' is selected in the subject toolbar.
- Tune the wheel zoom parameters for a smoother zooming UX.
- Require the ~~Shift~~ Ctrl key for wheel zoom.
- Add an `allowsScrolling` prop. Disabling window scroll is the default behaviour for JSON data viewers with `VisXZoom`. When `allowsScrolling` is enabled, the mouse wheel scrolls the window by default, and zooms with the ~~Shift~~ Ctrl modifier key.
- a maintenance refactor: upgrade `VisXZoom` to use the [render props …
=> fix(classifier): ctrl to zoom images and wheel zoom for drawn marks

packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
- Fix the `SingleImageViewer` title, which was being rendered outside the SVG.
- Fix the tests to catch missing titles.
- Add a default title for single image subjects.
Single image subjects should now be properly labelled in the accessibility tree. You should be able to check their accessible name in the storybook, with either Chrome or Firefox.
- Can be used with a …
=> fix(a11y): single image viewer title

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
Add smoke tests for the ImageToolbar stories and fix a broken import.
- fixes #6762
Open the Image Toolbar stories in the classifier storybook.
I've added failing smoke tests for those stories, so this PR should be OK to merge once CI tests are passing again.
=> fix(storybook): fix classifier Image Toolbar stories

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
- closes #6778 
- reverts refactor to use the render props pattern in SingleImageViewer and VisXZoom per #6757 back to component props
- the render props pattern is preferable to the component props pattern, so further investigation and refactoring is warranted, but for now, these changes fix a bug where the drawing mark subtask was opening when toggling between annotate and move modes
- staging/testing
- lib-classifier: https://local.zooniverse.org:8080/?project=1693&workflow=3838
- app-project: https://local.zooniverse.org:3000/projects/markb-panoptes/test-project-1-mb-fem-lab/classify/workflow/3838?env=staging&demo=true
- ⚠️  production ⚠️ 
- …
=> lib-classifier: Refactor SingleImageViewer and VisXZoom back to component props

packages/lib-subject-viewers/package.json, yarn.lock
Conversation started from Slack and a [dependency bump](https://github.com/zooniverse/front-end-monorepo/pull/6737) for an unused package. This cleans up the two no-longer-used packages that were used when the VolumetricViewer was under more intensive development.
- Tests pass
=> Remove unused dependencies from VV.

packages/lib-classifier/src/components/Classifier/components/shared/StepNavigation/StepNavigation.js
Closes #6798 
This PR provides a _rudimentary fix_ for the Tutorial system's StepNavigation, to prevent the Tutorial UI from completely breaking when a tutorial has too many steps.
Before this patch:
After this patch:
<details>
<summary>(Previous solution:)</summary>
This solution was replaced [after this comment.](https://github.com/zooniverse/front-end-monorepo/pull/6799#issuecomment-2758633484)
</details>
=> Tutorial: fix navigation breaking when too many steps

packages/lib-subject-viewers/src/VolumetricViewer/helpers/pointColor.js, packages/lib-subject-viewers/src/VolumetricViewer/tests/pointColor.spec.js
Fix color looping bug wherein creating a new mark with an annotationIndex greater than the number of colors generated should loop to the 1st color instead of erroring.
Load up the `lib-subject-viewers` storybook on production and this branch. Use "shift+click" to create at least 12 different marks on the 4x4x4 Story (any story works, this is the simplest example). This will fail in production and start re-looping through the colors.
=> VV: fix bug that limits the max number of marks.

packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
Implement the [ARIA Accordion Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/) for the Plane View of the Volumetric Viewer
- Running Storybook locally with the Volumetric Viewer, click anywhere on the header to expand/collapse the planar view. - Using the keyboard, test that the three required keyboard interactions work as expected from the ARIA Accordion Pattern page (enter, space, tab, shift+tab). 
- The whole header should be highlighted when its element is focused through keyboard navigation.
=> Implement ARIA recommendation for the Accordion pattern for the VV Planes view

packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
When the Histogram controls are narrowed, all marks should remain visible regardless of if the underlying color has been removed from the histogram in the Plane view
Load up the Volumetric Viewer in the `lib-subject-viewer` Storybook. Annotate any voxel and then use the sliders for the histogram to hide voxels that are too dark / too light. It's possible to slide one slider all the way over to the other slider, making only marks visible (good for testing purposes). Before this change, marks would disappear in the Plane view.
=> Fix bug where the VV planar view wouldn't show an annotation if the histogram had removed its underlying color's voxel

packages/lib-classifier/src/plugins/tasks/experimental/volumetric/README.md, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js, packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js, packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
- lib-subject-viewer
Update the submitted classification that gets uploaded to Panoptes to match the Freehand Line method of having all points formatted as `{ x, y, z }`. 
Load up the classifier locally with a [test volumetric project](https://localhost:8080/?project=kieftrav/volumetric-viewer&env=staging), create a mark, submit classification, and inspect the `console.log()` of the classification export. The  format should be as follows:
```js
{
points: {
active: [{ x, y, z}],
all: [{ x, y, z}],
connected: [
[{ x, y, z}],
],
}
}
```
=> Update VV classification export to match the FreehandLine tool

packages/lib-classifier/src/plugins/tasks/experimental/volumetric/README.md, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js, packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.spec.js, packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js, packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js, packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
Update the annotation export so that it only has the `connected` and `active` points and removes `all`. Follow on from #6802 
Load up the classifier locally with a [test volumetric project](https://localhost:8080/?project=kieftrav/volumetric-viewer&env=staging), create a mark, submit classification, and inspect the `console.log()` of the classification export. The  format should be as follows:
```js
{
points: {
active: [{ x, y, z}],
connected: [
[{ x, y, z}],
],
}
}
```
=> Update the VV annotation to only send active and connected points.

packages/app-root/src/app/groups/[groupId]/projects/GroupAllProjectsContainer.js, packages/app-root/src/app/groups/[groupId]/projects/page.js, packages/lib-user/dev/components/App/App.js, packages/lib-user/src/components/GroupAllProjects/GroupAllProjects.js, packages/lib-user/src/components/GroupAllProjects/GroupAllProjectsContainer.js, packages/lib-user/src/components/GroupAllProjects/index.js, packages/lib-user/src/components/index.js, packages/lib-user/src/components/shared/AllProjects/AllProjects.js, packages/lib-user/src/components/shared/AllProjects/AllProjects.stories.js, packages/lib-user/src/components/shared/AllProjects/index.js, packages/lib-user/src/components/shared/index.js, packages/lib-user/src/index.js, packages/lib-user/src/translations/en.json
app-root
lib-user
Toward: https://github.com/zooniverse/front-end-monorepo/issues/6690
[Figma](https://www.figma.com/design/qbqbmR3t5XV6eKcpuRj7mG/Group-Stats?node-id=412-9650)
This is one of multiple PRs needed to create the All Projects pages for individual users and user groups. There will be other PRs branched from this one to handle All Projects from UserHome and UserStats. In this PR:
- Created a simple shared AllProjects component. It simply displays an array of `projects` with ProjectCard.
- Created a route for https://www.zooniverse.org/groups/[groupId]/projects
- Created a page component in lib-user called GroupAllProjects using the existing containers for other group pages, common hooks, layout, etc.
- There will eventually be a link in the Top Projects section of a group page, …
=> Create an All Projects page for user groups

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
- closes #6821 
- check if user is using CTRL + scroll and if they are, then don't call `onFirstScroll` callback to show CTRL + scroll message
- if user's first scroll is with CTRL + scroll, then set `hasScrolledRef` to `true` to prevent CTRL + scroll message from showing on subsequent scrolls
- any with an image, like https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/classify/workflow/693
1. put classifier in pan/zoom mode
2. press CTRL + zoom
3. note **no** "Use CTRL + zoom..." message shows
4. zoom without CTRL
5. also note **no** "Use CTRL + zoom..." message shows
- …
=> lib-classifier: Refactor VisXZoom onFirstScroll and hasScrolledRef per initial CTRL + scroll event

packages/lib-content/src/screens/About/About.js, packages/lib-content/src/screens/OurTeam/OurTeam.js, packages/lib-content/src/screens/OurTeam/OurTeam.spec.js, packages/lib-content/src/screens/Publications/Publications.js, packages/lib-content/src/screens/Publications/Publications.spec.js
lib-content
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6053
Run app-root locally and visit
- https://local.zooniverse.org:3000/about/publications
- https://local.zooniverse.org:3000/about/teams
The sidebar aria-label should be translated correctly.
- Can be used from the keyboard [WebAIM guide to …
=> lib-content: Fix aria-label in Sidebar in OurTeam and Publications

packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js, packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js, packages/lib-user/src/components/shared/ContentBox/ContentBox.js, packages/lib-user/src/components/shared/ContentBox/components/ContentHeading.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.js, packages/lib-user/src/translations/en.json
- lib-user
- closes #6380 
- closes #6316 
- add `tabIndex={0}` to horizontally scrollable lists
- add a11y name, with `aria-labelledby` or `a11yTitle`, to lists
- add scroll-snap styling to lists
- user's homepage:
- lib-user: https://local.zooniverse.org:8080/
- app-root: https://local.zooniverse.org:3000/
- tab to list, use arrow keys to scroll left/right
- note scrolling snaps so list item is centered
- RecentProjects: http://localhost:6008/?path=/story/components-userhome-recentprojects--default
- RecentSubjects: …
=> lib-user: Refactor lists with a11y name, tabindex, and scroll-snap

package.json, packages/app-root/next.config.mjs, packages/lib-panoptes-js/package.json, yarn.lock
- Fixes a security warning with superagent versions < 9.
- Bumps `@zooniverse/panoptes-js` to 0.5.2.
- Overrides transitive dependencies on superagent 8 via `panoptes-client`.
- lib-panoptes-js
- app-root
- app-project
- closes #6824.
Run production builds of the root app and the project app. Nothing has changed in terms of functionality, and there shouldn't be any breaking changes in either API client. The breaking change in superagent 9 was dropping support for Node < 14.18.
Example …
=> build(deps): bump superagent from v8 to v10

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js, packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js, packages/lib-classifier/src/plugins/drawingTools/shared/SVGContext.js
Add the `VisXZoom` transform matrix to `SVGContext`, so that we can use it directly in `LineControls` and avoid the controls jumping when the DOM changes.
- lib-classifier/plugins/drawingTools
- follow-up to #6811. 
- fixes #6818.
Same as #6811. You should notice little or no flickering of the line controls when panning and zooming on this branch.
https://github.com/user-attachments/assets/43c2d917-d310-48c6-bbcf-c759a36c6750 …
=> refactor(lib-classifier): clean up LineControls matrix calculations

packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js, packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.stories.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
lib-classifier
Closes: https://github.com/zooniverse/front-end-monorepo/issues/6061
- Use a Grid for the subject viewer layout instead of a flexbox
- There are screenshots of Squirrel Mapper in the linked Issue, but Active Asteroids and Daily Minor Planet are good projects to test too
=> lib-classifier: Use a Grid for subject viewer container in CenteredLayout

packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.js, packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js, packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js, packages/lib-user/src/components/shared/TopProjects/TopProjects.js
- lib-user
- closes #6847 
- edits `scroll-snap-align` from `center` to `start`, this keeps the left-most card completely visible as a user scrolls
- there might be a case for `center` (keep center-most card center aligned within parent container) or `end` (keep right-most card visible), but after the discussion in the linked issue and testing locally - I think `start` is the preferable option, or my non-technical take is that it is the option that "looks most correct" compared to the other options, especially visually within the larger layout/page whose other horizontal lists will be initially showing the left-most card fully
- user's homepage:
- lib-user: …
=> lib-user: Refactor horizontal lists scroll-snap-align to start

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.stories.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/shared/ComponentDecorator.js, packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js, packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
- closes #6779 
- iteration on #5994 
- add a disabled state to Annotate button
- refactor WorkflowStepStore with `hasActiveAnnotateTask` for annotate task in active step
- refactor SubjectViewerStore to enable annotate or move per `hasActiveAnnotateTask`
- refactor ImageToolbar Button pressed (not) hover styling, see https://github.com/zooniverse/front-end-monorepo/issues/6779#issuecomment-2768686700
- lib-classifier:
- staging test project: https://local.zooniverse.org:8080/?project=335
- ⚠️ production project ⚠️ : https://local.zooniverse.org:8080/?project=22977&env=production&workflow=25770
- app-project:
- staging test project: …
=> lib-classifier: Refactor ImageToolbar buttons Annotate and Move per active step annotate task

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/isInBounds.js, packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js, packages/lib-classifier/src/plugins/drawingTools/hooks/useScale.js
Update `useScale` to check if the `canvas` DOM node exists before calculating the subject image scale on the screen.
Update `isInBounds` to also catch the case where `svgContext.canvas` is undefined or null.
Fix `canvasRef` in `SingleImageCanvas` so that it reports the correct dimensions for the subject image, in Firefox.
Remove the `canvasRef` hack from `InteractionLayer`, now that `SingleImageCanvas` is fixed.
- fixes #6881
Should be the same as #6882.
You'll want to check that this hasn't regressed #6490, so be sure to check in Firefox, with the subject zoomed in. Remember to test with a rotated image too, to make sure that rotation transforms are still correctly accounted …
=> fix(lib-classifier): screen scale calculations for SVG subject images

packages/lib-react-components/src/Media/components/Audio/Audio.spec.js
Converted tests from Enzyme to RTL. No changes other than to test file.
=> Convert Audio tests from Enzyme to RTL

packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
Closes: #6907 
Related: zooniverse/Panoptes-Front-End#7313
This PR fixes an issue where Bluesky links were going to the wrong URLs, i.e. the Bluesky links should go to bsky.app/PROFILE/accountname, not bsky.app/accountname
Changes made:
- formatUrlObject now _dynamically constructs_ Bluesky links, instead of relying on the pre-built URL in projectResource.urls[x].url
- Edit a test project _on PFE PR 7313_ , e.g. https://pr-7313.pfe-preview.zooniverse.org/lab/1982?env=staging
- Go to Project Details, Social Links section.
- Add/edit a Bluesky external link, e.g. add the zooniverse.bsky.social account
- Also check that the SocialLinkEditor editor visually makes sense by showing the subpath.
- Add/edit a non-Bluesky external link, e.g. add therealzooniverse account to …
=> ProjectLink: fix Bluesky external links

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js, packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Fix a bug where zoom in/out becomes stuck at either maximum or minimum zoom after `pointerup` by remembering to clear the current timer when the pointer is released.
- closes #6921.
- reverts a change from #5050.
- Talk: [infinite zoom in FEM still happens](https://www.zooniverse.org/talk/17/3683475?comment=6051429&page=1).
Zoom in or out, but release the pointer while off the pressed button. This fires the `pointerup` handler, but not the `click` handler.
https://github.com/user-attachments/assets/0b9b159e-b80a-4ace-a75e-de04b1302017 …
=> fix(classifier): infinite zoom bug

.github/workflows/deploy_storybook.yml
Inspired by today's deploy build [failing](https://github.com/zooniverse/front-end-monorepo/actions/runs/16198155248). After investigation of a nondescript error `failure to build fe-project`, I remembered something like this happened when I first created the `lib-subject-viewers` package and added it to our deploy process. 
The solution ended up needing to build the `lib-classifier` as part of the yaml file. I believe this has to do with the fixed `VolumetricViewer.stories.js` that was part of this week's deploy and its asynchronous import of `lib-subject-viewers`... i.e. Storybook can't build+deploy properly without its underlying packages building the importable dependencies (i.e …
=> Add Classifier build to Storybook deploy pipeline

packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js, packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
https://github.com/zooniverse/front-end-monorepo/issues/6093
Added a `max-height: 80vh;` to the tutorial containing div. This leaves the tutorial unaffected on desktop while accommodating the mobile experience. I tried to use the new unit of 'dvh' but that did not work for mobile safari on my device. The downside (which I consider negligible to the existing non-functionality) is that on other mobile browsers there is extra/dead space below the tutorial navigation.
Load up `app-project` locally, find your computer's local IP address in the WiFi settings, and then load up the Woodpecker Cavity Cam project main page on your iOS device. From there, you can select a workflow and view the changes to the tutorial (helps testing in a private tab). 
Example URL (please update with your machine's …
=> Fix issue with mobile scrolling for tutorial popup on safari.

packages/app-project/package.json, packages/app-root/package.json, packages/lib-classifier/package.json, packages/lib-subject-viewers/package.json, packages/lib-user/package.json, yarn.lock
Several, but most importantly lib-classifier
- I published a new version of `@zooniverse/async-states` today (v0.1.0) after converting its tests to Vitest
- While Mark and I were manually testing frontend.preview for deployment, I noticed that the subject queue wasn’t advancing after a completed classification.
- Advancing the next subject listens for `asyncStates.posting`. This is the only code in FEM (and probably all of Zooniverse) that looks for the value `.posting`.
- Turns out, since I did not tell FEM’s packages to bump to `@zooniverse/async-states` v0.1.0, they were still using v0.0.1, which should have been fine, but [v0.0.1](https://www.npmjs.com/package/@zooniverse/async-states/v/0.0.1) doesn’t have `.posting`. It has only four: `initialized, loading, success, error` 🤦🏼‍♀️ The …
=> Use async-states v0.1.0 in all packages

packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.jsx, packages/lib-classifier/src/plugins/drawingTools/models/marks/RotateRectangle/RotateRectangle.js
Affects: Drawing Task -> RotateRectangle drawing tool
Closes #7052 
This PR changes how the RotateRectangle marks behaves, when a user resizes it by moving/dragging one of its four corners (drag handles).
Say we have a rectangle mark, with four corners ABCD, and origin/centre-coordinate O:
```
A-------B
|       |
|   O   |
|       |
D-------C
```
New behaviour:
- RotateRectangle: when resizing by dragging a corner, the action is _anchored_ to the _opposite corner._
- So if we drag C ↘️, A will remain static, B will move ➡ and D will move ⬇️. O will move ↘️ too, by half the distance that C moves.
- This is basically the same as how the standard Rectangle drawing tool works, except that it _respects the rotation_ of the RotateRectangle.
- **Important: the annotation …
=> RotateRectangle: new resize behaviour

packages/lib-classifier/src/store/ClassificationStore.js, packages/lib-classifier/src/store/subjects/SubjectGroup/README.md
- Milestone [#31](https://github.com/zooniverse/front-end-monorepo/milestone/31)
- Closes Issue #6903 
- Related PR's: [#6979](https://github.com/zooniverse/front-end-monorepo/pull/6979), [#7357](https://github.com/zooniverse/Panoptes-Front-End/pull/7357), and [#7050](https://github.com/zooniverse/front-end-monorepo/pull/7050)
Does a check before submitting the Classification JSON to see if the active workflow's `subject_viewer` is a `subjectGroup`, and if so, adds all the `subject.subjectIds` to the `classification.links.subjects` array.
Load up the lib-classifier locally and open [this project](https://localhost:8080/?project=darkeshard%2Fsurvos-testing-2020-subject-group-viewer&workflow=3412) to have a test SubjectGroup workflow. Click the Done button to submit a classification, …
=> SGV 1: Submit subject.subjectIds when submitting a classification for a subjectGroup
