zooniverse/front-end-monorepo

packages/lib-panoptes-js/src/index.js

What the description says. Adds the project mocks from the client to the library's exports so it's available for test writing in apps.

Add project mocks to lib export

---

packages/lib-panoptes-js/package-lock.json
packages/lib-panoptes-js/package.json
packages/lib-panoptes-js/src/config.js
packages/lib-panoptes-js/src/config.spec.js
packages/lib-panoptes-js/src/panoptes.js
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/projects/projects.spec.js
packages/lib-panoptes-js/test/mocha.opts

Closes #28. This adds default query params for `http_cache` which the current client has defined and I believe is for the db read replica. Also adds check and param for `admin` which is currently in PFE's code base, but it makes sense to move into the client itself.

Add default query parameters

---

packages/lib-panoptes-js/src/resources/projects/helpers.js

Package: panoptes-js
Removes cruft accidentally left in the project helpers file.

Remove cruft accidentally left in project helpers file

---

packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/README.md
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/index.js
packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
packages/lib-classifier/src/components/Classifier/components/Layout/Layout.spec.js
packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.spec.js
packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/index.js
packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.js
packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.spec.js
packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/index.js
packages/lib-classifier/src/components/Classifier/components/Layout/index.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.spec.js
packages/lib-classifier/src/helpers/layouts/index.js
packages/lib-classifier/src/helpers/layouts/layouts.js
packages/lib-classifier/src/helpers/layouts/layouts.spec.js
packages/lib-classifier/src/store/ClassifierStore.js
packages/lib-classifier/src/store/ClassifierStore.spec.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/RootStore.spec.js

Adds a default layout for the clasifier UI. Requires #80 merging first.
Originally in #74

Add layouts

---

packages/lib-panoptes-js/.travis.yml
packages/lib-panoptes-js/docs/tutorials.md
packages/lib-panoptes-js/src/index.js
packages/lib-panoptes-js/src/resources/media/mocks.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/projects/index.js
packages/lib-panoptes-js/src/resources/projects/rest.spec.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/tutorials/helpers.js
packages/lib-panoptes-js/src/resources/tutorials/index.js
packages/lib-panoptes-js/src/resources/tutorials/mocks.js
packages/lib-panoptes-js/src/resources/tutorials/rest.js
packages/lib-panoptes-js/src/resources/tutorials/rest.spec.js
packages/lib-panoptes-js/src/utilityFunctions/index.js

Closes #63.
This adds the helper functions for `GET` requests for the tutorial resource.
I also snuck in a fix for the exports for the projects resource helpers too.

Panoptes.js: Tutorials resource

---

packages/lib-grommet-theme/src/dark.js
packages/lib-grommet-theme/src/index.js
packages/lib-grommet-theme/src/light.js

Closes #24 and #25.
This adds a light and dark js file with the defined colors that are unique to those themes. Also adds a few more colors available to the global set. Right now the light and dark theme files are just color variants, not really full fledged themes on their own so they are added to the deep freezed object with the global constants. I removed the `Headings.js` file because it was blank.

Light and dark themes

---

packages/lib-classifier/package.json

Package: **Classifier**
This fixes a small issue in the Classifier package, where the main entry point in `package.json` didn't match where the file was.
`package.json` specifies that `package.main` is `dist/index.js`, but the `npm run build` command (see webpack.dist.js) compiles to `dist/main.js` instead.
n/a
n/a

Fix main entry point in Classifier's package.json

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js

A few fixes and additional tests for #82. Renamed `adjustments` prop to `svgAdjustments` to make it clear what it is for.
We should consider the styled-components test util or the one from storybook to tests the variable styles depending on props in the `Button` component, but I don't know how to either of those options yet, so it'll have to come in a follow up PR.

Add buttons review

---

packages/lib-panoptes-js/docs/README.md
packages/lib-panoptes-js/docs/subjects.md
packages/lib-panoptes-js/src/index.js
packages/lib-panoptes-js/src/resources/projects/helpers.spec.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/subjects/helpers.js
packages/lib-panoptes-js/src/resources/subjects/helpers.spec.js
packages/lib-panoptes-js/src/resources/subjects/index.js
packages/lib-panoptes-js/src/resources/subjects/mocks.js
packages/lib-panoptes-js/src/resources/subjects/rest.js
packages/lib-panoptes-js/src/resources/subjects/rest.spec.js

Closes #64.
Adds subjects resource request helpers for HTTP GET requests. The others can be filled out when needed since they're only used by the lab.
~WIP because I still need to write docs.~ Docs are updated.

Panoptes.js Subjects requests

---

packages/lib-panoptes-js/docs/README.md
packages/lib-panoptes-js/docs/projects.md
packages/lib-panoptes-js/docs/subjects.md
packages/lib-panoptes-js/docs/tutorials.md
packages/lib-panoptes-js/src/panoptes.js
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/projects/rest.js
packages/lib-panoptes-js/src/resources/projects/rest.spec.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/subjects/rest.js
packages/lib-panoptes-js/src/resources/subjects/rest.spec.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/tutorials/rest.js
packages/lib-panoptes-js/src/resources/tutorials/rest.spec.js

Adds an `authentication` parameter to the various requests in anticipation of the auth clients. When defined, it'll add the `Authentication` header. I also fixed the projects' common requests helpers to be consistent with the other requests' expected parameters so that the API is consistent. 
As always, WIP because docs need updating.

Auth param

---

.dockerignore
Dockerfile
Jenkinsfile
README.md

Package: all
This adds a basic `Jenkinsfile` for running tests. Currently, it's naive - it creates a Docker image, installs the dependencies, then runs tests for all packages. This is because none of these packages have been published yet - once that's set up, we can start using `lerna changed` etc.
TODO:
- Only run tests for changed packages
- Publish changed packages

Add jenkinsfile for tests

---

plop/generators/component.js
plop/plopfile.js

Fixes an error where the entryPoint wasn't being correctly set, and fixes the case of the `index.js` file for new components.

Fix a couple of errors in plop component generator

---

packages/lib-panoptes-js/package-lock.json
packages/lib-panoptes-js/package.json
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/projects/rest.spec.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/subjects/rest.spec.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/tutorials/rest.spec.js
packages/lib-panoptes-js/test/mocha.opts

Package: `panoptes-js`
Closes #88.
Rewrites tests to use `nock` instead of `superagent-mock`, which causes the test runner to hang. Also uses `async / await` instead of promises, and a bit of housekeeping.

Use `nock` instead of `superagent-mock`

---

README.md
docs/troubleshooting-guide.md

This PR adds some documentation to help devs troubleshoot issues with installing and running the Zooniverse Front-End Monorepo. 
The Troubleshooting Guide is intended to be an evolving document to record known instances of - and solutions to - those weird problems that crop up _while the monorepo is still in active development._
The documentation should be made more formalised when the monorepo stabilises, but until then, this should help people figure out what to do when installers, systems, and scripts don't run as they "should".
A big thanks to @rogerhutchings and @srallen for helping me punch through the bizarre nonsense I encountered during my own setup.
This is ready for review.

Add troubleshooting guide for devs

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addInterfaceLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setPointStyle.spec.js

Adds a set of tests (and testing strategy) for D3 helper functions.

Add unit tests for D3 helper functions

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/index.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js

Closes #238 
Ensures a new subject is plotted on the chart, adds a placeholder drawing task for the tasks area.

Fix LCV not loading next subject

---

packages/app-project/components/ClassifyPage/ClassifyPage.js
packages/app-project/components/ClassifyPage/ClassifyPage.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatistics.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatistics.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBar.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBar.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/addBackgroundLayer.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/createBar.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/createLabel.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/MainGrid.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/MainGrid.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/AnimatedNumber.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/AnimatedNumber.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/index.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/locales/en.json
packages/app-project/package.json
packages/app-project/stores/Project.js

Adds the Project Statistics box to the classifier page.
~~requires #232 merging first~~

Add Statistics box to project app

---

README.md
bin/bootstrap.sh
plop/generators/component.js
plop/templates/component/Component.spec.js.hbs
plop/templates/component/Container.spec.js.hbs
plop/templates/component/MSTContainer.js.hbs
plop/templates/component/MSTContainer.spec.js.hbs

Package: all
Closes #269.
Adds a bootstrap script to help get things up and running more smoothly, and updates the `plop` generators to correctly create containers and create MST-connected containers.

Bootstrap script, new component generators

---

packages/lib-classifier/src/store/Workflow.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js
packages/lib-classifier/src/store/WorkflowStore.spec.js

Rewrites the `WorkflowStepStore` tests to work purely in isolation. We'll come up for a proper strategy for functional testing later.

Rewrite WorkflowStepStore tests as pure unit tests

---

packages/lib-auth/dev/components/App/App.js
packages/lib-auth/package-lock.json
packages/lib-auth/package.json
packages/lib-auth/src/controllers/oauth/createOAuthClient.js
packages/lib-auth/src/models/oauth/CredentialsStore.js
packages/lib-auth/src/models/oauth/CredentialsStore.spec.js
packages/lib-auth/src/models/oauth/UserResource.js
packages/lib-auth/src/models/oauth/UserStore.js
packages/lib-auth/webpack.dev.js
packages/lib-auth/webpack.dist.js

Package: lib-auth
Closes #267
This is a continued refactor on the auth lib. This PR includes the following changes:
- Use the `PANOPTES_ENV` environmental variable with the webpack builds if defined otherwise use a default avlue. Add a npm script to build using staging under `build:dev`. Use this script when developing against staging.
- Add the `initialize` function to the public API. This will determine whether to load stored credentials or to grab them from the url and then fetch and return the user. If there are no credentials, just return a promise with null value. I tried to be more clever and use some kind onAction or onSnapshot MST method, but this was really the wrong way to go and I couldn't get it to work quite right with waiting for the user resource …

Auth environment fix and login/logout callback support

---

packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/locales/en.json

Removes an unnecessary ternary in favour of using counterpart's pluralization method.
Thanks to @eatyourgreens for the tip

Use pluralization instead of ternary expression

---

packages/lib-react-components/package-lock.json
packages/lib-react-components/package.json
packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.js
packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.spec.js

This replaces the window size detection code with [`react-resize-detector`](https://github.com/maslianok/react-resize-detector) (see https://github.com/zooniverse/front-end-monorepo/pull/275#discussion_r234658387)

Use react-resize-detector

---

packages/lib-auth/src/controllers/oauth/createOAuthClient.js
packages/lib-auth/src/models/oauth/UserStore.js
packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.js
packages/lib-classifier/src/store/utils/getBearerToken.js
packages/lib-classifier/src/store/utils/index.js

Package: lib-classifier, lib-auth
Closes #288
Refactors the use of the auth lib by the classifier based on the latest refactor. Classifier expects a user prop and when it's falsey, then UPP is cleared.

Clear user project preferences on logout

---

packages/lib-classifier/src/store/Workflow.js

zooniverse/Panoptes#2963 merged which added the steps attribute. It is defaulted to an empty object, but the db type is jsonb, so we should be able to store an array of pairs when a workflow's steps get defined. This is updating the Workflow model so that the classifier loads.

Add support for jsonb default for steps

---

packages/lib-panoptes-js/package-lock.json
packages/lib-panoptes-js/package.json

Move check-engines and check-dependencies to devDependencies

Move check-engines and check-dependencies to devDependencies

---

packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/tasks/Graph2dRangeXTask.js
packages/lib-classifier/src/store/tasks/index.js

Requires #279
Replaces #319 
The goal of this PR is to add a new Workflow Task type called `"graph2dRangeX"` (tm) which is used to denote a selection of "ranges" (x-positions, and widths) of interest on a graph.
- The Task Panel on the Classifier should ideally display the instructions of the Graph Ranges Task when said task is active. (See #309)
In the `workflow` resource, the `"graphRanges"` task would look something like...
```
workflow.tasks =
{
"T1": {
"help": "",
"type": "graph2dRangeX",
"required":false,
"instruction":"Mark a transition."
}
}
```
(Feel free to comment on this structure; I did a straight rip of the `"text"` annotation task. I'm aware that there's some discussion on standardising how these Tasks should be structured, e.g. should it be …

Classifier - TESS Light Curve Viewer - add "graph2dRangeX" Workflow Task type

---

packages/app-project/next.config.js

Modifies webpack config to specify resolution for `styled-components`, fixing the duplicate declaration warning.

Add specific resolution for `styled-components`

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/getClickCoords.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/preventDefaultAction.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setUserAnnotationAttr.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setUserAnnotationAttr.spec.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/annotations/Graph2dRangeXAnnotation.js
packages/lib-classifier/src/store/annotations/Graph2dRangeXAnnotation.spec.js
packages/lib-classifier/src/store/annotations/index.js

~~Requires (and is a sequel to) #279 and #352~~ 👌 (Merged!)
Replaces #309 (309 has gone waaay off base)
Closes #241 
The goal of this PR is to let users add annotations via the LCV
_When in Annotation mode (selected from the Classifier page toolbar), users can click on the light curve to plonk down a "Graph Range"-type annotation (with a fixed width), which indicates the range where a dip in the brightness has been detected_
NOTE: the annotation data should be in the form of: `{ x: number, width: number }`
- `x` marks the centre of a selection range (aka a column) indicating a dip in the light curve.
- `width` marks the total range of the, er, selection range.
NOTE: not covered in this PR -
- ability to edit or remove existing Annotations.
See …

Classifier - TESS Light Curve Viewer - allow adding Annotations (ver 2)

---

plop/templates/component/Component.spec.js.hbs
plop/templates/component/Container.spec.js.hbs
plop/templates/component/MSTContainer.spec.js.hbs

Adds `expect(wrapper).to.be.ok` as the smoke test in plop-generated components.

Add more sensible smoke test to component templates

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Graph2dRangeXTask/Graph2dRangeXTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Graph2dRangeXTask/Graph2dRangeXTask.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Graph2dRangeXTask/index.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Graph2dRangeXTask/locales/en.json
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js
packages/lib-classifier/src/store/tasks/Graph2dRangeXTask.spec.js

This PR adds the Graph2dRangeX task to the Classifier's Task Area.
_The Graph2dRangeX task can be seen on the right side. Yes, that bit of text. That's all._
This task area is currently a very simple copy of the Drawing Task placeholder, which only has space for `instructions`, and nothing more. The Task (in the Task Area) has _no interactive bits._
There is currently no intention to improve this Task any further (save maybe for some styling updates?), at least until we get a design review on the UX.
The Task can be tested on any project workflow with the custom `graph2dRangeX` task. For convenience, try `http://localhost:8080/?project=1862` on staging.

Classifier - TESS Light Curve Viewer - add Graph2dRangeX task (for Task Area)

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js

Parallel to #376
When using the Light Curve subject viewer, if a user attempts to _add Annotations_ while the current workflow task is NOT a `graph2dRangeX` task, the subject viewer mode will automatically switch to Move mode.
This behaviour mimics the current behaviour on the [PFE Classifier component](https://master.pfe-preview.zooniverse.org/dev/classifier) - Annotate mode only matters (to the subject viewer and/or annotation pane) when the current active task is a drawing task.
Based on discussions with @srallen and @eatyourgreens on Slack (`#frontend-rewrite`) on Fri 18 Jan 2019,
- The "current active step" in a Workflow _can have multiple tasks,_ such as with the Notes from Nature combo which features two text inputs and a dropdown menu on the screen for a …

Classifier - TESS Light Curve Viewer - lock Annotate mode to only Graph2dRangeX task

---

packages/lib-auth/package-lock.json

Run a fresh install of all dependencies for lib-auth.
Package: lib-auth
Closes #363.

Rebuild lib-auth package lock

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js

Explicitly specify height and width 100% on the subject image. Fixes a bug where Firefox renders the image with height and width 0.

Add height and width to subject image

---

packages/lib-classifier/package-lock.json
packages/lib-classifier/package.json

Security patch for webpack-dev-server.

Security fix: upgrade webpack-dev-server

---

packages/lib-classifier/package-lock.json
packages/lib-classifier/package.json
packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.spec.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/HeartIcon.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/index.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/locales/en.json
packages/lib-classifier/test/enzyme-setup.js

Adds a functional toggle button for favourites, plus tests.
Towards #397.

Add Favourites toggle button

---

packages/app-project/.babelrc
packages/app-project/components/ClassifyPage/ClassifyPage.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/index.js
packages/app-project/components/ClassifyPage/components/ConnectWithProject/ConnectWithProjectContainer.js
packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.spec.js
packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.spec.js
packages/app-project/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
packages/app-project/package-lock.json
packages/app-project/package.json
packages/app-project/stores/Project.js
packages/app-project/test/mocha.opts
packages/lib-classifier/.babelrc
packages/lib-classifier/package-lock.json
packages/lib-classifier/package.json
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/store/ResourceStore.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.js
packages/lib-classifier/src/store/utils/getBearerToken.js

Adds the lib-classifier component to the project app and gets it to play ball. 
**Note:** The classifier doesn't render anything, since at this commit it appears to be broken -- or at least, was not working when run standalone either -- and is probably waiting on some of @shaunanoordin's PRs.
Close #390
Close #300
Close #345

Add classifier component to app-project

---

packages/app-project/package.json
packages/lib-async-states/package.json
packages/lib-auth/package.json

Package: lib-auth, lib-async-states, app-project
The latest version of lerna has changes to the bootstrap command and having a custom defined npm install script that calls bootstrap was causing an infinite loop of bootstrap commands being called. This update removes the custom defined npm install script for these packages and let's lerna do its thing.

Do not define custom npm install script

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLabel.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.js

package: lib-classifier
Requires / targets #385
This PR allows each Annotation to be deleted.
- This was done by modifying the standard D3 Brush with a 'Remove Annotation' button that does exactly that.
_Two Annotations (annotation-brushes) with a teal 'X' button on each_
This PR targets #385 for ease of review.
- If #385 hasn't been merged to master, this PR should continue to target that PR.
- If #385 _has_ been merged to master, this PR should be re-targeted to master.

Classifier - TESS Light Curve Viewer - add 'Remove Annotation' buttons

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
packages/lib-classifier/webpack.dist.js

Closes #422. Also breaks long strings in table cells, in case they're e.g. a link.

Fix a couple of bugs in Subject Metadata modal

---

packages/app-project/stores/Project.js
packages/app-project/stores/Project.spec.js
packages/app-project/stores/Store.spec.js
packages/app-project/stores/initStore.spec.js
packages/app-project/test/mocha.opts

Package:
app-project
Runs the app-project store tests and fixes failing tests.
Overlaps with #437, so there may be small merge conflicts with that PR. This one should probably merge first.

Run app-project store tests

---

packages/lib-panoptes-js/src/index.js
packages/lib-panoptes-js/src/resources/collections/commonRequests.js
packages/lib-panoptes-js/src/resources/collections/helpers.js
packages/lib-panoptes-js/src/resources/collections/index.js
packages/lib-panoptes-js/src/resources/collections/mocks.js
packages/lib-panoptes-js/src/resources/collections/rest.js
packages/lib-panoptes-js/src/resources/collections/rest.spec.js

Add collections to the API client, so that we can wire up the classifier favourites and collections buttons to the API.
Adds `collections.create|get|update|delete` and a couple of helpers to link and unlink subjects.

Add collections to the API client

---

packages/app-project/package-lock.json
packages/app-project/package.json
packages/app-project/pages/_app.js
packages/app-project/stores/Collections.js
packages/app-project/stores/Collections.spec.js
packages/app-project/stores/Store.js
packages/app-project/stores/User.js
packages/app-project/stores/initStore.js
packages/app-project/test/chai-config.js
packages/app-project/test/mocha.opts

Package:
app-project
Depends on #430 
Adds a collections store, which holds your project favourites. Loads favourites, or creates them if they don't exist yet, on log in. Adds actions to add or remove a list of subject IDs as favourites.

Add user collections to a project

---

packages/app-project/components/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.spec.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/index.js
packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/locales/en.json

Adds an error boundary to the component wrapping the classifier.

Add error boundary to `ClassifierWrapper`

---

packages/app-project/components/Head/Head.js
packages/app-project/components/Head/Head.spec.js
packages/app-project/components/Head/HeadContainer.js
packages/app-project/components/Head/HeadContainer.spec.js
packages/app-project/components/Head/index.js
packages/app-project/components/Head/locales/en.json
packages/app-project/pages/_app.js
packages/app-project/stores/Project.js

Fills out title, description and other meta tags.
Closes #425 .
TODO:

Populate <head />

---

packages/app-project/stores/Collections.spec.js

Fix a test that broke when I changed the default name for new collections.

Fix create new favourites test

---

packages/app-project/components/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/pages/_app.js
packages/app-project/stores/User.js

Package:
app-project
Adds user.checkCurrent() to the User store, and adds `user.loadingState` flag, which is set to `loading` while we run the initial check for a logged-in user. Displays a 'logging in' message while we check for a user.

Wait on user before rendering the classifier

---

packages/app-project/pages/_app.js
packages/app-project/src/components/ProjectHeader/ProjectHeader.js
packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
packages/app-project/src/components/ProjectHeader/index.js
packages/app-project/src/components/ProjectHeader/locales/en.json
packages/app-project/src/screens/ClassifyPage/ClassifyPage.js

Related to #44.
Adds the start of the project header component. In the interest of keeping velocity up, I'm trying to keep PRs small at the moment - this one simply adds in the component with the project title. Backgrounds, nav etc to come in subsequent PRs.

Start project header component

---

packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js

Remove .only from UPP tests

---

packages/app-project/next.config.js
packages/app-project/package-lock.json
packages/app-project/package.json

Fix #468, ensures that the same panoptes endpoint is used on client and server 🎉 
- Bumps nextjs to version 8, which supports the `env` object in `next.config.js`.
- Adds a passthrough for `PANOPTES_ENV` to `next.config.js`, with a default as `staging`
- Removes the `PANOPTES_ENV` declaration from `npm run dev`

Bump to Next 8, fix environment mismatch

---

packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/Subject.js

Closes #364
This PR adds a number of Subject-related information to the submitted Classification's metadata. Basically, it's a copy of this PR from PFE - https://github.com/zooniverse/Panoptes-Front-End/pull/5197 - and the goal of this PR is to get the Classifier closer to par with the PFE Classifier.
~~WIP.~~
- ~~I've already updated the Classifications store to accept `metadata.subjectSelectionState` (note: will be translated to `metadata.subject_selection_state`)~~
- ~~but it turns out I need to update the _Subject store_ too, because the data model missing ol' stuff like `subject.alreadySeen` (aka `subject.already_seen`) and etc. I _think,_ anyway. brb while I check.~~
Ready for review. See https://github.com/zooniverse/front-end-monorepo/pull/476#issuecomment …

Add Subject flags (metadata) to Classifications

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js

This PR fixes tests in the LightCurveViewer's d3 sub-tasks' tests. This unfortunately wasn't caught in #400, which introduced configurable chart styles.

Classifier - fix tests on Light Curve Viewer

---

packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js

Re-render after the timeout.
Use done() to delay evaluating the test.
Closes #491.
This should be merged into #487 before that merges.

Fix delayed image loading test

---

packages/app-project/stores/Recents.js
packages/app-project/stores/Recents.spec.js
packages/app-project/stores/Store.js

Package:
app-project
Towards #37.
Store recent subjects for user and project
Add a Recents store. Request recents on initial user login.
Test that the store initialises, fetches recents on user change and adds new subjects properly for both authenticated and anonymous users.
Actions:
- `recents.fetch()` fetches existing recents for authenticated users.
- `recents.add({ subjectId, locations })` adds a recent subject to the beginning of the recents queue.
Todo:

Recent classifications for project

---

packages/lib-react-components/src/ZooHeader/ZooHeader.js

The `Box` containing the main project links expands the width of the container, which it doesn't need to do; removing `flex='grow'` stops this.

Prevent ZooHeader page links from growing too wide

---

packages/app-project/stores/Collections.js
packages/app-project/stores/Collections.spec.js

Package:
app-project
Towards: #398
Update the collections store to allow for searching and creating collections, and adding new subjects to them.
My thinking, at the moment, for the 'add to collections' popup is:
- searching collections calls `searchCollections(query)` and displays the results from the stored `collections` array.
- selecting a search result calls `addSubjects(collectionId, subjectIds)`.
- creating a new collection calls `createCollection(options, subjectIds)`, creating a new collection and adding the subject to it in one go.
Todo:

Search and create collections

---

packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js

Toward #113
This adds the seen timestamp to the `TutorialStore` when the tutorial is made active. This is in preparation for determining whether or not the tutorial should be seen on first visit.

Track seen date for tutorial during session

---

packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/workers/index.js
packages/lib-classifier/src/workers/registerWorkers.js
packages/lib-classifier/src/workers/unregisterWorkers.js

I discovered that the worker for the classification queue wasn't functioning as I believed it was. The issue is that I thought it was intercepting the POST request when there was a failure to put it into the queue, but with normal functioning, the POST request in the store and in the worker were going through, duplicating the classification. A few changes are needed:
1. If we're going to listen to the fetch event and intercept it, we need to be using fetch. Superagent is XHR. 
2. We then need to use a listener and call `event.respondWith` to interrupt the original POST request OR use a built in workbox tool for route listening on fetch that will call a callback upon failure (see: https://stackoverflow.com/questions/50129311/requests-through-se …

Unregister workers

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/screens/ClassifyPage/index.js
packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.js
packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLinkContainer.js
packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLinkContainer.spec.js
packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/index.js
packages/app-project/src/shared/components/ContentBox/ContentBox.js
packages/app-project/src/shared/components/ContentBox/ContentBoxContainer.js
packages/app-project/src/shared/components/ContentBox/ContentBoxContainer.spec.js
packages/app-project/src/shared/components/ContentBox/index.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/SubtitleContainer.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/SubtitleContainer.spec.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/index.js
packages/app-project/stores/Store.js
packages/app-project/stores/UI.js
packages/app-project/stores/UI.spec.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js

Package: app-project, lib-classifier
There are some missing/incorrect colours for various elements, this PR fixes some of those to match the designs.

Fix some of the colours on the classifier page

---

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.spec.js
packages/app-project/test/create-global-document.js
packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js

Packages:
lib-classifier
app-project
- Adds an onCompleteClassification prop to the classifier, which is called with the classification and subject when a classification completes. 
- Updates the classify page to add a new recent subject on classification complete.
- Adds tests.

Add onCompleteClassification callback to the classifier

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
packages/lib-classifier/src/store/ClassificationStore.js

Closes #513 and closes #514 .
- I created an onSubmit event handler for the done button which handles adding a default annotation before calling to complete the classification. 
- Switch the TaskInputField to use `checked` instead of `defaultChecked` which is why the task appeared to have an annotation for new subjects and classifications. The store was correctly resetting the classification and annotations, just the UI was not displaying the checked state correctly.
- Updates tests and fixes a missing prop warning for the NextButton tests.
- Removes some cruft
When testing in the app-project, I didn't see that MST warning anymore, so I think this was related to #514 and thus I'm saying it's resolved too.

Set default annotation on Done button submit

---

packages/app-project/pages/_document.js

Update `_document.js` to match [latest next example for styled components](https://github.com/zeit/next.js/blob/canary/examples/with-styled-components/pages/_document.js)

Update _document to match latest next example for styled components

---

packages/app-project/pages/About.spec.js
packages/app-project/pages/Classify.js
packages/app-project/pages/Classify.spec.js
packages/app-project/pages/Home.js
packages/app-project/pages/Home.spec.js
packages/app-project/pages/Index.spec.js

Removes the test files from the `pages` directory, since Next.js has a non-configurable behaviour that builds _everything_ in that folder into the production bundles, and re-exports the page components from the src directory in the remaining pages files (which should be tested).

Remove page tests, and re-export page components

---

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.spec.js
packages/app-project/stores/Collections.js
packages/app-project/stores/Collections.spec.js
packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/RootStore.spec.js
packages/lib-classifier/src/store/Subject.js
packages/lib-classifier/src/store/Subject.spec.js

Package:
lib-classifier
app-project
Closes #397.
Adds an `onToggleFavourite` callback prop to the classifier. Wires up the favourites button so that clicking it adds/removes the current subject from your favourites collection for the project.
Still needs some work to maybe disable the button, or prompt to sign in, if there's no logged-in user.

Wire up the favourite button

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModal.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModal.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModalContainer.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModalContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/CreateCollection.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/CreateCollection.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/index.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/locales/en.json
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/index.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/locales/en.json
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/index.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/locales/en.json
packages/app-project/stores/Collections.js
packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/RootStore.spec.js
packages/lib-classifier/src/store/Subject.js
packages/lib-classifier/src/store/Subject.spec.js

Package:
app-project
Closes #398.
Adds an 'Add to collection' modal box to the Classify page, which can then be triggered from the Classifier or from the Recent Subjects components.
It should be passed a subject ID, and allow you to add that subject to an existing collection or a new collection.

Add to collection

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.spec.js

Package:
lib-classifier
Closes #548.
Adds tests for the case where the first answer has been selected in single and multiple answer tasks. Fixes single answer tasks when the first answer is selected.

Allow first answer to be checked in question tasks

---

packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js

Sets up an observer in the TutorialStore and updates seen date time depending on the UPP state. Still WIP due to tests. I removed the seen time for mini-courses because I refreshed myself on how these work and they are only shown to logged in users, so we do not need to track the seen time for the session in addition to the UPP. 
The store is getting a bit unwieldy, so I think the common actions between tutorials and minicourses should be pulled out into a general store, then a store for tutorial kind and minicourse kind could be composed as a follow up, post TESS launch.

Set active tutorial depending on UPP state

---

packages/app-project/src/components/ProjectHeader/ProjectHeader.js
packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.js
packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.spec.js
packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.js
packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.spec.js
packages/app-project/src/components/ProjectHeader/components/Avatar/README.md
packages/app-project/src/components/ProjectHeader/components/Avatar/index.js
packages/app-project/src/components/ProjectHeader/components/Avatar/locales/en.json

cc #44
Adds a circular avatar icon into the project header.

Add avatar to project header

---

packages/app-project/src/components/ProjectHeader/ProjectHeader.js
packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js
packages/app-project/src/components/ProjectHeader/components/Nav/NavContainer.js
packages/app-project/src/components/ProjectHeader/components/Nav/NavContainer.spec.js
packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.js
packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.spec.js
packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/index.js
packages/app-project/src/components/ProjectHeader/components/Nav/index.js
packages/app-project/src/components/ProjectHeader/components/Nav/locales/en.json

Adds the standard nav links to the project header.
cc #44

Add ProjectHeader nav links

---

packages/app-project/pages/_app.js
packages/app-project/src/components/Head/HeadContainer.js

Package:
app-project
Generates the url to use for the meta tags from the request headers.
fix #569

Get hostname from request headers for meta tags

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js

Set the correct background colour for the classify page

Use correct background color

---

packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.js

Package:
react-components
Fixes a warning caused by Grommet's Box component inadvertently being passed a `height` and `width` prop from `react-resize-observer`

Ensure only required props are passed to <Box />

---

packages/app-project/src/components/ProjectHeader/ProjectHeader.js
packages/app-project/src/components/ProjectHeader/components/Background/Background.js
packages/app-project/src/components/ProjectHeader/components/Background/Background.spec.js
packages/app-project/src/components/ProjectHeader/components/Background/BackgroundContainer.js
packages/app-project/src/components/ProjectHeader/components/Background/BackgroundContainer.spec.js
packages/app-project/src/components/ProjectHeader/components/Background/index.js

Package:
app-project
Closes #556.
Adds the project background image to the header component.

Add project header background image

---

packages/app-project/next.config.js
packages/app-project/pages/_app.js
packages/app-project/src/components/Head/Head.js

Closes #574.
Gets the current HEAD commit id, logs it to the console and injects it into the rendered HTML. It turns out it's not at all straightforward to create HTML comments in JSX, so a custom `meta` tag seemed like a good compromise

Add deployed commit id

---

packages/app-project/stores/YourStats.js

Use the newly minted stats host in kubernetes cluster, this will fix the long timeout errors that were happening in the swarm cluster.

use the new graphql stats host

---

kubernetes/deployment.tmpl

use the one we push to in jenkinsfile
```
kubectl get pods
front-end-staging-f5b475878-kdqpj          0/1       ErrImagePull   0          4s
kubectl describe pod front-end-staging-f5b475878-kdqpj
... pulling image "zooniverse/fe-project:0646cd983059a46e5e11eaf1cfb2359b15f01b4a"
... Failed to pull image "zooniverse/fe-project:0646cd983059a46e5e11eaf1cfb2359b15f01b4a": rpc error: code = Unknown desc = Error response from daemon: manifest for zooniverse/fe-project:0646cd983059a46e5e11eaf1cfb2359b15f01b4a not found
... Error: ErrImagePull
... Back-off pulling image "zooniverse/fe-project:0646cd983059a46e5e11eaf1cfb2359b15f01b4a"
```
Package:
Closes # .

use the correct dockerhub repo

---

packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.js
packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.spec.js

This was an experiment in using DI via default props, but it practice it just threw up warnings.

Fix warning about `Avatar` missing a prop

---

packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModalContainer.js

Fixes the console warning about a missing required prop, and adds propTypes for the props that are still being used. 
Note that I've used `isRequired` _and_ provided a default prop; I think the store hasn't finished instantiating itself by the time this component is mounted, so this avoids further warnings. We've avoided doing this in the past, but I think this will need to be done throughout the app, as these props are strictly speaking required by the component for it to work.

Fix warning about required prop in CollectionsModalContainer

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js

I've removed logging of the event stream, as it was cluttering the console. I have left the code in, however, as a reminder of how to start interacting with it when we start building out the tools for the SingleImageViewer

Remove logging of event stream subscription

---

Dockerfile
package.json
packages/app-project/package.json
packages/lib-async-states/package.json
packages/lib-classifier/package.json
packages/lib-grommet-theme/package.json
packages/lib-panoptes-js/package.json
packages/lib-react-components/package.json

Package: all
Following on from https://github.com/zooniverse/front-end-monorepo/pull/584#discussion_r267945685, this bumps the required node version to 10.

Bump to node 10

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/index.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/locales/en.json
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/Project.js
packages/lib-classifier/src/store/Project.spec.js
packages/lib-classifier/src/store/Workflow.js
packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js
packages/lib-classifier/test/factories/ClassificationFactory.js
packages/lib-classifier/test/factories/ProjectFactory.js
packages/lib-classifier/test/factories/index.js

Closes #383 
This PR adds a **"Done & Talk"** button the the Classifier.
- The "Done & Talk" button appears at the final step of the Classification process.
- Clicking on the button **submits the Classification** AND **opens a new window/tab** to the Talk page, featuring the Subject that was just classified.
- ⚠️ currently, the "Done & Talk" button always appears, regardless of the workflow configuration and whether the Talk board has been set up. I'm considering whether I should use the [PFE implementation](https://github.com/zooniverse/Panoptes-Front-End/blob/96959d42d2a2228b35b99d1d7b2a2d5c7b2a62e4/app/classifier/task-nav.jsx#L94), but I'm still trying to wrap my head around the "check if Talk board has been disabled by looking at …

Classifier - add "Done and Talk" button

---

packages/app-project/src/components/ProjectHeader/ProjectHeader.js
packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js

Closes #567.
Makes the project title a link back to the project home when on another page. Copies PFE, in that only the title and not the avatar work as a link.

Make project title a link when not on the project home page

---

packages/app-project/stores/Recents.js
packages/app-project/stores/Recents.spec.js
packages/app-project/stores/YourStats.js
packages/app-project/stores/YourStats.spec.js
packages/lib-async-states/src/async-states.js
packages/lib-async-states/src/async-states.spec.js
packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/src/store/ResourceStore.js
packages/lib-classifier/src/store/ResourceStore.spec.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
packages/lib-classifier/src/store/utils/ClassificationQueue.js
packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js
packages/lib-panoptes-js/src/panoptes.js
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/collections/commonRequests.js
packages/lib-panoptes-js/src/resources/collections/rest.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.js
packages/lib-panoptes-js/src/resources/projects/rest.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.js
packages/lib-panoptes-js/src/resources/subjects/rest.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.js
packages/lib-panoptes-js/src/resources/tutorials/rest.js

Package: lib-panoptes-js, lib-classifier, app-project, lib-async-states
This is branched off of the branch for #552. This is a fairly large refactor to allow setting many headers for the panoptes requests. This is because we need to set `If-Match` and `If-Unmodified-Since` headers for successful PUT requests (we didn't have one in the code until now). I missed this at first pass of writing the new panoptes.js client. So, the basic request functions now take a headers object rather than just the string for the authorization header. I've updated all of the places where I found a header being set to be an object now. 
The PUT request is almost working, but I'm still getting a 412 because I haven't figured out how `If-Unmodified-Since` is supposed to be set. I'm looking …

UPP PUT request when tutorial is seen by logged in user

---

packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js

Branched off of #552. This fixes an issue where sometimes the reference to the media would not resolve because the request for it hadn't finished before the tutorial modal opened up. We now wait for the request for the media to finish before setting the tutorial and calling to show the modal.

Wait for the media fetch

---

Jenkinsfile
kubernetes/deployment.tmpl

Package: fe-project
1. deploy the fe-project app image to kubernetes
2. switch the image labelling for the base vs app images
3. App images deploy via k8 so they need to have a unique image tag (Git commit)
4. Switch the deployment template to deploy the fe-project app.

deploy the correct image

---

packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/Classification.spec.js
packages/lib-classifier/src/store/ClassificationStore.js

Closes #498
Adds `classifier_version` to the classification metadata. Services like caesar/aggregation may want to know this and act upon it if necessary.

Add classifier_version to classification metadata

---

packages/lib-classifier/webpack.dist.js
packages/lib-react-components/webpack.dist.js

Package: lib-classifier, lib-react-components
Disables minification for easier debugging for now.

Disabling minification for now for easier debugging

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js

Update the Done & Talk onClick handler to set the url redirect as the onHide callback for feedback.
ToDo:
Package:
lib-classifier
Closes #598.

Defer Done & Talk until feedback closes

---

packages/app-project/pages/_app.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
packages/app-project/stores/Project.js
packages/app-project/stores/Project.spec.js
packages/lib-panoptes-js/src/config.js
packages/lib-panoptes-js/src/panoptes.js
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.js
packages/lib-panoptes-js/src/resources/projects/rest.js

Package: app-project, lib-panoptes-js
This another attempt at setting the correct env by using url query param during the initial server side load in the app. I've decided to pass the env along as a query param, so it's still panoptes.js's responsibility to set the host based on the env for the requests, but it just adds another route to set it.
This makes loading a staging project in production work:
- Locally run `npm run build && npm start` to start the app in production mode
- Load up a staging project like: `http://localhost:3000/projects/nora-dot-test/planet-finders-beta/classify?env=staging`
Or:
- locally run `npm run dev` to start the app in staging mode 
- Load up a production project like: `http://localhost:3000/projects/zookeeper/galaxy-zoo/classify?env=pr …

Set env by query during initial server side load

---

packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js

Package:
lib-classifier
Removes `self.fetchMedia` from the tutorial store, since it isn't used outside the store. Can anyone see why doing this breaks the tests?

Remove self.fetchMedia from tutorial store

---

packages/lib-classifier/src/store/TutorialStore.js
packages/lib-classifier/src/store/TutorialStore.spec.js

Package:
lib-classifier
This builds off #606 because I made changes to the tutorial tests there. It mocks the tutorial client to reject with an error on `tutorials.getAttachedImages()`, and expects the tutorial not to be shown in that case.
It also tests the case where media requests resolve after tutorial requests, to make sure that we aren't showing the tutorial before it's ready.

Test tutorial media errors

---

packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js
packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.spec.js

Package:
app-project
Hooks up the `View more stats` link in the corner of the stats widget.

Hookup view more stats link

---

packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.js
packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.spec.js

Closes #625.
Moves the `aria-label` for the Zooniverse Approved icon to the icon svg, and removes the `title` attribute.

Move aria label to icon

---

packages/lib-classifier/src/store/FieldGuide.js
packages/lib-classifier/src/store/FieldGuide.spec.js
packages/lib-classifier/src/store/FieldGuideStore.js
packages/lib-classifier/src/store/FieldGuideStore.spec.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/test/factories/FieldGuideFactory.js
packages/lib-classifier/test/factories/MediumFactory.js
packages/lib-classifier/test/factories/index.js

For #391
This is adding the store and tests for the field guide in the classifier. UI will be added in a separate PR
~WIP because we're working on improving the tests for the tutorial still and the field guide is fairly similar, so we should learn from that first.~

FieldGuide store

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/shared/components/ContentBox/ContentBox.js
packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
packages/lib-grommet-theme/src/index.js
packages/lib-react-components/src/ZooFooter/ZooFooter.js
packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
packages/lib-react-components/src/ZooHeader/ZooHeader.js

Package: app-project, lib-grommet-theme, lib-classifier
Adds an `edgeSize` property to the grommet theme using the 10px multiples as per the designs, then adjust the spacing on the actual elements to match.

Adjust paddings/margins in theme to match design

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js

Closes #638.
Use the Zooniverse Markdown component instead of the one from Grommet.

Use zooniverse markdown instead of grommet

---

packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js

Closes #607.
I gave it another go to try using Grommet's `RadioButtonGroup` which does have accessible focus, and this seems to be working. @eatyourgreens if this is better, then let me know and I'll update tests accordingly. Is there anything else needed for accessibility here?

Focus accessibility for tutorial navigation

---

packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js

Render modal title as an h2

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js

Adds in the missing `aria-label`s to the classifier toolbar

Ensure toolbar buttons have an aria-label

---

packages/lib-panoptes-js/src/resources/subjects/helpers.js

Stop the subject generator test from generating subjects with IDs of 0.
Package:
Closes #676.

Set minimum mocked subject ID to 1 in random tests

---

packages/app-project/package-lock.json
packages/app-project/package.json
packages/lib-classifier/package-lock.json
packages/lib-classifier/package.json
packages/lib-react-components/package-lock.json
packages/lib-react-components/package.json

Replace standard with standardx.
Install the jsx-a11y plugin.
Configure the linter to use the recommended a11y rules.
Package:
app-project, lib-classifier, lib-react-components

Install an accessibility linter

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.spec.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/index.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js
packages/lib-classifier/test/factories/SubjectFactory.js

Closes #649 
I removed the `size` prop from the DataTable and the table is now accessible. This seems to be a Grommet bug, opened issue at https://github.com/grommet/grommet/issues/3006
To still have the table overflow, I wrapped it with a Box and set the height and overflow. 
I reduced the size of the rows. I'm not 100% what the size should be since the InDesign prototype is not inspectable: https://projects.invisionapp.com/d/#/console/12923997/270495352/preview so I tried to eyeball it. @beckyrother what should the size of the rows be here?
I extracted out the function that filters what is displayed to be usable by the store. Project 272 has subjects that only have hidden metadata, so the button should be hidden. (This is actually a bug in …

Subject metadata modal fixes

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.js
packages/lib-grommet-theme/src/index.js
packages/lib-react-components/src/Media/components/Audio/Audio.js
packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
packages/lib-react-components/src/Media/components/Video/Video.js
packages/lib-react-components/src/Modal/WithLayer.js

Package: lib-classifier, lib-react-components, lib-grommet-theme
For #666
Fixes:
- heading and paragraph styling in selected item content
- item heading no longer being cutoff when overflow happens
- adds box-shadow to the react-components Modal
- set paragraph default in theme to take a max-width of 100% and more specific styles can be defined in components

Field guide style fixes

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.spec.js
packages/lib-react-components/src/Modal/WithLayer.js

Package:
classifier, react-components
Allow interaction with the classifier while the field guide is open, and show the guide on the right.

Turn off modality for the field guide

---

packages/lib-grommet-theme/src/index.js

Package:
Closes #666 
Updates the theme's line-height settings for paragraphs and span texts according to @beckyrother's input in #666 
Medium size is Grommet's default and with a font-size: 14px and line-height of 18px, I set the rest of the sizes to follow a 4px difference.

Update line heights for paragraphs and span texts

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js

Fixes
> body copy is too small, please make all body 14px
in #695

Use default theme sizes for paragraphs

---

packages/app-project/pages/_document.js

Package:
app-project
Closes #692 
cc #174 #217
Adds the GTM tags from https://developers.google.com/tag-manager/quickstart

Add Google Tag Manager in production

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/RelatedProjectsContainer.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/RelatedProjectsContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/index.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/locales/en.json
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModal.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModal.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModalContainer.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModalContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/ProjectCard.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/ProjectCard.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/index.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/locales/en.json
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/index.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/locales/en.json
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/index.js

Package:
app-project
Adds the UI for the related projects modal. I'm going to do the selection strategy in a separate PR.

Add components for related projects modal

---

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js
packages/lib-classifier/src/components/Classifier/components/Feedback/components/index.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/getFeedbackViewer.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/getFeedbackViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/index.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js

Towards #205.
- adds feedback related brushes to `LightCurverViewer`
**Refactor in progress:**
- extract feedback specific code from `LightCurveViewer`
- move feedback specific brush code elsewhere
- add to LCV something like `renderAlternativeBrushes` that takes custom brush render code prop
^ should be done soon, but don't want to hold this up for beta testing

Init add of feedback brushes to feedback modal

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js

Move the collections modal into the classify page container. This fixes a bug where the collectionsModal ref was lost if you logged in after loading the page, causing the Add To Collection button to crash the classifier.
Package:
app-project
Fixes the bug mentioned in this comment: https://github.com/zooniverse/front-end-monorepo/pull/690#issuecomment-482125976

Move collections modal into classify container

---

packages/lib-panoptes-js/src/resources/collections/commonRequests.js
packages/lib-panoptes-js/src/resources/collections/rest.spec.js

Pass auth headers properly when removing a subject from a collection.
Package:
Closes #707.

Pass auth headers with collections delete requests

---

packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/Subject.js
packages/lib-classifier/test/factories/SubjectFactory.js

Add selected_at to the subject model, and copy it across to new classifications.
Package:
lib-classifier

Add selected_at to subjects

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.spec.js

Disable 'add to collections' or 'add to favourites' if there's no logged-in user.
Package:
lib-classifier
Closes #658.

Disable add to collections for anonymous users

---

packages/app-project/pages/_document.js

Fixes #710 
This PR fixes an issue where - if the website is hosted on a server that _isn't_ set to `NODE_ENV=production` - then visual styling elements aren't displayed properly.
Basically, you see this...
...instead of this...
Currently, in `app-project/pages/_document.js`, the `<Head>` element isn't rendered at all if the web server's NODE_ENV isn't set to production. The lack of a Next.js `<Head>` in these instances basically screwed up style injections for the `app-project` website, causing all sorts of visual shenanigans.
Side note, this means that the website always looks fine if the dev has `NODE_ENV` set to production on their machine, or on the actual production server.
Ready for review!

Fix Next.js document so it correctly renders <Head>

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.js

Closes issues associated with the field guide listed in #695 
- Item icons consistently render at 100px by 100px
- Padding is consistently 30px all around now. 
You can use PH: Beta project to test http://localhost:8080/?project=1862

Make sure field guide item icons stay the same size. Consistent padding.

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.spec.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataButton/MetadataButton.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataButton/MetadataButton.spec.js

I rebase incorrectly a few minutes ago which left an undefined function type error. This fixes that issue and makes the metadata button more consistent with the rest of the metatools buttons by using the disabled prop rather than hide the button if there is no metadata.
Can be tested for disabled-ness with this project: http://localhost:8080/?project=272

Fix undefined error with metadata button

---

packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js

Package: lib-classifier, lib-react-components
Fixes these items from #695
- Pagination dots are too far apart, arrows are even farther. There should be 5px between each element
- Between the teal bar and the top of the H2 should just be 30px.
- Why does 'Planet Finders BETA Tutorial' appear on each slide
- The entire contents of the tutorial should scroll, not just the text part
- the tutorial doesn't scroll when it's in the tab state

Additional tutorial style fixes

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.js

Wraps the button with a Link and passes the href to the `/#projects` anchor on the signed in home page (Grommet Buttons render as anchors with button styling if they have an href prop). Only show it if the user is signed in. Adds tests.

Add link for user stats only if logged in

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js

Key the viewer by subject ID, forcing it to unmount and remount for each subject.
Package:
lib-classifier
Closes #719.

Add a key to the subject viewer

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js

Following on from #720, this removes the subjectId prop from the subject viewer and simplifies the check to see if the subject has changed on component update.
Package:
lib-classifier

Remove the subjectId prop from the subject viewer

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/locales/en.json

I'm writing a tiny API for finding related projects, but it's not quite ready to go yet. In the meantime, let's remove this button in order to get the app out of the door.

Disable related projects button

---

packages/lib-react-components/src/PlainButton/PlainButton.js
packages/lib-react-components/src/PlainButton/PlainButton.stories.js

Removes the :hover styling from disabled buttons. Adds a disabled button to the storybook.
Package:

Remove hover state from disabled buttons

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js

Tab design fixes

---

packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js

Change the tutorial height from a fixed 465px to 53vh.
Package:
lib-classifier
This is a quick fix that stops the tutorial from resizing the subject viewer.

Reduce tutorial height

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/withKeyZoom/index.js
packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js

Add +/- keys as zoom controls when the image toolbar has focus.
Stub out handlers for the left and right cursor keys.
Add a keydown listener to the light curve viewer.
Package:
lib-classifier

Add keyboard zoom to the image tools

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
packages/lib-classifier/src/store/SubjectViewerStore.js

Add an onPan callback to the light curve viewer.
Wire up the left and right arrow keys to call onPan.
Update the tests for withKeyZoom to include left and right panning.
Package:
lib-classifier
Closes #722.

Add keyboard pan controls

---

packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js

Add default props so that withKeyZoom doesn't crash if expected callbacks aren't defined.
Package:
lib-classifier

Add default props for pan/zoom callbacks

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js

Closes #732.
- until rotate and fullscreen buttons implemented, hides `disabled` buttons by returning `null`
- [the Button component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js) will be refactored for a tooltip, and as part of that refactor we will revisit if/how we will disable a button

Hide disabled tools

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
packages/app-project/src/shared/components/ContentBox/ContentBox.js
packages/lib-grommet-theme/src/index.js

Package: 
app-project, lib-grommet-theme
Closes #736.
- Fix box shadow colours
- Set box shadows in project app from theme

Fix elevations

---

docs/arch/README.md
docs/arch/adr-14.md

This PR adds an ADR discussing our choice to use an external CMS - Contentful - to manage our static content - notably our Team and Publications entries in the new `app-about` package.
See PR #731 for the first instance of the usage of Contentful.
Awaiting review.
@rogerhutchings , can you also please add some notes about choosing Contentful in specific? (It's the part marked `...`)

Add ADR 14 - Using an external CMS for content pages

---

package-lock.json
packages/app-project/package-lock.json
packages/app-project/package.json
packages/lib-classifier/package-lock.json
packages/lib-classifier/package.json
packages/lib-grommet-theme/package.json
packages/lib-react-components/package-lock.json
packages/lib-react-components/package.json

Package: fe-project, lib-classifier, lib-grommet-theme, lib-react-components
Upgrades Grommet to v2.6.6, which includes:
- fixed theme issue on grommet button
- DataTable overflow issue
- active theme support
- custom drop overflow
Might help with a few little issues we're having, at minimum good to stay current.

Bump Grommet

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
packages/lib-react-components/src/helpers/withThemeContext/README.md
packages/lib-react-components/src/helpers/withThemeContext/index.js
packages/lib-react-components/src/helpers/withThemeContext/withThemeContext.js
packages/lib-react-components/src/helpers/withThemeContext/withThemeContext.spec.js
packages/lib-react-components/src/index.js

~**This follows #769, which needs to be merged first**~
- Creates a HOC for using Grommet's `ThemeContext` component
- Refactors `NextButton` to use the HOC
- Refactors the `Tabs` component to use the HOC instead of creating a new `Grommet` context

Refactor theme context HOC, use for tabs

---

packages/lib-grommet-theme/src/index.js

Fixes the regression to the circle size after #747. I'm not sure if this fixes the issue in #746 because I can't replicate it using the emulators. We'll have to start testing with actual devices.

Update theme for the radio buttons

---

packages/lib-classifier/webpack.dev.js

This fixes the crashing that was happening with the dev-classifier and React hooks. Apparently more than one React was loading even though the troubleshooting's guide suggestion on how to test this didn't log in a way to indicate more than one was loading. Basically we need to use aliases anytime we're symlinking in development it seems.

Alias react for dev environment

---

packages/lib-grommet-theme/src/index.js

Closes #772
Sets the default padding for the button component in the theme.

Set default padding for button in the theme

---

packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js

Use a provider to add the mock store, then get the wrapped component and test expected behaviour against that.
Package:
lib-classifier
Just a couple of small changes to make the tests cleaner, after reading up on how to test Higher Order Components in MobX and React.

Clean up withKeyZoom HOC tests

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.spec.js

Fixes a regression introduced in #779 and adds a test to cover what broke. Apparently you can't use implicit returns in functional setState calls?

Use explicit return in functional setState. Add test

---

packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js

Fixes modal header issues noted in this comment: https://github.com/zooniverse/front-end-monorepo/issues/746#issuecomment-487744230
Use min-height instead of a fixed height

Use min-height instead of fixed height

---

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
packages/lib-classifier/src/components/Classifier/components/Feedback/locales/en.json

For #774
Updates the Feedback's modal button to say 'Keep Classifying' per #774

Update Feedback modal button label

---

packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js

Closes #739 .
Forces the stats button to be teal. There may be other cases where this comes up, but this covers the last affected button on the page.

Ensure stats button is always teal

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
packages/lib-classifier/src/store/SubjectViewerStore.js

Package:
lib-classifier
Closes #511 .

Disable task area while subject is loading

---

packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
packages/lib-react-components/src/ZooHeader/ZooHeader.js
packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js

Package: lib-react-components, app-project
I noticed that the links to the user's profile and collections was broken in the header menu. I'm not sure what would be a good check and test for this beyond setting it as required in the prop types. I don't think it'd be a good idea to not render the menu or certain links if the user login was undefined like it was before.

Make user login prop required. Pass it along in app-project

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/SubjectViewerStore.js
packages/lib-classifier/test/enzyme-config.js

Get image dimensions from the HTML image preloader. Create a new, fake event and fake target on SVG image load, since the originals are read-only. Pass the fake event, with the HTML image dimensions, to the subject viewer store via the onReady event handler.
Todo:
Package:
lib-classifier
Closes #201.
Closes #304.

Record subject image dimensions on load

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js

Remove the spy on componentDidMount. Set a timeout instead, to wait for component state to update on mock subject load.
Package:
lib-classifier

Use a timeout for LCV async tests

---

packages/app-project/src/components/ProjectName/ProjectName.js
packages/app-project/src/components/ProjectName/ProjectName.spec.js
packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js

This refactors the ClassifyPage to hide the project name and to stack the theme toggle below the classifier on small screens.

Refactor ClassifyPage classifier area and components for mobile view

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/store/SubjectViewerStore.js

Package:
lib-classifier
Mock a bad image for the single image viewer and stub console error logging. Test the component error handler for the cases where either the HTML `img` or the SVG `image` elements throw an error.
Rename `handleSubject` to `getImageSize`, to make its purpose clear.
Add an `onError` action to the subject viewer store and use that to handle subject viewer errors. Rename `SubjectViewerStore.ready` to `SubjectViewerStore.loadingState` and change it from a boolean to an enumeration of loading states.

Add tests for errors when loading subject images

---

kubernetes/deployment.tmpl
packages/app-content-pages/package.json
packages/app-content-pages/server/server.js

Sets the asset prefix, so JS bundles are correctly fetched from the specific app subdomain, rather than falling back to `www.zooniverse.org` (where they don't exist)

Set asset prefix to correctly fetch resources

---

kubernetes/deployment.tmpl
packages/app-project/server/server.js

Following on from the setting for app-content-pages, this allows the setting of `assetPrefix` for the project app.

Allow asset prefix for app-project

---

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js

Sets message container to a smaller fixed height if the viewer is present. Makes the modal itself larger:

Set message container height if viewer is present

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js

Temporarily disables the stats widget, as it's not really required for the TESS production launch.
cc #38

Temporarily disable the stats widget

---

packages/lib-grommet-theme/src/index.js

Uses `accent-2` for the dark theme controls, closes #852

Fix dark theme controls

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/SpacedHeading.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/SpacedHeading.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/index.js
packages/lib-grommet-theme/src/index.js

Closes #856.
Does a minor refactor as well to use the `Markdownz` component prop instead of styled-components (as it's basically styling a Grommet component anyway), and uses the `theme` prop from `withTheme` instead of importing the zooTheme directly

Fix field guide titles

---

packages/lib-grommet-theme/src/index.js

Closes #855
Sets the light and dark background colors for the drop. This can be checked with the Select component in the collections modal in the app-project.

Set light and dark background for drop container in theme

---

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataMask.js

Closes #851 .
- the data-mask from the initial subject viewer was being applied to the feedback viewer, this adds a random number to the data-mask id to differentiate
- small edits to Feedback Modal sizing

Add random number to data-mask ID

---

packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.js
packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.js
packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.js
packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.spec.js
packages/app-project/src/shared/components/ProjectStatistics/locales/en.json
packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.js

Replace lipsum text in stats box

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataMask.js

This PR follows up on PR #866, which generates a random ID for each instance of a Light Curve Viewer, to prevent multiple Data Mask `clipPath`s from having identity collisions. (See Issue #851 )
This PR addresses two things:
1. It adds the randomly generated ID to the `<g.data-layer>`.
_Without this PR, `<clipPath#data-mask-0.407396...>` is defined with a unique ID, but the `<g.data-layer>` is still looking for the old `<clipPath#data-mask>` (without the unique ID)_
_As a result, the clipPath is ignored altogether, and the data points in the Data Layer are rendered outside the intended Data Mask._
2. it fixes the issue where the _randomly generated ID is the same for every instance_ of the LCV.
@mcbouslog So this is something interesting I found out: if you set a …

Light Curve Viewer - add missing Data Layer ID, fix randomised IDs

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/SpacedHeading.js

Sets the field guide titles to white in dark mode.

Ensure dark theme field guide has correct title color

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js

Closes #875
This doesn't fix the issue in the way #875 suggests. The underlying remark dependency does sanitization on the src attributes of html and there's no way to customize it to allow for a regex to parse it. This is probably for the best for security reasons. Instead, let's override how images are rendered in the field guide and disallow resizing via markdown syntax and set a fixed height that the thumbnail service will use. This fixes how the images render to a much nicer size for TESS. Long term, though, we might consider the reverse solution and adding a markdown-it plugin for the old Markdownz to support resizing syntax in the alt tag area of the markup. 
Check it out locally: …

Override how img are rendered in the field guide

---

packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/index.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/reduceFeedbackMessages.js
packages/lib-classifier/src/components/Classifier/components/Feedback/helpers/reduceFeedbackMessages.spec.js

Adds a basic reducer to show each feedback message once, with a number of matches next to it.

Basic feedback reducer

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
packages/lib-classifier/src/store/Subject.js
packages/lib-classifier/src/store/Subject.spec.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Add an openInTalk action to subjects and invoke it when Done & Talk is pressed. 
Remove the code from the DoneAndTalkButtonContainer that updated window.location to open a Talk page.
Instead, we now intercept the subject queue advance and look to see if we expect feedback or if Done & Talk has been pressed, then go to Talk if it's safe to do so.
Package:
lib-classifier
Closes #900.

Fix Done And Talk when feedback isn't present

---

package-lock.json
package.json
packages/app-content-pages/package.json
packages/app-project/package.json
packages/lib-classifier/package.json
packages/lib-grommet-theme/package.json
packages/lib-panoptes-js/package.json
packages/lib-react-components/package.json

Package:
All
Following on from #898, this installs snazzy globally and adds it back into the linter scripts for each package.

Add snazzy formatting back to the linter

---

packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Add some tests:
Package:
lib-classifier
Closes #904.

Handle empty subject queues properly

---

packages/tools-standard/package.json

The test script error blocks tests from running across the repo, so get rid of it.
Package:
tools-standard
Closes #915 .
Remove the error that zooniverse/standard throws when running `npm test`.

Remove test script

---

packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModalContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/CreateCollection/CreateCollection.spec.js
packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js

Use withArgs to create specific spies in tests, rather than using calledOnceWith.
Package:
app-project

Use withArgs for spies

---

packages/app-project/stores/UI.js
packages/app-project/stores/UI.spec.js
packages/app-project/stores/helpers/cookie.js

Closes #903
Checks for a value in the cookie and if not present, then defaults to light mode. The easiest way I found to test this manually is to compare the local running app to production and toggle the light and dark modes and then open the site in a new tab. 
I also change the MST lifecycle method that adds the observer to `afterCreate` because it is not depending on any kind of parent tree value.

Make the default for UI mode to be from the cookie value

---

packages/app-project/src/components/AuthModal/shared/components/withCustomFormik/README.md
packages/app-project/src/components/AuthModal/shared/components/withCustomFormik/withCustomFormik.js
packages/app-project/src/components/AuthModal/shared/components/withCustomFormik/withCustomFormik.spec.js

As a follow up, I checked to see if onBlur is on working with the `withCustomFormik` HOC with the refactor from #918 and it does now! Tests are passing for it, so I now I have confidence it can be used with the login form.

Add back support for customization of onBlur

---

packages/app-content-pages/src/screens/Publications/components/Publication/Publication.js

Use publication citation as link, instead of `view publication`

---

packages/app-content-pages/README.md
packages/app-project/README.md

Add some ops service links to app readmes

Add some ops links

---

packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
packages/app-project/src/components/AuthModal/components/RegisterForm/locales/en.json

Closes #929
I've added a regex pattern for a browser based validation to the real name field. I decided to go the blacklist route rather than the whitelist route and blacklist the `@` symbol as a proxy for disallowing email address submissions. Other special characters and unicode characters may legitimately be used for real names and I think it'll be much harder to create a whitelist without error. I think it'll be unlikely someone will use `@` in a real name. If this is an acceptable approach, I'll open a parallel PR to update the currently used PFE form. 
Here's what I've made the message when the validation fails:

Disallow at symbol in real name field

---

packages/app-project/stores/UI.js

Closes #903
Adds the domain to the cookie being set if in production. I'm not sure how to go about testing this.

Add domain to the cookie being set

---

packages/app-project/stores/UI.js
packages/app-project/stores/UI.spec.js

Closes #903 hopefully
I'm not totally sure if this will fix what we're observing on production. What is happening is that the cookie is present, but is being switched when the app loads from dark to light if the cookie is storing a dark mode. Presumably the cookie is being set regardless of the mode right now. I refactored the store to only set the cookie on the patch event of the store and added tests for this.

Refactor how the cookie is being set and when

---

packages/app-project/package-lock.json
packages/lib-async-states/package-lock.json
packages/lib-classifier/package-lock.json
packages/lib-grommet-theme/package-lock.json
packages/lib-panoptes-js/package-lock.json
packages/lib-react-components/package-lock.json
packages/tools-standard/package.json

I think the occasional error around linking up `@zooniverse/standard` is the missing `publishConfig` property in the package.json - see https://jenkins.zooniverse.org/job/Zooniverse%20GitHub/job/front-end-monorepo/job/master/435/console

Add publishconfig to zoo-standard, rebuild locks

---

packages/app-content-pages/package-lock.json

Package: app-content-app, app-project
I didn't catch that #952 didn't have a rebuilt lock for the content app.

Rebuild package-lock.json for content app

---

packages/lib-panoptes-js/package-lock.json
packages/lib-panoptes-js/package.json
packages/lib-panoptes-js/src/config.spec.js
packages/lib-panoptes-js/src/panoptes.spec.js
packages/lib-panoptes-js/src/resources/collections/rest.spec.js
packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/projects/rest.spec.js
packages/lib-panoptes-js/src/resources/subjects/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/subjects/helpers.spec.js
packages/lib-panoptes-js/src/resources/subjects/rest.spec.js
packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
packages/lib-panoptes-js/src/resources/tutorials/rest.spec.js
packages/lib-panoptes-js/src/utilityFunctions/index.js
packages/lib-panoptes-js/test/chai-config.js
packages/lib-panoptes-js/test/mocha.opts

Fix a bunch of eslint errors, mostly variables that are declared but not used.
Also installs `dirty-chai` and updates chai expectations to use function calls.
Package:

panoptes.js: fix linter errors and warnings

---

packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.spec.js

Fix a broken import.
Simplify the tests by moving repeated describe blocks into a single function that takes social link props as an argument.
Package:

Fix Social Anchor tests

---

packages/app-project/pages/_app.js

Setting ui.mode to an empty string creates an invalid snapshot for the UI model.
Package:
app-project

Initialise ui.mode with a valid value

---

.yarnrc
package.json
yarn.lock

via https://github.com/zooniverse/front-end-monorepo/pull/991#pullrequestreview-259075330
- Sets the default version prefix to tilde
- Bump top level packages, use tildes
1. `cd` to the project root dir
1. Run `yarn add left-pad -W`
1. Open up the `package.json` and verify the version prefix
1. Trash your changes to `package.json` and `yarn.lock` (obvs)

Set save prefix to `~`

---

.travis.yml

Don’t fetch packages from npm if we’ve already downloaded them.

Cache packages between Travis builds

---

packages/lib-classifier/src/store/ResourceStore.js
packages/lib-classifier/src/store/ResourceStore.spec.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/RootStore.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js

This updates the reference to `safeReference` and fixes the headers to be an optional type with a default. Fixes one broken test, with `only` left in on purpose to show tests are now passing.
Note that setting active to undefined in the reset action is removed. This is because `safeReference` now handles this for us. When the referenced data is removed from the associated map, it'll automatically set the reference to undefined.

[MST Upgrade] Update ResourceStore

---

packages/lib-classifier/src/store/ProjectStore.js
packages/lib-classifier/src/store/ProjectStore.spec.js

Updates `ProjectStore` to use `types.safeReference`. The store doesn't have any actions, so its just a model declaration, and doesn't have need for tests beyond a smoke test. I did update the smoke test to check for truthiness instead. `only` left in purposely to show the tests for this store are now passing.

[MST Upgrade] Update project store

---

packages/app-content-pages/src/screens/Publications/Publications.js
packages/app-content-pages/src/screens/Publications/locales/en.json
packages/app-content-pages/src/shared/stores/Publications/Publications.js

cc #876
This changes the store to return the category titles from Contentful, rather than translate them in the app. This means that everything on that page can be edited via the CMS.
Once a language selector is in place, we'll need to send the language code along with the request in Contentful, or store translations locally (probably more likely) - this is captured in #877

Use contentful category titles

---

packages/lib-classifier/src/store/WorkflowStore.js
packages/lib-classifier/src/store/WorkflowStore.spec.js

Updates `WorkflowStore` to use `types.safeReference` and to use `isValidReference` when using other store's references. Updates tests except for the test for loading a workflow by query param. These tests will change when we switch over to the url fragments instead, so they're disabled for now. `only` left in on purpose to scope the tests to show they're passing for the `WorkflowStore`

[MST Upgrade] Update WorkflowStore

---

packages/lib-classifier/README.md

Updated the local host information as well as updated with yarn information.
Package:
Closes # .
Minor updates to the lib-classifier README.

Update start up information in README

---

packages/lib-react-components/src/Markdownz/Markdownz.js
packages/lib-react-components/src/Markdownz/Markdownz.spec.js

Parallel to zooniverse/markdownz#83
Adds support to the restricted usernames list.

Add support to restricted names list

---

packages/lib-classifier/src/store/ResourceStore.js
packages/lib-classifier/src/store/Subject.js
packages/lib-classifier/src/store/Subject.spec.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js
packages/lib-classifier/test/factories/SubjectFactory.js
packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js

This updates the SubjectStore and SubjectResource model as well as fix a few bugs:
For `ResourceStore`:
- Added check to make sure the response body has length before storing it
For `SubjectResource`:
- Added `isValidReference` existential checks for project and workflows
- Updated test and added tests for the viewer view getter
- ~Removed cruft describe blocks~
For `SubjectStore`:
- `types.reference` is now `types.safeReference`
- Removed unnecessary `types.optional` around the `types.map`
- Added `isValidReference` for the existential checks for the store's `active` property that is a reference
- Removed the actions set to `undefined` in the returned object for the actions. MST will just simply throw an undefined type error, so don't do …

[MST Upgrade] Update SubjectStore

---

packages/lib-classifier/src/store/FieldGuideStore.js
packages/lib-classifier/src/store/FieldGuideStore.spec.js

Updates the FieldGuideStore to work with the newer versions of MobX/MST:
- Updates `types.reference` to `types.safeReference`
- Only `types.safeReference` can be undefined and implicitly uses `types.maybe`
- Adds `isValidReference` check for the active project reference
- Updates tests to instantiate stores we are not testing to an empty object. Uses the actual `RootStore` so the `afterAttach` lifecycle fires as expected for the stores we are testing. Note the `FieldGuideStore` is coupled with the `ProjectStore` in its lifecycle, so the `ProjectStore` instantiates as normal so the references work.
`only` is left in purposely so it can be more clearly seen that the tests for the `FieldGuideStore` are now passing.

[MST Upgrade] Update FieldGuideStore

---

packages/lib-classifier/src/store/SubjectStore.spec.js

Adds a describe block to make sure every declaration of rootStore is locally scoped to a function.
Adds a test to check that advancing the queue reduces its size by one.
Package:
lib-classifier

Fix shadowing in the SubjectStore tests

---

packages/lib-classifier/README.md
packages/lib-classifier/docker-compose.yml
packages/lib-classifier/webpack.dev.js

Run webpack dev server and the storybook in a container using `docker-compose up`.
Shut down the running server with `docker-compose down`.
Run the tests with `docker-compose run --rm dev test`.
Browse the dev classifier on http://localhost:8080 and storybook on http://localhost:6006 as usual.
Package:
lib-classifier

Add docker-compose to the classifier

---

packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Move the minimum subject queue size into a constant and update tests.
Package:
lib-classifier
Towards #1042.

Make minimum subject queue size configurable

---

packages/app-content-pages/README.md
packages/app-content-pages/docker-compose.yml

Add a docker-compose file to the content pages app.
`docker-compose up` to run a server on  http://localhost:3000.
`docker-compose down` to stop the dev server.
`docker-compose run --rm dev test` to run the tests.
`docker-compose run --rm --service-ports dev storybook` to run the storybook on http://localhost:9001.
Package:

Add docker to app-content-pages

---

kubernetes/deployment.tmpl

No need to pay the overhead to run additional staging services, keep it lean.

switch to 1 staging replica

---

docs/arch/README.md
docs/arch/adr-17.md

For #694.
I have two questions from writing this that I still think we should decide upon:
- Should we continue to use https://fe-project.preview.zooniverse.org as the destination sub-domain for the master branch staging deploys? As we add more apps, using `fe-project` doesn't really make sense and won't accurately reflect what's deployed. I believe currently both `fe-project` and `fe-content-pages` are built and deployed on merge to master.
- Should individual apps be deployed in their own images and process?
- Should we have a staging webpack build for the libraries to not uglify the builds so we can more easily debug using the staging app?

Add ADR 17

---

packages/lib-classifier/src/store/FeedbackStore.spec.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Package:
lib-classifier
This adds a couple of missing specs for `subjectStore.advance()`. Advancing the queue should:
- make the next subject in the queue active.
- remove the current active subject.
- reduce the size of the queue by one.
- change the active subject.
I've also removed `values().next()` in favour of using `subjectStore.active` to get the active subject, but tests are still failing and I can't see why.
`rootStore` is removed fro the subject store tests, and `setupStores` is renamed, to avoid name collisions with other store tests.
Tests will pass if the subject store tests are run in isolation.
EDIT: tests pass if `rootStore.subjects.advance()` is only called once so I've edited some of the tests to do that.
UPDATE: Feedback helpers were stubbed to enable feedback. …

Add specs for subject queue advance

---

packages/lib-grommet-theme/CHANGELOG.md
packages/lib-grommet-theme/package.json

Adds a postversion script to push up the new version tag and publish. Updates the changelog.

Theme: Update changelog. Add postversion script

---

packages/app-project/package.json
packages/lib-classifier/package.json
packages/lib-react-components/package.json
yarn.lock

Package: almost all of em
Bumps zoo grommet theme version to 2.1.0 across packages. Fixes broken theme on site.

Bump theme version across packages

---

packages/lib-classifier/src/store/FieldGuideStore.js
packages/lib-classifier/src/store/FieldGuideStore.spec.js

This refactors the FieldGuideStore tests to get them passing again. This bypasses MST lifecycle `afterAttach` by scoping the mocked store to only the FieldGuideStore and not using the `RootStore` at all. I suspect there's still something wrong in how we're setting up the stores, but this setup is more the direction I'd like to go with the tests, and adding later a specific test for `afterAttach` that involves the `RootStore` rather than use it across the board.
I've also added a few `isValidReference` checks that were missing still.

[MST Upgrade] Update FieldGuideStore and tests

---

packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js

For #874 (maybe closes?)
- Updates the conditional to check that the feedback rules sizes is greater than 0 before updating the classification metadata with feedback information. 
- Updates the feedback store `update` action to only update the feedback rules if feedback is active
- Adds specs for both
The feedback store tests could use refactoring, however, I'm trying to minimize the merge conflict that this will cause with the MST updates (and subsequent test updates that caused). So this is really only scoped to test for these bug fixes.
There may still be a scenario where `isActive` is true, but there are no feedback rules because the subject is a real subject and has no feedback rule subject metadata, so `isActive` shouldn't be true, but …

Feedback bug fixes

---

packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.js
packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.spec.js

If these changes make sense, we'll open a new PR (based on #1062), which will in turn take care of #1061.
I merged #1062 and it broke TESS' feedback. I think it's because before merge `metadata-to-rules` would return an array of feedback rule objects, but with the changes TESS' metadata feedback info returned something unexpected. Here is a related screenshot (note `falsy` output is before filtering on Boolean):
I have a few staging projects with LCV feedback, all of which worked with the changes. However, I didn't realize TESS includes subject metadata for feedback with headers like `feedback_[1]_id`, note the `ruleIndex` is `[1]` as opposed to just `1` or `abc` and I think that may have caused the issue, but I can't pinpoint exactly how or why.
staging project …

Refactor feedback metadata-to-rules

---

packages/lib-classifier/src/store/feedback/helpers/generate-rules.spec.js
packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.js
packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.spec.js

Package:
lib-classifier
Closes #1061.
Copies over the changes to feedback from zooniverse/Panoptes-Front-End#5445
Allows feedback with a rule ID of 0 (or other rule keys with falsy values) by converting rule values to strings before checking that they exist.
Also adds a spec and a check for subject feedback where the rule index is not a number.

Allow feedback rules with falsy values 

---

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsCarousel.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsCarousel.spec.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js

Add a carousel view for recent Talk subjects at small screen sizes, plus spec.
Package:
app-project

Talk widget: Add an image carousel

---

packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Package:
lib-classifier
Adds an `append` action to the subject store, plus a couple of specs.

Add subjects.append(newSubjects)

---

packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js

Adds the dark/light theme toggle and responsive context to the project home page.
Package:
app-project

Add the theme toggle to the project home page

---

packages/app-content-pages/docker-compose.yml
packages/app-project/README.md
packages/app-project/docker-compose.yml
packages/lib-classifier/docker-compose.yml

Update docker-compose for the development environment to mount local source files to the running container, but not other files such as local node modules or config.
Should fix problems where `yarn install` has to be run locally in order to use docker for local development, because node modules installed in each package under `/usr/src/packages` are replaced by node modules from the mounted local volume.
Also fixes some errors in the `app-project` README.
Package:
app-project
lib-classifier

docker-compose: mount local source files

---

packages/lib-classifier/src/store/tasks/DrawingTask.js

Changes the switch default from `null` to `types.model({})` so that the classifier doesn't crash with Kitteh Zoo anymore. Its drawing task uses an ellipse which we don't have a model for yet. 
We might want to change line 16 in the workflow step store to do the same?

Change default from null to types.model

---

packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.js
packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.spec.js

For #1112. Not marking as closed because there are a couple more specs and improvements I want to make and I'm not confident this is 100% fixing the bugs I've seen.
Some TESS subjects have metadata with null values:
`metadata-to-rules` helper function attempt to convert this to a string, but `null.toString()` will throw.

Check for null or undefined metadata value

---

.travis.yml
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js

Add an onNewSubject action to the feedback store and add tests when feedback is and isn't active. Rearrange the feedback store tests so that global stubs are only set for the action tests.
Package:
lib-classifier

Test feedback on subject change

---

kubernetes/deployment-staging.tmpl

Use .preview.zooniverse.org for staging assets.

Change the asset prefix for staging

---

packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js

Related to #1112 
Checks if metadata value is null and displays `"null"` for it.
Before:
After:

Handle null subject metadata values to display in table

---

packages/lib-classifier/src/store/feedback/helpers/generate-rules.js
packages/lib-classifier/src/store/feedback/helpers/generate-rules.spec.js

Related to #1112. Checks for the existence of the subject rule id and workflow rule id before calling `toString` on them.

Check id existence before calling toString

---

packages/lib-classifier/src/store/FeedbackStore.js

For #1112 
This checks that there are rules in addition to feedback being active when calling `update` when an annotation is added. This prevents inaccurate feedback metadata being added to the classification. 
This should have tests updated to cover this scenario, but I'm holding to do that to prevent a massive merge conflict with the mobx-upgrade branch.

Prevent classification feedback metadata being added incorrectly

---

README.md
kubernetes/deployment-staging.tmpl

Package: all
As discussed, this switches the k8 config setting to use production environment. I've started on updating the readme to describe this in more detail.

Switch to production environment in k8 config

---

packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js

Make `feedback.isActive` a view that wraps the `isFeedbackActive` helper. Update tests to stub `isFeedbackActive` when they mock active or inactive feedback.
Adds a `feedback.isValid` view, rather than validating feedback in component code.
Package:
lib-classifier

Make feedback.isActive a computed value

---

packages/lib-classifier/src/store/feedback/helpers/is-feedback-active.spec.js

Related to #1121. Updates tests to use `false` as the argument when the resource is invalid. The Feedback store is using `isValidReference` which returns true or false depending on if the active reference is valid.

Update is-feedback-active tests to use false instead of empty object

---

packages/app-project/README.md

Add some notes on how to use docker containers to interactively test apps, i.e. from a bash console in the container with all the required test infrastructure installed.
I found this flow useful:
1.  dip into the code
0. make some changes
0. test my changes using `.only` mocha syntax
0. re-run the tests with `yarn test`
0. iterate until happy

Add docker testing notes

---

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js

Add basic stories for the recent Talk comments component on the project home page.
This PR demonstrates a layout bug with either the Media component or the SubjectThumbnail component: the aspect ratio of the subject preview is wrong for video subjects and portrait images.
Package:
app-project

Add stories for recent talk comments

---

packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.js

Changes the Grid definition in the Connect to Project widget to make it responsive.
Before:
After:

Make Connect widget responsive

---

packages/lib-classifier/src/store/feedback/helpers/generate-rules.js
packages/lib-classifier/src/store/feedback/helpers/generate-rules.spec.js
packages/lib-classifier/src/store/feedback/helpers/is-feedback-active.js
packages/lib-classifier/src/store/feedback/helpers/is-feedback-active.spec.js
packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.spec.js

Package:
lib-classifier
Adds some tests to the feedback helper functions that call them with null, undefined or false (invalid) projects, workflows and subjects.
This is more for completeness than anything else, to rule out another potential cause of #1112.

Test feedback with invalid or undefined arguments

---

packages/app-project/pages/_app.js

The function generating the host URL (used in OG tags etc) is breaking when run on the client. This makes it server/client agnostic by checking for the `req` object, and falling back to `location` when `req` is unavailable.

Make generateHostUrl server-agnostic

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/lib-classifier/package.json
packages/lib-panoptes-js/docs/CHANGELOG.md
packages/lib-panoptes-js/package.json
yarn.lock

Package: lib-panoptes-js, lib-classifier, apps
Published panoptes.js to 0.1.0. This updates the changelog and the libraries and apps that use it.

Update to panoptes.js 0.1.0

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/locales/en.json

Adds a disabled button with a `nothing to classify` message to the Hero component when there are no active workflows. 
cc #1152
Closes #1150

Add no workflows fallback to Hero

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js

Package:
- adds conditional for width > 0 to existing filter on brush annotations before saving brush annotations as classification annotations
Notes:
- I think this could be done in a few different ways, alternatively:
- checking width on const declaration (line 210), if less than zero then handle then, would keep annotation (as opposed to adding in filter which eliminates entire related annotation)
- separate filter, arguably easier to read, possible performance downside (and 2 filters on same thing (`raw`) would be strange)
- I'm sure others
- I didn't see related tests, which I didn't think there were, but might be right in front of me, if so I'll add tests asap
- intentionally as `>` and not `>=`, as I can't think of instance where width would …

Add LCV annotation filter conditional for width greater than zero

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js

Adds an `xsmall` gap between workflow selection buttons in the Hero widget:

Add gap between workflow select buttons

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.js

Adds a `min-height` of `545px` to the Hero component, as per the design review in #1152.

Add a `min-height` to the Hero component

---

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.spec.js

Set the maximum subject thumbnail size to 270px width, 200px height.
See #1152.

Adjust preview thumbnail size

---

packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.spec.js

Fix the img role for the stats chart bars.
Hide the axis tick text, which makes no sense when read out of context.
Package:
app-project

Fix invalid ARIA role

---

packages/app-project/README.md

Update the development instructions to run the dev server and storybook in the background.
Package:
app-project

Run the dev server in the background

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js

Add focus and hover styles to the workflow links on the project home page.
The colour is taken from the Next button styles here:
https://github.com/zooniverse/front-end-monorepo/blob/cacf750a015ce9758c6b044b6f888abffaf9cb92/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js#L24-L29
NB. those workflow links don't have dark theme styles set at the moment, but the current colour seems to work with both light and dark backgrounds.
If we're using these styles in multiple places, then they should be inherited from the theme, rather than defined in a `theme.js` file buried in the classifier.
Package:
app-project

Add focus and hover styles to workflow links

---

packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.js

The lower footer links (privacy policy, jobs etc.) are always displayed horizontally, which is too wide for smaller screens (e.g. iPhone SE). This makes them render vertically on `small` screen sizes.
Weirdly, I found that trying to do it with `styled-components` (by creating a `StyledBox`) broke the spacing between child items :(
Wide:
Narrow:

Make lower footer responsive

---

.dockerignore
Dockerfile
Jenkinsfile
README.md
bin/bootstrap.sh
docker-compose.yml
packages/app-content-pages/Dockerfile
packages/app-content-pages/README.md
packages/app-content-pages/docker-compose.yml
packages/app-project/Dockerfile
packages/app-project/docker-compose.yml
packages/lib-classifier/docker-compose.yml

Package:
lib-classifier
app-project
- Split the docker build into `bootstrap`, which installs the monorepo and builds dependencies, and `production-apps`, which builds the NextJS apps.
- Remove the NextJS builds from the bootstrap script.
- update the docker-compose setup to use the appropriate named target for each local docker image. `front-end-monorepo_dev` builds from the `bootstrap` stage. `front-end-monorepo_prod` builds from the `production-apps` stage.
- rename the test service to yarn, since it runs yarn commands, and remove local mounted volumes when testing the production set-up. If local files change, you'll need to run `docker-compose build` to test the changes in a new production image.
- Update the Jenkins build to build `zooniverse/front-end-monorepo` …

Add a multi-stage Docker build for production apps

---

Jenkinsfile

https://jenkins.io/doc/book/pipeline/docker/#building-containers points out that the argument string should end in a path (I think) to the current build context.

Add the Dockerfile path to the initial build

---

packages/app-project/.storybook/lib/backgrounds.js
packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js

Updates the backgrounds available to be usable as a configuration default for stories. Updates the `SubjectPreview` stories to have a `Box` background that can react to the dark theme toggling as well as add a 'dark theme' story that sets the story background to be like the project app by default.

Update SubjectPreview stories

---

packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js

Add a story for recent Talk subjects, on the project home page, on small screens.
Package:
app-project

Add a story for the recent subjects carousel

---

packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/README.md

Make the collections button self-contained by adding a collections modal to it. Open the modal when the button is clicked (the modal is responsible for closing itself.) Add tests to check that the modal is opened when the button is enabled and clicked.
Package:
app-project
Towards #1193.

Package up the collections button

---

package.json
packages/app-project/package.json
yarn.lock

Install `storybook-deployer`.
Deploy all the storybooks to GitHub pages with `yarn deploy-storybook`.
https://zooniverse.github.io/front-end-monorepo/
Closes #1173.

Deploy all storybooks to GitHub pages

---

packages/app-project/package.json
yarn.lock

Bumps next to the latest production release, allowing us to (amongst other things) use the new `public` folder feature (#1214).

Bump next to 9.1.1

---

packages/app-project/next.config.js
packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js

Closes #1214
Makes `assetPrefix` available as a run-time config property, so that it gets correctly set by the local env var and generates the correct urls. Removes it from the build-time config block, as it would have to be dynamically set by Jenkins and we'd then have to build separate images depending on the environment

Move assetPrefix to runtime config

---

packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js

Update `convertWorkflowToUseSteps` to create steps from `task.tasks` in combo tasks.
Update `setTasks` to log unsupported tasks and continue, rather than failing at the first unsupported task in a workflow.
Add a combo task to the tests when a workflow has no defined steps.
Package:
lib-classifier

Create steps from combo tasks

---

packages/lib-panoptes-js/docs/CHANGELOG.md
packages/lib-panoptes-js/package.json

Follow up to #1229 
Updates the changelog and versions to 0.1.1. The other packages should pick up the update since they use the tilde.

Bump panoptes.js to v0.1.1

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.spec.js
packages/lib-classifier/src/store/tasks/MultipleChoiceTask.js
packages/lib-classifier/src/store/tasks/SingleChoiceTask.js
packages/lib-classifier/src/store/tasks/SingleChoiceTask.spec.js
packages/lib-classifier/src/store/tasks/Task.js

I started adding stories for the text task in #1212 then realised that setting up the Tasks component to work with mocks deserved its own PR.
This PR:
- sets up stories for the Tasks component, using basic mocked stores and the question tasks as an example. 
- converts TaskHelp to a functional component that is conditionally rendered by the Tasks component.
- rewrites the SingleChoiceTask and MultipleChoiceTask components and models so that they can be tested in isolation, following the pattern for the text task in #1212
Package:
lib-classifier

Set up Task stories

---

packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.js
packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.spec.js

Closes #1197.
I've just tested this on https://frontend.preview.zooniverse.org/projects/srallen086/srallen-testing?env=staging, and it looks okay now (possibly because the component was moved in #1233). Just in case, I've added the `fill` prop to the banner `Box`.

Ensure ProjectAnnouncement takes the width of its container

---

packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/tasks/DataVisAnnotationTask.js
packages/lib-classifier/src/store/tasks/DrawingTask.js
packages/lib-classifier/src/store/tasks/MultipleChoiceTask.js
packages/lib-classifier/src/store/tasks/SingleChoiceTask.js
packages/lib-classifier/src/store/tasks/SingleChoiceTask.spec.js
packages/lib-classifier/src/store/tasks/Task.js
packages/lib-classifier/src/store/tasks/Task.spec.js

This PR delegates responsibility for creating new annotations to individual tasks, with the aim of simplifying the classifications store and making it easier to add new tasks.
- Add a default annotation to each task model.
- Add a generic createAnnotation action to all tasks.
- Remove getAnnotationType and createDefaultAnnotation from the classifications store.
Package:
lib-classifier

Add a default annotation to tasks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js

Preload subject images with a HTML `<img>` element. Set subject dimensions and render the SVG image once the HTML image has loaded.
Add stories for the image viewer.
Package:
lib-classifier
For #1094.

Preload images for the single image viewer

---

packages/lib-classifier/.babelrc
packages/lib-classifier/.storybook/webpack.config.js
packages/lib-classifier/package.json
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/index.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/locales/en.json
packages/lib-classifier/src/plugins/tasks/TextTask/index.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/webpack.dev.js
packages/lib-classifier/webpack.dist.js
packages/lib-grommet-theme/CHANGELOG.md
packages/lib-grommet-theme/src/index.js

Adds the text task from #1212 without any of the changes to component loading. The new task code is manually added to each component or store that depends upon it.
I've kept the file structure from #1212 for convenience, but that can be changed.
EDIT: functionally, this works but it needs styling. 
Package:
lib-classifier
Closes #1141.

Add a text input task

---

packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.stories.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.stories.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.stories.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.stories.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.spec.js
packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/FeedbackStore.spec.js
packages/lib-classifier/src/store/FieldGuideStore.spec.js
packages/lib-classifier/src/store/Subject.spec.js
packages/lib-classifier/src/store/SubjectStore.spec.js
packages/lib-classifier/src/store/TutorialStore.spec.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js
packages/lib-classifier/src/store/WorkflowStore.spec.js
packages/lib-classifier/webpack.dev.js

Alias the classifier test utils directory to `@test` for more convenient module resolution.
Package:
lib-classifier

Alias test/ to @test in dev

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Background/Background.js

Hero images can currently expand beyond the available space in the Hero widget if they're taller than the height of the workflows box; this forces them to only flex to the available height.

Only allow hero images to fill available space

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/locales/en.json

Following on from our Slack conversation, this changes the call to action to "Get Started!"

Replace "Classify" with "Get started" as the call to action

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.spec.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelectorContainer.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelectorContainer.spec.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/index.js
packages/app-project/stores/Project.js
packages/app-project/stores/Project.spec.js

This allows the project home page to use the project's workflow description if available, and falls back to a default message if there isn't one specified.
As @eatyourgreens pointed out, this is a localised string; next thing to do is setup a language store, and enhance the resource models to support translations.

Use the project's workflow description

---

packages/lib-grommet-theme/README.md

Adds examples of the colours used in the theme to the README for `lib-grommet-theme`

Add colour examples to readme

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/lib-classifier/package.json
yarn.lock

Package: app-project, lib-classifier, app-content-pages
Updates the PJC dependency to the latest release candidate to prepare for Panoptes's update. We're still using the auth client from PJC here.

Update PJC for auth client use

---

packages/app-project/stores/Project.js
packages/app-project/stores/Project.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.spec.js

Closes # .
Fixes the `Project` model in the project app because the `workflow_description` can be null from Panoptes.

Workflow description can maybe be null

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingMarks/DrawingMarks.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/components/tools/DeleteButton.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/components/tools/DrawingToolRoot.js

Package:
lib-classifier
Add the drawing tool root to the tab order so that we can tab through drawn marks.
Select and deselect marks on focus and blur.
Add labels to marks so we can announce focus changes.
Add a label to the delete button.
Testing this in the dev classifier: Draw a few marks, click the theme toggle to focus it, then Tab/Shift-Tab forward and backward through the page. All drawn marks should be in the page tab order.

Drawing: Add drawn marks to the tab order

---

packages/lib-classifier/package.json
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
yarn.lock

Upgrade mobx-react to 6.1.4, which supports hooks.
The drawing tool work uses React Hooks, which aren't supported by `mobx-react` version 5. As a result, some of the new drawing components can't be wrapped in observers.
Package:
lib-classifier

Upgrade mobx-react to version 6

---

packages/lib-classifier/src/plugins/tasks/models/Task.js
packages/lib-classifier/src/store/AnnotationsStore.js
packages/lib-classifier/src/store/AnnotationsStore.spec.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/ClassificationStore.js

Generalise annotations, in preparation for drawing subtasks.
- Move annotations to an AnnotationsStore model, so that they can be also be used by drawing marks.
- Make Classification an AnnotationsStore.
Package:
lib-classifier

Extract annotations out of classification model

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js

Fix tests that broke in #1308.
Remove the DrawingContainer from tests, as it's no longer used anywhere.
Replace rect with a styled rect in InteractionLayer tests.
Package:
lib-classifier

Drawing: Fix broken tests

---

.travis.yml
package.json
yarn.lock

Package:
all
Upgrade coveralls. Switch CI to run `npm run test:ci` since yarn was generating empty coverage reports.

Upgrade coveralls to 3.0.9 and fix CI coverage reports

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js

Add a generic `Tool` model.
Add `tool.disabled` to all tools.
Disable tools when `tool.marks` reaches its max size.
Disable the drawing surface when the active tool is disabled.
Disable a tool choice in the task area when that tool is disabled.
Add `task.isComplete` to drawing tasks (see #1307.)
Package:
lib-classifier

Drawing: limit marks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js

Target: `drawing-remove-rxjs` (#1266)
This PR fixes the issue in `drawing-remove-rxjs` where the classifier app crashes when encountering a Task that's not a Drawing Task.
- `InteractionLayerContainer` now performs existential checks for the `activeDrawingTask` and `activeTool` variables.
- The `InteractionLayer` is only used for drawing interactions, so is displayed ONLY when there's an active Drawing Task in the Workflow, AND an Active Drawing Tool is selected for that task.

Drawing: fix InteractionLayer's crash from 'undefined' activeDrawingTask/activeTool

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton.js
packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js
packages/lib-classifier/src/plugins/drawingTools/components/Line.js
packages/lib-classifier/src/plugins/drawingTools/components/Point.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Line.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Point.js

Calculate the subject image scale when the subject image loads. Pass the scale down as a prop to marks. Scale rendered mark sizes and delete button position.
Package:
lib-classifier

Drawing: scale marks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js

Disable pointerDown events when the interaction layer is disabled, but allow other pointer events to be handled.
Package:
lib-classifier
Closes #1355.
TODO:

Drawing: disable mark creation

---

packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.js
packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js

Replace transformation matrices with scale transforms where they are being used for linear scaling.
Package:
lib-classifier

Drawing: Remove transformation matrices

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js

Delete marks when they are completely outside the SVG drawing canvas by comparing the bounding client rectangles of the mark element and the parent SVG element. Based on PFE's [`isInBounds`](https://github.com/zooniverse/Panoptes-Front-End/blob/abab2b0115231dc34fd824f70f46a0c372b3043e/app/lib/is-in-bounds.coffee#L1-L8) function.
Package:
lib-classifier
Closes #1334.

Drawing: check for out-of-bounds marks

---

packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js
packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js

Add names for the forwardrefs in the DragHandle and DrawingToolRoot components.
Add Component.render.name as a third option when trying to figure out a component's name.
Package:
lib-classifier
Closes #1386.

Name anonymous forwardRef functions

---

docs/arch/README.md
docs/arch/ad-22.md
docs/arch/adr-15.md
docs/arch/adr-22.md
packages/lib-classifier/src/plugins/drawingTools/README.md

A description of the drawing tools and their public interfaces.
Package:
lib-classifier
Closes #1350.

ADR 22: Drawing tools

---

docs/arch/README.md
docs/arch/adr-23.md

An ADR describing why `plugins/tasks` was added to the classifier, with some questions about how it might be changed or improved.
Package:
lib-classifier
Closes #1351.

Add an ADR for task plugins

---

packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.js
packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js

Define prop types and defaults for the drawing delete button.
Add specs for the delete button.
Package:
lib-classifier

Drawing: Add delete button specs

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js
packages/lib-classifier/src/plugins/drawingTools/shared/SVGContext.js

https://github.com/zooniverse/front-end-monorepo/pull/1388#pullrequestreview-335473579 suggests moving away from transforming the SVG element directly when we transform drawings eg. by rotating the subject.
This PR removes the `svg` prop from drawing components and replaces it with `SVGContext`, which can be used to pass the transformation context to child components.
Enzyme's shallow rendering doesn't support `useContext` so a few components are now tested with a full DOM mount.
Package:
lib-classifier

Drawing: Replace svg props with SVGContext

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
packages/lib-classifier/src/store/SubjectViewerStore.js
packages/lib-classifier/src/store/SubjectViewerStore.spec.js

Add a `rotate()` transform to SVG subject images.
Add a `rotation` angle and `rotate()` action to the SubjectViewer store.
Enable the rotation button in the image toolbar.
TODO:
Package:
lib-classifier

Add subject image rotation

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Line/Line.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.js

Use `getParentOfType` to get the tool that created a mark.
Remove redundant tool props from mark components.
Pass marks to annotations by reference.
Clear stale marks from a tool if the current annotation is empty.
Remove `workflowSteps.tasks`, which was only being used to look up the tool for a given mark.
Add tests for rendered marks in the subject viewer.
Package:
lib-classifier
Closes #1363.

Drawing: Use the state tree to get a mark's tool

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js

- Remove `useState` from tasks, so that the current task value is always passed in as a prop via the task annotation.
- Observe tasks for changes.
- Rewrite tests to directly test annotation values.
Package:
lib-classifier
Closes #1407.

Remove useState from tasks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js

Add the current drawing task marks to the InteractionLayer as an observable array.
Package:
lib-classifier
Closes #1411.

Drawing: Add marks prop to InteractionLayer

---

packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js

Add stories for the Line and Point drawing marks. Each mark has an active and complete (deselected) state.
Package:
lib-classifier

Add Line and Point stories

---

packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js

Add getAngle and getDistance to all marks.
Add tests.
Package:
lib-classifier

Drawing: Add angle and distance helpers to marks

---

packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js

Change `mark.tool` to return a mark's grandparent, rather than search for a parent of a specific type.
Package:
lib-classifier

Make mark.tool generic

---

packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.spec.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js

Make (x, y, angle) common, optional properties for all marks, defining the position of the mark and rotation about that position.
Package:
lib-classifier

Drawing: Add x, y, angle to drawing tool root

---

packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool/LineTool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js

Add toolType to all marks.
Add toolType to createMark for all tools.
Add a type to the Tool model.
Update tests.
Package:
lib-classifier

Drawing: Add toolType to marks

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.js
packages/lib-classifier/src/plugins/tasks/models/Task.js
packages/lib-classifier/src/store/Step.spec.js

Towards #1239. In order to render a form for the drawing subtasks linked to a particular transcription line, we want to be able to pass an annotation into a Task component independent of whether that annotation comes from the classification or a mark.
- connect `Tasks` to the classifications store.
- get the current annotation for each task from `classification.annotations`.
- Pass annotations into `TaskComponent` as an `annotation` prop.
- Add `annotation.update(value)` to update an annotation independent of where it is stored in the state tree.
- Update tests.

Decouple Task components from classifications

---

packages/app-project/next.config.js
packages/app-project/pages/_document.js

Catch errors during `Document.getInitialProps(ctx)` and log them to Sentry. Render the error message to the page.
Pass SENTRY_DSN to the browser when webpack bundles the client code.
Package:
app-project
Closes #1451 (I think.)

Project app: catch errors in initial page render

---

packages/app-project/next.config.js
packages/app-project/package.json
yarn.lock

Package:
app-project
Add `withSourceMaps()` to the project app config.
Install `@zeit/next-source-maps@0.0.4-canary.1` to get client and server source maps.

Project app: add source maps to the NextJS build

---

packages/lib-grommet-theme/CHANGELOG.md
packages/lib-grommet-theme/README.md
packages/lib-grommet-theme/src/index.js

Package:
Closes #1456
Adds white to theme since we're using it with a couple of the newer WIP subject viewers.

Add white to theme

---

packages/lib-classifier/src/store/AnnotationsStore.js
packages/lib-classifier/src/store/AnnotationsStore.spec.js
packages/lib-classifier/src/store/ClassificationStore.js

Add `annotationsStore.removeAnnotation(taskKey)`, which finds the last annotation matching the supplied task key and removes it from the store.
Package:
lib-classifier
Closes #1498.

Classifier: delete annotations by task key

---

packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js

Test drawing tool subtasks by checking the task model against an expected snapshot for each type of valid subtask.
Package:
lib-classifier

Drawing: fix evergreen subtask tests

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js

Move `activeMark` and `setActiveMark` to the drawing task model, so that the active mark can be accessed from the subtask popup box.
Package:
lib-classifier
Towards #1315.

Drawing: add active mark to the drawing task

---

packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js

Fixes #1507 
This PR fixes an issue where, when a user clicks on an Answer label, the label isn't highlighted (marking it as selected/active) BUT the answers are correctly recorded in the Classifications.
Can be tested on any workflow with a single multiple-choice-answer task, e.g. http://localhost:8080/?env=staging&project=1895
The issue stems from (what appears to be) a conflict with the _store observers_ applied to the MultiChoiceTask component. Specifically, when the MultiChoiceTask component is exported with the `withTheme` decorator, the component stops listening for changes in the annotations store.
This means that when a user clicks on an Answer (i.e. action on a component), the annotations store will _correctly_ update (i.e. the selected answer is added …

Fix 1507 - allow MultipleChoiceTask component to observe changes again

---

packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.spec.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/Classification.spec.js
packages/lib-classifier/src/store/ClassificationStore.js

Package:
lib-classifier
Towards #1443.
Use snapshot processors to serialise classifications as per [ADR 25](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-25.md#annotation-json-structure-1).
Add a new `toSnapshot` view to annotations and classifications, which returns a snapshot where all references have been resolved to full snapshots.

Drawing: Add classification snapshot processors

---

packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
packages/app-content-pages/src/screens/Team/TeamContainer.js
packages/app-content-pages/src/screens/Team/TeamContainer.spec.js

Package: app-content-pages
Closes #1499 
If the contentful API call errors (missing secret client setup) then the `teamData|publicationsData` are left undefined. This PR fixes this issue by adding a check for undefined values and replaces them with an empty array on props and adds default values to the API requests
For bonus points (and learnings), I added tests on the default props API calls to contentful API for team and publications data.

fix content pages pages when API data is unavailable

---

packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
packages/app-content-pages/src/screens/Team/TeamContainer.js
packages/app-content-pages/src/screens/Team/TeamContainer.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.spec.js
packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/Classification.spec.js
packages/lib-classifier/src/store/ClassificationStore.js

This reverts commit 7aceaca920df06d831e2de8e653d8d3291b2e5a2.
Restore staged features from #1506 and #1475.

Revert "Tmp revert for migration (#1515)"

---

packages/app-content-pages/README.md
packages/app-content-pages/docker-compose-prod.yml
packages/app-content-pages/docker-compose.yml
packages/app-project/README.md
packages/app-project/docker-compose-prod.yml
packages/app-project/docker-compose.yml

use existing docker-compose for dev workflows and testing. Add a prod compose file for testing the project app dockerfile manually
Linked to #1494

add prod compose file for production dockerfile testing

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js

Fixes #1536 
This PR fixes issue 1536, where the Classifier would crash every time a Classification is submitted. This problem seems to stem from the `SVGPanZoom` component attempting to remove an event listener for an `undefined` DOM element on unmount, which in turn was caused by the use of `createRef()` instead of `useRef()`
Here are the tech deets:
- when _mounting the component,_ `scrollContainer.current` is correctly defined as a HTML node.
- when _unmounting_ however, `scrollContainer.current` is `undefined`
- Turns out, this is because `createRef()` doesn't play well with _functional components..._ because it apparently supposed to be called only once (i.e. `constructor () { this.myRef = createRef() }` ), and with functional components the initial value …

Fix 1536 - allow Classifier to submit Classifications without Crashing

---

packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js

Remove `DrawingTask.afterCreate()`.
Add preprocessors to both the drawing task and tool models, which will generate valid task snapshots from tool details if none are already present in the provided snapshot. This allows us to load in tools created by the project builder while also writing new code that can generate tools directly from snapshots eg. when creating tools for tests.
Package:
lib-classifier

Drawing: generate subtasks from tool details

---

packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js

Set colours for line state: active, transcribed, completed or default.
Add start and end circles.
Package:
lib-classifier

Transcription line updates

---

packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js

Package:
lib-classifier
A couple of small changes to the `draggable` decorator, which makes SVG components draggable.
- remove the `dragging` prop from child components/elements. It wasn't being used for anything except debugging.
- remove the `coords` prop from children.
- pass back the `{ x, y }` coordinates of the pointer on `dragMove`. This isn't being used at the moment, but will be needed for shapes that use rotation transforms (eg. the ellipse) and for freehand drawing.

Drawing tools: draggable updates

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js

Fixes #1543 
This PR ensures that when a drawing mark isn't active (i.e. it was made in a previous workflow step), it can't be moved.
EDIT: Just saw @eatyourgreens's comment in https://github.com/zooniverse/front-end-monorepo/issues/1543#issuecomment-591973928

Fix 1543 - inactive drawing marks must not be draggable

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/FocusSeriesCheckBoxes.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/FocusSeriesCheckBoxes.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/index.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js

Package:
Closes #1429
**PRs #1526 and #1527 need to be merged first**. This adds the functionality for toggling UI focus on data series in the variable star viewer. WIP because this still needs some specs for the changes in `Controls`, but there's some setup for nock in #1527 that I'd like to use, so that comes first.
This should be manually testable in the storybook, but here's also a gif demonstrating it:
And a close up screenshot of the hover/focus state because the gif doesn't show it well:
Indesign links for comparison:
Design for checked/unchecked style state: https://projects.invisionapp.com/d/main#/console/17294981/4030 …

[VSLCV] Series focus control

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js

Add the `withTheme` decorator to the task area, then pass the theme down to individual tasks as a prop.
See #1507 and #1511 for context. `observer` can't be applied to a component that's been decorated with `withTheme`, so we have to be careful how the theme is passed down to observed tasks.
Package:
lib-classifier

Classifier: Pass the theme prop to task components

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js

- adds refs, scroll handlers so active frame is visible if list of frames has overflow
- misc. styling cleanup

Add frame scroll handler

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/store/AnnotationsStore.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/FeedbackStore.js
packages/lib-classifier/src/store/FeedbackStore.spec.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/RootStore.spec.js
packages/lib-classifier/src/store/Subject.spec.js
packages/lib-classifier/src/store/TutorialStore.spec.js
packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js
packages/lib-classifier/src/store/WorkflowStore.spec.js

Consolidate the subject observers from the feedback, workflow steps and classifications stores into one function in the root store. When the subject changes, reset the workflow steps, create a new classification, then reset subject feedback. I think this will fix #1521 by making sure the first task is selected before the classification is created.
This PR also fixes a couple of infinite loops that showed up in the Tutorial Store tests (infinitely requesting new subjects) and the UPP Store tests (infinitely requesting a new workflow.) 
I've also moved the Feedback `onAction` listener up to the root in order to mute warnings from that store. Classification and Mark `onAction` listeners are replaced with `beforeDestroy` actions to remove those warnings too. Otherwise, I was finding the …

Classifier: Consolidate store subject observers

---

packages/lib-classifier/src/store/SingleImageSubject/SingleImageSubject.js
packages/lib-classifier/src/store/SingleImageSubject/SingleImageSubject.spec.js
packages/lib-classifier/src/store/SingleImageSubject/index.js
packages/lib-classifier/src/store/Subject/Subject.js
packages/lib-classifier/src/store/Subject/Subject.spec.js
packages/lib-classifier/src/store/Subject/index.js
packages/lib-classifier/src/store/SubjectGroup/SubjectGroup.js
packages/lib-classifier/src/store/SubjectGroup/SubjectGroup.spec.js
packages/lib-classifier/src/store/SubjectGroup/index.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore.spec.js

Adds a basic model for grouped subjects, which are composed of single image subjects. A `SingleImageSubject` is a refinement of `Subject` which has exactly one image. Not 0. Not 2. Three is right out.
Package:
lib-classifier
Towards #1484.

Classifier: Grouped subject models

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/index.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js

Show the move cursor when subject images can be panned by dragging.
Package:
lib-classifier
Closes #1489.

Classifier: Add the move cursor to draggable subjects

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js

Fixes errors that are preventing the project hero and workflow selector stories from working in the storybook.
- removes the broken mock router context from the stories.
- adds a mock store and provider.
- adds existence checks before using the Next router.
- defaults project and owner in the URL to `undefined`.
Package:
app-project
Closes #1446.

Project hero stories

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStore.js

Tasks stories created a new store each time the story function ran (eg. when a knob setting changes), which throws errors in the MobX Provider. The store is redefined here to be a single, constant variable and individual stories change it by calling actions on the WorkflowSteps model.
Some undefined reference errors in individual stores are also caught and fixed here.
Package:
lib-classifier

Classifier: fix Tasks storybook errors

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js

Pulls out relevant fixes from #1576 for the task stories. I've included one tiny bug fix for the TaskHelp for the key prop as well.

Fix background, Grommet props for Task stories

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js

The zoom in/out buttons call onPointerUp twice when released. The second call throws errors in PEP, since the active pointer has already been released. Fix this by stubbing the onClick handler for the Grommet button.
Package:
lib-classifier

Classifier: fix pointer not found errors

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js

Add zoomIn/zoomOut as a click handler for the Grommet zoom buttons. This allows the buttons to be operated with the Enter key or the spacebar.
Package:
lib-classifier
Closes #1581.

Classifier: fix zoom button key handlers

---

packages/app-content-pages/next.config.js
packages/app-content-pages/package.json

Enable source maps for the content pages app. See also #1467.
Package:

Add withSourceMaps to app-content-pages

---

Jenkinsfile
kubernetes/deployment-production.tmpl
kubernetes/deployment-staging.tmpl
packages/app-project/src/helpers/logger/initializeSentry.js

Remove the shared environment from Jenkins builds. Instead, declare the Git commit and Sentry DSN separately for each NextJS app build.
Also fix that I set the wrong DSN for the project app in #1590.
Package:
app-project
Closes #1592.

Remove shared environment from Jenkins builds

---

.github/workflows/main.yml
packages/app-content-pages/src/helpers/logger/initializeSentry.js
packages/app-project/src/helpers/logger/initializeSentry.js

Add a couple of new GitHub actions.
- on merge to master, create a new Sentry release from the commit SHA, link to all commits since the last finalised release and deploy it as a staging release.
- on publishing a new release, which is always production-release for this repo, get the existing release for the commit SHA and finalise it, then deploy as a production release.
Update the Sentry client to use commit SHA for release versions.
Package:
app-project
Closes #1583.

Create Sentry releases on push to master

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
packages/lib-classifier/src/helpers/createLocationCounts/createLocationCounts.spec.js
packages/lib-classifier/src/helpers/index.js
packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.js
packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.spec.js
packages/lib-classifier/src/helpers/validateSubjectLocations/index.js
packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js
packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.spec.js
packages/lib-classifier/src/store/Subject/Subject.js
packages/lib-classifier/src/store/Subject/Subject.spec.js
packages/lib-classifier/src/store/SubjectStore.js

- Add `validateSubjectLocations` to the Subject model as a refinement for locations.
- Change the MIME type and file extension validators to return false, rather than throwing, for invalid MIME types and file extensions.
- Expect `Subject.create(snapshot)` to throw an error if the provided snapshot  contains invalid file locations.
Package:
lib-classifier

Classifier: Validate locations before creating subjects

---

Jenkinsfile
kubernetes/deployment-production.tmpl
kubernetes/deployment-staging.tmpl

Add the NextJS app build environment (staging or production) to their Docker image names, so that we can distinguish between staging and production versions of the apps when deploying.

Add build environment to Docker image names

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js

The test project and workflow http://local.zooniverse.org:8080/?project=1764&workflow=3392 using the transcription task was failing to go to the next step of tasks. This was because of a missing safe reference type in the models. The filter for the annotations to display previous task marks also had a syntax error. 
WIP because I'm going to look to see if there are any tests that can be updated or added.

Fix transcription task when there are other steps

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js

Fixes subtask showing after all drawing tools, even if no subtasks.
- adds conditional check for subtasks (`mark.tasks`) before setting subtask visibility (`setSubTaskVisibility`)

Add check for subtasks before setSubTaskVisibility

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js

This PR allows custom Subject Viewers to have their own configuration objects, in their respective Workflow's configuration object.
- For example, this workflow configuration states that we want to use the "Subject Group" viewer (which displays images in a grid) in this workflow, and that SubjectGroupViewer should be using a 5x5 grid:
```
workflow.configuration = {
subject_viewer: 'subjectGroup',
subject_viewer_config: {
grid_columns: 5,
grid_rows: 5
}
}
```
- The definition of a custom Subject Viewer's configuration object is specific to that Subject Viewer (effectively arbitrary at this point of development) so I used `type.frozen`
- Additionally, the SubjectGroupViewer component - the primary viewer that will be affected by/that requires this update - has been …

Classifier: add `subject_viewer_config` to `workflow.configuration`

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js

- http://localhost:8080/?project=1876&workflow=3363
- adds related test and refactor to save current frame when creating mark

Add frame to InteractionLayer mark creation

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
packages/lib-classifier/src/store/SubjectViewerStore.js
packages/lib-classifier/src/store/SubjectViewerStore.spec.js

Towards #1538, however, this refactors for transcription workflows. **Conditionally setting pan, zoom and rotation based on task or workflow is still needed.**
- refactors SVGPanZoom to reset on new image
- refactors SubjectViewerStore to reset rotation in `onSubjectReady`

Refactor to reset pan, zoom, or rotate on new frame

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.stories.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.stories.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.stories.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.stories.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.stories.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/TranscriptionTask.stories.js
packages/lib-classifier/test/factories/tasks/TranscriptionTaskFactory.js

Reorganizes the stories to be closer to their code and enables us to add multiple stories per task. Refactored `TranscriptionLine` to be task flexible as we want to allow project builders to use the tool type in either the drawing task or transcription task. The colors are only hardcoded and have meaning for the transcription task, so this adds a `color` prop back to the `TranscriptionLine` and set the default state to be an empty string. The `state` prop will only be set by the TranscriptionTask or TranscribedLines models in a follow up PR.
As an aside, the task stories refactor and the …

Reorganize task stories. Make TranscriptionLine task type flexible for color

---

packages/lib-classifier/src/store/Classification.js
packages/lib-classifier/src/store/Classification/Classification.js
packages/lib-classifier/src/store/Classification/Classification.spec.js
packages/lib-classifier/src/store/Classification/ClassificationMetadata.js
packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js
packages/lib-classifier/src/store/Classification/index.js
packages/lib-classifier/src/store/ClassificationStore.js
packages/lib-classifier/src/store/ClassificationStore.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js

Replace updateClassificationMetadata() with classification.metadata.update().
Package:
lib-classifier

Classifier: Remove updateClassificationMetadata

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js

Towards #1625. 
- filters marks by current frame
For a subsequent PR - filtering marks by frame should be dependent on [workflow/subject-viewer configuration](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js#L9) as while a transcription workflow would likely want this behavior a survey workflow may not, similar to #1538.

Add marks filter per frame

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js

This fixes another broken story found under the ScatterPlotViewer that shows multiple data series and vertical error bars. It's using the mock variable star LCV data.

Fix scatter plot story

---

packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
packages/app-content-pages/src/screens/Publications/getStaticProps.js
packages/app-content-pages/src/screens/Publications/getStaticProps.spec.js
packages/app-content-pages/src/screens/Team/TeamContainer.js
packages/app-content-pages/src/screens/Team/getStaticProps.js
packages/app-content-pages/src/screens/Team/getStaticProps.spec.js
packages/app-content-pages/src/screens/Team/locales/en.json

On API errors, we don't want to build a static page which is then served for the next hour. Instead, log the error to Sentry and rethrow. NextJS should serve up its default 500 error page, then attempt to rebuild on the next request.
Package:
Closes #1687.

Content pages: Abort static page builds on API errors

---

packages/lib-react-components/src/index.js

Export the ZooniverseLogotype component from Zooniverse React Components.
Package:
Closes #1708.

ZRC: export ZooniverseLogotype

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.spec.js

- in SubTaskPopupContainer adds check for `activeMark.subTaskVisibility`, if `false` return `null`, if `true` return `SubTaskPopup` component

Add activeMark subTaskVisibility check to SubTaskPopup render

---

packages/lib-react-components/CHANGELOG.md
packages/lib-react-components/package.json

Closes #1708 
With #1710 merged, the lib-react-components package is ready for a patch push to npm, allowing the ZooniverseLogoType to be exported.

Patch React Components

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js

Closes #1702.
- refactors `React.createRef()` within completed and transcribed lines map, now creating ref per line
- updates callbacks, `createMark`, `showConsensus` accordingly ^

Refactor transcribed lines ref for subtask positioning

---

packages/lib-classifier/webpack.dev.js

I was having trouble getting the dev classifier mini app to run without this setting in the latest chrome. If you get an invalid certificate error and it won't let you continue, you can type in `badidea` while on that tab, then it'll load the page (sneaky chrome!).

Add https: true setting for the dev classifier

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.spec.js

Towards #1719.
- add tests for transcribed lines filtered by frame and shownMarks
- refactor TranscribedLinesContainer to return null if shownMarks not all or no lines per frame
- refactor TranscribedLinesContainer to render TranscribedLines with only lines per frame

Refactor TranscribedLinesContainer for frame and shownMarks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js

Towards #1719. 
- refactor InteractionLayerContainer tests for previous annotation values from multiple frames
- refactor InteractionLayerContainer to filter previous annotation values per frame

Refactor InteractionLayerContainer to filter previous annotation values per frame

---

package.json
yarn.lock

Bump storybook-deployer to 2.8.6.

Upgrade storybook-deployer

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json

Based on feedback from the researcher, I'm modifying the period calculation to only apply the result to the period bar chart. ~Draft PR pending on ok from the researchers on this change.~ Researcher's have approved change.

Only calculate period bar chart

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js

Fixes #1688 
`onPointerDown` method now checks for an active tool before running. Several prettier updates.

Added a check for active tool

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerConnector.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerConnector.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/index.js

I've added a connector component to connect the VSLCV to the stores. This is similar to what I've recently done with the `DataImageViewer`. It provides a separation of concerns and the ability for us to more easily test the store connection in isolation.
In addition, the VSLCV is now actually connected to the stores to get the active subject.

Refactor VSLCV to use connector component

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/index.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.spec.js
packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js

This finishes adding support for several more specific subject viewers, including the VSLCV, so that we can actually load a workflow with this configuration.

Allow for configuration of several more viewers

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
packages/lib-react-components/CHANGELOG.md
packages/lib-react-components/src/CloseButton/CloseButton.js
packages/lib-react-components/src/CloseButton/CloseButton.spec.js
packages/lib-react-components/src/CloseButton/CloseButton.stories.js
packages/lib-react-components/src/CloseButton/README.md
packages/lib-react-components/src/Modal/Modal.js
packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.js
packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.spec.js
packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js
packages/lib-react-components/src/MovableModal/MovableModal.js
packages/lib-react-components/src/MovableModal/MovableModal.stories.js

Package:
lib-classifier
Closes #1785.
Remove the default heading colours from the `Modal` component, so that the defaults in `ModalHeading` are used.
Fixes padding around the content in `ModalBody` too.
Adds a few tests to check default props, where styles are passed as props.
TODO:

ZRC: Fix modal default colours

---

packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js

Package:
app-project
When a project's workflows are complete, the active workflows query returns an empty response. This adds a test to `fetchWorkflowsHelper` for that case, and fixes the API handler to return an empty response for the project Hero component.

Project: Fix the workflows helper when all workflows are complete

---

packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/dev/index.js
packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.js
packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.spec.js
packages/lib-classifier/src/store/Workflow/SubjectSet/index.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.spec.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/index.js
packages/lib-classifier/src/store/Workflow/Workflow.js
packages/lib-classifier/src/store/Workflow/Workflow.spec.js
packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
packages/lib-classifier/test/factories/SubjectSetFactory.js
packages/lib-classifier/test/factories/WorkflowFactory.js
packages/lib-classifier/test/factories/index.js

Add `workflow.subjectSets`, which is a `SubjectSetStore`. Use `workflow.subjectSets.active` for subject selection.
Based off #1804.
~~Set to draft because workflow store tests are failing with invalid reference errors.~~

Add a subject set store to workflows

---

packages/lib-classifier/dev/components/App/App.js
packages/lib-classifier/dev/index.js
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/store/ResourceStore/ResourceStore.js
packages/lib-classifier/src/store/ResourceStore/ResourceStore.spec.js
packages/lib-classifier/src/store/ResourceStore/index.js
packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.js
packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.spec.js
packages/lib-classifier/src/store/Workflow/SubjectSet/index.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.spec.js
packages/lib-classifier/src/store/Workflow/SubjectSetStore/index.js
packages/lib-classifier/src/store/Workflow/Workflow.js
packages/lib-classifier/src/store/Workflow/Workflow.spec.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js
packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
packages/lib-classifier/src/store/WorkflowStore/index.js
packages/lib-classifier/test/factories/SubjectSetFactory.js
packages/lib-classifier/test/factories/WorkflowFactory.js
packages/lib-classifier/test/factories/index.js

Package:
lib-classifier
Closes #1792 
Explicitly call the `workflows.selectWorkflow(workflowID)` action when the classifier mounts. Pass in any `workflowID` prop that was passed to the classifier, otherwise fallback to default project workflow selection. Remove the `selectWorkflow()` actions that automatically run when the project or UPP loads.
Add an optional `subjectSetID` parameter, which will restrict subject selection to that subject set: `workflows.selectWorkflow(workflowID, subjectSetID)`.
Workflow and subject set IDs are validated against a project's linked active workflows and a workflow's linked subject sets before being loaded.

Classifier: load specific workflows and subject sets

---

packages/app-content-pages/package.json
packages/app-content-pages/server/set-logging.js
packages/app-project/package.json
packages/app-project/server/server.js
packages/app-project/server/set-cache-headers.js
packages/app-project/server/set-cache-headers.spec.js
packages/app-project/server/set-logging.js
packages/app-project/server/set-logging.spec.js
yarn.lock

Add express to the project app, with [morgan](https://github.com/expressjs/morgan) for request logging. The server setup is copied from #950, including cache headers.
Bumps morgan to 1.10.
Package:
app-project
Closes #1468.
Closes #1807.

Project: Add app-project express server

---

kubernetes/deployment-staging.tmpl

Package:
Turn on the cache headers added in #950 and #1812, allow the app to specify how long resources should be cached in CDN, browsers for.

turn on app cache headers

---

kubernetes/deployment-production.tmpl

turn on the caching headers for next js apps. Ensure that our CDN doesn't indefinitely cache the app response pages and break our deploys.
Package: app-project & app-content-pages

enable cache headers on production services

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
yarn.lock

Upgrade the NextJS apps to mobx-react 6.1.4.
The upgrade breaks refs in a couple of places in the project app, so there are some changes to the 'add to collections' modal in order to fix those.
Package:
app-project

Upgrade to mobx-react 6

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
yarn.lock

This reverts commit 0ca7407f56a19d16fb9f58390742ea72350073ed.
This reverts the mobx-react upgrade. Possible cause for #1839 based on the change set that went out with the last deploy (https://github.com/zooniverse/front-end-monorepo/compare/7ae8d2e2d6d45f4145ce3ea00ee5ec8095282177...682f0d0fd29102419f30c37e4cb09a49b604cf0e), but unconfirmed since I've been unable to replicate. Given that the reports began after the deploy last Thursday, it's reasonable to suspect something within the latest change set and the mobx-react upgrade is the only one that I reasonable think could be a cause. An alternative would be to point the production tag back to …

Revert "Upgrade to mobx-react 6 (#1820)"

---

packages/lib-classifier/src/store/SubjectStore.js

This PR adds a console message that helps us track Subject IDs.
- The message `Loading subject 12345` appears in the dev console when a new Subject is loaded, where 12345 is the Subject's ID.
- This is mostly useful for Sentry error logging, to identify which Subject was encountered before/during a crash.
Context: this addition is being made to help debug a TESS bug that's difficult to replicate locally. Our suspicion is that specific subjects are causing the crash, but we don't have enough data in our logs to determine which subjects.
- Open any project with Subjects, e.g. `https://local.zooniverse.org:8080/?env=production&project=12754`
- The message should appear whenever a new Subject loads, i.e. getting the first Subject on page load and after clicking …

Classifier: add a console message when loading Subjects

---

packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
packages/lib-classifier/src/plugins/tasks/models/Task.spec.js

Test `task.defaultAnnotation` for each task type. Verify that it generates unique annotation IDs.
Package:
lib-classifier

Classifier: Test default annotations for tasks

---

packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/index.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/index.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.spec.js
packages/lib-classifier/src/store/Step.js

This adds an adapter (and tests) for the simple dropdown task, so that we can test it out in staging. Dropdown tasks are converted to simple dropdown tasks if they contain only one select menu. More complex tasks are not transformed, and should throw an error in the classifier.
https://localhost:8080/?project=908&workflow=3339
Package:
lib-classifier

Classifier: Simple dropdown task adapter

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/theme.js

Package:
Fix style regression with the phase controls. Also Closes #1857. I don't remember what the z-index is for and it doesn't seem necessary now.

Fix VSLCV style regression introduced from grommet upgrade

---

packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js

Add a required toggle to the simple dropdown stories.
Package:
lib-classifier

Classifier: add Required to dropdown stories

---

packages/lib-classifier/src/plugins/drawingTools/README.md
packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/models/Task.js
packages/lib-classifier/src/plugins/tasks/readme.md
packages/lib-classifier/src/store/Step.spec.js

Wrap any calls to `self.annotation` inside `tryReference`, since `task.annotation` stores a reference to an annotation and not the annotation itself.
Remove `task.updateAnnotation(value)`. Task components should call `annotation.update(value)` on their annotation prop.
Fix annotation references to explicitly use the annotation ID.
https://mobx-state-tree.js.org/concepts/references
Package:
lib-classifier

Task models: remove unused actions and use tryReference to access annotations

---

packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js

Closes #1703 
This includes several improvements for the layout of the classifier including:
- Setting the height on the image toolbar to `min-content` so it doesn't stretch to the height of the subject
- Setting the height for the task area to `min-content` for the same reason
- Wrapping the task area and image toolbar in containers and giving the child items position sticky when the top of the element hits the 10px from the top viewport. What this does is finally give us this UX (@beckyrother !!!):
The containers give us the height necessary for the position sticky to work. I also had to remove that `overflow: hidden` set …

Fix layout issues for transcription projects

---

packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.stories.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.stories.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js

Add observers to the `Tasks` component in task stories, so that each story reacts to changes in the mock classification and step.
Package:
lib-classifier
Closes #1906.

Add observers to the classifier task stories

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.js
packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
packages/lib-classifier/src/plugins/tasks/models/Task.js
packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
packages/lib-classifier/src/plugins/tasks/readme.md
packages/lib-classifier/src/store/Step.spec.js

Add an optional id parameter to `task.defaultAnnotation` and change the code throughout to use `task.defaultAnnotation()`.
Package:
lib-classifier

Classifier: Add an id parameter to task default annotations

---

packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.spec.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/components/SubjectGroupComparisonTask.spec.js
packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.js
packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.spec.js

Follows #1855
PR 1855 introduces an ID parameter to most Tasks (Single Choice Task, Text Task, etc). This PR adds the same changes to two newer tasks that didn't yet follow the new updated format:  Simple Dropdown Task and Subject Group Comparison Task.
Test URLs:
- Simple Dropdown Task: https://local.zooniverse.org:8080/?env=production&project=12754&workflow=16106&subjectSet=85771 (custom workflow, designed to work with a Subject Set selector)
- Subject Group Comparison Task: https://local.zooniverse.org:8080/?env=staging&project=1900&workflow=3412 (custom workflow, with additional `workflow.config.subject_viewer = 'subjectGroup'`)
How to Test:
- Accessing either of those URLs on `master` will result in an immediate crash of the web app.
- Accessing either of those URLs on this PR's …

Add missing ID parameter to Simple Dropdown and Subject Group Comparison Tasks

---

package.json
packages/app-content-pages/docker-compose.yml
packages/app-content-pages/package.json
packages/lib-react-components/package.json

Add a top-level storybook script, so that `yarn storybook` builds and starts all four storybooks on different ports.
I found this useful while testing out #1913.
Package:
app-project
lib-classifier

Add top-level storybook script

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js

Connect up the Task component so that it gets its annotation and disabled state from the store. Replace useContext and useState with a useStores hook in the Task component. Add an optional store prop for passing stores in during tests.
Package:
lib-classifier

Classifier: generic Task connector

---

packages/lib-react-components/CHANGELOG.md
packages/lib-react-components/src/MovableModal/MovableModal.js

It looks like I accidentally left a hardcoded value for `cancel` on the `Rnd` component when I ported it to the shared component library. This PR fixes it so that its value is defined from props.

Remove hardcoded cancel value from MovableModal

---

packages/lib-classifier/package.json
yarn.lock

This is another thing I missed when adding the `MovableModal` to the shared component library. The classifier itself no longer directly uses react-rnd, so it doesn't need to be a dependency.

Remove react-rnd dependency from the classifier.

---

packages/app-content-pages/.storybook/main.js
packages/app-content-pages/package.json
packages/app-project/.storybook/main.js
packages/app-project/package.json
packages/lib-classifier/.storybook/main.js
packages/lib-classifier/package.json
packages/lib-react-components/.storybook/main.js
packages/lib-react-components/package.json
packages/lib-react-components/src/Markdownz/Markdownz.stories.js
yarn.lock

Uninstall `@storybook/addon-notes`. It's deprecated, in favour of [`addon-docs`](https://github.com/storybookjs/storybook/blob/master/addons/docs/README.md), and doesn't seem to be receiving security patches.

[Security] Remove storybook/addon-notes

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js

Remove `storiesOf` from the drawing tool stories and replace them with [Component Story Format](https://storybook.js.org/docs/react/api/csf) functions.
Package:
lib-classifier

Classifier: Convert drawing stories to CSF

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/plugins/drawingTools/README.md
packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js
packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.spec.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js

This extends #1921 to fix #1919 by adding `tool.handlePointerMove(event, mark)` and `tool.handlePointerUp(event, mark)` to the tool model. The pointer is captured on mark creation, and pointer events are handled by the drawing surface until the new mark is finished (https://github.com/zooniverse/front-end-monorepo/issues/1919#issuecomment-737989521). `handlePointerMove` and `handlePointerUp` are called during mark creation and allow tools to implement custom validation of marks. By default, a mark is dragged on pointer move and finished on pointer up, but the transcription line tool overrides these to wait for a second pointer down, which finishes the line. Ellipses might also implement this, to allow for two swipes to create both axes of an ellipse.
I've tested this on browserstack, on a …

Drawing tools: add actions to handle events during mark creation

---

packages/lib-classifier/src/store/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore.spec.js

This fixes something I missed while reviewing #1885. The change on the `Workflow` model type for steps caused this warning to start to be thrown: `[mobx.array] Attempt to read an array index (1) that is out of bounds (1). Please check length first. Out of bound indices will not be tracked by MobX`
This only appears with projects actually configured to use steps, so TESS, Stellar Sleuths and any staging test project we've setup as well and in the specs (if you scope to this model's specs, the warning is thrown, but doesn't fail a test either. Not sure if we want to start testing for warnings...)
The issue is that mobx warns …

Fix mobx warning about accessing an undefined index in an array

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js

A quick fix for positioning of the subtask popup. Check for the existence of a DOM node before setting the modal's visibility.
Package:
lib-classifier
Closes #1949.
Testing URL: https://localhost:8080/?project=11300&env=production

Fix subtask positioning

---

packages/lib-classifier/src/plugins/tasks/SurveyTask/index.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyAnnotation.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.spec.js

Closes #1900.
- adds survey task model tests
- adds survey task model (basic)
Notes:
- subsequent PR incoming to refactor survey task and survey task annotation to utilize `types.refinement`

Add survey task model

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/lib-classifier/package.json
packages/lib-panoptes-js/package.json
packages/lib-react-components/package.json
yarn.lock

- Upgrade all outdated packages to their latest allowed versions.
- Bump `jsdom` to 16.4.
- Bump `contentful` to 8.1, which upgrades `axios` to 0.21.1.

Upgrade outdated packages

---

yarn.lock

Bump `contentful` and `seven-ten` to their latest versions. Fixes a security issue with `axios`.

[Security] Patch outdated dependencies

---

packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js

The first argument passed to initStore should be the boolean flag `isServer`. This PR calls `initStore(true, snapshot)`, rather than `initStore(snapshot)`.

Fix initStore args

---

.github/workflows/ci-tests.yml
README.md
packages/app-content-pages/server/set-logging.spec.js
packages/app-project/server/set-logging.spec.js
packages/app-project/stores/UI.spec.js
packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.spec.js

Set up a copy of the production build environment. Run a full install (to install the build tools.) Run a test build of all the libraries and the NextJS apps. Run the tests with PANOPTES_ENV=test.
#1943 restricts the Jenkins builds to deploys only, so this runs a full build of the monorepo as part of the CI tests for each PR. In theory, this should catch breaking changes in the NextJS apps before we merge to staging.

Add a production test build to CI Tests

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuide.stories.js

Add stories for the field guide using the new CSF format. Can be previewed by running `yarn storybook` in the `lib-classifier` folder. You might have to scroll the left hand list of stories to find the new one for the field guide. The button should be clickable to launch the field guide on the right hand side of the preview area.

Create general field guide story

---

packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js
packages/lib-react-components/src/CloseButton/CloseButton.stories.js
packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
packages/lib-react-components/src/GoldButton/GoldButton.stories.js
packages/lib-react-components/src/Media/Media.stories.js
packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
packages/lib-react-components/src/Modal/Modal.stories.js
packages/lib-react-components/src/MovableModal/MovableModal.stories.js
packages/lib-react-components/src/PlainButton/PlainButton.stories.js
packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
packages/lib-react-components/src/SpacedHeading/SpacedHeading.stories.js
packages/lib-react-components/src/SpacedText/SpacedText.stories.js
packages/lib-react-components/src/Tabs/Tabs.stories.js
packages/lib-react-components/src/Tooltip/Tooltip.stories.js
packages/lib-react-components/src/Tooltip/components/Label/Label.stories.js
packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.stories.js
packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js

Storybook v6 deprecated `addon-notes` in favour of the Docs page for each component story. This PR replaces the `notes` parameter with the `docs` parameter for all the ZRC stories. This should add each component's Readme to its Docs page in the storybook.
Package:

ZRC: Add Readme docs to React Components stories

---

packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
packages/app-project/stores/Project.js
packages/app-project/stores/Project.spec.js
packages/lib-classifier/src/store/Project/Project.js
packages/lib-classifier/src/store/Project/Project.spec.js

This PR removes `/classify` as the route for a project's default workflow. If a project has a single active workflow, then `/classify` will set that as the `workflowID` prop for the classifier. If a project has multiple workflows, then you are expected to select a workflow by specifying it in the URL: `/classify/workflow/:workflow_id`. In the second case, `/classify` no longer selects the default workflow for you.
One side effect of this change is that navigation links and workflow links on the project homepage now link to workflows by ID, even for projects that have only one workflow.
Package:
app-project
lib-classifier

Remove /classify as the route for a project's default workflow

---

packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js

Missed from #1953 and found while testing #1985. Removing the effect from the suggestions variant resolves the issue. Tested using https://local.zooniverse.org:8080/?project=11300&env=production
You can easily replicate the issue on the master branch loading up that project, clicking a previous mark and then cancelling. Check out this branch and it is resolved.

Refactor suggestions task

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js

Use `mark.isComplete`, not `task.isComplete`, when validating drawing and transcription subtasks. Update `Mark.isComplete` to use `tasks.some`.
Test URLs:
Drawing task: https://localhost:8080/?project=908&workflow=3370
Transcription task: https://localhost:8080/?project=11300&env=production
Package:
lib-classifier
Closes #1986.

Classifier: use mark.isComplete for subtask validation

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js

Disable pointer events for `PreviousMarks`. This fixes the hover styles for marks that can't be selected. It also allows marks to be drawn over.
- Transcription task: https://localhost:8080/?project=11300&env=production
- Multiple drawing tasks: https://localhost:8080/?project=7170&env=production
Package:
lib-classifier
Closes #2005.
Closes #2003.

Style PreviousMarks with pointer-events: none

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.spec.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.stories.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/index.js
packages/app-project/src/shared/components/SubjectSetPicker/locales/en.json
packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json

This PR reorganises the code for workflow selection on the Classify page, including some small fixes for bugs.
- The popup workflow selector is moved into its own `WorkflowMenu` component, with tests and stories. (@srallen the code here shows an example of documenting functional component props with CSF.)
- the close button should be removed from the workflow popup now.
- the wording on the subject set selector should now say 'Back to workflow choice.'
- workflow buttons should now say 'set selection.'
Closes #1998.
Package:
app-project

Engaging Crowds: Subject set selection fixes

---

packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js
packages/lib-react-components/src/CloseButton/CloseButton.stories.js
packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
packages/lib-react-components/src/GoldButton/GoldButton.stories.js
packages/lib-react-components/src/Markdownz/Markdownz.stories.js
packages/lib-react-components/src/Media/Media.stories.js
packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
packages/lib-react-components/src/Modal/Modal.stories.js
packages/lib-react-components/src/MovableModal/MovableModal.stories.js
packages/lib-react-components/src/PlainButton/PlainButton.stories.js
packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
packages/lib-react-components/src/SpacedHeading/SpacedHeading.stories.js
packages/lib-react-components/src/SpacedText/SpacedText.stories.js
packages/lib-react-components/src/Tabs/Tabs.stories.js
packages/lib-react-components/src/Tooltip/Tooltip.stories.js
packages/lib-react-components/src/Tooltip/components/Label/Label.stories.js
packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.stories.js
packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js

Add a top-level Components category to the ZRC storybook. ~~Move the admin checkbox back under ZooFooter stories. Move the close button under Modal stories.~~
Follows on from #1969, where we noted that the sidebar structure for the ZRC storybook is a little confusing.
Package:

React Components: storybook structure

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.stories.js

Cancel event bubbling for scroll wheel events on the subtask popup and the consensus popup. This stops wheel events from bubbling up to the containing SVG image, in the React tree, and triggering wheel zoom in/out.
I've also taken the opportunity to add some documentation to the consensus popup component, and converted its stories to CSF.
Package:
lib-classifier
Closes #1835.

Classifier: Trap scroll wheel events on drawing tools popups

---

packages/app-project/src/shared/components/ContentBox/ContentBox.js
packages/app-project/src/shared/components/ContentBox/ContentBox.spec.js

We aren't linking to any client-side pages from the ContentBox component, so this replaces Link with Anchor, which will load a new page in the browser. It also adds tests and fixes a small typo (linkUrl should be linkProps.)
Further down the line, we may want logic that renders `Link` or `Anchor`, depending on whether the target page is part of the NextJS app.
Package:
app-project
Closes #2012.

Project: ContentBox: remove client-side links

---

packages/lib-classifier/dev/components/App/App.js

This PR fixes an issue where, upon attempting to view certain projects, the classifier crashes (full crash, white screen) with the error: _Uncaught TypeError: Invalid attempt to destructure non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method._
- This bug was accidentally introduced in #2017 
- Explanation: with the line `const [singleActiveWorkflow] = (active_workflows.length === 1) && active_workflows`, the first condition before the && returns a boolean (when false, I think), and the [singleActiveWorkflow] then tries to _array-destructure_ a _boolean_ value, which makes the JS compiler go BLARP then go home for a nap.
- Fix is straightforward, comes from Jim, and passes for all tests 👍 
Setup: localhost, …

Fix error where the code attempted to array-desctructure a boolean

---

packages/app-content-pages/package.json
packages/app-project/package.json
yarn.lock

Package: app-project, app-content-pages
Upgrading to version 6, which doesn't require any changes according to the [change log](https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#600):
> This major version release doesn't contain any breaking API/code changes. Starting from the version 6.0.0, all SDKs that support sending sessions data will do so by default. See our Release Health docs to learn more. As of this version, it applies to all Browser SDKs (Browser, React, Angular, Vue, Gatsby etc.). Node.js and other related Server SDKs will follow soon after, in the minor 6.x release. You can opt-out of this behavior by setting …

Bump the sentry packages to v6

---

packages/app-content-pages/src/helpers/logger/initializeSentry.js
packages/app-project/src/helpers/logger/initializeSentry.js

Package: app-projects,  app-content-pages
I've set Sentry to ignore the ResizeObserver error message. This is benign according to the spec authors and there's an open issue to change it to be a warning. See: https://github.com/WICG/resize-observer/issues/38

Add ResizeObserver message to ignoreErrors option

---

packages/lib-classifier/package.json
packages/lib-classifier/src/components/Classifier/Classifier.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
yarn.lock

PEP is entering a kind of EOL (see #2035) and I'm suspecting it may be the cause of a few Sentry reported bugs and potentially a silent bug with an occasional duplicate mark being created with the transcription line tool. I haven't been able to replicate the issue of duplicate marks, but we're gonna try this out since we have to do this anyway. 
There shouldn't be any regressions, other than support for Safari 12 is dropped, but to double check anyway: https://localhost:8080/?project=1764&workflow=3392

Remove PEP

---

packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js

Panoptes project resources can contain null values. These should be undefined for optional properties in the project model. This PR casts nullish values to undefined, so that types.optional works as expected.
Package:
app-project

Project: cast null properties to undefined

---

packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js

Add `researcher_quote:null` to the mock project in tests, so that we can test the project model with an invalid snapshot (see #2053.)
Check for a 404 response after creating the project model, so that `getStaticPageProps` returns early if the project model fails.
Package:
app-project

Project: test null project properties

---

packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js

Partly toward #2061. I've updated the `getNavLink` helper to build the href for the about page to use an absolute url to zooniverse.org when in production. I also updated it to route to `/about/research`,  but we'll still  need the redirect as described in #2061 for direct links. When we're ready to launch the about pages, this change to use an absolute url in production in the helper will be reverted.

Update getNavLink helper for about page routing

---

packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.spec.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js

This is a quick fix to get the project navbar about link to route to the existing PFE page as we would expect. This should function like the social media links on the homepage which also use a standard anchor. #2065 works on frontend.preview but not on prod deploy. Let's get this fixed for now and circle back.

Use standard anchor for about page link for now

---

packages/app-project/package.json
packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
packages/app-project/src/helpers/fetchSubjectSets/index.js
packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
yarn.lock

Adds a query which gets available subject numbers, for a given workflow, from the Cellect API. 
Removes included subject sets from the workflows API query (see #678.) Subject sets are fetched separately, by ID, from the Panoptes API. This increases the number of API requests required to build each page, but allows us to limit subject set requests to grouped workflows. 
Updates the API mocks, in data-fetching tests, to include grouped/non-grouped cases and to add the `/subject_sets` endpoint.
Wraps the data-fetching requests in try/catch, so that we can log API errors to Sentry.
Package:
app-project
Closes #1956.

Engaging Crowds: Subject set completeness

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js

For #2075 and #1978.
Removes the `onWheel` event from `SVGPanZoom`. A suggested refactor is in #2075 for the future. It should be noted that this is not a regression as the wheel event is new to the classifier here and a project hasn't launched with it yet.

Remove mouse wheel zoom from SVGPanZoom

---

packages/app-content-pages/package.json
packages/app-project/package.json
yarn.lock

Upgrade the content pages and project app to NextJS 10.0.9.
The new router in Next 10 will be a breaking change for client-side navigation in the project app. I've opened #1973 to track that. In the meantime, this version of Next is fully backwards compatible with v9, so we can carry on using the old code in production.
Package:
app-project

Upgrade Next to version 10

---

packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js

Follow-up from #2064.
This removes the logs that I added in order to debug task navigation for looping, recursive workflows. It also removes a redundant `_selectStep` call since the undo manager manages `workflowSteps.active` for us: there's no need to manually set it after an undo.
Package:
lib-classifier

Classifier: Clean up step annotations history

---

packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js

Add `set_member_subjects` to the API mocks for page props. Add a mock subject to mock subject sets, to check that the API response is being added to page props as expected.
Package:
app-project
Closes #2090.

Project app: Add set_member_subjects to API mocks for page props

---

packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js

The workflowSteps store creates or overwrites `step.next` for each workflow step, which then breaks the Done & Talk button for single choice questions. This PR removes that code so that the value of `step.next` is taken from `workflow.steps`, for each step.
Package:
lib-classifier

Fix Done & Talk for single answer tasks

---

packages/lib-classifier/src/store/Workflow/Workflow.js
packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js
packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.spec.js

Transcription workflows have steps defined, so they bypass `convertWorkflowToUseSteps`. However, the Next Task selector in the project builder still sets `task.next` to a task key for each task and single choice answer. This PR runs `convertWorkflowToUseSteps` on all incoming workflow snapshots. It checks `step.next` for each step, and tries to set it from `task.next` if it doesn't exist.
https://localhost:8080/?env=production&project=9006&workflow=18244&demo=true
Package:
lib-classifier
Closes #2102.

Classifier: Set step.next for transcription tasks

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js

This an experimental change, to suggest some possible fixes for #2082.
Give each transcription line a fixed ID, when it is created from a previous line. Observe transcription task marks for changes. Re-use an existing transcription line, rather than creating a new line, when a magenta line is clicked.
Optionally: disable or even hide magenta lines when they have a linked transcription line with the same line ID.
See #1836 for discussion of whether magenta lines should still be interactive after creating a green line.
Package:
lib-classifier
Closes #2082.

Transcription task: Allow one transcription line for each previously transcribed line

---

packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.stories.js
packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
packages/app-project/src/shared/components/SubjectPicker/helpers/columns.js
packages/app-project/src/shared/components/SubjectPicker/helpers/columns.spec.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
packages/app-project/src/shared/components/SubjectPicker/helpers/index.js
packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.js
packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.spec.js
packages/app-project/src/shared/components/SubjectPicker/index.js
packages/app-project/src/shared/components/SubjectPicker/locales/en.json
packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js

Work-in-progress towards allowing volunteers to select which subject they work on, from a sequential set of pages in a prioritised subject set. See #1884 for the designs.
You can test this locally on http://local.zooniverse.org:3000/projects/darkeshard/engaging-the-crowds-2020?env=production
After selecting workflow 16106 (the third workflow) and subject set, you should be shown a list of subjects from https://redsea.zooniverse.org. Clicking on any subject ID will take you to the classifier for the selected workflow and subject set. The subject should be selected in the URL.
There's only one subject set indexed at the moment, which is a set of letters from ASM. You should be able to search and sort that set using the Grommet data table headings.
TODO:
Package:
app-project
Closes #1884.

Engaging Crowds: Subject picker tool

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js

The VisX zoom API has a (semi) undocumented method to get the string value of the transform matrix which can easily be added as an attribute to a child SVG group or image element. The scatterplot won't use this because the scales have to be recalculated to properly do zooming, so this is for future setup of an SVG image using this or possibly other elements.

Add string transform output to passed down props

---

packages/app-project/pages/projects/[owner]/[project]/about/education.js
packages/app-project/pages/projects/[owner]/[project]/about/faq.js
packages/app-project/pages/projects/[owner]/[project]/about/index.js
packages/app-project/pages/projects/[owner]/[project]/about/research.js
packages/app-project/pages/projects/[owner]/[project]/about/results.js
packages/app-project/pages/projects/[owner]/[project]/about/team.js
packages/app-project/pages/projects/[owner]/[project]/classify/index.js
packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
packages/app-project/pages/projects/[owner]/[project]/index.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
packages/app-project/src/helpers/notFoundError/notFoundError.js
packages/app-project/src/helpers/notFoundError/notFoundError.spec.js

Next 10 added `notFound` and `redirect` to the object returned by `getStaticProps` and `getServerSideProps`. This PR adds `notFound` to the `notFoundError` helper, and to the page props helpers. `redirect` is added to routes that previously modified the response to redirect.
Package:
app-project

Update app-project to use redirect and notFound

---

packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js

Requests to cellect.zooniverse.org intermittently timeout or fail with an empty response. When that happens, no subject sets are fetched for a workflow and subject set selection is broken. This PR falls back to using `workflow.links.subject_sets` if Cellect fails.
Package:
app-project

Engaging Crowds: Fallback to workflow.links when Cellect fails

---

packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/index.js
packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/locales/en.json

Toward #2143
Implements just the modal UI for workflow assignment. There's no functionality implemented to view this in context of the classifier. However, there is a story: http://localhost:6006/?path=/story/workflow-assignment-assignment-modal--default
Run `yarn storybook` in the lib-classifier folder to have a look.

Add modal for workflow assignment

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js

Package:
lib-classifier
Closes #2154.
The `Tasks` component will crash the classifier if it renders while `workflowSteps.active` or `classifications.active` are undefined. That condition can be triggered by changing the active workflow while the classifier is mounted (#2154.)
This PR fixes that bug by checking for `classification` and `step` before calculating the `isComplete` prop. ~~It also adds a default value for the `step` prop, so that `step.tasks` doesn't crash the classifier.~~ The `Tasks` component also waits until `classification` and `step` are defined, before rendering.

Classifier: check classification and step before rendering Tasks

---

packages/lib-classifier/webpack.dev.js
packages/lib-classifier/webpack.dist.js

`gitCommit()` fails on production Docker builds because `.git` is excluded from the Docker image now. This PR wraps gitCommit() in try/catch. The Jenkins build should pick up the commit ID from the build environment, with `gitCommit()` setting a default value.
Here's an example of a broken build:
https://jenkins.zooniverse.org/job/Zooniverse%20GitHub/job/front-end-monorepo/job/master/1114/console
Package:
lib-classifier

Classifier: catch git errors during builds

---

packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.spec.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.js
packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.spec.js

Switch the subject indexing tool over to Datasette.
This PR lets you select a subject set and subject to classify. #2148 is needed in order to load the indexed subjects into the classifier.
Test URL:
http://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues?env=production&demo=true
The Minutes workflow for Scarlets & Blues has subject sets which are indexed in Datasette.
Package:
app-project

Engaging Crowds: switch to Datasette for subject browse & search

---

packages/app-content-pages/package.json
packages/app-project/package.json
packages/lib-panoptes-js/package.json
yarn.lock

Package:
- app-project
- lib-panoptes-js
Fixes login issue from `url-parse` v1.5.0 which duplicated part of pathname with sign-in / register.
- update `package.json`s for packages noted above, `yarn.lock` for `url-parse` v1.5.1

Update url-parse to 1.5.1

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/README.md
packages/lib-classifier/src/store/SubjectGroup/README.md

This is a documentation update for the Subject Group Viewer system
- A better example of the workflow configuration was added. The previous documentation was missing the "subject_group.num_columns" and "subject_group.num_rows" field that's now essential for the new /subjects/grouped endpoint
- The "Subject Groups" used by the viewer has been expanded upon.

Update SubjectGroupViewer README (May 2021)

---

packages/lib-classifier/src/store/SubjectSet/SubjectSet.js
packages/lib-classifier/src/store/SubjectSet/SubjectSet.spec.js
packages/lib-classifier/src/store/SubjectStore.js
packages/lib-classifier/src/store/Workflow/Workflow.js
packages/lib-classifier/src/store/Workflow/Workflow.spec.js
packages/lib-classifier/src/store/helpers/getIndexedSubjects/getIndexedSubjects.js
packages/lib-classifier/src/store/helpers/getIndexedSubjects/getIndexedSubjects.spec.js
packages/lib-classifier/src/store/helpers/getIndexedSubjects/index.js
packages/lib-classifier/src/store/helpers/index.js
packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/index.js
packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/subjectSelectionStrategy.js
packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/subjectSelectionStrategy.spec.js
packages/lib-classifier/test/factories/SubjectSetFactory.js

Get indexed subject selection working for Engaging Crowds projects. Indexed selection shows you every subject from an indexed set in order. ~~Setting this to draft because I think `subjects.populateQueue()` might still need some refactoring.~~ The logic for subject selection was getting messy, so I've moved the selection strategy into its own helper function. I think that will fix `422: Unprocessable entity` errors, which have been happening when subjects were requested with an invalid query. `subjectSelectionStrategy` should only return valid query parameters for each API endpoint.
Test URLs:
https://localhost:8080/?demo=true&project=12268&workflow=17077&subjectSet=92752&env=production
Load subject set 92752 and classify every subject from the first one(priority 129) to the last. …

Engaging Crowds: enable indexed subject selection

---

packages/lib-classifier/package.json
packages/lib-classifier/src/store/ClassificationStore.js
yarn.lock

Remove seven-ten and delete the onClassificationSave hook that was using `Split`.
Package:
lib-classifier

Remove seven-ten

---

.github/workflows/ci-tests.yml

Add --frozen-lockfile to `yarn install` during the CI builds.
I missed this in #2168.

Freeze the lockfile during CI builds

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js

Testing of #2187 uncovered a drawing bug on master: `PreviousMarks` doesn't update if you go back and change a drawing annotation. If you go back and add a new mark, the new mark isn't rendered. If you go back and delete a mark, the classifier crashes, because `PreviousMarks` now holds a reference to a mark that doesn't exist.
When I refactored the Next button in #2062, I moved `step.completeTasks` into the `next()` action, which is tracked by undo/redo. Now, pressing the Next button always redoes the first value you set for a drawing/transcription annotation, ignoring any new marks and restoring the IDs of any deleted marks. References to deleted  marks crash the store, with an invalid reference error.
This PR fixes that by running `step.completeTasks`, for the active workflow step, …

Classifier: track annotation changes on step change

---

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.stories.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js

Package:
Towards #1991.
- refactor RadioInputs and RadioInput to support `onClick`, in subsequent PR `onKeyDown`
- refactor Questions `handleAnswer` to delete unanswered question
- fix related tests, edit RadioInputs story

Add deselect functionality to survey task question radio input

---

.github/workflows/ci-storybook.yml

Includes the fix for project storybook builds from #2190.
This PR adds a CI workflow which runs `yarn deploy-storybook --dry-run` to check that the storybooks build. I've not made it required, so PRs can still be merged with broken storybooks.
I've also added caching, so that the storybook build should re-use the yarn cache from the test monorepo build, rather than running the full install again.

CI: build the storybooks

---

packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js

Package:
Closes #2216.
Changed `LinkList` height property to `fit-content`.
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/height) docs say Firefox does not support the CSS property `fit-content`, but when run in the latest version of Firefox, the LinkList height is still styled with the property `moz-fit-content`.
Can test by running storybook on all browsers.

Fix extra space that Safari renders below footer

---

Dockerfile
docker-compose.yml

Build production images from node:14-alpine. Replace bash with /bin/sh, as bash isn't available in alpine images.
This should reduce our deployed image size from 2.55GB to around 1.8GB. Local builds should hopefully be faster too.

Build with node:14-alpine

---

packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
packages/app-project/stores/Store.js
packages/app-project/stores/User.js
packages/app-project/stores/UserPersonalization.js
packages/app-project/stores/UserPersonalization.spec.js
packages/app-project/stores/UserProjectPreferences.js
packages/app-project/stores/UserProjectPreferences.spec.js
packages/app-project/stores/YourStats.js
packages/app-project/stores/YourStats.spec.js

Toward #2205 
This has three main parts:
- A refactor of `YourStats` to only handle the stats server request and data
- The addition of `UserPersonalization` to handle the shared bits between `YourStats` and UserProjectPreferences`
- The async fetch and storing of the UPP resource
I initially thought about using MST's [`types.compose`](https://mobx-state-tree.js.org/API/#compose) in `UserPersonalization` of two stores, but eventually to remove the redundancy between the project app and the classifier, the UPP store will have other HTTP requests it is handling for updating the UPP and creating it initially, so it async state needs to be tracked separately from the user …

Integrate UPP store in project app

---

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js

Package:
Closes #2242.
Staging:
- https://local.zooniverse.org:8080/?project=1634&workflow=2434
- remove Grommet Drop component
- adds Grommet Stack component
- updates SurveyTask tests accordingly
Notes:
- subsequent PR incoming to disable Done or equivalent (only visible if choice content is small, like Fire)
- subsequent PR to fix focus to first input
- subsequent PR to fix dark theme

Refactor SurveyTask Choice render, from Drop, to Stack

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js

packages: code change in `lib-classifier`, but can only be tested on `app-project`
Fixes #2221
Follows #2241 
This PR is a follow up to 2241, which adds an image placeholder for the Single Image Viewer, to solve the issue of drawing components not fully working when the Classifier page is _re-visited after navigating away from it._
- The problem context and solution is the same, **just on different viewers.**
- This PR addresses the issue where the Davy Notebooks projects is STILL encountering the issue "solved" by 2241, since D-Notes (as the cool kids call it) is using an MF Viewer not an SI Viewer.
BE SURE TO TEST THIS ON DAVY NOTEBOOKS
1. Bootstrap everything
2. Open the Classify Page of Davy Notebooks: http://localhost:3000/projects/humphrydavy/davy-notebooks-project/classify?env=produ …

Classifier: add image placeholder for Multi Frame Viewer

---

packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js
packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js

We don't want the auth banner to render server side, and because it doesn't render until 5 classifications are made, it never actually will, however, the code expects window to be defined, so tell next explicitly to dynamically import it with no SSR. 
Current staging shows a flash of a window is no defined on the initial render: https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?demo=true
Local project on this branch doesn't: http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?demo=true
And to confirm that the banner still does appear as expected, you can make 5 classifications …

Use next.js dynamic import to not SSR auth invite banner.

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.spec.js
packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js

If workflowID and/or subjectSetID are defined in the Classify page URL, this skips past workflow selection and/or subject set selection when opening the workflow menu.
Something I missed in #2132: if you link directly to a workflow or subject set, then that workflow or set should already be selected in the workflow menu when the Classify page opens.
Test URLs:
Workflow selected, jump straight to subject set selection
http://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/17077?env=production&demo=true
Subject set selected, jump straight to subject selection
http://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/17077/subject-set/92751?env=production&demo=true
Subject set selected but workflow doesn't use subject selection …

Engaging Crowds: Add URL workflow and subject set to WorkflowMenu

---

packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js

Cache subject sets by ID, in `fetchSubjectSets`, so that we only fetch each set once from Panoptes. For HMS NHS, I'm seeing this speed up `getServerSideProps` from ~8s to ~1.5s.
Package:
app-project

Project: Cache subject sets across workflows

---

Dockerfile
README.md

Add a second stage to the Docker build. The second stage takes the packages built by the first stage and builds a new image from them. The new image has a production install of `node_modules` (no dev dependencies) and deletes source code from the built packages. Removing dev dependencies shaves ~500MB off the final image size.
The build is loosely based on [the NextJS Docker example](https://nextjs.org/docs/deployment#docker-image), adapted for our monorepo.

Remove dev dependencies and src from Docker builds

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js

Remove the imageViewer ref from SingleImageViewerContainer and MultiFrameViewerContainer. Instead, reference the svg DOM node from SingleImageViewer. Pass that node down to individual drawing components in SVGContext.
~~Remove `getScreenCTM` from the context since any SVG element should have a `getScreenCTM` method.~~ Messing with the transformation matrix breaks tools that use `rotate` transforms, so I've left the context alone.
Package:
lib-classifier

Classifier drawing tools: simplify SVGContext

---

kubernetes/deployment-production.tmpl
kubernetes/deployment-staging.tmpl

this PR reinstates the CPU request values in #2261 as they are used for the horizontal pod autoscaler metrics. Making these CPU requests too low means the autoscaler will kick in and run more pods for each app service. 
As such this PR reinstates the values back to previous to reinstate the original scaling behaviour.

Reset cpu requests to ensure the HPA pod scaling is correct

---

packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js

Toward #2205
This updates the modal to use a Next.js Link in place of the button placeholder there previously and correctly link to the assigned workflow id. This can be observed in the storybook story.

Link to workflow in assignment prompt

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js

Fixes #2274
This PR fixes a bug (introduced in #2241) where the "Reset Image/View" doesn't correctly reset the image, and actually adds a horizontal+vertical pan offset.
- The problem is that the `onZoom()` function of SVGPanZoom stores/remembers the naturalWidth/naturalHeight of the _placeholder image_
- This fix refreshes the `onZoom()` function when the subject image loads and replaces the placeholder image.
- Please see #2274 for more details.
Project: any project with a single image viewer
Testing URL: [I Fancy Cats!](https://localhost:8080/)
Testing Steps:
- Open the classifier and wait for subject image to load.
- Subject image should load with a zoom of 1.0, and translation/pan/offset of (0,0) , and a rotation of 0.
- Move the subject image around (drag …

Classifier: fix "Reset Image/View" action (fix 2274)

---

packages/lib-classifier/src/store/SubjectStore.js

Add the active subject set to the workflow observer in the subjects store, so that the subject queue resets when the selected subject set changes.
Package:
lib-classifier
Closes #2279.

Classifier: observe active subject set for changes

---

packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
packages/app-project/src/shared/components/SubjectSetPicker/helpers/mockWorkflow.js

Replace `subjectSet.availableSubjects` with `subjectSet.completeness`, which is a number between 0 and 1. `subjectSet.completeness` is calculated after we fetch the grouped subject counts from Cellect.
Subject sets are copied, not referenced, from the subject set cache in order to fix #2283.
Package:
app-project
Closes #2283.

Engaging Crowds: Refactor subject set completeness

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js

Remove `SVGContext` from `InteractionLayer`. Use `DOMPointReadOnly`, if supported, instead of `SVGPoint`, which allows us to remove the passed SVG element from context. I've also renamed the passed element from `svg` to `canvas`, and this is passed down in order to perform matrix transformations on dragged tools etc.
Follows up on the changes in #2255.
Package:
lib-classifier

Classifier: use DOMPointReadOnly for drawing

---

packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.spec.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.stories.js

Package:
Towards #1991.
Staging:
- recommend related Storybook components, easy to toggle `disabled` true/false, unlike...
- project - https://local.zooniverse.org:8080/?project=1634&workflow=2434
- add disabled property to ChoiceButton component
- add disabled property to DropButton in FilterStatus component

Add disabled functionality to survey task ChoiceButton and FilterStatus

---

packages/app-project/README.md
packages/app-project/package.json
packages/app-project/server/dev-server.js
packages/app-project/server/server.js
yarn.lock

Package: project-app
Toward the workflow assignment effort...
This adds [devcert](https://github.com/davewasmer/devcert#readme) to the project app which creates a local certificate authority to generate self-signed SSL certificates (more info on how this works: https://github.com/davewasmer/devcert#how-it-works). Currently, we can get around Chrome's security warnings about SSL by using `http://localhost` and typing in `thisisunsafe`, but we still cannot sign in to Panoptes because of CORS errors. Adding this will enable us to use `https://local.zooniverse.org:3000` and `https://localhost.zooniverse.org:3000` which will get auth to work with Panoptes.
Note that the first time this is run on Mac …

Add devcert to deal with SSL in browsers for local dev (particularly Chrome)

---

packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.js
packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.spec.js

Closes #2296 
Added a new function, `rotateXY`, to include the angle of the rectangle when resizing.
Then using this function on each `DragHandle` (corner) of the rectangle.
See Issue #2296 for a great explanation of this.
With this new update, resizing the rectangle has a mirroring effect where the center will remain and the width/height will resize on both sides of the center point.
Because of this, the `resizing` unit test was updated and a new unit test was created for resizing a rotated rectangle.

Rotate rectangle resize

---

packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js

Package:
- app-project
- removes `console.log('store', store)` from WorkflowSelectorConnector, noticed reviewing in prep for production deploy

Remove console.log from WorkflowSelectorConnector

---

packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav.js
packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/theme.js
packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.js
packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.spec.js
packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js

Package:
app-project
I added the `ThemeModeToggle` to all Project About pages along with appropriate styling for dark theme.
There are some linter corrections included for double-quotes vs single-quotes.

Add dark theme styling to Project About pages

---

packages/lib-react-components/CHANGELOG.md
packages/lib-react-components/src/CloseButton/CloseButton.js
packages/lib-react-components/src/CloseButton/CloseButton.spec.js
packages/lib-react-components/src/CloseButton/README.md
packages/lib-react-components/src/PlainButton/PlainButton.js
packages/lib-react-components/src/PlainButton/PlainButton.spec.js
packages/lib-react-components/src/PlainButton/PlainButton.stories.js
packages/lib-react-components/src/PrimaryButton/PrimaryButton.js
packages/lib-react-components/src/PrimaryButton/PrimaryButton.spec.js
packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js

Toward #2249.
Grommet's `Button` allows us to specify an `href` which will then render an anchor tag that is styled as a button. This is convenient and is definitely used in our code base, however, all other `Button` props are still accepted including `disabled`. This is a problem because links cannot be disabled via attribute. What happens is with this combination you have a link styled like a disabled button, but is still functional. There is a method to pseudo-disable a link, but it's better to just render text rather than do that. 
At first, I thought I'd create a new component for our shared components library that was a span styled like a button, but …

Use as prop to render a span when href is defined and disabled is true

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js

During the refactor from #2277, the `videoViewer ref` in `SingleVideoViewerContainer.js` was removed.
With the `videoViewer ref` removed, videos were not loading properly and users would see the 'Something went wrong' message.
The `videoViewer ref` is still needed in this file to calculate the video dimensions.
With this `ref` now in place, video dimensions are properly being calculated and loaded!
All unit tests are passing and UI is behaving as expected.
In the front-end-monorepo folder, run yarn bootstrap to build the packages. Then cd packages/lib-classifier and run yarn dev.
Project URL: [https://localhost:8080/?env=production&project=13789&workflow=16843](https://localhost:8080/?env=production&project=13789&workflow=16843)

Added videoViewer ref back to svg element

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.js

Add a missing `alignSelf="center"` to the 'Next available subject' button.
https://local.zooniverse.org:8080/?project=12268&workflow=17076&subjectSet=96235&subject=63413209&env=production&demo=true&finished=true
Package:
lib-classifier
Closes #2327.

Classifier: Fix Finished modal button alignment

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js

My mistake in adding the smoke test the other day when fixing the tutorial. Be sure to only render inside the `it` statement function or inside a `before` or `beforeEach` so it gets cleaned up and doesn't pollute the test jsdom for other tests.

Render inside the it statement so it doesn't pollute other tests

---

packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js

Replace the `gap` prop with CSS gaps in `WorkflowSelectButtons`. Grommet renders gaps as `<div>` elements, but that generates invalid lists, with extra divs between the list items.
Package:
app-project
Closes #2338.

Project: WorkflowSelectButtons: fix list structure

---

Dockerfile
docker-compose.yml

Reverts zooniverse/front-end-monorepo#2309 as it breaks the Jenkins build.

Revert "Docker build and compose improvements"

---

packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.spec.js

Package:
- adds `wrapper.unmount()` to the two nested test blocks that open the Field Guide modal
Note:
- the Field Guide modal is opened in the noted test blocks, and remained in the testing DOM, causing an issue with react-testing-library tests

Add unmount to FieldGuideWrapper tests

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/README.md
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/glyphComponents.js

Toward #1851
This refactors how a glyph symbol is assigned to a data series. A glyph is now assignable by way of the series option object or falls back to the order of the data series array. This can be manually tested by running the storybook and having a look at the `VariableStarViewer` story. The first data series should be a red circle and the second a blue cross.

Refactor glyph assignment

---

packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js

Remove `hide_classification_summaries` from `workflowSteps.shouldWeShowDoneAndTalk`, so that we always show Done & Talk on the last step of a workflow (except for flagged classifications.)
Package:
lib-classifier

Always hide workflow summaries

---

packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js

Use a named stub for `console.error`, so that we don't clobber the console in other tests eg. feedback or the subject viewers. Test that invalid tasks are not added to `tool.tasks`.
Package:
lib-classifier

Classifier: Refactor drawing Tool tests

---

packages/lib-classifier/src/store/SubjectStore/AvailableSubjects/AvailableSubjects.js
packages/lib-classifier/src/store/SubjectStore/AvailableSubjects/index.js
packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js

On pressing 'Next Available Subject', fetch 10 queued, unclassified subjects. Cycle through those 10 subjects each time the button is pressed again. When a new available subject is selected, use it to seed a new, ordered queue from the `/api/subjects/selection` endpoint. Clear the stored, available subjects when a classification is submitted.
Test URL:
https://localhost:8080/?project=12268&workflow=17076&subjectSet=96235&subject=63413209&env=production&demo=true&finished=true
Press 'Next Available Subject' a few times to try cycling through a selection of unclassified pages.
Alternatively, build the libraries and try it out with a logged-in volunteer at
http://local.zooniverse.org:3000/projects/bogden/scarlets-and-blues/classify/workflow/17076/subject-set/96235/subject/63413209?env=product …

Engaging Crowds: fetch multiple queued subjects for Next Available Subject

---

packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.spec.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/locales/en.json

Add the subject set display name to the the `SubjectSetProgressBanner` for grouped workflows, so that we can see which subject set we are working on.
Try this out on HMS NHS:
https://localhost:8080/?project=11429&workflow=18619&subjectSet=82738&env=production&demo=true
Package:
lib-classifier
Towards #2278.

Engaging Crowds: Show the subject set name for grouped workflows

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
packages/lib-classifier/test/mockStore/mockStore.js

Mock a grouped workflow, with an indexed subject set, for the TaskArea tests. Render the task area with and without an indexed workflow, and with and without finished subjects, and test that the popup renders correctly for indexed, finished subjects.
I've set the tests up to run when `store.subjects` is ready (copying a technique from the UPP store tests) and test whether the popup text and buttons are shown. I've also added tests to check whether the task inputs are disabled. I haven't added any tests to check what happens when the popup buttons are pressed.
Package:
lib-classifier
Closes #2297.

Engaging Crowds: test DisabledTaskPopup

---

packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/index.js
packages/app-project/stores/YourStats.js

Ignore the local time zone and use UTC when calculating your daily classification counts. With this change, the daily stats chart should always begin on a Monday, regardless of which time zone you're in. Classifications should be shown on the day that you made them, not the day before.
http://localhost:9001/?path=/story/project-app-screens-classify-daily-classifications-chart--plain
I've also upgraded the chart component to remove `inject`, and upgraded the stories to remove `storiesOf`.
Package:
app-project
Closes #2244.

Use UTC for daily stats calculations

---

packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.spec.js

Some small improvements to the popup that disables the task area for finished subjects.
- check `subject.alreadySeen` instead of `subject.already_seen`.
- close the popup when Next Available is pressed.
- close the popup when Select a Subject is pressed.
- close the popup when `isOpen` is false.
This fixes a few small bugs that @mrniaboc found while testing.
https://local.zooniverse.org:8080/?project=12268&workflow=18504&subjectSet=96699&subject=64213748&env=production&demo=true
Package:
lib-classifier

Classifier: improvements to the Finished popup

---

packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
packages/lib-classifier/src/store/Subject/Subject.js
packages/lib-classifier/src/store/Subject/Subject.spec.js
packages/lib-classifier/src/store/Workflow/Workflow.js
packages/lib-classifier/src/store/Workflow/Workflow.spec.js

This fixes a couple of bugs in the workflow and subject models.
- `workflow.prioritized` is always falsy, even for prioritised workflows.
- `subject.priority` is a string, which leads to unexpected results when you try to compare two subjects by priority order.
I've tagged this with Engaging Crowds, but I think we're using prioritised selection outside that project eg. for Davy Notebooks too.
Package:
lib-classifier

Classifier: Priority subject fixes

---

packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/locales/en.json
packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
packages/lib-classifier/src/store/RootStore.js
packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
packages/lib-classifier/src/store/SubjectStore/helpers/getIndexedSubjects/getIndexedSubjects.js
packages/lib-classifier/src/store/SubjectStore/helpers/getIndexedSubjects/getIndexedSubjects.spec.js
packages/lib-classifier/src/store/SubjectStore/helpers/subjectSelectionStrategy/subjectSelectionStrategy.js
packages/lib-classifier/src/store/SubjectStore/helpers/subjectSelectionStrategy/subjectSelectionStrategy.spec.js

Add Next and Previous buttons to the progress banner for indexed subject sets. 'Next' advances the subject queue to the next subject. 'Previous' queries the subject set index API for the previous subject ID, loads that subject from Panoptes then sets that subject as the active subject. Once previous subjects have been loaded into the queue, ‘Previous’ will use them, rather than trying to load them again. 
The subjects store has new actions and properties, to handle the different cases of workflows that use indexed subjects (Engaging Crowds projects) and all other workflows, which use regular queued subject selection.
- `subjects.queue`: an array of Subject IDs, in the order that they'll be classified. New subjects can be appended to the end of the queue, or prepended to the start of the …

Engaging Crowds: Next/Previous subject navigation

---

packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js

Pass the active drawing task annotation down to the `InteractionLayer` components as a prop. Update the annotation incrementally, when a new mark is created, rather than waiting until drawing is complete for the current step.
Here's a test project with a couple of drawing steps, including some subtasks.
https://localhost:8080/?project=908&workflow=3370
Package:
lib-classifier

Classifier: Refactor drawing task annotations

---

packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js

Rewrite `WorkflowSteps.getNextStep` to make it clear that it returns the first step by default.
Following conversation in #2392 about how confusing it can be to read `resources.values().next().value`, this replaces `steps.keys().next().value` in `getNextStep` to make it clear that the first step is returned by default.
Package:
lib-classifier

Classifier: Clarify getNextStep

---

packages/lib-classifier/src/plugins/tasks/index.spec.js
packages/lib-classifier/src/plugins/tasks/models/Annotation.js

Add the `annotation._inProgress` flag, which is false by default, but true once an annotation has been updated by the classifier.
Add some generic tests which create and update an annotation for each registered task type.
For Engaging Crowds, we'd like to be able to detect when a volunteer has begun to work on a subject, so that we can warn them before clearing their classification when changing to a new subject. `annotation._inProgress` here should hopefully provide a flag that we can use to detect when classification work has begun.
Package:
lib-classifier

Engaging Crowds: Add annotation._inProgress

---

packages/lib-classifier/src/helpers/useStores/useStores.spec.js
packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js

Move mocks for the `useStore` and `SubjectStore` tests into before() blocks, so that they aren't run during global setup for all tests.
When you run tests on master, you'll see the following messages printed before the tests run:
```
Fetching more subjects
Fetching more subjects
Fetching more subjects
```
Those messages are caused by some mocks that are run globally for all tests. This PR moves those mocks into `before` blocks for the tests that use them.
Package:
lib-classifier

Classifier: Remove mocks from global test setup

---

packages/app-project/src/shared/components/NavLink/NavLink.js
packages/app-project/src/shared/components/NavLink/NavLink.spec.js

Final step in launching the project about pages. This should be done after two other issues / PRs are done:
- Migrating the Frontdoor rules to to NGINX http-frontend: https://github.com/zooniverse/operations/issues/523
- Adding about pages to redirect on PFE router: https://github.com/zooniverse/Panoptes-Front-End/pull/6014

Remove absolute link used for project about pages

---

packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
packages/app-project/src/shared/components/SubjectPicker/locales/en.json

subject set search API allows the sort order to be desc via special _sort_desc param, https://docs.datasette.io/en/stable/json_api.html#special-table-arguments
Grommet datatable provides the 'asc' or 'desc' direction key on the callback function https://v2.grommet.io/datatable#onSort - use this in the API call from the UI component to ensure the API can return more than the first 100 rows of data
Closes - issue detected when testing Engaging Crowd projects subject picker tool

ensure datatable UI can use desc sort order at subject-set-search API

---

packages/app-project/stores/UserPersonalization.js
packages/app-project/stores/UserPersonalization.spec.js

Package:
- app-project
Closes #2467.
- adds test for anonymous user incrementing classifications 5 times, shouldn't trigger UPP store refresh
- add user existence check in increment action of UserPersonalization store before triggering UPP store refresh
Staging project for testing:
- https://local.zooniverse.org:3000/projects/nora-dot-test/planet-finders-beta/classify/workflow/3317?demo=true

Add user existence check before UPP refresh in increment action of UserPersonalization store

---

packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js

Add `page_size` to subject set queries, and set it to the number of linked set IDs for a workflow.
This should allow us to show more than 20 linked sets for a workflow. The query runs on every request for grouped workflow page props, so be careful about making these queries too big/slow.
This workflow lists 20 subject sets on master, but should show 40 on this branch.
https://www.zooniverse.org/projects/bogden/scarlets-and-blues/classify/workflow/18504
Package:
app-project

Add page_size to subject set queries

---

packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsConnector.js
packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js
packages/app-project/stores/Store.js
packages/app-project/stores/User/Collections/Collections.js
packages/app-project/stores/User/Collections/Collections.spec.js
packages/app-project/stores/User/Collections/index.js
packages/app-project/stores/User/Recents/Recents.js
packages/app-project/stores/User/Recents/Recents.spec.js
packages/app-project/stores/User/Recents/index.js
packages/app-project/stores/User/User.js

Recents and Collections only make sense in the context of a user. This refactors `store.collections` and `store.recents` as `store.user.collections` and `store.user.recents`.
Package:
app-project

Refactor user collections and recents

---

packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsConnector.js

Copy `recents` to a JavaScript array, via `recents.slice()`, before passing it to the `RecentSubjects` component.
Package:
app-project
Closes #2511.

Fix Your Recent Classifications
